### ISSUE TITLE
Build error: terms not accepted

### ISSUE THREAD

**Issue by Kuro07** [mpv-android/mpv-android#100]
Hi there, I've been having problems trying to build mpv. I'm always getting the error below:

<pre>
> Configure project :app
Checking the license for package Android SDK Platform 27 in /home/osboxes/mpv-android/buildscripts/sdk/android-sdk-linux/licenses
Warning: License for package Android SDK Platform 27 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
</pre>

I was also getting this error #92 but I just installed the latest version of gradle instead and it seems to have fixed it. I'm not sure if that's the reason why the build is falling. I did use the buildscripts provided and tried re-running them a few times but I'm still getting the same error.

**Comment by sfan5** [comment]
try running `yes | ./tools/bin/sdkmanager "platforms;android-27"`` inside `./buildscripts/sdk/android-sdk-linux`

**Comment by Kuro07** [comment]
It's giving me the error of `bash: ./tools/bin/sdkmanager: No such file or directory
`

**Comment by sfan5** [comment]
This is probably because we were still using the old SDK, I've pushed a change (24090b441ff78431cbef0f5c2ace2f545df6880b).
Please retry from a clean working state.

**Comment by Kuro07** [comment]
I get this error now `Warning: File /home/osboxes/.android/repositories.cfg could not be loaded.
License android-sdk-license:
`
It still goes through but I get stuck at the accepting terms. I accept it and nothing happens after that.

**Comment by sfan5** [comment]
No idea what's wrong here. are both your home directory and `~/.android` writable?

**Comment by Kuro07** [comment]
Thanks! It's been fixed. It just took a while before proceeding with the script. Took around 20 mins or so for it to go through. No idea why though.
