### ISSUE TITLE
MPV PiP mode is Stuck at 1:1 Ratio with Subs overlapping 

### ISSUE THREAD

**Issue by sujitFYI** [mpv-android/mpv-android#1000]
This is not a bug but request that MPV pip mode need some work. 

Mpv pip mode will show any Ratio content is fixed 1:1 size pip ans srt subtitles overlap in default size which make it unusable.
![Screenshot_2024_0919_214150](https://github.com/user-attachments/assets/0d034219-3075-4c95-b969-8e0ae390261e)
This is default Windows size of Pip where Overlapping subs is happening 

![Screenshot_2024_0919_214132](https://github.com/user-attachments/assets/0bde7d5b-346b-4521-9554-2e8075090e78)
This is when pinch enlarge the size of window there's no Overlapping but still it looks awful with all those black borders.

Other players resize their Pip windows according to content aspect ratio and Subtitles never overlap it look exactly same like in full screen and some extra Controls e.g. MX Player 

Although I don't want it to replicate Other app but making PiP size 16:9 will be more Optimal as its best ratio to watch any content with less Black borders. 

I've edited a images to how it'll look.
![Picsart_24-09-19_21-52-58-087](https://github.com/user-attachments/assets/8014c167-fcbd-44b2-b2ce-a1b6d3f3288e)

That's will be all 
Thankyou sfan

**Comment by sfan5** [comment]
Works fine on my device.
