### ISSUE TITLE
默认加载/关联外部字幕

### ISSUE THREAD

**Issue by liweishu** [mpv-android/mpv-android#1003]
打开视频的时候并没有默认加载外部字幕，这在从 Solid Explorer 等文件管理器打开视频的时候非常的不方便。
特别是 mpv-android 手动加载外部字幕使用的是 documentsui，这需要再从 documentsui 打开到指定目录才能选取字幕。

至于 mpv-android 支持从 documentsui 打开视频，这很鸡肋。因为 documentsui 对 smb 的支持基于 [cifs-documents-provider](https://github.com/wa2c/cifs-documents-provider) 等 app，但 Android 并不鼓励使用 smb（或许是 google 为了推广收费的网络存储服务），这些基础 app 的功能薄弱， smb 传输速率非常的低下，并不足以支持高码率视频的播放。
这迫使我转而寻求 Solid Explorer 等第三方文件管理器来支持 smb，但这方法加载外部字幕非常麻烦。

mpv-android 无论第三方文件管理器，还是 documentsui，甚至旧的文件选择器都不支持默认加载外部字幕。

**Comment by sfan5** [comment]
duplicate of #625, see comment there.
