### ISSUE TITLE
Add SRT protocol support

### ISSUE THREAD

**Issue by bbaa-bbaa** [mpv-android/mpv-android#1005]
Secure Reliable Transport (SRT) is an open source video transport protocol. 
Adding support for the srt protocol will benefit the viewing of some live streams.

**Comment by sfan5** [comment]
can you name some sites or platforms that actually use SRT?

**Comment by bbaa-bbaa** [comment]
Most web platforms currently only use srt for push streaming,But srt support can helps me watch some network camare devices like https://pro.sony/ue_US/products/ptz-network-cameras/secure-reliable-transport
