### ISSUE TITLE
Can't double click to play video on storage

### ISSUE THREAD

**Issue by tuanden0** [mpv-android/mpv-android#101]
I'm using NVIDIA Shield Tablet and install the lastest version of mpv on CHplay.
Everything is OK, but I can't double to play video in my storage. The player show blackscreen with the control bar.
If I use the MPV to open video in the file browser of MPV, the video played normally.

**Comment by sfan5** [comment]
logcat output would be nice.

**Comment by tuanden0** [comment]
I bought a new android device so it's OK now
Thank you.
