### ISSUE TITLE
Android 10 issue 

### ISSUE THREAD

**Issue by waseemhehe** [mpv-android/mpv-android#1011]
### Important information

Android version: 
Android 10 

i m using Android 10,
![image](https://github.com/user-attachments/assets/eed95103-4aac-44ce-ab75-4dd94baf4643)

IN THIS whenever i start video or play next video, screen take time to show views even they initialize, in other version it show views fast  
what's problem , same issue is coming in your latest build 

  

https://github.com/user-attachments/assets/1dbb45b8-2b8d-4f04-9511-f2744e555306

**Comment by sfan5** [comment]
You are not using mpv-android.

**Comment by waseemhehe** [comment]
https://github.com/user-attachments/assets/85e1e9c6-b37f-4bd6-93e0-2320d7d376b7

i just change the ui in your code nothing else  @sfan5 
now i m using your view nothing changed still take time u can see

**Comment by obscenelyvague** [comment]
Issue related to decoder on Huawei phones. Same bug as #915 most likely.

**Comment by waseemhehe** [comment]
@obscenelyvague THANKS
