### ISSUE TITLE
Mark watched popup after each episode

### ISSUE THREAD

**Issue by ACR-Jeff** [mpv-android/mpv-android#1015]
### Important information

Android version: 
Android TV version 9

mpv-android version:

Which version of mpv-android introduced the problem (if known): 2024-09-15 Build
I've even tried [build #330](https://github.com/mpv-android/mpv-android/actions/runs/11092380026) and the results were the same.
### Description

Describe your issue in detail here.

I use mpv-android as an external player on my Nvidia Shield 2017 with Jellyfin, When I "Shuffling All" episodes to play at random, After each episode it will result in a popup after each episode "Mark Watched: The item didn't appear to play as long as its duration. Mark watched?"
This doesn't happen with any other external player that I have installed except mvp-android. Which lead me to debug and follow through with logcat.

Shouldn't it automatically mark what's played as watched and continue on to the next?

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s mpv '*:F'

[mpv-logcat.txt](https://github.com/user-attachments/files/17370593/mpv-logcat.txt)

**Comment by sfan5** [comment]
Your log is not complete but I don't see anything out of the ordinary either.

I just re-tested and mpv-android is behaving according [our documentation](http://mpv-android.github.io/mpv-android/intent.html).
Jellyfin might be handling the result intent incorrectly. Have you asked them to investigate this?

> Which version of mpv-android introduced the problem (if known): 2024-09-15 Build

does that mean it works correctly on 2024-08-20, or is that simply the version you have?
