### ISSUE TITLE
Can not jump to position on the same media path if called with intent again

### ISSUE THREAD

**Issue by chenyanming** [mpv-android/mpv-android#1018]
### Important information

Android version: Android 14

mpv-android version:

Which version of mpv-android introduced the problem (if known):

2024-09-15 release / 8039
### Description

Describe your issue in detail here.

If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.

I am using on Termux:

1. call `am start -a android.intent.action.VIEW -t video/any -d file:////storage/emulated/0/org/notes/web/story_2.mp3 --ei position 5000 -p is.xyz.mpv`
2. then call `am start -a android.intent.action.VIEW -t video/any -d file:////storage/emulated/0/org/notes/web/story_2.mp3 --ei position 8000 -p is.xyz.mpv` the location does not change .

**Comment by sfan5** [comment]
mpv-android will not process intents and seek in the video *while* it is running. That is by design.

**Comment by chenyanming** [comment]
May I know why?

**Comment by sfan5** [comment]
Intents are a request to mpv-android to view (play back) a media file and not a form of IPC for influencing runtime behavior.
The only other useful way to handle it would be to append the requested entry to the playlist (maybe already happens?).
