### ISSUE TITLE
PIP mode

### ISSUE THREAD

**Issue by waseemhehe** [mpv-android/mpv-android#1025]
I noticed that in apps like MX Player, X Player, and Playit, their Picture-in-Picture (PIP) mode appears customized rather than using the default Android PIP. It seems they may be using a library or custom implementation to achieve this. I would like to incorporate a similar custom PIP feature in an MPV player. Could you explain how this is typically done and if it’s possible to add such functionality to MPV?

**Comment by sfan5** [comment]
> Could you explain how this is typically done

I am not a development consultant.

> if it’s possible to add such functionality to MPV?

probably.
