### ISSUE TITLE
SeekBar

### ISSUE THREAD

**Issue by waseemhehe** [mpv-android/mpv-android#1029]
Hello!

I'm working on implementing a seek bar thumbnail feature in MPV, where frames are displayed along the seek bar as the user scrubs through it. The project is already using FFmpeg, so I'm looking for a way to efficiently extract frames from the video. Is there an FFmpeg command or function that could help generate these frames? Any guidance would be appreciated!

![image](https://github.com/user-attachments/assets/c274b8c5-dbd6-49aa-8f9f-a52cc2b2ebfd)

**Comment by sfan5** [comment]
Please do your own research.
