### ISSUE TITLE
automatically scan for subtitle files

### ISSUE THREAD

**Issue by ZhouJiatai** [mpv-android/mpv-android#1030]
Android: 12
mpv: v0.38.0

Mpv on my mobile phone cannot automatically scan for subtitle files (e.g., *.vtt) in the same directory as the video files. Instead, I have to manually open the subtitle files after opening the video files, which seriously reduces my efficiency. I once thought something was wrong with my phone, so I tried to grant mpv access to all files, but it seemed that mpv never requested that access. So, does mpv possess the capability to automatically scan for subtitle files? If not, is there any possibility of adding this feature in the future?

**Comment by sfan5** [comment]
I could make a good guess what the cause of this is (namely SAF vs. direct file access).
But you are essentially reporting a bug, but without using the bug report template. And that template asks for a log file so I can diagnose the problem.
