### ISSUE TITLE
Playback issue on mpv android, working in mpv net and samsung video player

### ISSUE THREAD

**Issue by Takcsik24** [mpv-android/mpv-android#1037]
Android version:
Android 14, One UI 6.1

mpv-android version:
2024-11-16-release

### Description

I just made 2 soft-subbed video, and copied to my phone. mpv net and samsung video player can play this .mkv files, but mpv android freezed and crashed.

https://mega.nz/folder/j05QgIRA#nZC9whISWO6ClQ2n2jOGnw

**Comment by sfan5** [comment]
Cool, you forgot to post the log file.
