### ISSUE TITLE
RMVB file can be opened from the folder selector but can't be seen in the old file selector

### ISSUE THREAD

**Issue by linsui** [mpv-android/mpv-android#1039]
### Important information

Android version: 14

mpv-android version: 2024-11-16

Which version of mpv-android introduced the problem (if known):

### Description

RMVB file can be opened from the folder selector but can't be seen in the old file selector. In the old file selector the file is not displayed in the folder.

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s mpv '*:F'

You can attach text files on Github directly or use sites like https://0x0.st/ to upload your logs.
Depending on the nature of the bug, a log file might not be required and you can *omit this section*. If in doubt provide one, it will help us find possible issues later.

### Additional information

If your issue is only reproducible with a specific (type of) file, provide a short sample file that can be used to reproduce the problem.
You can again use https://0x0.st/ or other cloud storage to share it.

If your issue relates to a certain set of configuration options, provide a full copy of your `mpv.conf` below.

If no additional information is provided please *delete this section*.

**Comment by sfan5** [comment]
Android 11 or newer has a hardcoded whitelist of media file extensions, which it will show to apps using the "old" direct file access way. The system pretends all other files do not exist.

The document picker does not have this restriction.

**Comment by linsui** [comment]
Thanks!
