### ISSUE TITLE
Virtual Reality 360

### ISSUE THREAD

**Issue by waseemhehe** [mpv-android/mpv-android#1040]
[https://github.com/dfaker/VR-reversal](https://github.com/dfaker/VR-reversal)

I came across the [VR-reversal GitHub repository](https://github.com/dfaker/VR-reversal), which mentions VR support for MPV and shows related commands. However, when I try to use these commands, they don't seem to work, and I couldn't find any mention of native VR support in the official MPV documentation. Does MPV currently support VR? If so, what commands are available, and how can this feature be utilized? If not, is there any plan to integrate such functionality in the future?

**Comment by sfan5** [comment]
duplicate of #1016.
