### ISSUE TITLE
Make playback pause on headphone disconnect optional

### ISSUE THREAD

**Issue by 9viz** [mpv-android/mpv-android#1043]
[ Cue xkcd workflow comic: https://xkcd.com/1172/ ]

I use a wired headphone always and practically only ever use mpv when I go for a walk.  Sometimes my headphone accidentally disconnects because it gets caught in my coat, etc.  What used to be a simple job of replugging in my headphone to get audio back now involves having to open mpv and press the play-pause button.

[ The corresponding button on my headphone is busted.  ]

Having the auto-pause feature is a hinderance especially since 90% of the time I do not mind that I missed the audio as I reconnect my headphone.  Could we please have an option to disable it?

### Additional information

mpv-android 2024-11-16-release / 40 (release)
mpv v0.39.0-338-gdd5f2069b8 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov 19 2024 10:13:45
libplacebo version: v7.349.0 (v7.349.0-26-g5788a82f-dirty)
FFmpeg version: N-117784-g0b8c9cf5b4
FFmpeg library versions:
   libavcodec      61.24.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.47.100
   libswresample   5.4.100
   libswscale      8.9.101
Configuration: -Diconv=disabled -Dlua=enabled -Dlibmpv=true -Dcplayer=false -Dmanpage-build=disabled -Ddefault_library=shared --cross-file=/home/vagrant/build/is.xyz.mpv/buildscripts/prefix/arm64/crossfile.txt
List of enabled features: android android-media-ndk build-date cplugins dvbin egl-android ffmpeg gl glibc-thread-name gpl libass libavdevice libdl libplacebo linux-fstatfs lua memrchr opensles posix ppoll pthread-condattr-setclock vector vt.h zlib

**Comment by sfan5** [comment]
You can use the "Ignore Audio focus" setting for this.

**Comment by 9viz** [comment]
Thanks for the quick response, that works!  If you think this is good enough control, I am happy to have this issue closed.
