### ISSUE TITLE
Video quality option.

### ISSUE THREAD

**Issue by Univalpha** [mpv-android/mpv-android#1050]
Dear developers thanks for this wonderful app 💗

could you allow the video quality reduction to 144p instead of the lowest setting of 480p we have now? 
I saw someone posted this as a comment i also wanted this feature. 
This feature will help us who watches lecture and documentaries but on limited data.

I hope this request is not technically difficult and don't eat your precious time.

**Comment by sfan5** [comment]
Sure. I will reply to this in the ytdl PR thread.

**Comment by Univalpha** [comment]
Thank you so much sir 😊
