### ISSUE TITLE
Support fuzzy subtitle 

### ISSUE THREAD

**Issue by lopoki** [mpv-android/mpv-android#107]
Please support fuzzy subtitle just like in linux mpv when playing local or content:// video file.

 Currently mpv android only plays subtitle that has exactly the same name as the video file.
This doesn't work well because all other media player and media management software such as mx player, Plex or Kodi use the following pattern :
File.mkv
File.en.srt
File.eng.srt

I tested on Nvidia shield for playing local files and files from google drive (opened via X-plore or Solid explorer), mpv android doesn't play subtitle. 

In Linux you can configure by default for mpv to use fuzzy subtitle so that all avaliable srt are also opened.

**Comment by sfan5** [comment]
Now possible by editing mpv.conf directly, though it won't work at all for `content://` URLs.
