### ISSUE TITLE
Audio volume during video playback

### ISSUE THREAD

**Issue by calvintam236** [mpv-android/mpv-android#109]
I have tried to play a video file using mpv, and I found that:
1. mpv android have a significant volume difference compared to Google Photos (like 30%+)
2. the lower frequency is gone
3. same for speaker and headphones

My settings:
- Same media volume
- Razer Phone (support Dolby Atmos)
- Android 7.1.1

**Comment by sfan5** [comment]
Does the file you're playing have 5.1 audio?
mpv may downmix differently than Android's builtin player.

**Comment by calvintam236** [comment]
I don't think so.
