### ISSUE TITLE
stats.lua built-in alternative

### ISSUE THREAD

**Issue by xyzz** [mpv-android/mpv-android#11]
stats.lua: https://github.com/Argon-/mpv-stats

When controls are shown and the option is enabled in developer settings ( #3 ) it should display some simple text overlay with all info written on it, easiest would be to implement it all in Java since we already have all the property retrieval functions.

**Comment by xyzz** [comment]
WIP: https://github.com/mpv-android/mpv-android/tree/xyz/stats

this is waiting for settings menu #3

**Comment by joshdekock** [comment]
How do you want to merge this? want me to make a patch, apply it to my settings branch, and then create another commit for the actual setting, or do you want to put the setting in with this branch (which would require #3 merged first)

**Comment by jeeb** [comment]
Initial version merged.
