### ISSUE TITLE
Unable to play videos when open with URL. 

### ISSUE THREAD

**Issue by wanizubair** [mpv-android/mpv-android#111]
#### Expected behavior

The app should be able to play videos when open with URL. 

#### Actual behavior

The app is not able to play videos while opening with URL 

#### How to reproduce
 
Launch the app.

Click on the three dots at the top corner of the app. 

Click the Open URL

Enter the Url of video, video doesn't play

* Application :mpv-android 
* Operating system:Android Nought 7.0

#### Recording Of The Bug
https://youtu.be/pwYx2i6xb4w    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/unable-to-play-videos-when-open-with-url">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sfan5** [comment]
mpv-android does not support youtube URLs at this time
support is planned, for the work-in-progress state see #58
