### ISSUE TITLE
Split screen video stops playing when out of focus

### ISSUE THREAD

**Issue by junaru** [mpv-android/mpv-android#114]
In split screen video freezes whenever mpv loses focus. Audio continues to play as expected.
Background playback set to "Always". Video: https://www.youtube.com/watch?v=vorH9umtMeg

Device info:
![screenshot_20180329-182926](https://user-images.githubusercontent.com/59161/38097905-465e96dc-337f-11e8-9b90-9df7363de29d.png)
![screenshot_20180329-182915](https://user-images.githubusercontent.com/59161/38097912-49e8b986-337f-11e8-927f-f93dbe13f411.png)

` $ adb logcat | grep -F "``adb shell ps | grep is.xyz.mpv | cut -c10-15``" > log.txt`

[log.txt](https://github.com/mpv-android/mpv-android/files/1860797/log.txt)

**Comment by sfan5** [comment]
mpv is resuming playback in the background because it thinks that mpv is not visible anymore.
You won't actually need to enable "Background playback" to use split-screen.

Will take a look at fixing this later.

**Comment by junaru** [comment]
> You won't actually need to enable "Background playback" to use split-screen. 

Strange, without "Background playback" both audio and video pause when focus is lost.
Tested on both master 983ceaf and bgplay_improvements af03faf - same results.

**Comment by sfan5** [comment]
Please try (based on `sfan5/bgplay_improvements`): https://0x0.st/sMiV.diff
