### ISSUE TITLE
Turning on save-position-on-quit results in videos resuming without video

### ISSUE THREAD

**Issue by philipl** [mpv-android/mpv-android#117]
I tried it out after the mpv.conf support from @sfan5 when in. It turns out that when save-position-on-quit is turned on, mpv-android disables the vo before it saves the player state. This means that when it resumes, it resumes without the vo and just plays audio.

Gist with logs for the two cases: https://gist.github.com/philipl/0c57f965392468805aa6fb113fc02b10

**Comment by JonAziz1** [comment]
Did you ever find a solution?

**Comment by philipl** [comment]
I did not investigate. Given that all of the logic around saving state is in mpv itself, presumably there's no way to filter the state that's stored by making changes in mpv-android. That would imply the only solution is to reorder when the vo is disabled.

**Comment by seowalex** [comment]
@sfan5 is there a planned fix for this?

**Comment by sfan5** [comment]
#134

**Comment by seowalex** [comment]
Nice thanks for the quick reply
