### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mpv-android/mpv-android#119]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

so it's a bug, not a feature request more

**Comment by c-e-p-x-u-o** [comment]
Please reopen it untill it fixed.

**Comment by xyzz** [comment]
It's fixed in 6386e3d0473458e272a7fce36d0eccca86356c49
