### ISSUE TITLE
Wrong url of F-Droid repo

### ISSUE THREAD

**Issue by hotlittlewhitedog** [mpv-android/mpv-android#120]
The url to F-Droid in this page ( https://github.com/mpv-android/mpv-android ) is pointing to the repo of Izzy, not the official repo of F-Droid. Please adapt.  

Your package is still under construction.

**Comment by sfan5** [comment]
We don't have a package on the official f-droid repository.

**Comment by theScrabi** [comment]
@sfan5 how hard would it be to get mpv to the official repository?

**Comment by xyzz** [comment]
No idea.
