### ISSUE TITLE
Remuxed MKV Files

### ISSUE THREAD

**Issue by MatthewAllan93** [mpv-android/mpv-android#121]
Hi, when I try to play some remuxed MKV files that I have just done, the player doesn't play them correctly it goes really fast, sound doesn't work and displays the time code like "-577014:-32:-22" for example. I am using the 2018-04-29 Test Build. Hope this issue can be fixed soon.

**Comment by sfan5** [comment]
Please post a [`logcat`](https://developer.android.com/studio/command-line/logcat) log of mpv playing the affected file.

**Comment by MatthewAllan93** [comment]
Here in the [logcat.txt](https://github.com/mpv-android/mpv-android/files/1997512/logcat.txt) file, I hope it helps :).

**Comment by sfan5** [comment]
Same result with hwdec disabled?
Does it work with `demuxer=lavf` in the config?

Either way mpv has some kind of problem with the timestamps in your file, so it might be a good idea to file an issue on [mpv-player/mpv](https://github.com/mpv-player/mpv/issues/new) with a sample file.

**Comment by MatthewAllan93** [comment]
It works with HW decoding disabled.

**Comment by sfan5** [comment]
Likely stale.
