### ISSUE TITLE
[Question] Does building with AArch64 have any advantage for 64-bit SoCs?

### ISSUE THREAD

**Issue by kkanungo17** [mpv-android/mpv-android#122]
Performance improvements and the like?

**Comment by sfan5** [comment]
It can bring performance improvements.
However I haven't benchmarked this, so I can't tell you how much faster it would be.

Also note that not every phone with 64-bit SoC can actually run 64-bit native code, check the output of `getprop ro.product.cpu.abilist`

**Comment by xyzz** [comment]
When I tested it, comparing arm/thumb2/aarch64 there weren't any performance improvements.
