### ISSUE TITLE
MPV [2018-04-29-alpha] Can not playing file by URL

### ISSUE THREAD

**Issue by Icramss** [mpv-android/mpv-android#124]
# Expected behavior

Actually the app can play video files with URL

# Actual behavior

When playing video with URL, Video can not be played. I took the URL from youtube

You must copy the URL on youtube to paste into OPEN URL in the MPV app

# How to reproduce

- Download app on playstore
- Open the MPV app
- tap on 3 dots on the right side of the top
- Tap OPEN URL
- please go to youtube and copy the video url
- paste in OPEN URL
- Tap okay
- vide can not be played

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version : 28-04-29-alpha

# Recording of the bug

https://youtu.be/sFTBqXcBE-A

**Comment by andrew-shulgin** [comment]
AFAIK, MPV-Android does not support YouTube URLs currently.
See https://github.com/mpv-android/mpv-android/pull/58

**Comment by sfan5** [comment]
That's indeed correct.
Even if I finally finish implementing ytdl support, it won't be pushed to the Play Store as Google will most likely disagree with it.
