### ISSUE TITLE
VO Framedrops when using bluetooth speaker

### ISSUE THREAD

**Issue by Skrity** [mpv-android/mpv-android#127]
__Version:__  mpv-android-2018-04-29-debug.apk
__Log:__ [logcat_06-13-2018_02-59-22.txt](https://github.com/mpv-android/mpv-android/files/2096177/logcat_06-13-2018_02-59-22.txt)
__Screenshot:__ ![screenshot_mpv_20180613-025849](https://user-images.githubusercontent.com/22554542/41323352-8826bf64-6eb6-11e8-8fed-ac95c81420af.png)
__Systems tested:__ Nexus 4(lineageos-15.1, oreo), Nexus 7 2013(lineageos-14.1, nougat), Xiaomi Redmi Note 3(lineageos-14.1, nougat, arm64). Problem occur on all 3 devices and tested with 2 different bluetooth speakers.

__Problem:__ When playing any video through Bluetooth audio device weird video stutter/desync is observed and OSD shows VO dropped frames. Disabling bluetooth fixes the stutter, so is disabling audio track. Disabling HW decoding does nothing. "Video Sync" option seem to have some effect, but none of the choices yield even remotely watchable result.

`audio-buffer=0.5` from [here](https://github.com/mpv-player/mpv/issues/4672) haven't made any difference, while with `audio-buffer=0.05` drops were gone, but playback was ~40-70% slower.

Next part for all I know can be useless nonsense but anyway.
Since changing vo and ao options from Settings -> Advanced -> Edit mpv.conf did nothing (even `ao=null`) I deduce they are hard coded in some way or another.
While trailing this issue I found an apk [here](https://github.com/mpv-player/mpv/pull/5602) that wasn't affected by this issue: https://github.com/mpv-player/mpv/pull/5602#discussion_r174288136. Although it was affected by this issue: https://github.com/mpv-player/mpv/pull/5602#issuecomment-372822570 when using HW, my issue was gone and I could watch videos on SW.
My only guess is that change in `vo` resulted in this issue gone, so I summon @sfan5 and @tmm1 in high hopes that they can provide some insight.

Regards.

**Comment by sfan5** [comment]
> Since changing vo and ao options from Settings -> Advanced -> Edit mpv.conf did nothing, I deduce they are hard coded in some way or another.

That's indeed how it is. 

> While trailing this issue I found an apk here that wasn't affected by this issue: mpv-player/mpv#5602 (comment).

The APK you've found does not only contain changes related to debugging of that issue, but at the time I was also testing ao_audiotrack (mpv-player/mpv#5589):
![bildschirmfoto_2018-06-13_10-20-07](https://user-images.githubusercontent.com/1042418/41338833-93becf5a-6ef3-11e8-8ec1-d468b4ca7eb5.png)

　

It looks like despite mpv-player/mpv#5628 tuning the buffer count & sizes, Bluetooth audio is still(?) not reliable.
Anyway, here's a freshly built APK with ao_audiotrack enabled: https://0x0.st/sLPd.apk

**Comment by Skrity** [comment]
> Anyway, here's a freshly built APK with ao_audiotrack enabled: https://0x0.st/sLPd.apk

This one worked wonders, although this build has slightly worse A-V sync ratio(regardless of hwdec or bluetooth): ~0.000091-0.000400 versus 0.000031 on 2018-04-29 apk(not perceived by my eyes).

As this fixes the issue I wonder how would merge of https://github.com/mpv-player/mpv/pull/5589 impact the mpv-android. 

Will ao_audiotrack supersede ao_opensles and will ao_opensles be sometimes used as fallback or not.
I imagine the current fix won't be sufficient in the latter case thus we might be forced to look into underlying cause of this issue.

**Comment by sfan5** [comment]
Especially due to passthrough support, ao_audiotrack really only has advantages and I'm pretty sure we'll select it as a default once it's merged into mpv.

**Comment by Skrity** [comment]
I'll continue to use your APK for the time being while ao_audiotrack is getting honed.
Since the issue is pretty much resolved should I close it or wait until master branch gets the fix?

P.S. Huge thanks @sfan5 for taking the time and helping me with this issue, I really appreciate it. 😃

**Comment by tmm1** [comment]
Good to know ao_audiotrack fixes this too.

I have some more changes locally, so I'll plan to update my PR soon and merge it.

**Comment by tomty89** [comment]
Although I am not sure if the device buffer (Enqueue) size has anything to do with the stutter, the default (250ms) in mpv is not used by mpv-android as it uses "optimal" values from AudioManger:
https://github.com/mpv-android/mpv-android/blob/2f4f846b5cd29548831217f278b678f99d27449d/app/src/main/java/is/xyz/mpv/MPVView.kt#L59
https://github.com/mpv-android/mpv-android/blob/2f4f846b5cd29548831217f278b678f99d27449d/app/src/main/java/is/xyz/mpv/MPVView.kt#L58
Which is static (non sink-based) and could even be total garbage (does not apply to any possible sink) in some devices.

Here are the cases on my phone:
```
### internal ###

$ termux-audio-info
{
  "PROPERTY_OUTPUT_SAMPLE_RATE": "48000",
  "PROPERTY_OUTPUT_FRAMES_PER_BUFFER": "192",
...
  "AUDIOTRACK_SAMPLE_RATE": 192000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES": 23046,
  "AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY": 48000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY": 192
}

### usb ###

$ termux-audio-info
{
  "PROPERTY_OUTPUT_SAMPLE_RATE": "48000",
  "PROPERTY_OUTPUT_FRAMES_PER_BUFFER": "192",
...
  "AUDIOTRACK_SAMPLE_RATE": 96000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES": 3844,
  "AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY": 96000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY": 480
}

### Bluetooth @ 44.1kHz ###

$ termux-audio-info
{
  "PROPERTY_OUTPUT_SAMPLE_RATE": "48000",
  "PROPERTY_OUTPUT_FRAMES_PER_BUFFER": "192",
...
  "AUDIOTRACK_SAMPLE_RATE": 48000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES": 11544
}

### Bluetooth @ 48kHz ###

$ termux-audio-info
{
  "PROPERTY_OUTPUT_SAMPLE_RATE": "48000",
  "PROPERTY_OUTPUT_FRAMES_PER_BUFFER": "192",
...
  "AUDIOTRACK_SAMPLE_RATE": 44100,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES": 10776
}
$

### 88.2kHz and 96kHz are also possible with LDAC, where the buffer size in frames will be even larger ###
```

(Ref: https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/AudioAPI.java)

Apparently the setting cannot be overridden with mpv.conf, probably because it was parsed before the setting, so I cannot test whether larger device buffer size helps in this, but there's essentially no advantage at all in using the "optimal" values from AudioManager anyway.

**Comment by Skrity** [comment]
Fixed, probably since https://github.com/mpv-android/mpv-android/commit/75ffd04dddb93bafaef343e0fc3bc6dce2702d96
