### ISSUE TITLE
Broken hwdec on Fire TV Stick

### ISSUE THREAD

**Issue by neik1** [mpv-android/mpv-android#129]
Hi guys,

I am having an issue with streaming HD channels to my FTVS and using the HW decoder. HD channels start to flicker a lot and the image looks like a mess.
Apparently this isn't just a MPV specific problem other with other players happens exactly the same.
The same channels play flawlessly on the PC and on an Android Box I have.

If you need further information, just let me know!

**Comment by neik1** [comment]
You need to give me a helping hand. How do you create a log?

**Comment by sfan5** [comment]
[logcat](https://developer.android.com/studio/command-line/logcat) is part of the Android SDK.
Start logcat, then start mpv-android and reproduce the bug and save the output that was printed during that time.

**Comment by neik1** [comment]
Thanks for the hint!

Here you go: https://paste.ubuntu.com/p/XxBQmQ97qP/

**Comment by sfan5** [comment]
Since you're using Emby, have you tried reporting this issue to their devs? Have you verified this bug outside of Emby?

`V/mpv     ( 4859): [cplayer:warn] Invalid video timestamp: 2.518411 -> -9223372036854775808.000000`
The hardware decoder is not returning any useful timestamps.
`I/MediaCodecLogger( 4859): tv.emby.embyatv.HW.video.avc Dropping frame`
Some emby-specific mediacodec component seems to be dropping frames.

**Comment by neik1** [comment]
Yes, I already had contact the emby devs but we couldn't find a solution yet.

Given that the last time Emby was in between I created a new logcat using the latest mpv build (non-debug) over here: https://github.com/mpv-android/mpv-android/releases

Logcat: https://paste.ubuntu.com/p/TYnXv7XsgW/

I opened the files directly from the storage of the FTVS using the new MPV installation.

Also noted the following line on the overlay stats inside MPV: Dropped Frames: 0 (decoder), 713 (output)
Judging from this, frames appear to be dropped, right?

**Comment by sfan5** [comment]
I don't see any timestamp warnings, but frames are indeed still being dropped.
Since you said this happens in vlc too, I'd say it's a bug in the mediacodec implementation of your platform.

**Comment by neik1** [comment]
Actually, it is happening with literally every player I have tested so far.
Do you think this is an hardware issue or this something that can be solved on the software side?

**Comment by tmm1** [comment]
The FTV stick is very underpowered. You can try https://github.com/amzn/exoplayer-amazon-port and report a bug to them if it has the same problem.

**Comment by neik1** [comment]
FYI.. This is happening with other players as well, e.g. VLC, so I opened a topic over there as well.

For those interested -> https://forum.videolan.org/viewtopic.php?f=35&t=144988&p=474980#p474980

**Comment by tmm1** [comment]
I don't have any apk, you would need to build it yourself.

I don't see any sample video file anywhere so I can't try to reproduce. Maybe you can run mediainfo on the stream and post the results.

**Comment by neik1** [comment]
Unfortunately, I do not know how to do that. Do you have a how to?

Here is a sample and the mediainfo of it: https://www65.zippyshare.com/v/CbDWPgBB/file.html

`General
ID                                       : 1 (0x1)
Complete name                            : C:\Users\ferre\Downloads\Sample.ts
Format                                   : MPEG-TS
File size                                : 46.8 MiB
Duration                                 : 1 min 6 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 5 904 kb/s

Video
ID                                       : 256 (0x100)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Format settings, GOP                     : M=4, N=48
Codec ID                                 : 27
Duration                                 : 1 min 6 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan type, store method                  : Separated fields
Scan order                               : Top Field First
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 257 (0x101)
Menu ID                                  : 1 (0x1)
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : LC
Muxing mode                              : ADTS
Codec ID                                 : 15
Duration                                 : 1 min 6 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -192 ms

Other
ID                                       : 258 (0x102)-100
Menu ID                                  : 1 (0x1)
Format                                   : Teletext

Menu
ID                                       : 4096 (0x1000)
Menu ID                                  : 1 (0x1)
Duration                                 : 1 min 6 s
List                                     : 256 (0x100) (AVC) / 257 (0x101) (AAC) / 258 (0x102)-100 (Teletext)
Service name                             : Service01
Service provider                         : FFmpeg
Service type                             : digital television

`

**Comment by tmm1** [comment]
>Scan type : Interlaced
>Scan type, store method : Separated fields
>Scan order : Top Field First

This is a known issue with decoding interlaced h264 with separate fields in ffmpeg. I have proposed some ideas for fixing it but they don't work yet on the FTV stick (http://ffmpeg.org/pipermail/ffmpeg-devel/2018-June/231237.html)

Exoplayer should not have this bug, since it is specific to ffmpeg.

**Comment by neik1** [comment]
> This is a known issue with decoding interlaced h264 with separate fields in ffmpeg. I have proposed some ideas for fixing it but they don't work yet on the FTV stick (http://ffmpeg.org/pipermail/ffmpeg-devel/2018-June/231237.html)

Well, that doesn't sound that bad. So, if I got it right then the fix/workaround is just a matter of time to be implemented, right? Or is it still unclear if the fix will also solve the issues on the FTV Stick?

> Exoplayer should not have this bug, since it is specific to ffmpeg.

As you might have noticed I want to use the stream with Emby, which firstly uses the Exoplayer and just in case Exo fails it uses MPV as backup.
And exactly this is the point, Exo is far better in terms of smoothness but it struggles far more often to open some streams whereas MPV opens the streams but has this particular issue.

I really wouldn't mind trying a standalone version of Exo but finding the .apk hasn't been so easy...

**Comment by neik1** [comment]
@tmm1 ,  have been thinking about this and came to this conclusion:

If I see this right then the HW deinterlacer is causing the messy image due to a bug, right? Is there a way to pass the interlaced picture to the TV and let the TV's deinterlacer do its magic?

I mean afaik every TV should have a deinterlacer itself, right?

**Comment by tmm1** [comment]
No it's not possible to output an interlaced signal from the FireTV. Only 720p and 1080p outputs

**Comment by tmm1** [comment]
I ran some tests with newer FireTV models (pendant and cube), and they're all very buggy when trying to decode interlaced h264. I guess these devices are built and tested primarily for internet streaming, which always uses progressive h264.

I've reported some bugs to Amazon. I also reported a bug to the Exoplayer team since there's a separate issue where Exoplayer won't play these files even if the hardware decoder supports them: https://github.com/google/ExoPlayer/issues/4538

**Comment by neik1** [comment]
@tmm1, I want to thank you for investigating this and your big effort in trying to narrow this down.

Would be great if you could keep me posted about this as I am trying to keep tracking your tickets over at ExoPlayer (Google/Amazon) and wherever else there is a ticket related to this.

Thanks!

**Comment by shanmukhateja** [comment]
> This is a known issue with decoding interlaced h264 with separate fields in ffmpeg. I have proposed some ideas for fixing it but they don't work yet on the FTV stick (http://ffmpeg.org/pipermail/ffmpeg-devel/2018-June/231237.html)

So, all we need to do is compile ffmpeg for the Fire TV stick with the proposed patch (I see a diff log in there) and this problem shouldn't occur?

I realize this maybe a long shot and/or not worth the effort, but, in theory is it possible?

**Comment by tmm1** [comment]
That patch is invalid, and although it works on some devices it does not work on the FireTV

**Comment by sfan5** [comment]
Likely stale.
