### ISSUE TITLE
Open url with Header

### ISSUE THREAD

**Issue by Blablablar** [mpv-android/mpv-android#131]
I have used mpv in macOs terminal, play the bilibili video with header, command like this

mpv --user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0" --referrer="https://www.bilibili.com/" "http://cn-sxxa-cu-v-04.acgvideo.com/vg4/upgcxcode/88/04/41980488/41980488-1-80.flv?expires=1529645700&platform=pc&ssig=SGrK2cGCt9oBMzWYeESzEw&oi=2362399354&nfa=Rq1qY251hdDavKypfICkAA==&dynamic=1&hfa=2032095794&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=2eae5ee863764f12ab624acc91c8b8b6"

so how can I open url with header in mpv-android

**Comment by Blablablar** [comment]
Maybe I find the answer, just set option string like "MPVLib.setOptionString("user-agent", str)"

**Comment by zzzop** [comment]
> Maybe I find the answer, just set option string like "MPVLib.setOptionString("user-agent", str)"

May I ask where this option should be modified? Is the application internal or a configuration file?

**Comment by sfan5** [comment]
The quoted code is application-internal, however you can set the same options by editing mpv.conf, e.g.:
<pre>
user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
referrer="https://www.bilibili.com/"
</pre>

**Comment by LetrixZ** [comment]
Is there any way to add headers on runtime?
Tried with MPVLib.setOptionString but didn't do anything
