### ISSUE TITLE
Lua scripting support

### ISSUE THREAD

**Issue by seowalex** [mpv-android/mpv-android#132]
Is there support for lua scripting? I have tried to place a lua script in a few places, but they don't seem to work.

**Comment by sfan5** [comment]
Lua support is compiled in (even though it's unused due to the custom osc).
You should be able to make mpv load a script by putting `script=/sdcard/path/to/script.lua` into the config file.

**Comment by seowalex** [comment]
Thanks I have tested it and it indeed works.
