### ISSUE TITLE
Customize gestures & touch controls

### ISSUE THREAD

**Issue by seowalex** [mpv-android/mpv-android#133]
Are there any plans to allow customisation of touch controls (e.g. disable swipe to control brightness, allow double tap to play/pause)?

**Comment by MS9** [comment]
Yes i would also like double tap to play/pause function

**Comment by rohitghali** [comment]
I would like it too... Please add double tap to pause/play.

**Comment by 3xploiton3** [comment]
Customize by user is powerfull feature app,

Must be implemented soon

**Comment by rancidfrog** [comment]
Also,
Customize the offset for swipe to forward|rewind, currently it seeks too much. Allowing user to set the seconds would be great.

**Comment by 532910** [comment]
While I hate VLC, some things are better there.
Double tap left/right screen part for -/+ 10s scroll is a must. NewPipe although has this controls.

**Comment by 532910** [comment]
Thank you!
