### ISSUE TITLE
Audio equalizer/mods not working in mpv

### ISSUE THREAD

**Issue by NextFire** [mpv-android/mpv-android#135]
Hello,
It seems that mpv (at opposite of other video player like mxplayer) disables any audio equalizer/mods when playing a video such as the built-in Dolby Atmos enhancer on my Galaxy S9.
Is there any way to keep them active in mpv?

**Comment by tomty89** [comment]
Just tested with VLC, builtin sound effects on my phone (Xperia X) only works when it does passthrough (ENCODING_IEC61937) with JNI AudioTrack.

**Comment by NextFire** [comment]
Sorry I have no idea...

**Comment by tomty89** [comment]
Sound effects would probably only apply to tracks created from the Java layer (including JNI, of course). No luck here with OpenSLES or AAudio.

**Comment by smolseok** [comment]
Aw come on.. I was hoping to find something to help me here.. im on the same Device as @Nextfire and am experiencing the same problem..

**Comment by jonathan25** [comment]
I have an LG G5 and I stumbled with the same problem, some apps just outright "bypass" the equalizers and for my phone this means that I have no bass at all.
I'm not sure if this helps but, I'm using termux and I found this: https://github.com/termux/play-audio which uses OpenSL ES and it works fine with the equalizers.
