### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by danboid** [mpv-android/mpv-android#139]
Upon trying mpv-android for the first time today I was disappointed that it doesn't seem to use the same keyboard shortcuts as the desktop (Linux) version uses. Does it have any (USB/BT) keyboard shortcuts currently?

The main ones I would like to see added are:

SPACE for play/pause
. (period) frame advance
, (comma) Go back a frame

I also add a few other custom keys to enable panning, zooming and rotation so it'd be cool if you beat mainline mpv to including my extra shortcuts:

https://github.com/mpv-player/mpv/issues/5458

More specifically they are:

```
Alt+RIGHT add video-rotate 90
Alt+LEFT add video-rotate -90
Alt+- add video-zoom -0.25
Alt+= add video-zoom 0.25
Alt+j add video-pan-x -0.05
Alt+l add video-pan-x 0.05
Alt+i add video-pan-y 0.05
Alt+k add video-pan-y -0.05
Alt+BS set video-zoom 0; set video-pan-x 0; set video-pan-y 0
```

Thanks!

**Comment by sfan5** [comment]
Currently no key events at all are forwarded from Java to libmpv.

**Comment by danboid** [comment]
That'd be very handy for people using mpv-android with a physical keyboard.

The other mpv keyboard shortcuts I use constantly are the left and right arrows to move back and forth through a video.

**Comment by danboid** [comment]
With this it would be nice to see the ability to edit input.conf added in the same way that mpv-android lets you edit mpv.conf currently.

**Comment by ialfianzidny** [comment]
u can use 0x10003 add video-pan-x -0.05 whatever you want.

0x10003 for right click
