### ISSUE TITLE
Android 4.4 cannot locate symbol "mmap64"

### ISSUE THREAD

**Issue by ascmartins** [mpv-android/mpv-android#142]
Maybe Android 4.4 is out of scope, but I am trying hard to have MPV working on it, sadly I am getting the error:
```
 java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libavcodec.so" needed by "libmpv.so"; caused by could not load library "libswresample.so" needed by "libavcodec.so"; caused by could not load library "libavutil.so" needed by "libswresample.so"; caused by cannot locate symbol "mmap64" referenced by "libavutil.so"...
```
I am trying to figure out how to solve this, but so far I have no clue:

Will it be possible to make it work?

Thanks.

**Comment by sfan5** [comment]
Android 4.4 is definitely out of scope, from our experience devices that can't upgrade to 5.0 are too old/bad to be able to run mpv in the first place.

----

You need to actually lower the API level of the native toolchain to the one for 4.4. Some of these errors will already appear during compilation, for each of those you need to find a workaround that does not use the problematic function.

Blame Android's shitty libc.

**Comment by ascmartins** [comment]
Thanks @sfan5 .

I will try to check if I can disable the _FILE_OFFSITE_BITS in the hope it will not overwrite mmap with mmap64.

BTW I have written a Kotlin version of MPVLib.java that I' like to share if you find it useful, if so let me know the best way to give it.

**Comment by 3407673214** [comment]
Is there MPV APK that can run Android 4.4.4?

**Comment by ascmartins** [comment]
Honestly, I don't know, but you can check in [releases](https://github.com/mpv-android/mpv-android/releases)

**Comment by kn-yami** [comment]
> Is there MPV APK that can run Android 4.4.4?

[mpv-android 2016-09-18 release notes](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2016-09-18):

> All instances of running with OpenGL ES drivers from 4.4.x (API version 19) have been failures so far.

**Comment by realfinder** [comment]
I think there are no MPV APK that run in Android 4.4.X yet, I have Samsung Galaxy Note II and didn't find any, but I think it (Note II) can run mpv well since it can run vlc well so it worth support Android 4.4.2

**Comment by EKwongChum** [comment]
> Maybe Android 4.4 is out of scope, but I am trying hard to have MPV working on it, sadly I am getting the error:
> 
> ```
>  java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libavcodec.so" needed by "libmpv.so"; caused by could not load library "libswresample.so" needed by "libavcodec.so"; caused by could not load library "libavutil.so" needed by "libswresample.so"; caused by cannot locate symbol "mmap64" referenced by "libavutil.so"...
> ```
> 
> I am trying to figure out how to solve this, but so far I have no clue:
> 
> Will it be possible to make it work?
> 
> Thanks.

This "libavutil.so" may be a 64 bit package that requires mmap64;
For Android API < 20 ,is mmap instead of mmap64;
If you truely need this function,  maybe you can build a 32 bit "libavutil.so" from the ffmepg source code.
