### ISSUE TITLE
loop=inf stops after several repeat on the H96 pro+ device

### ISSUE THREAD

**Issue by tellamon** [mpv-android/mpv-android#147]
I'm working on my project with mpv on the android tv box. This project goal is kind of digital signage so I want to play the movie clip forever 24-7. The movie clip repeats for several times with loop=inf option but it stops eventually after about 30 minutes. I played with many parameters(cache, demuxer-lavf-buffersize, ...), but none of them help. I first thought my custom build had some problem but I tested with the Google store build and the problem still exist. The last log messages are always like below when it stops playing.
```
[4902.185][v][af] filter input EOF
[4902.185][v][af] filter output EOF
[4902.185][v][cplayer] audio EOF reached
```

- Android H/W : H96 Pro+ (AMLogic S912chip, spec:https://www.youtube.com/watch?v=-hyZcVnvpa8)
- Movie clip : First 30 seconds of [Big buck bunny](http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4) with (ffmpeg -i .\bbb_sunflower_1080p_30fps_normal.mp4 -c copy -t 30 output.mp4 )
- MPV Version : Google store version
- Applied Settings
  - Developer -> Show stats -> stats.lua: General
  - Advanced-> Edit mpv.conf:
```
loop=inf
log-file=/sdcard/a.log
```
- logfile : [a.log](https://github.com/mpv-android/mpv-android/files/2495731/a.log)

- Screenshot when it stopped(last frame): 

![device-2018-10-19-195713](https://user-images.githubusercontent.com/1867602/47215803-ae483100-d3dd-11e8-8796-abf262e1c093.png)

**Comment by sfan5** [comment]
`[vd] could not consume packet` does not necessarily indicate in an error, since it also happens once or twice in normal conditions
after the seek to 0.0 however, the hwdec stops returning any packets entirely

can you test and see if the bug appears with hwdec disabled?

@tmm1 might know more regarding mediacodec/hwdec

**Comment by tellamon** [comment]
@sfan5  you are right. That message was not a problem, I've edited the last log messages above to
```
[4902.185][v][af] filter input EOF
[4902.185][v][af] filter output EOF
[4902.185][v][cplayer] audio EOF reached
```

I'm testing it again with hwdec siabled.

**Comment by tellamon** [comment]
This bug appears also in [Xiaomi's Mi Box](https://www.mi.com/en/mibox/)

This bug did NOT appear with hwdec disabled. (SW decoding)

Is there any option that I can try to figure out what causes and fix this? I need hwdec enabled to get high FPS.

**Comment by tellamon** [comment]
Added Mi Box log  - [mibox-2018-10-19.log](https://github.com/mpv-android/mpv-android/files/2497627/mibox-2018-10-19.log)

It looks like it also has the following messages when it stopped playing.
```
[7700.794][v][af] filter input EOF
[7700.794][v][af] filter output EOF
[7700.795][v][cplayer] audio EOF reached
```
