### ISSUE TITLE
Need to hit Back button twice to exit app.

### ISSUE THREAD

**Issue by shanmukhateja** [mpv-android/mpv-android#148]
I noticed a bug on the Android app wherein you see a blank page with "../" as the only item on the page after you try to quit the app by pressing the Back button.

**Steps to reproduce:**

1. Open the app.

2. Tap on Back button once.

**Expected Output:**

The app would exit on back press.

**Actual output:**

A blank screen is loaded with `../` item. The user needs to hit Back button AGAIN to close the app. 

**Note**

I have personally noticed similar issues on my apps which involve `Fragments` so what happens is, the `MainActivity` stays at the 0th index of Android Back stack once it creates the required `Fragment`. Now, once the user starts tapping Back button, the app would cycle back till the stack is empty.

What I mean to say is, there could be an issue with Back stack not clearing out your initial `Activity` class that renders your Fragments.

**Device Information**

**Brand:** ONEPLUS
**Model:** Oneplus 5T A5000
**Android:** Oxygen OS 8.1.0

**Comment by sfan5** [comment]
The back button should probably not be used by the file manager to go up one level.
