### ISSUE TITLE
Support for aomedia-av1 codec

### ISSUE THREAD

**Issue by alive4ever** [mpv-android/mpv-android#154]
Latest ffmpeg has supported av1 encoding and decoding.

It would be better to add support for av1 playback, since there is no video player app on Android supporting av1 playback.

A sample av1 video inside mp4 container is attached.

[av1-sample.zip](https://github.com/mpv-android/mpv-android/files/2709172/av1-sample.zip)

**Comment by sfan5** [comment]
There's a branch with experimental support for AV1 using libaom: https://github.com/mpv-android/mpv-android/tree/sfan5/av1

For "real world usage", we'll probably want to use libdav1d or wait until ffmpeg adds a built-in AV1 decoder.

**Comment by thousandsofthem** [comment]
libdav1d is the only reasonable way atm

**Comment by Pentaphon** [comment]
Yes, please add libdav1d.

**Comment by nr1jack** [comment]
Please add AV1, thanks.
1jack

**Comment by xdilemite** [comment]
For those that require av1 dav1d support here's the apk[https://drive.google.com/open?id=1mUwovGMHWxLuOl5v18jrbUstEaUsRH1j](url)

**Comment by Pentaphon** [comment]
Doesn't mpv already have libdav1d support? Shouldn't this already be in the latest mpv-android?

**Comment by sfan5** [comment]
Yes, but we don't ship with it.

**Comment by Pentaphon** [comment]
>Yes, but we don't ship with it.
Why not?

**Comment by vipinaggar** [comment]
pls provide apk with av1 dav1d support and youtube-dl like the one you have posted under pull request

**Comment by xdilemite** [comment]
here's a mpv test build with dav1d support and vulkan

**Comment by vipinaggar** [comment]
> https://drive.google.com/file/d/1K3VBzwRD6uRRIJx0mkOo_BsTXR_dDHh2/view?usp=sharing
> here's a mpv test build with dav1d support and vulkan

Thanks but support for youtube-dl is not their pls add support for dav1d to mpv dt 17-03-2020

**Comment by sfan5** [comment]
added in a44d89458b5417b72c2b9d4c46e5f33b4d4351cd

**Comment by xdilemite** [comment]
https://drive.google.com/file/d/1J2prqAr74S_h0i9jpevsNo7U1goIQ7QY/view?usp=sharing
@vipinaggar  test with ytdl support
