### ISSUE TITLE
[enhancement] keep file position

### ISSUE THREAD

**Issue by Geobert** [mpv-android/mpv-android#163]
Would be cool to keep track of position of files (with a configurable max nb of files) so when opening the same file from a file manager, it restore the position.

The idea is to use a file manager to browse and use mpv only to play as its browser is quite weak atm.

**Comment by sfan5** [comment]
Already exists
`Settings > General > Save position on quit`

**Comment by Geobert** [comment]
Thank you for your answer!

However, I can't see this option on 2018-04-29-alpha (from Play Store)

**Comment by Geobert** [comment]
Tried nightly build, and can see the option there. However, it does not work if I press Home. I need to press Back. (see https://github.com/mpv-android/mpv-android/issues/162)
