### ISSUE TITLE
Open MPV with CLI(termux) ?

### ISSUE THREAD

**Issue by Justsoos** [mpv-android/mpv-android#165]
As we know, termux had a build-in Mpv, but it can not play video correctly.
https://github.com/termux/termux-packages/issues/878

So, I found a way to open Mpv app, like:
`$ am start -n is.xyz.mpv/is.xyz.mpv.MainActivity`
But till now, I have no idea to pass the URL or path to MPV app by this way.
Could U guys make a patch for it? Or just show me the parameters of CLI call method?

**Comment by andrew-shulgin** [comment]
Hello! You can call **MPVActivity** with **filepath** parameter:
`$ am start -n is.xyz.mpv/is.xyz.mpv.MPVActivity -e filepath <url>`

**Comment by Justsoos** [comment]
Either `am start -n is.xyz.mpv/is.xyz.mpv.MainActivity -e` or
`am start -n is.xyz.mpv/is.xyz.mpv.MPVActivity -e `got same result:
`Error: Argument expected  pathfile`
My mpv installed from Google play store.

**Comment by andrew-shulgin** [comment]
Please read the command more carefully and replace `<url>` with your URL.

**Comment by Justsoos** [comment]
Sorry, lost the word "after" by copy & paste, the error prompt is 
`Error: Argument expected after <path file>`

**Comment by andrew-shulgin** [comment]
So pass your URL there

**Comment by Justsoos** [comment]
Btw, is here a wiki page for this interface, like howto pass the `referrer`, `ytdl=no` to MPV app?

**Comment by kn-yami** [comment]
Why would you need to pass `ytdl=no`? AFAIK `mpv-android` is already compiled without `ytdl` support...

**Comment by Justsoos** [comment]
> Why would you need to pass `ytdl=no`? AFAIK `mpv-android` is already compiled without `ytdl` support...

Just an example to get the point, as I have worked well with MuPV on non-Adroid OS by CLI.

**Comment by kn-yami** [comment]
I see. The problem with passing command line options to `mpv-andoid` is caused by that fact that `mpv-android` is an Android application that uses `libmpv` and the only the application itself can set the `libmpv` options. In theory you could have an easily accessible configuration file - `/sdcard/custom.conf` for example - included in the `mpv.conf` that you can edit using application's UI (`include=/sdcard/custom.conf`) that you could edit before opening a file. This would be the closest equivalent to CLI options that I can think of.

**Comment by icewyvrn** [comment]
> Hello! You can call **MPVActivity** with **filepath** extra parameter: `$ am start -n is.xyz.mpv/is.xyz.mpv.MPVActivity -e filepath <url>`

how do you pass subtitle?

**Comment by Rendevior** [comment]
> As we know, termux had a build-in Mpv, but it can not play video correctly. [termux/termux-packages#878](https://github.com/termux/termux-packages/issues/878)
> 
> So, I found a way to open Mpv app, like: `$ am start -n is.xyz.mpv/is.xyz.mpv.MainActivity` But till now, I have no idea to pass the URL or path to MPV app by this way. Could U guys make a patch for it? Or just show me the parameters of CLI call method?

If you're interested, you could pass arguments easily via cli using this [wrapper](https://github.com/Rendevior/mpv-android-argparse).
