### ISSUE TITLE
save position is common for all file

### ISSUE THREAD

**Issue by Geobert** [mpv-android/mpv-android#169]
With "save to position" enable (build 231), when using a external explorer, opening a video file, quitting (using back) and opening a new video, this new video start at the position saved for the other video

**Comment by sfan5** [comment]
This is due to `content://` URIs being resolved into just a file description from the view of libmpv.
An easy possible fix would be to override the path mpv hashes for saving positions, if that's possible.

**Comment by wnoun** [comment]
We can hook `on_load`, then pass `content` URIs to mpv and set `stream-open-filename` in hook with the file descriptor. Also I think the `stream_cb` API is a right solution.

**Comment by sfan5** [comment]
We used to have a [`stream_cb` based solution](https://github.com/mpv-android/mpv-android/blob/mpv-android-2017-06-14/app/src/main/jni/android_content.cpp), but this was dropped in favor of resolving the fd in the Java part. Maybe it's time to reintroduce that.

**Comment by sfan5** [comment]
This is <i>mostly</i> fixed by 65478aa44813a191f1d39cacdbfe4d33fc7edd9f, though the bug will still happen with some apps (e.g. Google Drive).
The bug will be fully fixed when the `stream_cb` solution is added again (probably soon).
