### ISSUE TITLE
[ffmpeg/video:error] hevc_mediacodec: Failed to dequeue output buffer (status=-542398533)

### ISSUE THREAD

**Issue by tanyiok1234** [mpv-android/mpv-android#170]
Environment：Sony XZ Premium (Snapdragon 835)

Issues: HEVC Main10 hardware decoding fails. OMX.qcom.video.decoder.hevc can be started successfully, but soon fallback to software decoding due to "hevc_mediacodec: Failed to dequeue output buffer (status=-542398533)".

PS: If I enforcing “vo=mediacodec_embed, hwdec="mediacodec" by modify MPVView.kt，hardware decoding works. But predictably, interpolation loss it functions, which is the most outstanding point of MPV in my point of veiw. But at least proofs the OMX decoder works fine.

log：
`
02-20 00:35:28.733 30033  [vo/gpu:v] Assuming 60.000004 FPS for display sync.
02-20 00:35:28.733 30033  1217 V mpv     : [vd:v] Container reported FPS: 23.976025
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v] Codec list:
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v]     hevc - HEVC (High Efficiency Video Coding)
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v]     hevc_v4l2m2m (hevc) - V4L2 mem2mem HEVC decoder wrapper
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v]     hevc_mediacodec (hevc) - H.265 Android MediaCodec decoder
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v] Opening decoder hevc
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v] Looking at hwdec hevc_mediacodec-mediacodec-copy...
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v] Trying hardware decoding via hevc_mediacodec-mediacodec-copy.
02-20 00:35:28.734 30033  1217 V mpv     : [vd:v] Using underlying hw-decoder 'hevc_mediacodec'
02-20 00:35:28.735 30033  1217 V mpv     : [vd:v] Pixel formats supported by decoder: mediacodec
02-20 00:35:28.735 30033  1217 V mpv     : [vd:v] Codec profile: unknown (0xffffff9d)
02-20 00:35:28.735 30033  1217 V mpv     : [vd:v] Requesting pixfmt 'mediacodec' from decoder.
02-20 00:35:28.735 30033  1217 V mpv     : [ffmpeg/video:v] hevc_mediacodec: Using surface 0x0
02-20 00:35:28.735 30033  1217 V mpv     : [ffmpeg/video:warn] hevc_mediacodec: Unsupported or unknown profile
02-20 00:35:28.898 30033  1217 V mpv     : [ffmpeg/video:v] hevc_mediacodec: Output crop parameters top=0 bottom=1079 left=0 right=1919, resulting dimensions width=1920 height=1080
02-20 00:35:28.898 30033  1217 V mpv     : [ffmpeg/video:v] hevc_mediacodec: MediaCodec started successfully: codec = OMX.qcom.video.decoder.hevc, ret = 0
02-20 00:35:28.898 30033  1217 V mpv     : [vd:v] Selected codec: hevc (HEVC (High Efficiency Video Coding))
02-20 00:35:28.898 30033  1217 V mpv     : [vf:v] User filter list:
02-20 00:35:28.898 30033  1217 V mpv     : [vf:v]   (empty)
02-20 00:35:28.899 30033  1217 V mpv     : event: audio-reconfig
02-20 00:35:28.900 30033  1217 V mpv     : [ad:v] Codec list:
02-20 00:35:28.900 30033  1217 V mpv     : [ad:v]     flac - FLAC (Free Lossless Audio Codec)
02-20 00:35:28.900 30033  1217 V mpv     : [ad:v] Opening decoder flac
02-20 00:35:28.900 30033  1217 V mpv     : [ad:v] Requesting 1 threads for decoding.
02-20 00:35:28.900 30033  1217 V mpv     : [ad:v] Selected codec: flac (FLAC (Free Lossless Audio Codec))
02-20 00:35:28.900 30033  1217 V mpv     : event: audio-reconfig
02-20 00:35:28.900 30033  1217 V mpv     : [af:v] User filter list:
02-20 00:35:28.900 30033  1217 V mpv     : [af:v]   (empty)
02-20 00:35:28.900 30033  1217 V mpv     : [cplayer:v] Starting playback...
02-20 00:35:28.901 30033  1217 V mpv     : event: file-loaded
02-20 00:35:28.908 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.908 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.909 30033  1217 V mpv     : [af:v] [in] 48000Hz stereo 2ch s32
02-20 00:35:28.909 30033  1217 V mpv     : [af:v] [userspeed] 48000Hz stereo 2ch s32
02-20 00:35:28.909 30033  1217 V mpv     : [af:v] [userspeed] (disabled)
02-20 00:35:28.909 30033  1217 V mpv     : [af:v] [convert] 48000Hz stereo 2ch s32
02-20 00:35:28.909 30033  1217 V mpv     : event: chapter-change
02-20 00:35:28.910 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.910 30033  1217 V mpv     : [ao:v] Trying audio driver 'opensles'
02-20 00:35:28.910 30033  1217 V mpv     : [ao/opensles:v] requested format: 48000 Hz, stereo channels, s32
02-20 00:35:28.923 30033  1217 V mpv     : [ao/opensles:v] device buffer: 12000 samples.
02-20 00:35:28.923 30033  1217 V mpv     : event: audio-reconfig
02-20 00:35:28.923 30033  1217 V mpv     : [ao/opensles:v] using soft-buffer of 12000 samples.
02-20 00:35:28.923 30033  1217 V mpv     : [cplayer:info] AO: [opensles] 48000Hz stereo 2ch s16
02-20 00:35:28.923 30033  1217 V mpv     : [cplayer:v] AO: Description: OpenSL ES audio output
02-20 00:35:28.923 30033  1217 V mpv     : [autoconvert:v] inserting resampler
02-20 00:35:28.923 30033  1217 V mpv     : [swresample:v] format change, reinitializing resampler
02-20 00:35:28.923 30033  1217 V mpv     : [swresample:v] 48000Hz stereo s32 -> 48000Hz stereo s16
02-20 00:35:28.924 30033  1217 V mpv     : [af:v] [out] 48000Hz stereo 2ch s16
02-20 00:35:28.924 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.925 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.925 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.927 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.927 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.927 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.928 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.929 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.930 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.931 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.933 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.935 30033 30033 E mpv     : mpv_get_property(track-list/0/lang) format 1 returned error property unavailable
02-20 00:35:28.935 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.942 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.942 30033 30033 V mpv     : auto rotation: aspect ratio = 1.7777778
02-20 00:35:28.942 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.942 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.942 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.943 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.943 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.945 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.951 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.955 30033  1217 V mpv     : [vd:warn] could not consume packet

（ignore same warnings manually)

02-20 00:35:28.981 30033  1217 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
02-20 00:35:28.981 30033  1217 V mpv     : [ffmpeg/video:error] hevc_mediacodec: Failed to dequeue output buffer (status=-542398533)
02-20 00:35:28.981 30033  1217 V mpv     : [vd:warn] Error while decoding frame!
02-20 00:35:28.981 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.982 30033  1217 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
02-20 00:35:28.982 30033  1217 V mpv     : [ffmpeg/video:error] hevc_mediacodec: Failed to dequeue output buffer (status=-542398533)
02-20 00:35:28.982 30033  1217 V mpv     : [vd:warn] Error while decoding frame!
02-20 00:35:28.982 30033  1217 V mpv     : [vd:warn] could not consume packet
02-20 00:35:28.982 30033  1217 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
02-20 00:35:28.982 30033  1217 V mpv     : [ffmpeg/video:error] hevc_mediacodec: Failed to dequeue output buffer (status=-542398533)
02-20 00:35:28.982 30033  1217 V mpv     : [vd:warn] Error while decoding frame!
02-20 00:35:28.983 30033  1217 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
02-20 00:35:28.983 30033  1217 V mpv     : [ffmpeg/video:error] hevc_mediacodec: Failed to flush codec
02-20 00:35:33.103 30033  1217 V mpv     : [vd:v] Falling back to software decoding.
02-20 00:35:33.103 30033  1217 V mpv     : [vd:v] Detected 8 logical cores.
02-20 00:35:33.103 30033  1217 V mpv     : [vd:v] Requesting 9 threads for decoding.
02-20 00:35:33.104 30033  1217 V mpv     : [vd:v] DR failed - disabling.
02-20 00:35:33.180 30033  1217 V mpv     : [vd:v] Using software decoding.
`

**Comment by sfan5** [comment]
Likely stale.
