### ISSUE TITLE
Is there an example for JAVA?

### ISSUE THREAD

**Issue by grahaisw** [mpv-android/mpv-android#171]
I'm very interested for using mpv library, but i need a time to learn the Kotlin language. Is there any example for using libmpv in JAVA Android?

Thank you in advance.

**Comment by sfan5** [comment]
mpv-android does __not__ provide an embeddable libmpv on Android.

If you want to use libmpv in your own Android app, take a look at these:
https://github.com/mpv-android/mpv-android/blob/master/app/src/main/java/is/xyz/mpv/MPVLib.java
https://github.com/mpv-android/mpv-android/tree/master/app/src/main/jni
