### ISSUE TITLE
File picker broken on newer Android versions due to default home path being /sdcard

### ISSUE THREAD

**Issue by VitinhoCarneiro** [mpv-android/mpv-android#173]
Issue found on Lenovo Moto Z Play, stock Android 8.0.0-retbr.

Every time you install mpv-android, the default path is set to `/sdcard` - this folder is inexistent on newer versions of Android, and causes the file browser to look for files in the system root - which is normally inaccessible, leading to nothing being listed.

This may cause potential users to drop the application, thinking it does not work and does not list the files.

The current mitigation for this issue is to manually go on the configuration menu and set the default path to `/storage/emulated/0`.

**Comment by sfan5** [comment]
Is there any documentation on which directories apps can expect to exist?
Perhaps the default should be determined using [`getExternalStorageDirectory()`](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory%28%29)

**Comment by samoht0** [comment]
The common fail-safe solution on system side it to have a legacy symlink /sdcard (and some more).
Hardly understandable to remove it, as this should cause problems with quite a few apps.
Legacy paths are typically symlinked in init.rc (example):
https://android.googlesource.com/device/lge/hammerhead/+/3251ef5/init.hammerhead.rc

> Perhaps the default should be determined using [`getExternalStorageDirectory()`](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory%28%29)

Looks good to me.

**Comment by sfan5** [comment]
Well, as it turns out, that is exactly what the code does:
https://github.com/mpv-android/mpv-android/blob/d052d782f5392a39cc7d48738973bfd6e1f6077c/app/src/main/java/is/xyz/mpv/MainActivity.kt#L32-L33

Are all Android 8 ROMs broken this way?

**Comment by samoht0** [comment]
> Are all Android 8 ROMs broken this way?

No, updated legacy symlinks still present in google's source:
https://android.googlesource.com/platform/system/core/+/refs/tags/android-cts-8.1_r14/rootdir/init.rc
And so, fine with LineageOS 15.1 (8.1 base):
https://github.com/LineageOS/android_system_core/blob/lineage-15.1/rootdir/init.rc

Would be interesting, if the Moto Z Play has a /sdcard symlink and, if so, where it points (/ should be readable without elevated privileges, I guess).

**Comment by VitinhoCarneiro** [comment]
Okay, that's weird. I just tested and /sdcard indeed maps to my internal storage. Configuring the starting directory to /sdcard in mpv does indeed work.

I just noticed now, that upon clearing the user data and opening the app as if it was the first time, and giving the app access to storage (as is requested), the directory shown in the file manager is indeed /; however, the initial directory is then immediately set to /sdcard, and exiting and reopening the app makes it load the correct directory. It's as if it tried to load the starting directory before it was set.

Maybe it has something to do with the storage access permission?

**Comment by samoht0** [comment]
> Maybe it has something to do with the storage access permission?

You can test it like this:
* remove and re-install app
* grant storage permission in app's settings *before* first launch
If this works fine, it looks like some permission granting issue.

On SLIM6: No problems with granting permission at runtime after first launch.

**Comment by VitinhoCarneiro** [comment]
Indeed, by enabling the storage permission before opening the app, the file browser launches correctly, but on /storage/emulated/0 instead of /sdcard, which is the configured starting path for the file browser. Reopening the app then makes the file browser open on /sdcard.

Both locations do map to the same place, but this may be some useful information on fixing the bug.

**Comment by sfan5** [comment]
I guess this is part of the problem:
<pre>
src/main/res/xml/pref_general.xml:        android:defaultValue="/sdcard"
</pre>

**Comment by samoht0** [comment]
AFAIK "/sdcard" should be fine on storage side (apart from badly hacked roms). As reported above, it works with pre-enabled storage permission.
"/storage/emulated/0" is unsuitable, as it represents user#0 (main) and breaks usage, if there're more users.
Is there any permission handling included in the code?

**Comment by sfan5** [comment]
this is the only permission handling code I can find
https://github.com/mpv-android/mpv-android/blob/d052d782f5392a39cc7d48738973bfd6e1f6077c/app/src/main/java/is/xyz/filepicker/FilePickerFragment.java#L61-L82

**Comment by samoht0** [comment]
OK, and beginning line 84 there's a check for granted permission and if so, path is refreshed. Looks sane.
Considering the stated problem, refreshing path fails, even if permission is granted. Restart helps. Race condition or some security restriction with newer android versions? Don't know.
Easiest option would be to fill in some permission description (...required to play your locally stored files. Granting permission might need to restart app to take effect, or something).

**Comment by samoht0** [comment]
It's OT, but I hope the short question is OK here:
Why are Travis builds done with some rather old pinned ffmpeg commit source?

**Comment by sfan5** [comment]
Because nobody bothered to update the pinned commit and it still builds fine using that old version.

**Comment by Skrilltrax** [comment]
Hi, just came across this and on first launch after accepting the file permission the app is at `/` instead `/sdcard`. Subsequent launches seems fine. Also android Q is bringing scoped storage so that needs to be fixed too i guess.
