### ISSUE TITLE
Video position resets when toggling split screen.

### ISSUE THREAD

**Issue by Chuunie** [mpv-android/mpv-android#177]
When toggling split screen (long press recents button) the video position resets to the beginning. Enabling save position on quit doesn't change the behaviour. Running Android 9, LineageOS 16, mpv-android 2019-04-18 Test Build.

**Comment by sfan5** [comment]
I have attempted to fix this in d3307d482e61b3b18350ba26e8f011751d91abdf, but I can't test it myself.
