### ISSUE TITLE
Android Laggy playback

### ISSUE THREAD

**Issue by xDevi69** [mpv-android/mpv-android#180]
### mpv version and platform
mpv-android 2019-04-18-alpha (Shield TV)

### Reproduction steps
Playing any 4K HDR content on a SDR screen.

### Expected behavior
Smooth playback, HDR to SDR tonemapping.

### Actual behavior
Laggy playback.

### Sample files

Any 4K HDR HEVC video file.

**Comment by sfan5** [comment]
So, do you have a log file?
