### ISSUE TITLE
Settings become almost unreadable if the device is using a dark theme

### ISSUE THREAD

**Issue by VitinhoCarneiro** [mpv-android/mpv-android#181]
When your system UI is using a dark theme, the default text color is set to white so that it can be read on a dark background.

However, the settings menu on mpv enforces a whitish background for some reason, but the default font color is used, resulting in the user being completely unable to read any of the settings.

The screenshots below demonstrate this effect. (AOSiP 9.0, dark theme)

![Screenshot_mpv_20190428-220433](https://user-images.githubusercontent.com/16991318/56872684-3862f900-6a02-11e9-9ede-d9677b3370f7.png)
![Screenshot_mpv_20190428-220446](https://user-images.githubusercontent.com/16991318/56872683-37ca6280-6a02-11e9-8e1a-4dade9fd2d2b.png)

This makes it almost impossible to use the settings menu - the only way to be able to read the labels on each option is by long-pressing on them, resulting in an opaque beige highlight being drawn under the text and making it somewhat readable.

**Comment by sfan5** [comment]
Probably fixed since settings have an explicit theme now.
