### ISSUE TITLE
Error when run app

### ISSUE THREAD

**Issue by khizar1556** [mpv-android/mpv-android#192]
when i run the app from android studio it gives the error
Execution failed for task ':app:mergeDebugJniLibFolders'.
 can anyone please describe it how it will be solved?

**Comment by khizar1556** [comment]
i am trying to run buildscript on windows but it gives diferent error everytime please tell me how can i access the library

**Comment by khizar1556** [comment]
@xyzz @tmm1 @jeeb @sfan5  please review this 

when i run this buildall.sh it gives warning and error can you please see i am using git bash to run this commands on windows

 sh buildall.sh
Building mpv-android...
Dependencies: mpv
Target mpv not found
/c/mpv-android /c/mpv-android/buildscripts
Warning: libmpv.so not found in native prefix for arm64, support will be omitted
Warning: libmpv.so not found in native prefix for x86_64, support will be omitted
Warning: libmpv.so not found in native prefix for x86, support will be omitted
buildscripts/scripts/mpv-android.sh: line 31: ndk-build: command not found
/c/mpv-android/buildscripts
ls: cannot access '../app/build/outputs/apk/debug/*.apk': No such file or directory
ls: ca

**Comment by xyzz** [comment]
It's not possible to build this on Windows, you need Linux or osx.

**Comment by khizar1556** [comment]
@xyzz i tried it on linux but it still gives an error Target mpv not found

**Comment by xyzz** [comment]
https://github.com/mpv-android/mpv-android/blob/master/buildscripts/README.md#build

**Comment by khizar1556** [comment]
@xyzz do me a favour can you please make me a short video

**Comment by khizar1556** [comment]
i got this error when i run /.download.sh
error
‘sdk-tools-linux-3859397.zip.1’ saved [136964098/136964098]

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 5 more


when i run /.buildall.sh
error is :
Building mpv-android...
Dependencies: mpv
Target mpv not found
~/personalProjects/mpv-android ~/personalProjects/mpv-android/buildscripts
Warning: libmpv.so not found in native prefix for arm64, support will be omitted
Warning: libmpv.so not found in native prefix for x86_64, support will be omitted
Warning: libmpv.so not found in native prefix for x86, support will be omitted
buildscripts/scripts/mpv-android.sh: line 31: ndk-build: command not found
~/personalProjects/mpv-android/buildscripts
ls: cannot access '../app/build/outputs/apk/debug/*.apk': No such file or directory
ls: cannot access '../app/build/outputs/apk/release/*.apk': No such file or directory

please solve this @xyzz 
please sir

**Comment by xyzz** [comment]
Try this solution https://stackoverflow.com/a/51644855

**Comment by khizar1556** [comment]
@xyzz  check this erro now 
make[1]: armv7a-linux-androideabi21-clang: Command not found
Makefile:195: recipe for target 'aes.o' failed
make[1]: *** [aes.o] Error 127
Makefile:18: recipe for target 'lib' failed
make: *** [lib] Error 2
in buildall.sh file
