### ISSUE TITLE
No video output from a h.264 10bit file

### ISSUE THREAD

**Issue by ghost** [mpv-android/mpv-android#193]
Every other video formats (such as HEVC, 10-bit HEVC, and regular h.264) works pretty well on MPV. However on 10bit h.264 the video just refuses to play and instead outputs a black screen. I've tried playing the same video file through Samsung's built-in video player which works fine and I've also tried playing it on other players such as VLC and MX Player which also works fine so I'm sure that my hardware can actually play these videos.

I've also tried using the Hardware decoding feature, with 
mediacodec using these options...
--vo=mediacodec_embed 
--hwdec=mediacodec
--wid=(intptr_t)(*android.view.Surface) 

and

mediacodec-copy using these options....
--vo=gpu
--hwdec=mediacodec_copy
--gpu-context=android

Additional settings that I have in my conf. are saturation, speed and panscan which I'm sure aren't messing anything up. 

I'm really confused and don't really understand what's going on, can someone help me out. I would also supply a "log file" but I don't know how to make mpv produce one.

Thanks.

**Comment by aeseok** [comment]
Sorry this was my old account I lost access to it.

**Comment by aeseok** [comment]
I lost access to this account so I had to make a new one. Still waiting for some assistance.

**Comment by aeseok** [comment]
I fixed this by setting deband onto CPU. I have no idea how that worked I was just going through the settings and trying out random things and then it started working. Can a mod set this issue as closed.

**Comment by sfan5** [comment]
Enabling cpu deband has the side effect of converting frames to yuv420p (8-bit) before output.
If 10-bit rendering is indeed the problem (driver bug?), you can just use `--vf=format=yuv420p` as an easier workaround.

**Comment by aeseok** [comment]
Ah, I see thanks again!
