### ISSUE TITLE
Vertical artifacting on Galaxy Tab S4

### ISSUE THREAD

**Issue by 7h3-b1g-b055** [mpv-android/mpv-android#196]
When playing back videos, I've been noticing vertical stripe artifacts that move around as the video plays.

![Screenshot_20190711-023717_mpv](https://user-images.githubusercontent.com/32139837/62108231-25fd9300-b26f-11e9-896c-bf6ae97070ea.jpg)

And here's the same shot in VLC:
![Screenshot_20190711-023621_VLC](https://user-images.githubusercontent.com/32139837/62108240-301f9180-b26f-11e9-87b4-417a1750d942.jpg)

It may be a little hard to tell, but if you look closely, you can clearly see lines going up and down the video that aren't supposed to be there (it's most obvious between her eyes). This happens with a fresh install as well. I'm sorry if I'm not describing it too well, but I don't know the correct vocabulary for whatever's going on here.

Here's the logcat for playing a video:
https://pastebin.com/LxpaQQhZ

And a couple more shots:
![Screenshot_20190730-021352_mpv](https://user-images.githubusercontent.com/32139837/62108512-db304b00-b26f-11e9-969b-4748e1fa064b.jpg)

![Screenshot_20190730-021216_mpv](https://user-images.githubusercontent.com/32139837/62108523-df5c6880-b26f-11e9-8ac2-4a058f2831ab.jpg)

FWIW, this doesn't seem to happen on my Galaxy Note 8 which has essentially the same hardware, so it might have to do with the different resolutions of the devices.

**Comment by sfan5** [comment]
Scaler settings, anything in mpv.conf?
I've seen this before when the GPU can't quite handle the scaler for whatever reason (also on a Samsung tablet with 1440p display in fact).

> my Galaxy Note 8 which has essentially the same hardware

Does that include the same GPU and the same screen resolution?

**Comment by 7h3-b1g-b055** [comment]
mpv.conf:
```
demuxer-seekable-cache=yes
demuxer-max-back-bytes=157286400

profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
glsl-shader="FSRCNNX_x2_16-0-4-1.glsl"
glsl-shader="KrigBilateral.glsl"
glsl-shader="adaptive-sharpen.glsl"
linear-downscaling=no
sigmoid-upscaling=no
volume-max=150
```
(I basically use the same conf on android as I do for desktop, though that may be unwise.)
Scalar settings are lanczos for both up and down scaling in the video settings. 

The note has a 2960x1440 display, 6 GB of ram, a SD 835 and Adreno 540. The Tab S4 has a 2560x1600 display, 4 GB of RAM, and the same SD 835 and Adreno 540.

**Comment by 7h3-b1g-b055** [comment]
On another note, I've just discovered that I could reproduce the issue if I put `profile=gpu-hq` in the mpv.conf on my phone. It also went away when I got rid of it on my tablet, so that had to be the culprit. You can consider this issue solved.
