### ISSUE TITLE
Couldn't find "libmpv.so"

### ISSUE THREAD

**Issue by fahadpadhiar** [mpv-android/mpv-android#20]
Hello ,
           I downloaded the source code and installed it on an android device. On playing a file the app crashes and it says Couldn't find "libmpv.so". How can i get this file ? any help would be highly appreciated.

Regards
Fahad Padhiar

**Comment by xyzz** [comment]
Are you building using buildscripts? https://github.com/mpv-android/buildscripts

**Comment by fahadpadhiar** [comment]
Thanks a lot for your kind response. I have successfully build it using the above build-scripts. I have "libmpv.so" and other .so files now as well. I  highly appreciate your swift response. 
Thanks

**Comment by khizar1556** [comment]
@xyzz i building using buildscripts but i dont get any libmpv and .so files
