### ISSUE TITLE
Suggestion add 'max_stream_bps' to .conf

### ISSUE THREAD

**Issue by yo-1234** [mpv-android/mpv-android#202]
suggestion to add 'max_stream_bps' to .conf
I have a 4Mbs connection that I have found works well at <2Mbs
If the contents of a m3u8 link are inspected, the following might be seen:

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=803724,AVERAGE-BANDWIDTH=535424,RESOLUTION=416x234,CODECS="avc1.4d600d,mp4a.40.2"
[track1].m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1537462,AVERAGE-BANDWIDTH=1024224,RESOLUTION=640x360,CODECS="avc1.4d601e,mp4a.40.2"
[track2].m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2533088,AVERAGE-BANDWIDTH=1687488,RESOLUTION=854x480,CODECS="avc1.4d601e,mp4a.40.2"
[track3].m3u8

Now by comparing 'max_stream_bps' to those bandwidth numbers, mpv could select a stream with Mbs  (for this example) of track2. (lower resolution picture).

This is not an original suggestion on my part, I have seen it implemented in another program (with a strange, perhaps Wierd name), and it Works really,really well on a live stream.

It is also of interest to know that while a (uber)stream might originate from a distant land, the [tracks] might not. And these datas in the case of a live stream,  cannot arrive faster than frame rate.

I suggest adding this to .conf rather than on screen because .conf much simpler, (re-initialisation of stream not required).

Perhaps a 'geek stats' display on stream load might help?

Thanks.

**Comment by sfan5** [comment]
mpv has an option for that: [`--hls-bitrate`](https://mpv.io/manual/master/#options-hls-bitrate)
