### ISSUE TITLE
Seek gestures conflict with android 10 navigation

### ISSUE THREAD

**Issue by philipl** [mpv-android/mpv-android#203]
The new android 10 gesture navigation conflicts fairly badly with the seek gestures. You have to use 'back' to return from the player to the file browser and you're much more likely to seek in the player than manage a back gesture. Seems like we need an explicit area where seek won't trigger, like having seek in the top half and back in the bottom half, for example.

**Comment by philipl** [comment]
Given that the more likely conflict is seeking when you want to go back, adding a stop button would avoid the need to use the back gesture. That could be done as configuration via #206 if not a first class action.

**Comment by KaKi87** [comment]
Hello,

I'm experiencing the same issue.

For now I can't find any other way than killing and re-opening the app.

Any news on the button idea ?

Thanks

**Comment by sfan5** [comment]
You now need to show the player UI first before performing a gesture.

**Comment by KaKi87** [comment]
You mean click then swipe instead of just swipe ? That's really bad UX.

**Comment by sfan5** [comment]
Yes.
Bad UX for a video player that's usually in immersive mode anyway? Hmm I wouldn't say so.

**Comment by KaKi87** [comment]
Before this change, seeking would require : touchstart -> touchmove -> touchend.

After this change, seeking requires : touchstart -> touchend -> touchstart -> touchmove -> touchend.
