### ISSUE TITLE
How to build in Windows (Android Studio)?

### ISSUE THREAD

**Issue by gmikhail** [mpv-android/mpv-android#207]
When I try to build android project in Android Studio I get an error

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugJniLibFolders'.
...
Caused by: java.lang.NullPointerException
...
```
As I understand, first I need to build all libraries and mpv-android native code. But whet I try to do it, I get

```
$ sh buildall.sh --no-deps mpv-android
Building mpv-android...
/d/Documents/GitHub/mpv-android /d/Documents/GitHub/mpv-android/buildscripts 
Warning: libmpv.so not found in native prefix for arm64, support will be omitted
Warning: libmpv.so not found in native prefix for x86_64, support will be omitted
Warning: libmpv.so not found in native prefix for x86, support will be omitted
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in ./AndroidManifest.xml. NDK binaries will *not*  be compatible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problem s.md for more information.
Android NDK: ERROR:jni/Android.mk:swresample: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that D:/Documents/GitHub/mpv-android/buildscripts/scripts/../prefix/armv7l/lib/libswresample.so exists  or that its  path is correct
make: Entering directory `D:/Documents/GitHub/mpv-android/app/src/main'
make: Leaving directory `D:/Documents/GitHub/mpv-android/app/src/main'
C:/Users/Mikhail/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../build/core/prebuilt-library.mk:45: *** Android NDK: Aborting     .  Stop.
/d/Documents/GitHub/mpv-android/buildscripts
ls: cannot access '../app/build/outputs/apk/debug/*.apk': No such file or directory
ls: cannot access '../app/build/outputs/apk/release/*.apk': No such file or directory
```

So... how do I build libmpv.so and libswresample.so?

**Comment by xyzz** [comment]
See the docs in https://github.com/mpv-android/mpv-android/blob/master/buildscripts/README.md. Windows is not supported by the build scripts but it might work if you use WSL.

**Comment by gmikhail** [comment]
> See the docs in https://github.com/mpv-android/mpv-android/blob/master/buildscripts/README.md. Windows is not supported by the build scripts but it might work if you use WSL.

Thanks, I will try.
PS: I can not add "help wanted" label. Is this prohibited in this repository? Or am I just blind?

**Comment by purvagevaria** [comment]
Hi @gmikhail  and @tanyiok1234 your issues got resolved? I am struggling for 2 days with the same issue.

**Comment by salman660** [comment]
> Well, interestingly....I am struggling with the "Execution failed for task ':app:mergeDebugJniLibFolders' " error now.
> 
> By the way, I am using the original ./buildall.sh script under WSL. I am not sure what's going wrong.

Same here help please

**Comment by purvagevaria** [comment]
@salman660 @tanyiok1234 I was also facing the same issue with wsl. I performed build steps in ubuntu 20 and migrate code in windows android studio and that worked for me but that is too much lengthy process and right now library buid doesn't have windows os support so I am struggling with same.
