### ISSUE TITLE
request: orientation OSD button

### ISSUE THREAD

**Issue by nahuhh** [mpv-android/mpv-android#209]
Request:
- OSD button to force an orientation switch
- setting within "settings>video" to set the default orientation

Options for
- Smart (plays portrait videosin portrait and landscape videos in landscape) 
- Device (follows device setting)
- Free rotation (even if device is locked you can rotate) 
- Force landscape
- Force portrait

**Comment by sfan5** [comment]
mpv-android already has these:
> - OSD button to force an orientation switch
> - setting within "settings>video" to set the default orientation
> - Smart (plays portrait videosin portrait and landscape videos in landscape) 
> - Force landscape
> - Force portrait

**Comment by grravity** [comment]
Unless I'm missing something, where is the OSD button?

Settings > video is the default orientation, however I see nothing to change it per video on the video OSD.

A similar option for aspect ratio adjustment would be appreciated too.

**Comment by sfan5** [comment]
The button to switch orientation only appears if you have Settings > General > Screen orientation set to anything _except_ "Automatic".

**Comment by grravity** [comment]
I had it on device orientation, and it's on automatic now. I didn't see the orientation button on either.

**Comment by sfan5** [comment]
Oh, you're right. When the advanced menu was added it was moved into there, it's at the very bottom and titled "Switch Orientation".

**Comment by grravity** [comment]
I see no switch orientation under advanced either, just the aspect ratio adjustment.

**Comment by sfan5** [comment]
I was wrong earlier, the orientation button only appeared when you selected either 'Landscape' or 'Portrait', but not 'Device'.
Since that doesn't make too much sense, I've changed it just now: 1bbc145403cdf1b94911fe433e7a8871580c39d9

**Comment by grravity** [comment]
Thanks, also I was curious but didn't want to open a new issue because it wasn't that important
Does the mpv.conf override settings in the app?
For example if I choose mitchell scaler in mpv settings, but go and set lancoz in the mpv.conf, is it using mitchell or lancoz?

**Comment by sfan5** [comment]
Yes, `mpv.conf` overrides any app settings.
