### ISSUE TITLE
Add support for handling intents

### ISSUE THREAD

**Issue by joshdekock** [mpv-android/mpv-android#21]
So it'd be nice if you could open mpv from other apps, like the gallery, and for this you need to handle intents. This is described in https://developer.android.com/training/basics/intents/filters.html

**Comment by xyzz** [comment]
That's already implemented, does it not work for you?

**Comment by joshdekock** [comment]
Oops, yes, it was just a problem with defaults. I had to unset the other ones (and then reboot because it wasn't registering). After that it works.
