### ISSUE TITLE
Feature request: support for MediaSession

### ISSUE THREAD

**Issue by pbienst** [mpv-android/mpv-android#212]
Are there any plans to support MediaSession?

https://medium.com/androiddevelopers/building-a-video-player-app-in-android-part-3-5-19543ea9d416

This would increase the usability of mpv-android for background audio play tremendously: controls from the lock screen, headset or Android wear, ...

**Comment by sfan5** [comment]
Since mpv-android does not use ExoPlayer, media session is not applicable to it.
We need to implement any desired features that it would other provide manually, this is already done for e.g. the media notification.

**Comment by pbienst** [comment]
Perhaps I should study this in more detail, but I was under the impression that the MediaSession API is middleware that is independent of the exact backend that is used to do the actual media playing (exoplayer, libmpv,...)

Seems like a good way to avoid having to reinvent the wheel...

https://medium.com/androiddevelopers/understanding-mediasession-part-1-3-e4d2725f18e4
https://developer.android.com/reference/android/media/session/MediaSession

**Comment by sfan5** [comment]
I didn't look at it in detail either, it appears MediaSession is indeed implementation-agnostic.

A few more links:
https://developer.android.com/guide/topics/media-apps/audio-app/mediasession-callbacks
https://developer.android.com/guide/topics/media-apps/mediabuttons

**Comment by MrSenshi** [comment]
I'd very much like to see this implemented for better background play and notification buttons. That would make mpv-android a more viable minimalist music player for me.
