### ISSUE TITLE
Only Audio Plays. No Video

### ISSUE THREAD

**Issue by jcorder481** [mpv-android/mpv-android#213]
Hello. MPV isn't giving me any video on my device. Audio is playing but hw decode shows a mostly black screen with some flashing white lines. SW decode shows a bit more--like if the video is trying to play but it's a few more lines and the video is tiled on the display.

Device is a stock Galaxy Note 3 on Android 5.0. In vlc and other apps the video plays fine. On the same device but custom 8.1 rom the video plays fine in mpv. Any suggestions?

Log file below. Thank you in advance.

https://pastebin.com/DSsA1NZC

**Comment by sfan5** [comment]
Since it doesn't work with software decoding either I'd say this is a case of broken drivers.
Doubt it would help, but you can try `fbo-format=rgba8` in mpv.conf.

**Comment by jcorder481** [comment]
Thanks for the reply. Unfortunately it didn't change anything. Opening mpv.conf I saw:

dither-depth=auto

I forgot I tried that from an earlier googling. Both options together and separate didn't work.
