### ISSUE TITLE
Drop down menu with extra options (saturation, contrast, ...)

### ISSUE THREAD

**Issue by xdilemite** [mpv-android/mpv-android#214]
Please I would like our esteemed developers to add or include a  button to toggle Android keyboard in order to access mpv traditional keyboard commands. I attached a physical keyboard using  USB otg and was able to change saturation, contrast etc by pressing kbd buttons while playing video. This player has so much potential unlike any media player on android. Thanks in anticipation.

**Comment by sfan5** [comment]
I doubt controlling mpv is going to be comfortable like this:
![cap](https://user-images.githubusercontent.com/1042418/67297982-ed2a2e80-f4ea-11e9-89a3-2a0431dfbb82.jpg)

Exposing everything mpv offers in a good way is not easy, we can't put a million options into a single extra menu.

**Comment by xdilemite** [comment]
Thanks, How about a drop down menu to  cater for traditional keyboard board entries like saturation, contrast etc, although it's possible to set these options in the config.

**Comment by crisalis2** [comment]
> I doubt controlling mpv is going to be comfortable like this:
> ![cap](https://user-images.githubusercontent.com/1042418/67297982-ed2a2e80-f4ea-11e9-89a3-2a0431dfbb82.jpg)
> 
> Exposing everything mpv offers in a good way is not easy, we can't put a million options into a single extra menu.

Well, I wouldn't find it that uncomfortable and it would be just an option for those who want extensive "live" control.

Anyway, what about customizable options for the drop down menu? Just like there's normally the configurable keyboard shortcuts, you'd have here configurable drop down menu shortcuts. With a reasonable limit of them. It's certainly impossible to put a million options into the menu, but allowing the user to put the ones they prefer (changing the default ones) is an interesting solution to the problem, I think.

**Comment by sfan5** [comment]
> Anyway, what about customizable options for the drop down menu? Just like there's normally the configurable keyboard shortcuts, you'd have here configurable drop down menu shortcuts. 

Sure that sounds like a good idea.
How about configuring dropdown options in the style of https://github.com/mpv-android/mpv-android/pull/206#issue-320085700 (though the property stuff is probably not needed)?

**Comment by crisalis2** [comment]
Yes, that looks very interesting. I understand it was a single button that executed a single command? So now it would be a button that opens a menu and each entry of the menu executing a configured command. For configuring something like this, I think just the command and the menu entry title are needed.

**Comment by sfan5** [comment]
Implemented in 0a38cd3b464f110150cd9d394cb72efb5b474e18. You're welcome.
