### ISSUE TITLE
Interpolation flickers on S9+

### ISSUE THREAD

**Issue by Tsubajashi** [mpv-android/mpv-android#216]
Hi!
I recently tried to use interpolation on my Galaxy s9+, but found out it is flickering like crazy.
I tried with hwdec and swdec, but the issue remains the same.
I will include everything needed to fix the issue, aslong as i get help there as i dont know much in that area.
Here is an example how it looks: https://streamable.com/c40oe 
The flicker looks worse irl, the screen Recorder is only 30fps.

**Comment by sfan5** [comment]
version? This bug should have been fixed in 2019-09-02.

**Comment by Tsubajashi** [comment]
@sfan5 the Last release which is on this github. 2019-09-02

**Comment by sfan5** [comment]
Please provide a [`logcat`](https://developer.android.com/studio/command-line/logcat) log.

**Comment by Tsubajashi** [comment]
@sfan5 as soon as i am at home, ill Provide a logcat log

**Comment by Tsubajashi** [comment]
> So?

wasnt at home yet. currently in a bad family situation. i try to get it till the end of the week.,

**Comment by Tsubajashi** [comment]
Alrighty - i wont even be able to send a logcat for a few more days as im not home for a pretty long time. if there is a way to logcat whilst only using a phone that would be awesome, then i could do it faster.

Sorry to disturb you while i cant provide more information. i saw you released a new version - i will test it with that one when i have access to a pc or when i know how to logcat on mobile only.
