### ISSUE TITLE
Calling mpv-android from another app

### ISSUE THREAD

**Issue by philiprhoades** [mpv-android/mpv-android#223]
People,

mpv has been my goto media player on Linux for many years so thanks for mpv-amdroid!

I would like to create my first Android app - partly as an exercise but also recreating something I have done with a script on Linux calling mpv to play a sequence of MP3s.  Is it possible to call mpv-android from a minimal Android app I make?

Thanks,
Phil.

**Comment by sfan5** [comment]
There unfortunately isn't a way to do this.
The intent filters of mpv-android accept media based on metadata *or* HTTP(S) URLs, but no arbitrary file paths. So you wouldn't be able to open an M3U playlist.

**Comment by philiprhoades** [comment]
Damnh . . oh well . .

Thanks for the info!
