### ISSUE TITLE
How to get A-B loop?

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#225]
Hello,

I use the current mpv Android version: 2019-11-03-alpha on my Android 9 Samsung Galaxy S9+ device (no root). 

I want to use A-B loop.

How does it work exactly?

If I tap in mpv android (mpv.conf): 
For single file:
`--ab-loop-a=<01:00>=/storage/emulated/0/test.mp4`
`--ab-loop-b=<09:30>=/storage/emulated/0/test.mp4`

or

`--ab-loop-a=01:00=/storage/emulated/0/test.mp4`
`--ab-loop-b=09:30=/storage/emulated/0/test.mp4`

For all files:
`--ab-loop-a=<01:00>`
`--ab-loop-b=<09:30>`

or 

`--ab-loop-a=01:00`
`--ab-loop-b=09:30`

It doesn't work. I think 01:00 = 1 min and 09:30 = 9 min 30 s, right?

**Comment by sfan5** [comment]
You need to omit the -- inside mpv.conf:
<pre>
ab-loop-a=01:00
ab-loop-b=09:30
</pre>


There's currently no other way to use this functionality from the UI.

**Comment by JoinnA** [comment]
Thanks.

But, how I can make for different single file and not for all files the same.

This is not working:
`ab-loop-a=01:30=/storage/emulated/0/test2.mp4`
`ab-loop-b=10:30=/storage/emulated/0/test2.mp4`

**Comment by JoinnA** [comment]
@sfan5 
You can close the report here. I don't need it anymore.
