### ISSUE TITLE
hwdec-codecs option in mpv.conf ignored/overwritten

### ISSUE THREAD

**Issue by fr5gh** [mpv-android/mpv-android#227]
- mpv-android version: 2019-11-03-alpha

I left hardware decoding enabled in the settings. But would like to make additional settings for hwdec.
For example, I cannot use `hwdec-codecs=hevc`, nothing happens. When I open other video files that do not have a hevc codec, hardware decoding is still used.

**Comment by sfan5** [comment]
This option is hardcoded in the code, it could probably be made configurable <i>somehow</i>:
https://github.com/mpv-android/mpv-android/blob/43078e083bc42cb488097ec7d3db07f3a6e609c7/app/src/main/java/is/xyz/mpv/MPVView.kt#L115
