### ISSUE TITLE
The file view disappears

### ISSUE THREAD

**Issue by fr5gh** [mpv-android/mpv-android#228]
- mpv-android version: 2019-11-03-alpha
- Android 9 device (Samsung Galaxy A50)

The file view disappears in the path `/` after tapping once on the first purple folder.
If you want to go back to the default path `/sdcard`, you have to quit the app.

**Comment by fr5gh** [comment]
A question is also supported in mpv-android (file view) when viewing external storage files e.g. from USB flash drive? 

I can't check it, because when I tap on the first purple folder (with the 2 points `..`). Then I am in `/`, but mpv-android does not show me any folders. There is nothing there.

**Comment by sfan5** [comment]
I have my file picker root set to `/storage/emulated/0`, when I go up twice I arrive at `/storage` which contains a folder for my SD card.

**Comment by JoinnA** [comment]
@sfan5 
Hello,

I also have the same problem and use mpv from the google play store.

I have not changed any settings and use mpv default setting.

When I go up twice I am in / and can't see any file and folders anymore.

some users have the same problem and if they accidentally go up twice (typed too fast). then every user is in /.

the users can never to get "Default File Manager Path" again :(
except restart app.


you are not using the default path and if you go up thrice you are also in /

**Comment by JoinnA** [comment]
I have now discovered the same problem in "Pick File" e.g. when I want to add an external subtitle file during playback. 😥
