### ISSUE TITLE
Add scroll down for "conf" area

### ISSUE THREAD

**Issue by fr5gh** [mpv-android/mpv-android#229]
- mpv-android version: 2019-11-03-alpha
- Android 9 device (Samsung Galaxy A50)

I don't find the "conf" area so intuitive.

It can't be scrolled down there and it often happens when users are used to scroll down. Appears in "conf" area immediately highlighted, so a text selected. Although the user did not actually want to, but only wanted to scroll down.

**Comment by sfan5** [comment]
The config editor is already scrollable.
![shot](https://user-images.githubusercontent.com/1042418/72753481-52162300-3bc5-11ea-9361-308e72e191d4.png)
