### ISSUE TITLE
File picker truncates filenames

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#231]
https://github.com/mpv-android/mpv-android/issues/228#issuecomment-575831504

Hello,

I think the view in "Pick File" should be improved. It is very tiring for me to find the right files, because not all or part of the name + extension is shown.

This is how I know it from standard File Manager app:
Mom.and.friends.2019.10.10birthday.in.Missouri River.mp3
->
Mom.and.friends.2....Missouri River.mp3

Maybe also in combination while holding down a file, a small bar appears to see the full name + extension.

**Comment by rancidfrog** [comment]
Also, file picker has no fast scroll, so it is useless for large collections
No sort, so useless unless you arrange files separately in folders
UI could be improved for file selection with useful tools such as sort, fast scroll bar, ...
