### ISSUE TITLE
libmpv may not redraw frames when screen dimensions change

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#232]
Hello,

I have set the screen orientation to automatic.

When I open a music file with cover and turn the device to landscape mode or turn it back to portrait mode. The cover is completely shifted and not in its original position. 😢

-- Samsung Galaxy S9+ (Android 9) + mpv (2019-11-03-alpha)

**Comment by sfan5** [comment]
I remember this being a bug but I can't reproduce it with my current build, might be fixed inside mpv in the meantime.
