### ISSUE TITLE
Screen orientation (automatic) for videos does not work

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#234]
Hello,

I set the screen orientation in mpv settings (General) to "Automatic" and the Android device to "Auto rotate".

When I open a video file, the video is always in landscape mode, even though the device is in portrait mode.

When I try to rotate the device somehow so that the video is automatically displayed in portrait mode, it does not work. 

Only the landscape mode can be changed. 😢

-- Samsung Galaxy S9+ (Android 9) + mpv (2019-11-03-alpha)

**Comment by sfan5** [comment]
Your description is not clear enough. Is the video file you are opening landscape or portrait? Which resolution does it have?

When testing this myself I did however find that it doesn't take rotation metadata into account.

**Comment by JoinnA** [comment]
Hi you,

it is a recorded landscape video from the Android device. The Android device was held in landscape format.

The resolution is 1920 x 1080

**Comment by sfan5** [comment]
Open a new issue with all details.
