### ISSUE TITLE
More feature(s) for headphone control

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#236]
Hello,

how I can use a headphone control (3.5 mm plug) for my Android device to get playlist (next)? It is a standard headphone (three buttons) from the box of the Android device.

I want to get the playlist (next) when I click the center button twice. Same as in the standard Music Player app. That means if I double click the center button in the playlist playback the next track in the playlist will be played.

Does this work with mpv Android (input.conf)?

--
Samsung Galaxy S9+ (Android 9) + mpv (2019-11-03-alpha)

**Comment by sfan5** [comment]
Possibly stale. Please re-test and comment.
