### ISSUE TITLE
How to get accurate touch gestures?

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#238]
Hello,

when I use seeking (touch gesture). Then the displayed time in the middle is not exactly the same as the progress bar.

In general, when I used the seeking (very slowly with my finger), the time was almost always displayed in two second steps.

The video file is here https://github.com/mpv-android/mpv-android/issues/239 - video file (downloaded 1080p, 60 FPS, mp4, 137 MB) https://www.youtube.com/watch?v=tUVWV6pDShs

![Screenshot_20200121-051010_mpv](https://user-images.githubusercontent.com/59565869/72813892-6b21e100-3c64-11ea-835c-bf467e24bc7d.jpg)

---------
I have also tested brightness and volume as touch gesture for you.

The volume gesture is executed in steps of 6% and 7%.

The brightness gesture is executed in 1% steps. But I noticed that after the first setting (e.g. first setting to 50%) a short stop (take your finger off the display) and a different value is set. The intermediate steps are not displayed (49%,48%,47%,46%). After the short stop, immediately set to 45% (only the finger may be pulled down). I did it very slowly with my finger.

--
Samsung Galaxy S9+ (Android 9) + mpv (2019-11-03-alpha)

**Comment by sfan5** [comment]
> Then the displayed time in the middle is not exactly the same as the progress bar.

Gestures use keyframe seeks which aren't exact.

> the time was almost always displayed in two second steps.

There is a minimum trigger distance for movements to register. 

> The volume gesture is executed in steps of 6% and 7%.

Volume adjustment happens with the granularity the device allows.

> After the short stop, immediately set to 45%

As far as I can tell, this is also caused by the minimum trigger distance.

**Comment by JoinnA** [comment]
Hi you,

can you fix this here? -> when I use seeking (touch gesture). Then the displayed time in the middle is not exactly the same as the progress bar.

"Gestures use keyframe seeks which aren't exact."

Can it be improved?


"Volume adjustment happens with the granularity the device allows."

Which Android phones support 1% steps? Samsung Galaxy Note 10+?


"As far as I can tell, this is also caused by the minimum trigger distance."

I put my finger on the same position on the display after the short stop and simply drag down. The intermediate steps is not shown, but immediately 45%. What if I want to go from 50% to 48%? This is not possible with this method.

Can it be improved?
