### ISSUE TITLE
What is the path for second Android device (connected by cable)?

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#240]
Hi,

I have two Android 9 devices connected together with a USB-C to USB-C 3.1 cable.

Is there a way to access other connected Android device in mpv via file picker to play media files?

I do not want to copy the media files to other Android device.

--
Samsung Galaxy S9+ (Android 9)
Samsung Tab S6 (Android 9)
Anker Powerline II USB-C to USB 3.1 Gen2 Cable
mpv (2019-11-03-alpha)

**Comment by sfan5** [comment]
If you can see the other device in the file manager that comes with Android, then yes it's possible to open mpv from there.

Whether that works via the mpv file picker: maybe or maybe not (that still needs to be fixed, see #228)
