### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sions124** [mpv-android/mpv-android#241]
mpv (2020-01-30-alpha.18)

Good afternoon,

I couldn't find an email contact address in the app and so I used the email address listed under Google Play Store: mpv@prismriver.jp

But unfortunately I never got an answer by email.
Is the email contact address still up-to-date?

I have some feedback.

Feedback 1:

There is no support in mpv Android for external media connected via USB OTG adapter.

Feedback 2:

Unfortunately, I cannot rotate videos that don't have rotation metadata into portrait mode when I rotate the device to portrait.
It is a 1080p video (Iron Man 3, mkv).

Screen orientation is set to automatic under General.

Feedback 3:
The screenshots for mpv Android in Google Play Store are outdated. The pictures show an old version of mpv Android.

Feedback 4:
If I want to select external subtitle during playback. I don't see the SD card icon and the file picker looks completely different than on the main page. So small and very long.

Can this be removed? I find it better if the same file picker layout (same size) appears as on the main page. The only difference is that it is not the file picker from the main page. In the title bar, could add the respective option name e.g. Open external subtitle... and Cancel button.

Feedback 5:
Create a playlist txt file in File Manager app and open it with mpv Android. playlist.txt is not recognized.

Feedback 6:
It is not possible to update the File Picker manually, e.g. by pull down. Similar to File Manager app (Cx File Explorer).

Sometimes I download videos and if mpv Android was previously open in the "Download" folder, then it is not possible to manually update the File Picker (pull down) to show the newly downloaded videos.

**Comment by sfan5** [comment]
> There is no support in mpv Android for external media connected via USB OTG adapter

I have tested this and it worked for me. More details would be helpful.

> I cannot rotate videos that don't have rotation metadata into portrait mode when I rotate the device to portrait

If a video has the "wrong" resolution (landscape) and is missing rotation metadata, there's not much mpv can do. Except maybe allow you to manually rotate.

> I don't see the SD card icon [...]

Storage selection is indeed not implemented (yet) for the inline filepicker, it currently shows you the same folder the video is in.

> Create a playlist txt file in File Manager app

mpv does not read plaintext playlists, you can instead create one in the [M3U](https://en.wikipedia.org/wiki/M3U) format. Make sure to add `#EXTM3U` on the first line.

> Sometimes I download videos and if mpv Android was previously open in the "Download" folder, then it is not possible to manually update the File Picker (pull down) to show the newly downloaded videos.

The file picker is supposed to automatically update, so this might be a bug.

**Comment by sions124** [comment]
> > There is no support in mpv Android for external media connected via USB OTG adapter
> 
> I have tested this and it worked for me. More details would be helpful.
> 
You simply take a USB-C OTG adapter and connect to your phone (USB-C port). Then take a USB-A flash drive and connect it to the OTG adapter.

Open mpv android and click on SD card icon. The USB flash drive is not mounted in mpv Android.

100% reproducible.
> > I cannot rotate videos that don't have rotation metadata into portrait mode when I rotate the device to portrait
> 
> If a video has the "wrong" resolution (landscape) and is missing rotation metadata, there's not much mpv can do. Except maybe allow you to manually rotate.

It is a normal 1920 x 1080 video (Iron Man 3, mkv, h.264). Yes it is a landscape video.

But I don't want to rotate manually  the video when click on "Switch Orientation" during playback.

But I have selected "automatic" under Screen orientation settings. Then when I rotate the phone to portrait mode, the video must also automatically switch to portrait mode. Just like with VLC Android. A bug in mpv Android or a feature request?

**Comment by sfan5** [comment]
> Open mpv android and click on SD card icon. The USB flash drive is not mounted in mpv Android.
> 100% reproducible.

Like I said, I have tested this and you need to be more specific on the conditions in which this does not work (such as your Android version).
![p](https://user-images.githubusercontent.com/1042418/73876747-cbfe0b80-4857-11ea-899d-4e04ce66e259.jpg)

> Then when I rotate the phone to portrait mode, the video must also automatically switch to portrait mode.

I think there might be a misunderstanding what the "Automatic" mode does. 
In automatic mode, when you play a landscape video mpv will lock your device to landscape and when you play a portrait video it will lock your device to portrait.
The free rotation mode you are thinking of was already requested in #209.

**Comment by sions124** [comment]
> Like I said, I have tested this and you need to be more specific on the conditions in which this does not work (such as your Android version).

I use a Xiaomi Redmi Note 8 Pro and Android 9 (MIUI 11). No root. I also reset the phone to factory defaults to be safe and reformatted the USB flash drive. Nevertheless it does not work.

In preinstalled File Manager app on the phone it is detected. The USB flash drive (32 GB) has the file system FAT32.

If information is missing please write back.

>  I think there might be a misunderstanding what the "Automatic" mode does.
> In automatic mode, when you play a landscape video mpv will lock your device to landscape and when you play a portrait video it will lock your device to portrait.
> The free rotation mode you are thinking of was already requested in #209.

I understand for video files. I thought "Automatic" meant free rotation.

But I noticed, why does it work with music file with cover? When I set to "Automatic" and open a music file with cover and rotate the phone from landscape to portrait, the cover rotates to portrait mode. Maybe only music files are currently supported?

**Comment by sfan5** [comment]
> But I noticed, why does it work with music file with cover?

Music covers are usually (nearly) square and could be optimally viewed in either portrait or landscape, so mpv allows any device rotation. The same would happen if you watch a square video.
