### ISSUE TITLE
4k h265 10 bit a shots (Sorry my english, any errors are the fault of the translator)

### ISSUE THREAD

**Issue by qw123wh** [mpv-android/mpv-android#242]
10 bit h265 4k movies can be viewed and listened to in jerks, please correct. This doesn't happen with other apps like Nova Video Player

**Comment by sfan5** [comment]
Is hardware decoding enabled? Is 10-bit HEVC even supported by it?
Please provide a [`logcat`](https://developer.android.com/studio/command-line/logcat) log.

**Comment by qw123wh** [comment]
Hi i tried to play the file on my redmi note 8 and it works perfectly. The problem is on my Android TV "W95 TV Box 2 GB RAM 16 GB ROM" non si riproduce bene né con decodifica hardware né con decodifica software .As I said before, I play this file well on the TV box with the Nova Video Player app with hardware decoding. Software decoding does not work with Nova video.  https://github.com/nova-video-player/aos-AVP
I don't know how to send a logcat I'm sorry
