### ISSUE TITLE
USB flash drive via OTG adapter is not mounted

### ISSUE THREAD

**Issue by ghost** [mpv-android/mpv-android#246]
mpv Android (2020-01-30-alpha.18)

The USB flash drive via OTG adapter is not mounted in mpv Android.
![Screenshot 1](https://user-images.githubusercontent.com/60618113/73935475-93276a80-491b-11ea-9413-e932128585e7.jpg)

I use a Xiaomi Redmi Note 8 Pro and Android 9 (MIUI 11). No root. I also reset the phone to factory defaults to be safe and reformatted the USB flash drive. Nevertheless it does not work.

It is detected in the pre-installed File Manager on the phone and can be used immediately without an access request. The USB flash drive (32 GB) has the FAT32 file system.

When I use other file manager app (Cx File Explorer) and not the pre-installed File Manager.
Then I have to grant access.
![Screenshot 2](https://user-images.githubusercontent.com/60618113/73935574-cbc74400-491b-11ea-860f-f4b758c33dfb.jpg)

Maybe this information helps? Maybe mpv Android has to implement something like this to work with these phone.

**Comment by sfan5** [comment]
The API your file manager uses is probably this one:
https://developer.android.com/reference/android/os/storage/StorageVolume.html#createAccessIntent(java.lang.String)

**Comment by sfan5** [comment]
Please test this APK: https://kitsunemimi.pw/tmp/mpv-android-2020-02-07.apk

If it doesn't show external storage, please also make a screenshot of the version info dialog (it shows debug output instead).

**Comment by sions124** [comment]
It doesn't show external storage.

![Screenshot_2020-02-07-11-10-15-231_is xyz mpv](https://user-images.githubusercontent.com/60618113/73997936-e8569100-499a-11ea-840f-065f1edbc2d2.jpg)

**Comment by sfan5** [comment]
Here's a new one: https://kitsunemimi.pw/tmp/mpv-android-2020-02-07_2.apk

**Comment by sions124** [comment]
It doesn't show external storage.

![Screenshot_2020-02-07-22-00-16-999_is xyz mpv](https://user-images.githubusercontent.com/60618113/74035736-ce966780-49f5-11ea-887b-175268e763b8.jpg)

**Comment by sfan5** [comment]
Thanks for testing, looks like mpv-android will need to use the explicit permission grant after all.

**Comment by sions124** [comment]
> Thanks for testing, looks like mpv-android will need to use the explicit permission grant after all.

If you want more tests to find out if it works without the explicit permission.

You can create as many samples as you want. I will test it and report the result.
