### ISSUE TITLE
mpv ui on macos

### ISSUE THREAD

**Issue by dheerajreddy57** [mpv-android/mpv-android#248]
Hi, I installed mpv through homebrew. But I don't see mpv in the applications list.

It is accessible from the terminal.
Is there a command to open mpv ui so I can drag and drop files to mpv?

**Comment by phanirithvij** [comment]
Yeah, I have the same problem. Is there a command to open mpv with no files selected on Mac?

**Comment by sfan5** [comment]
Wrong place, ask at https://github.com/mpv-player/mpv.

**Comment by phanirithvij** [comment]
Oh I didn't realize sorry.
