### ISSUE TITLE
lua script doesn't work after minimizing

### ISSUE THREAD

**Issue by mfcc64** [mpv-android/mpv-android#249]
I played audio file with lua script [visualizer.lua](https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua), everything worked fine. But, after I minimized the player and opened it again, the visualizer video dissappeared.

**Comment by sfan5** [comment]
Not related to the issue, but how did you load the script?

The reason for this is the fact that mpv-android automatically disables the video by setting `vid=no` when backgrounding.
The script could perhaps be written to accomodate this, perhaps there is also solution on the side of mpv-android.

**Comment by mfcc64** [comment]
I loaded the script by adding `script=/sdcard/mpv-scripts/visualizer.lua` at `mpv.conf` as suggested by #132.

**Comment by arhik** [comment]
I can't save lua file with lua extension. It disappears. How did you guys manage to do it ?

**Comment by biopsin** [comment]
And while visualizer is showing only software decoding is available, not shure this is by design..
