### ISSUE TITLE
adapt adaptive seeking

### ISSUE THREAD

**Issue by 257** [mpv-android/mpv-android#25]
...with a nice left or right swipe for 10x - 20x - 30x steps.

thanks

**Comment by jeeb** [comment]
N seconds seeking with a Google-predefined swipe I have already once implemented in a [work in progress branch](https://github.com/mpv-android/mpv-android/commit/b0887a331e70f6bc5907bccd4bf881105c9d14eb) that could be configurable or with some adaptive stuff depending on the length of the video, but @xyzz wanted something like VLC on Android does, which is much, much less simple and would be adaptive depending on the length and such of the swipe (you have to start defining the ranges of motion and such, a la https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/src/org/videolan/vlc/gui/video/VideoPlayerActivity.java#L1957 ).

If the first style is OK, I can try poking my first version into a better state and put that in, the second part would require quite a bit of extra work which might or might not be possible in the short term.

**Comment by mtaki14** [comment]
Any progress on this? This is pretty much a must usability wise, along with gestures for volume/brightness.

**Comment by xyzz** [comment]
#47
