### ISSUE TITLE
Android Studio Build Issue

### ISSUE THREAD

**Issue by hebeidev** [mpv-android/mpv-android#250]
I faced some issue when I build this repo on Android Studio. 
I tried to find out solutions to resolve this issue. But I failed. Please help me.
![image](https://user-images.githubusercontent.com/48370879/75068995-29e15300-54e8-11ea-9889-39735df49725.png)

**Comment by sfan5** [comment]
Did you run the build script according to the [build instructions](https://github.com/mpv-android/mpv-android/blob/master/buildscripts/README.md)?

**Comment by Roman8817** [comment]
Sorry I just found and trying to use that. Thank you for your update.

**Comment by purvagevaria** [comment]
@hebeidev Have you resolved above issue  ? I tried that but I am not able to resolve the build related issue.
