### ISSUE TITLE
Pause MPV when I call or  answer a phone call

### ISSUE THREAD

**Issue by sebma** [mpv-android/mpv-android#251]
Hi, I use MPV "2020-01-30 Test Build"

When I call or answer a phone call, `mpv` continues playing the audio and both I and my recipient can hear it.

Can you please fix this ?

**Comment by sfan5** [comment]
probable duplicate/related #103

**Comment by sfan5** [comment]
Should've been fixed by the audio focus feature, which will arrive in the Play Store shortly.
