### ISSUE TITLE
Add play/pause to background play notification

### ISSUE THREAD

**Issue by sebma** [mpv-android/mpv-android#252]
Hi,
Can you please implement 3 control buttons when the device is locked : PREVIOUS ; PLAY/PAUSE ; NEXT ?

**Comment by crisalis2** [comment]
Commenting/clarifying on the meaning of this feature request. Or maybe just adding my own request.

The following "1" and "2" are two ways in which I interpret this feature request.

1) Three buttons you can touch when mpv is playing in background, even when phone is in lock mode.
mpv-android already has this, except there's only two buttons (previous and next), with the play/pause button missing, which is kind of strange.
I think play/pause button should be added.

2) Three actions with the typical button in a TRRS cable when using headphones connected to the phone. With other players it works like this: one press is play/pause, two quick presses is next, three quick presses is previous. These work when the player is in background and/or the phone is locked. Additionally, when the player is not running, one press makes it start.
Right now mpv-android has the "one press -> play/pause" feature when in foreground, but not when it's in background or with the phone locked. Two presses and three presses don't work. Also, one press when mpv-android isn't running doesn't launch it.
I would like mpv-android to support all these functions.

**Comment by sfan5** [comment]
> [...], but not when it's in background or with the phone locked. [...] Also, one press when mpv-android isn't running doesn't launch it.

This is related to #212.
Since other music players remember the last played song/album/list but mpv doesn't, what would you expect it to do when you press the headphone buttons? Just launch the app?

**Comment by crisalis2** [comment]
> > [...], but not when it's in background or with the phone locked. [...] Also, one press when mpv-android isn't running doesn't launch it.
> 
> This is related to #212.
> Since other music players remember the last played song/album/list but mpv doesn't, what would you expect it to do when you press the headphone buttons? Just launch the app?

Just launching the app would be fine by me, but maybe it doesn't make much sense. Anyway, of all the functions that's the least important for me and I don't care for it that much. So doing nothing when the player is not running and the button is pressed, like until now, is also fine.

Just in case there was misunderstanding: you quoted a part of my message that referred to a different thing. The "but not when it's in background or with the phone locked" part is another thing. It just referred to the "normal" behaviour the one button press should have when mpv **is** running (background or lock mode included, but in any case running).

So button presses when the player is **not** running are not important for me.
But all the one press, two presses and three presses functionality when the player **is** running (background and lock mode included) would be quite desirable.

Also, I found that #236 is in the end the same thing as this/ #212, so maybe you want to close it.

**Comment by 532910** [comment]
progress bar

**Comment by omeringen** [comment]
Like @crisalis2 mentioned about it, i also have a bluetooth earbud. I would like to pause/play on earbud buttons(default is one click). It also skips to the next song with three clicks on right earbud, previous on three clicks on left one.
These functions works fine on another player(s) and this is a must have feature IMO.

Maybe i should fill another feature request since this bug we are currently in is about buttons only but we are also talking about earbud/headset interaction.

**Comment by Thewisem** [comment]
It seems this hasn't yet been implemented
