### ISSUE TITLE
mpv.conf : volume-max=1000 not working

### ISSUE THREAD

**Issue by sant527** [mpv-android/mpv-android#253]
I am using the latest version of mpv-android

I am trying to use the ` volume-max=1000` in the mpv.conf which i use in my linux desktop. It works fine there but here its not working

**Comment by sfan5** [comment]
mpv-android adjust the system volume instead of the soft volume you usually have in mpv.
softvol is still present but can't be used from the GUI.

**Comment by sant527** [comment]
So how to use soft-vol. Any way out
