### ISSUE TITLE
how to use keyboard shortcuts on mpv-android

### ISSUE THREAD

**Issue by sant527** [mpv-android/mpv-android#255]
Like how to view the keyboard and can start using p for pause etc

**Comment by xdilemite** [comment]
Connect a keyboard to your phone using otg or Bluetooth.

**Comment by erickyun** [comment]
download [hacker's keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard) in settings turn on `use permanent notification` and now you can use keyboard in mpv

**Comment by jewelsonn** [comment]
> download [hacker's keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard) in settings turn on `use permanent notification` and now you can use keyboard in mpv-android from the notification bar

The keyboard Does't stay. It just closes back in nano seconds. 

My suggession to devs, add profile buttons like a macro

**Comment by erickyun** [comment]
> 

İt works fine for me.
(Device: Xiaomi Redmi note 8 pro, Android: 11)

it's probably your device fault or you didn't setup it right?
