### ISSUE TITLE
Playing pipe.

### ISSUE THREAD

**Issue by maci3k90** [mpv-android/mpv-android#257]
Hello. 

Generally, for ffmpeg in Android I am using pipes from https://developer.android.com/reference/android/os/ParcelFileDescriptor 

Is it possible to play pipe with mpv-android, where I do not have pipe location on filesystem, but only its fiiledescriptor?

**Comment by sfan5** [comment]
mpv-android can play a `content://` URI which then gets [resolved into](https://github.com/mpv-android/mpv-android/blob/master/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L560) a ParcelFileDescriptor.
But it currently doesn't play a ParcelFileDescriptor directly.
