### ISSUE TITLE
Sync progress with desktop

### ISSUE THREAD

**Issue by felagund** [mpv-android/mpv-android#259]
Sometimes I play my files using MPV on my computer and sometimes I would like to continue watching them from my phone. With a rooted phone, I can mount the videos stored on my computer over SAMBA. I can also mount the "watch_later" directory that saves progress. Would it be possible to share that directory so that I could pick up from one device to the other? Or achieve that end by another means?

**Comment by sfan5** [comment]
Mounting the remote watch_later directory to `/data/data/is.xyz.mpv/files/watch_later` (path may be slightly different depending on Android version) on your phone should work.

**Comment by felagund** [comment]
I see, and then I must enable --ignore-path-in-watch-later-config so that the different paths in the two respecitve filesystems are not an issue, perfect! (not sure why something like md5 hash is not used instead of a path in the first place to be honest, but here is not the question to answer that I guees).
