### ISSUE TITLE
GLSL shaders doesn't work (Anime4K)

### ISSUE THREAD

**Issue by the80hz** [mpv-android/mpv-android#261]
I'm using version 2020-01-30
In mpv.conf i entered `glsl-shaders="/sdcard/Anime4K/Anime4K_Hybrid_v2.1a.glsl"` and nothing happened. I even pointed out Default File Manager Path and switched Debanding to GPU mode, but it didn't help either.

**Comment by sfan5** [comment]
I strongly suspect no mobile GPU will be able to handle that shader, but in any case you can use [`logcat`](https://developer.android.com/studio/command-line/logcat) to get a look at mpv's log and figure out what went wrong.
