### ISSUE TITLE
Playstore Availability for AndroidTV Devices (Nvidia Shield TV)

### ISSUE THREAD

**Issue by Kuro07** [mpv-android/mpv-android#267]
Hi,

Would it be possible to make mpv-android available for Android TV devices. I tried installing mpv-android from the play store but it doesn't appear in the search results. I also tried installing an APK that I downloaded and the player just crashed. I'm not sure if there's need to be a version compiled for AndroidTV devices.

**Comment by sfan5** [comment]
No idea about Android TV availability off the top of my head. But for the crash please provide [`logcat`](https://developer.android.com/studio/command-line/logcat) log and the version of mpv-android you tried.

**Comment by Kuro07** [comment]
I'll try to provide a logcat when I can. I just installed the latest version of mpv that was available here and it seems to have been fixed. For the Android TV availability, what i mean is that I'm unable to find mpv-android via the play store if I'm searching on my AndroidTV device.

**Comment by sfan5** [comment]
Okay looks like mpv-android is available on Android TV for real this time. Seeing some crashes reported from TV devices and marked "Installed from Google Play":
![grafik](https://user-images.githubusercontent.com/1042418/139584634-30b8186e-239a-4f4c-8f6f-03bfa754e43c.png)
