### ISSUE TITLE
HW decoding performance regression on latest release?

### ISSUE THREAD

**Issue by exegg** [mpv-android/mpv-android#268]
So I have been using MPV on my phone since march. No issues with HW playback on my phone, a Samsung J7 2018 with Exynos 7870.

But I updated to the latest version and now I am losing frames when playing video with HW decoding. Same videos play smoothly when I installed back the previous build. Tried a few clips and movies in H264 and H265. They all drop frames, even in low resolutions like 720p.

I enabled statistics and took a screenshot on one of the clips.
January build
![jan](https://user-images.githubusercontent.com/19347211/83312225-9652a900-a1df-11ea-9722-b9630494563e.jpg)

Latest release
![may](https://user-images.githubusercontent.com/19347211/83312248-a1a5d480-a1df-11ea-8e72-8442625ee19d.jpg)

**Comment by exegg** [comment]
Also tried it on a burner phone that has a Snapdragon 410 and H264 videos lose frames and are kinda choppy as well. SW mode allows smooth playback again... Or reinstalling the january build.

**Comment by sfan5** [comment]
Confirmed.
Reverting mpv to commit `6c2cc20` fixes it, there are 509 commits between `bf6afbc...6c2cc20`.

**Comment by sfan5** [comment]
<pre>
6a13954d67143fb3c4ac8a4a7624c23e3ecb9a3c is the first bad commit
commit 6a13954d67143fb3c4ac8a4a7624c23e3ecb9a3c
Author: wm4 <wm4@nowhere>
Date:   Fri Apr 10 01:45:45 2020 +0200

    vo: further reduce redundant wakeups
    
    In display-sync mode, the core doesn't need to woken up every vsync, but
    only every time a new actual video frame needs to be queued. So don't
    wake up if there are still frames to repeat.
    
    In audio-sync mode, the wakeup is simply redundant, since there's a
    separate timer (in->wakeup_pts) to control when to queue a new frame. I
    think.
    
    This finally brings the required playloop iterations down to almost the
    number of video frames. (As originally intended, really.)
    
    Also a fairly risky change.

 video/out/vo.c | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)
</pre>

**Comment by sfan5** [comment]
Fixed upstream.

**Comment by tmm1** [comment]
> Fixed upstream.

cc https://github.com/mpv-player/mpv/issues/7777 https://github.com/mpv-player/mpv/commit/57462580180ecc9006b625b94e895a38e1118f69 https://github.com/mpv-player/mpv/commit/c5158b057c8d0936ea12c5bc3153903263f03947
