### ISSUE TITLE
Request: Add a speed option between 1.5 and 2.0

### ISSUE THREAD

**Issue by justa9** [mpv-android/mpv-android#269]
Hello.

Currently mpv can use the following playback speeds: 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0. If a custom (user set) speed option cannot be implemented for technical or other reasons, I would like to ask that a speed between 1.5 and 2.0 (e.g. 1.75) be added. 

One reason is that there are media files where 1.5 is "too slow" while 2.0 is "too fast" to be comprehended. Another is that it makes sense to have better granulation for faster speeds since to the best of my knowledge people often want to speed media up, than slow them down (especially on mobile Android devices). In case you feel that adding another option makes the value switching more tiresome, I would kindly request to drop 0.25.

Thank you.

**Comment by sfan5** [comment]
> If a custom (user set) speed option cannot be implemented

While not convenient, you can always set a custom value in mpv.conf using e.g. `speed=1.23`.
