### ISSUE TITLE
Allow to set audio focus

### ISSUE THREAD

**Issue by XyzUA** [mpv-android/mpv-android#273]
Hello,

since the new update to version 2020-05-27-alpha and 2020-06-02-alpha cannot use 2 audio player app at the same time actively.

With this mpv Android version I could play 2 audio player app (default audio player from system and mpv android) simultaneously.
https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2020-01-30

2 music titles were active at the same time.

**Comment by rancidfrog** [comment]
There are a number of music apps which support this. A good example which deals with all cases:

![](https://i.imgur.com/iLgcX4M.png)
