### ISSUE TITLE
Build failed  -> task in 'mpv' failed with exit status 1

### ISSUE THREAD

**Issue by gmohiuddin215** [mpv-android/mpv-android#278]
I have been trying to build mpv-android in ubuntu but I'm stuck at mpv library.

Following are the issue shown in terminal:

231/421] Linking _build/mpv
[232/421] Compiling demux/demux.c
[233/421] Compiling demux/demux_edl.c
/home/acer-pc/Documents/mpv-android/buildscripts/sdk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llcms2
/home/acer-pc/Documents/mpv-android/buildscripts/sdk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -larchive
/home/acer-pc/Documents/mpv-android/buildscripts/sdk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldrm
/home/acer-pc/Documents/mpv-android/buildscripts/sdk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrubberband
/home/acer-pc/Documents/mpv-android/buildscripts/sdk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llua
/home/acer-pc/Documents/mpv-android/buildscripts/sdk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ljack
../audio/filter/af_rubberband.c:277: error: undefined reference to 'rubberband_delete'
../audio/filter/af_rubberband.c:110: error: undefined reference to 'rubberband_available'
../audio/filter/af_rubberband.c:145: error: undefined reference to 'rubberband_get_samples_required'
../audio/filter/af_rubberband.c:89: error: undefined reference to 'rubberband_new'
../audio/filter/af_rubberband.c:58: error: undefined reference to 'rubberband_set_time_ratio'
../audio/filter/af_rubberband.c:68: error: undefined reference to 'rubberband_set_pitch_scale'
../audio/filter/af_rubberband.c:155: error: undefined reference to 'rubberband_process'
../audio/filter/af_rubberband.c:163: error: undefined reference to 'rubberband_available'
../audio/filter/af_rubberband.c:176: error: undefined reference to 'rubberband_delete'
../audio/filter/af_rubberband.c:185: error: undefined reference to 'rubberband_available'
../audio/filter/af_rubberband.c:202: error: undefined reference to 'rubberband_retrieve'
../audio/filter/af_rubberband.c:169: error: undefined reference to 'rubberband_reset'
../audio/filter/af_rubberband.c:266: error: undefined reference to 'rubberband_reset'
../audio/filter/af_rubberband.c:0: error: undefined reference to 'rubberband_set_pitch_scale'
../audio/filter/af_rubberband.c:58: error: undefined reference to 'rubberband_set_time_ratio'
../audio/filter/af_rubberband.c:0: error: undefined reference to 'rubberband_set_pitch_scale'
../audio/out/ao_jack.c:237: error: undefined reference to 'jack_client_open'
../audio/out/ao_jack.c:181: error: undefined reference to 'jack_port_register'
../audio/out/ao_jack.c:246: error: undefined reference to 'jack_set_process_callback'
../audio/out/ao_jack.c:248: error: undefined reference to 'jack_get_sample_rate'
../audio/out/ao_jack.c:250: error: undefined reference to 'jack_set_buffer_size_callback'
../audio/out/ao_jack.c:251: error: undefined reference to 'jack_set_graph_order_callback'
../audio/out/ao_jack.c:260: error: undefined reference to 'jack_client_close'
../audio/out/ao_jack.c:271: error: undefined reference to 'jack_client_close'
../audio/out/ao_jack.c:203: error: undefined reference to 'jack_activate'
../audio/out/ao_jack.c:147: error: undefined reference to 'jack_get_ports'
../audio/out/ao_jack.c:155: error: undefined reference to 'jack_port_name'
../audio/out/ao_jack.c:155: error: undefined reference to 'jack_connect'
../audio/out/ao_jack.c:120: error: undefined reference to 'jack_port_get_buffer'
../player/lua.c:461: error: undefined reference to 'lua_close'
../stream/stream_libarchive.c:209: error: undefined reference to 'archive_read_close'
../stream/stream_libarchive.c:210: error: undefined reference to 'archive_read_free'
../stream/stream_libarchive.c:327: error: undefined reference to 'archive_read_new'
../stream/stream_libarchive.c:244: error: undefined reference to 'archive_read_append_callback_data'
../stream/stream_libarchive.c:209: error: undefined reference to 'archive_read_close'
../stream/stream_libarchive.c:210: error: undefined reference to 'archive_read_free'
../stream/stream_libarchive.c:244: error: undefined reference to 'archive_read_append_callback_data'
../stream/stream_libarchive.c:347: error: undefined reference to 'archive_read_support_format_rar'
../stream/stream_libarchive.c:348: error: undefined reference to 'archive_read_support_format_rar5'
../stream/stream_libarchive.c:354: error: undefined reference to 'archive_read_support_format_7zip'
../stream/stream_libarchive.c:355: error: undefined reference to 'archive_read_support_format_iso9660'
../stream/stream_libarchive.c:356: error: undefined reference to 'archive_read_support_filter_bzip2'
../stream/stream_libarchive.c:357: error: undefined reference to 'archive_read_support_filter_gzip'
../stream/stream_libarchive.c:358: error: undefined reference to 'archive_read_support_filter_xz'
../stream/stream_libarchive.c:359: error: undefined reference to 'archive_read_support_format_zip_streamable'
../stream/stream_libarchive.c:366: error: undefined reference to 'archive_read_support_format_zip_seekable'
../stream/stream_libarchive.c:369: error: undefined reference to 'archive_read_set_read_callback'
../stream/stream_libarchive.c:370: error: undefined reference to 'archive_read_set_skip_callback'
../stream/stream_libarchive.c:371: error: undefined reference to 'archive_read_set_open_callback'
../stream/stream_libarchive.c:373: error: undefined reference to 'archive_read_set_close_callback'
../stream/stream_libarchive.c:375: error: undefined reference to 'archive_read_set_seek_callback'
../stream/stream_libarchive.c:376: error: undefined reference to 'archive_read_open1'
../stream/stream_libarchive.c:413: error: undefined reference to 'archive_read_next_header'
../stream/stream_libarchive.c:417: error: undefined reference to 'archive_error_string'
../stream/stream_libarchive.c:423: error: undefined reference to 'archive_entry_filetype'
../stream/stream_libarchive.c:426: error: undefined reference to 'archive_entry_pathname'
../stream/stream_libarchive.c:209: error: undefined reference to 'archive_read_close'
../stream/stream_libarchive.c:210: error: undefined reference to 'archive_read_free'
../stream/stream_libarchive.c:209: error: undefined reference to 'archive_read_close'
../stream/stream_libarchive.c:210: error: undefined reference to 'archive_read_free'
../stream/stream_libarchive.c:474: error: undefined reference to 'archive_entry_size_is_set'
../stream/stream_libarchive.c:475: error: undefined reference to 'archive_entry_size'
../stream/stream_libarchive.c:493: error: undefined reference to 'archive_read_data'
../stream/stream_libarchive.c:495: error: undefined reference to 'archive_error_string'
../stream/stream_libarchive.c:539: error: undefined reference to 'archive_read_data'
../stream/stream_libarchive.c:510: error: undefined reference to 'archive_seek_data'
../stream/stream_libarchive.c:547: error: undefined reference to 'archive_error_string'
../video/out/drm_atomic.c:28: error: undefined reference to 'drmModeObjectGetProperties'
../video/out/drm_atomic.c:34: error: undefined reference to 'drmModeGetProperty'
../video/out/drm_atomic.c:56: error: undefined reference to 'drmModeFreeProperty'
../video/out/drm_atomic.c:64: error: undefined reference to 'drmModeFreeObjectProperties'
../video/out/drm_atomic.c:56: error: undefined reference to 'drmModeFreeProperty'
../video/out/drm_atomic.c:64: error: undefined reference to 'drmModeFreeObjectProperties'
../video/out/drm_atomic.c:86: error: undefined reference to 'drmModeGetPropertyBlob'
../video/out/drm_atomic.c:102: error: undefined reference to 'drmModeAtomicAddProperty'
../video/out/drm_atomic.c:56: error: undefined reference to 'drmModeFreeProperty'
../video/out/drm_atomic.c:64: error: undefined reference to 'drmModeFreeObjectProperties'
../video/out/drm_atomic.c:160: error: undefined reference to 'drmModeGetResources'
../video/out/drm_atomic.c:166: error: undefined reference to 'drmModeGetPlaneResources'
../video/out/drm_atomic.c:289: error: undefined reference to 'drmModeFreeResources'
../video/out/drm_atomic.c:289: error: undefined reference to 'drmModeFreeResources'
../video/out/drm_atomic.c:291: error: undefined reference to 'drmModeFreePlaneResources'
../video/out/drm_atomic.c:56: error: undefined reference to 'drmModeFreeProperty'
../video/out/drm_atomic.c:64: error: undefined reference to 'drmModeFreeObjectProperties'
../video/out/drm_atomic.c:199: error: undefined reference to 'drmModeFreeConnector'
../video/out/drm_atomic.c:193: error: undefined reference to 'drmModeGetConnector'
../video/out/drm_atomic.c:207: error: undefined reference to 'drmModeGetPlane'
../video/out/drm_atomic.c:210: error: undefined reference to 'drmModeFreePlane'
../video/out/drm_atomic.c:283: error: undefined reference to 'drmModeFreePlaneResources'
../video/out/drm_atomic.c:284: error: undefined reference to 'drmModeFreeResources'
../video/out/drm_atomic.c:449: error: undefined reference to 'drmModeDestroyPropertyBlob'
../video/out/drm_atomic.c:449: error: undefined reference to 'drmModeDestroyPropertyBlob'
../video/out/drm_atomic.c:383: error: undefined reference to 'drmModeGetCrtc'
../video/out/drm_atomic.c:387: error: undefined reference to 'drmModeFreeCrtc'
../video/out/drm_atomic.c:102: error: undefined reference to 'drmModeAtomicAddProperty'
../video/out/drm_atomic.c:437: error: undefined reference to 'drmModeCreatePropertyBlob'
../video/out/drm_atomic.c:102: error: undefined reference to 'drmModeAtomicAddProperty'
../video/out/drm_atomic.c:102: error: undefined reference to 'drmModeAtomicAddProperty'
../video/out/drm_atomic.c:437: error: undefined reference to 'drmModeCreatePropertyBlob'
../video/out/drm_common.c:554: error: undefined reference to 'drmGetDeviceNameFromFd'
../video/out/drm_common.c:557: error: undefined reference to 'drmFree'
../video/out/drm_common.c:560: error: undefined reference to 'drmGetVersion'
../video/out/drm_common.c:565: error: undefined reference to 'drmFreeVersion'
../video/out/drm_common.c:568: error: undefined reference to 'drmModeGetResources'
../video/out/drm_common.c:185: error: undefined reference to 'drmModeFreeConnector'
../video/out/drm_common.c:178: error: undefined reference to 'drmModeGetConnector'
../video/out/drm_common.c:247: error: undefined reference to 'drmModeFreeEncoder'
../video/out/drm_common.c:232: error: undefined reference to 'drmModeGetEncoder'
../video/out/drm_common.c:606: error: undefined reference to 'drmModeFreeResources'
../video/out/drm_common.c:159: error: undefined reference to 'drmModeGetConnector'
../video/out/drm_common.c:166: error: undefined reference to 'drmModeFreeConnector'
../video/out/drm_common.c:271: error: undefined reference to 'drmModeFreeEncoder'
../video/out/drm_common.c:253: error: undefined reference to 'drmModeGetEncoder'
../video/out/drm_common.c:219: error: undefined reference to 'drmModeFreeConnector'
../video/out/drm_common.c:582: error: undefined reference to 'drmSetClientCap'
../video/out/drm_common.c:588: error: undefined reference to 'drmSetClientCap'
../video/out/drm_common.c:623: error: undefined reference to 'drmModeFreeEncoder'
../video/out/drm_common.c:664: error: undefined reference to 'drmModeGetResources'
../video/out/drm_common.c:672: error: undefined reference to 'drmModeGetConnector'
../video/out/drm_prime.c:45: error: undefined reference to 'drmPrimeFDToHandle'
../video/out/drm_prime.c:71: error: undefined reference to 'drmModeAddFB2WithModifiers'
../video/out/drm_prime.c:76: error: undefined reference to 'drmModeAddFB2'
../video/out/drm_prime.c:103: error: undefined reference to 'drmModeRmFB'
../video/out/drm_prime.c:111: error: undefined reference to 'drmIoctl'
../video/out/drm_prime.c:111: error: undefined reference to 'drmIoctl'
../video/out/drm_prime.c:111: error: undefined reference to 'drmIoctl'
../video/out/drm_prime.c:111: error: undefined reference to 'drmIoctl'
../video/out/gpu/lcms.c:425: error: undefined reference to 'cmsCreateContext'
../video/out/gpu/lcms.c:428: error: undefined reference to 'cmsSetLogErrorHandlerTHR'
../video/out/gpu/lcms.c:431: error: undefined reference to 'cmsOpenProfileFromMemTHR'
../video/out/gpu/lcms.c:281: error: undefined reference to 'cmsDetectBlackPoint'
../video/out/gpu/lcms.c:285: error: undefined reference to 'cmsBuildGamma'
../video/out/gpu/lcms.c:286: error: undefined reference to 'cmsCreateRGBProfileTHR'
../video/out/gpu/lcms.c:288: error: undefined reference to 'cmsCreateXYZProfile'
../video/out/gpu/lcms.c:289: error: undefined reference to 'cmsCreateTransformTHR'
../video/out/gpu/lcms.c:292: error: undefined reference to 'cmsFreeToneCurve'
../video/out/gpu/lcms.c:293: error: undefined reference to 'cmsCloseProfile'
../video/out/gpu/lcms.c:294: error: undefined reference to 'cmsCloseProfile'
../video/out/gpu/lcms.c:299: error: undefined reference to 'cmsDoTransform'
../video/out/gpu/lcms.c:300: error: undefined reference to 'cmsDeleteTransform'
../video/out/gpu/lcms.c:231: error: undefined reference to 'cmsOpenProfileFromMemTHR'
../video/out/gpu/lcms.c:0: error: undefined reference to 'cmsBuildGamma'
../video/out/gpu/lcms.c:0: error: undefined reference to 'cmsBuildParametricToneCurve'
../video/out/gpu/lcms.c:338: error: undefined reference to 'cmsCreateRGBProfileTHR'
../video/out/gpu/lcms.c:341: error: undefined reference to 'cmsFreeToneCurve'
../video/out/gpu/lcms.c:342: error: undefined reference to 'cmsFreeToneCurve'
../video/out/gpu/lcms.c:343: error: undefined reference to 'cmsFreeToneCurve'
../video/out/gpu/lcms.c:437: error: undefined reference to 'cmsCloseProfile'
../video/out/gpu/lcms.c:322: error: undefined reference to 'cmsBuildParametricToneCurve'
../video/out/gpu/lcms.c:322: error: undefined reference to 'cmsBuildParametricToneCurve'
../video/out/gpu/lcms.c:322: error: undefined reference to 'cmsBuildParametricToneCurve'
../video/out/gpu/lcms.c:441: error: undefined reference to 'cmsCreateTransformTHR'
../video/out/gpu/lcms.c:446: error: undefined reference to 'cmsCloseProfile'
../video/out/gpu/lcms.c:462: error: undefined reference to 'cmsDoTransform'
../video/out/gpu/lcms.c:466: error: undefined reference to 'cmsDeleteTransform'
../video/out/gpu/lcms.c:490: error: undefined reference to 'cmsDeleteContext'
../video/out/gpu/lcms.c:104: error: undefined reference to 'cmsGetContextUserData'
../video/out/opengl/hwdec_drmprime_drm.c:280: error: undefined reference to 'drmModeGetCrtc'
../video/out/opengl/hwdec_drmprime_drm.c:284: error: undefined reference to 'drmModeFreeCrtc'
../video/out/opengl/hwdec_drmprime_drm.c:288: error: undefined reference to 'drmGetCap'
../video/out/opengl/hwdec_drmprime_drm.c:303: error: undefined reference to 'drmGetDeviceNameFromFd2'
../video/out/opengl/hwdec_drmprime_drm.c:206: error: undefined reference to 'drmModeSetPlane'
../video/out/opengl/hwdec_drmprime_drm.c:128: error: undefined reference to 'drmModeAtomicAlloc'
../video/out/opengl/hwdec_drmprime_drm.c:133: error: undefined reference to 'drmModeAtomicCommit'
../video/out/opengl/hwdec_drmprime_drm.c:138: error: undefined reference to 'drmModeAtomicFree'
../video/out/vo_drm.c:143: error: undefined reference to 'drmModeAddFB2'
../video/out/vo_drm.c:112: error: undefined reference to 'drmModeRmFB'
../video/out/vo_drm.c:112: error: undefined reference to 'drmModeRmFB'
../video/out/vo_drm.c:600: error: undefined reference to 'drmGetCap'
../video/out/vo_drm.c:217: error: undefined reference to 'drmModeGetCrtc'
../video/out/vo_drm.c:218: error: undefined reference to 'drmModeSetCrtc'
../video/out/vo_drm.c:499: error: undefined reference to 'drmModePageFlip'
../video/out/vo_drm.c:355: error: undefined reference to 'drmHandleEvent'
../video/out/vo_drm.c:112: error: undefined reference to 'drmModeRmFB'
../video/out/vo_drm.c:217: error: undefined reference to 'drmModeGetCrtc'
../video/out/vo_drm.c:218: error: undefined reference to 'drmModeSetCrtc'
../video/out/vo_drm.c:236: error: undefined reference to 'drmHandleEvent'
../video/out/vo_drm.c:244: error: undefined reference to 'drmModeSetCrtc'
../video/out/vo_drm.c:249: error: undefined reference to 'drmModeFreeCrtc'
../../libass/ass_render.c:52: error: undefined reference to 'FT_Init_FreeType'
../../libass/ass_render.c:58: error: undefined reference to 'FT_Library_Version'
../../libass/ass_render.c:64: error: undefined reference to 'FT_Done_FreeType'
../../libass/ass_render.c:151: error: undefined reference to 'FT_Done_FreeType'
../../libass/ass_render.c:1187: error: undefined reference to 'FT_Done_Glyph'
../../libass/ass_shaper.c:93: error: undefined reference to 'hb_version_string'
../../libass/ass_shaper.c:151: error: undefined reference to 'hb_font_destroy'
../../libass/ass_shaper.c:152: error: undefined reference to 'hb_font_funcs_destroy'
../../libass/ass_shaper.c:256: error: undefined reference to 'FT_Load_Glyph'
../../libass/ass_shaper.c:664: error: undefined reference to 'hb_unicode_funcs_get_default'
../../libass/ass_shaper.c:670: error: undefined reference to 'hb_unicode_script'
../../libass/ass_shaper.c:664: error: undefined reference to 'hb_unicode_funcs_get_default'
../../libass/ass_shaper.c:670: error: undefined reference to 'hb_unicode_script'
../../libass/ass_shaper.c:831: error: undefined reference to 'hb_language_from_string'
../../libass/ass_shaper.c:891: error: undefined reference to 'fribidi_get_bidi_types'
../../libass/ass_shaper.c:894: error: undefined reference to 'fribidi_get_bracket_types'
../../libass/ass_shaper.c:897: error: undefined reference to 'fribidi_get_par_embedding_levels_ex'
../../libass/ass_shaper.c:724: error: undefined reference to 'fribidi_get_joining_types'
../../libass/ass_shaper.c:725: error: undefined reference to 'fribidi_join_arabic'
../../libass/ass_shaper.c:726: error: undefined reference to 'fribidi_shape'
../../libass/ass_shaper.c:734: error: undefined reference to 'FT_Get_Char_Index'
../../libass/ass_shaper.c:618: error: undefined reference to 'hb_buffer_create'
../../libass/ass_shaper.c:648: error: undefined reference to 'hb_buffer_reset'
../../libass/ass_shaper.c:414: error: undefined reference to 'hb_ft_font_create'
../../libass/ass_shaper.c:424: error: undefined reference to 'hb_font_funcs_create'
../../libass/ass_shaper.c:426: error: undefined reference to 'hb_font_funcs_set_glyph_func'
../../libass/ass_shaper.c:428: error: undefined reference to 'hb_font_funcs_set_glyph_h_advance_func'
../../libass/ass_shaper.c:430: error: undefined reference to 'hb_font_funcs_set_glyph_v_advance_func'
../../libass/ass_shaper.c:432: error: undefined reference to 'hb_font_funcs_set_glyph_h_origin_func'
../../libass/ass_shaper.c:434: error: undefined reference to 'hb_font_funcs_set_glyph_v_origin_func'
../../libass/ass_shaper.c:436: error: undefined reference to 'hb_font_funcs_set_glyph_h_kerning_func'
../../libass/ass_shaper.c:438: error: undefined reference to 'hb_font_funcs_set_glyph_v_kerning_func'
../../libass/ass_shaper.c:440: error: undefined reference to 'hb_font_funcs_set_glyph_extents_func'
../../libass/ass_shaper.c:442: error: undefined reference to 'hb_font_funcs_set_glyph_contour_point_func'
../../libass/ass_shaper.c:444: error: undefined reference to 'hb_font_set_funcs'
../../libass/ass_shaper.c:209: error: undefined reference to 'hb_font_set_scale'
../../libass/ass_shaper.c:212: error: undefined reference to 'hb_font_set_ppem'
../../libass/ass_shaper.c:635: error: undefined reference to 'hb_buffer_pre_allocate'
../../libass/ass_shaper.c:636: error: undefined reference to 'hb_buffer_add_utf32'
../../libass/ass_shaper.c:0: error: undefined reference to 'hb_language_from_string'
../../libass/ass_shaper.c:557: error: undefined reference to 'hb_language_get_default'
../../libass/ass_shaper.c:642: error: undefined reference to 'hb_buffer_set_segment_properties'
../../libass/ass_shaper.c:645: error: undefined reference to 'hb_shape'
../../libass/ass_shaper.c:573: error: undefined reference to 'hb_buffer_get_length'
../../libass/ass_shaper.c:574: error: undefined reference to 'hb_buffer_get_glyph_infos'
../../libass/ass_shaper.c:575: error: undefined reference to 'hb_buffer_get_glyph_positions'
../../libass/ass_shaper.c:651: error: undefined reference to 'hb_buffer_destroy'
../../libass/ass_shaper.c:1001: error: undefined reference to 'fribidi_reorder_line'
../../libass/ass_shaper.c:277: error: undefined reference to 'FT_Face_GetCharVariantIndex'
../../libass/ass_shaper.c:279: error: undefined reference to 'FT_Get_Char_Index'
../../libass/ass_shaper.c:346: error: undefined reference to 'FT_Get_Kerning'
../../libass/ass_shaper.c:385: error: undefined reference to 'FT_Load_Glyph'
../../libass/ass_font.c:0: error: undefined reference to 'FT_Set_Charmap'
../../libass/ass_font.c:178: error: undefined reference to 'FT_Open_Face'
../../libass/ass_font.c:187: error: undefined reference to 'FT_New_Face'
../../libass/ass_font.c:199: error: undefined reference to 'FT_Done_Face'
../../libass/ass_font.c:200: error: undefined reference to 'FT_New_Face'
../../libass/ass_font.c:207: error: undefined reference to 'FT_Get_Postscript_Name'
../../libass/ass_font.c:104: error: undefined reference to 'FT_Get_Sfnt_Table'
../../libass/ass_font.c:263: error: undefined reference to 'FT_Get_Sfnt_Table'
../../libass/ass_font.c:264: error: undefined reference to 'FT_Get_Sfnt_Table'
../../libass/ass_font.c:286: error: undefined reference to 'FT_Request_Size'
../../libass/ass_font.c:311: error: undefined reference to 'FT_Get_Sfnt_Table'
../../libass/ass_font.c:339: error: undefined reference to 'FT_MulFix'
../../libass/ass_font.c:340: error: undefined reference to 'FT_MulFix'
../../libass/ass_font.c:475: error: undefined reference to 'FT_Get_Char_Index'
../../libass/ass_font.c:481: error: undefined reference to 'FT_Get_Char_Index'
../../libass/ass_font.c:501: error: undefined reference to 'FT_Set_Charmap'
../../libass/ass_font.c:549: error: undefined reference to 'FT_Load_Glyph'
../../libass/ass_font.c:557: error: undefined reference to 'FT_GlyphSlot_Oblique'
../../libass/ass_font.c:440: error: undefined reference to 'FT_MulFix'
../../libass/ass_font.c:443: error: undefined reference to 'FT_Outline_Embolden'
../../libass/ass_font.c:563: error: undefined reference to 'FT_Get_Glyph'
../../libass/ass_font.c:577: error: undefined reference to 'FT_MulFix'
../../libass/ass_font.c:579: error: undefined reference to 'FT_Outline_Translate'
../../libass/ass_font.c:580: error: undefined reference to 'FT_Outline_Transform'
../../libass/ass_font.c:581: error: undefined reference to 'FT_Outline_Translate'
../../libass/ass_font.c:404: error: undefined reference to 'FT_Outline_Get_Orientation'
../../libass/ass_font.c:602: error: undefined reference to 'FT_Done_Face'
../../libass/ass_fontselect.c:858: error: undefined reference to 'FT_New_Face'
../../libass/ass_fontselect.c:869: error: undefined reference to 'FT_Done_Face'
../../libass/ass_fontselect.c:870: error: undefined reference to 'FT_New_Face'
../../libass/ass_fontselect.c:876: error: undefined reference to 'FT_Get_Postscript_Name'
../../libass/ass_fontselect.c:887: error: undefined reference to 'FT_Done_Face'
../../libass/ass_fontselect.c:760: error: undefined reference to 'FT_Get_Sfnt_Name_Count'
../../libass/ass_fontselect.c:779: error: undefined reference to 'FT_Get_Sfnt_Name'
../../libass/ass_fontselect.c:818: error: undefined reference to 'FT_Get_Postscript_Name'
../../libass/ass_fontselect.c:936: error: undefined reference to 'FT_New_Memory_Face'
../../libass/ass_fontselect.c:116: error: undefined reference to 'FT_Get_PS_Font_Info'
../../libass/ass_fontconfig.c:327: error: undefined reference to 'FcConfigCreate'
../../libass/ass_fontconfig.c:328: error: undefined reference to 'FcConfigParseAndLoad'
../../libass/ass_fontconfig.c:332: error: undefined reference to 'FcConfigDestroy'
../../libass/ass_fontconfig.c:333: error: undefined reference to 'FcInitLoadConfig'
../../libass/ass_fontconfig.c:336: error: undefined reference to 'FcConfigBuildFonts'
../../libass/ass_fontconfig.c:341: error: undefined reference to 'FcConfigDestroy'
../../libass/ass_fontconfig.c:93: error: undefined reference to 'FcConfigGetFonts'
../../libass/ass_fontconfig.c:180: error: undefined reference to 'FcPatternGetString'
../../libass/ass_fontconfig.c:105: error: undefined reference to 'FcPatternGetBool'
../../libass/ass_fontconfig.c:110: error: undefined reference to 'FcPatternGetInteger'
../../libass/ass_fontconfig.c:111: error: undefined reference to 'FcPatternGetInteger'
../../libass/ass_fontconfig.c:112: error: undefined reference to 'FcPatternGetInteger'
../../libass/ass_fontconfig.c:113: error: undefined reference to 'FcPatternGetInteger'
../../libass/ass_fontconfig.c:121: error: undefined reference to 'FcWeightToOpenType'
../../libass/ass_fontconfig.c:159: error: undefined reference to 'FcPatternGetString'
../../libass/ass_fontconfig.c:165: error: undefined reference to 'FcPatternGetString'
../../libass/ass_fontconfig.c:173: error: undefined reference to 'FcPatternGetString'
../../libass/ass_fontconfig.c:66: error: undefined reference to 'FcPatternGetCharSet'
../../libass/ass_fontconfig.c:69: error: undefined reference to 'FcCharSetHasChar'
../../libass/ass_fontconfig.c:79: error: undefined reference to 'FcCharSetDestroy'
../../libass/ass_fontconfig.c:81: error: undefined reference to 'FcFontSetDestroy'
../../libass/ass_fontconfig.c:82: error: undefined reference to 'FcConfigDestroy'
../../libass/ass_fontconfig.c:274: error: undefined reference to 'FcPatternCreate'
../../libass/ass_fontconfig.c:278: error: undefined reference to 'FcPatternAddString'
../../libass/ass_fontconfig.c:279: error: undefined reference to 'FcPatternAddString'
../../libass/ass_fontconfig.c:280: error: undefined reference to 'FcPatternAddBool'
../../libass/ass_fontconfig.c:281: error: undefined reference to 'FcConfigSubstitute'
../../libass/ass_fontconfig.c:303: error: undefined reference to 'FcPatternDestroy'
../../libass/ass_fontconfig.c:197: error: undefined reference to 'FcPatternCreate'
../../libass/ass_fontconfig.c:198: error: undefined reference to 'FcPatternAddString'
../../libass/ass_fontconfig.c:199: error: undefined reference to 'FcPatternAddBool'
../../libass/ass_fontconfig.c:200: error: undefined reference to 'FcConfigSubstitute'
../../libass/ass_fontconfig.c:201: error: undefined reference to 'FcDefaultSubstitute'
../../libass/ass_fontconfig.c:205: error: undefined reference to 'FcPatternDel'
../../libass/ass_fontconfig.c:209: error: undefined reference to 'FcFontSort'
../../libass/ass_fontconfig.c:214: error: undefined reference to 'FcFontSetCreate'
../../libass/ass_fontconfig.c:216: error: undefined reference to 'FcPatternDestroy'
../../libass/ass_fontconfig.c:243: error: undefined reference to 'FcCharSetHasChar'
../../libass/ass_fontconfig.c:250: error: undefined reference to 'FcPatternGetCharSet'
../../libass/ass_fontconfig.c:252: error: undefined reference to 'FcCharSetHasChar'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/home/acer-pc/Documents/mpv-android/buildscripts/deps/mpv/_build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

**Comment by sfan5** [comment]
Looks like the mpv build is picking up libraries installed on your host system, this should definitely not be happening.
Can you pastebin `buildscripts/deps/mpv/_build/config.log` somewhere?

**Comment by gmohiuddin215** [comment]
Here is the pastebin of file you have asked for..
https://pastebin.com/w27PWc0c

**Comment by sfan5** [comment]
Looks like pkg-config is not doing what it is supposed to.
Do you have `PKG_CONFIG_PATH` or any other pkg-config related variables defined (check with `printenv`)?

**Comment by gmohiuddin215** [comment]
I ran the `printenv` command and the result is `PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig`.

**Comment by gmohiuddin215** [comment]
I have now changed `PKG_CONFIG_PATH` to `PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig` but still I'm getting the same `error: undefined reference to ' '`.

**Comment by sfan5** [comment]
This is fixed by 09825c3dac6d546b23c1b739bfe44076fa1e346d but before you try again make sure to the `prefix` folder inside buildscripts.
