### ISSUE TITLE
No package 'freetype2' found

### ISSUE THREAD

**Issue by gmohiuddin215** [mpv-android/mpv-android#279]
Solved the previous problem. But after i ran into this problem.

`checking pkg-config is at least version 0.9.0... yes
checking for FREETYPE... no
configure: error: Package requirements (freetype2 >= 9.10.3) were not met:

No package 'freetype2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.`
I have installed `libfreetype6` and `libfreetype6-dev`. I installed them again and following are their versions:
`$ sudo apt install fontconfig libfreetype6 libfreetype6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fontconfig is already the newest version (2.13.1-2ubuntu3).
libfreetype6 is already the newest version (2.10.1-2).
libfreetype6-dev is already the newest version (2.10.1-2).`

**Comment by sfan5** [comment]
Please show the contents of `buildscripts/deps/libass/_build/config.log`.
Also note that the script build libraries manually, installing from apt doesn't help.

**Comment by gmohiuddin215** [comment]
As you said that I shouldn't have installed libraries from apt so I accidentaly removed all the libraries including ubuntu i.e terminal. I have reinstalled ubuntu and build the project from ground. Now it has been build successfully without error.
