### ISSUE TITLE
Playing videos are strange on samsung phones

### ISSUE THREAD

**Issue by fifa87** [mpv-android/mpv-android#280]
I have built QT project using the following example on android.
https://github.com/mpv-player/mpv-examples

I used this recent libraries built by using github,
https://github.com/mpv-android/mpv-android
But on all new Samsung phones(Android 9-10) and few phones playing video is strange.
most Other phones are ok.
Please look at this link video.
https://drive.google.com/file/d/1EaVYDEt1_nzC-UjzG1NxWeZPC7CMypzi/view?usp=sharing
https://drive.google.com/file/d/1R5OYsI3rvXPhp0Ppj32Y2K16VCvbe0Ht/view?usp=sharing
are there anyone to help?

I used this options
    mpvSetProperty("hwdec", "auto-safe");

I used Qt.5.14.2. libmpv for android is recent on above github.
This is very urgent. please help me.
Best Regards.

**Comment by sfan5** [comment]
Interpolation can be buggy on some phones, I suggest you disable it.

**Comment by fifa87** [comment]
Thank you for your response.
But I have not been used Interpolation at first.
It was same.
I will be waiting for your great tip.
Best Regard.


On 6/19/2020 17:35，sfan5<notifications@github.com> wrote：

Interpolation can be buggy on some phones, I suggest you disable it.

**Comment by crisalis2** [comment]
Try writing "untimed" in the "Edit mpv.conf" option. It surprisingly works for me with no issues.

**Comment by fifa87** [comment]
I couldn't fix this issue finally.
i used QOpenGLFramebufferObject for rendering.
It works well in windows. But it couldn't work well on some phones(especially many samsung phones).
So i used native Surfaceview for rendering on Android.
