### ISSUE TITLE
No video/image display on LG G2 (D802)

### ISSUE THREAD

**Issue by ghost** [mpv-android/mpv-android#281]
##### Device information
Model: LG G2 (D802)
OS: Stock Android 5 (unrooted)

##### Problem description
mpv-android is unable to display video (e.g. MP4 files) or image (e.g. embedded image in FLACs) properly. I either see a black screen (Screenshot 1) or a corrupted output (Screenshot 2).
I am using default settings, and disabling hardware acceleration does not solve the issue.

Version | Outcome
------------ | -------------
2020-06-02 | Black screen
2018-02-22 | Corrupted output
2017-01-10-nodebug | Black screen
2016-04-20 | Corrupted output

VLC and other apps play videos correctly on my LG G2.

##### Screenshots
Screenshot 1:
![screenshot-1](https://user-images.githubusercontent.com/52369821/85215941-8bb6aa00-b36e-11ea-95b4-e0da72b7825b.png)

Screenshot 2:
![screenshot-2](https://user-images.githubusercontent.com/52369821/85215945-907b5e00-b36e-11ea-8d7c-90a2c526ebde.png)

**Comment by sfan5** [comment]
Please create a logfile using [logcat](https://developer.android.com/studio/command-line/logcat) and post it here. You can filter for mpv's output using ` -s 'mpv:*'`

**Comment by ipaucek4680** [comment]
[log.txt](https://github.com/mpv-android/mpv-android/files/4809272/log.txt)

During the process, I clicked on the "SW" ("HW") button to switch on/off HW decoding, but the issue is still present.

**Comment by sfan5** [comment]
Honestly no idea what could be causing this.
Here's two suggestions you can try in your mpv.conf: `fbo-format=rgba8` or `vf=format=yuv420p`.

**Comment by ipaucek4680** [comment]
I tried your suggestions but unfortunately mpv-android still does not work. :disappointed: 
Until this mystery is solved, I guess I will use VLC then.
Thank you very much for helping!

**Comment by T-10001** [comment]
How to apply `vf=format=yuv420p` programmatically?

Would it be `MPVLib.setOptionString("vf", "format=yuv420p")`?

**Comment by tmm1** [comment]
`"vf", "lavfi=[format=...]"`
