### ISSUE TITLE
No video on X96Max+2(Mali-G31 GPU) when GPU video filters applied

### ISSUE THREAD

**Issue by Kindzza** [mpv-android/mpv-android#292]
Model: X96Max+2 TV Box
OS: Stock Android 9 (rooted/unrooted)
mpv-android is unable to display video when GPU video filters applied. There's only a black screen displayed. The result is the same for 'sharpen' filter in mpv.conf, GPU debanding and all GPU video scalers except 'bilinear' one, no matter HW or SW decoding is used. Logcat logs are attached below. There were no such problems on similar(slow) GPUs like Adreno 308(Snapdragon 425) and PVR GE8320(Helio A22).
[mpv_gpu_deband.log](https://github.com/mpv-android/mpv-android/files/5012017/mpv_gpu_deband.log)
[mpv_gpu_lanczos.log](https://github.com/mpv-android/mpv-android/files/5012018/mpv_gpu_lanczos.log)
[mpv_gpu_sharpen.log](https://github.com/mpv-android/mpv-android/files/5012019/mpv_gpu_sharpen.log)

**Comment by theqp** [comment]
The same happens on my Galaxy S7

OS: Unofficial Lineage OS 17.1 
Chipset: Exynos 8890 Octa (14 nm)
CPU: Octa-core (4x2.3 GHz Mongoose & 4x1.6 GHz Cortex-A53)
GPU: Mali-T880 MP12

**Comment by Yaneca** [comment]
The same happens on Huawei P30 Pro, Mali-G76, Android 10. No video if any scaling besides the default is used or if debandingis activated

**Comment by BenjaminWegener** [comment]
After running some tests i can confirm, seems to be a problem with the mali kbase driver. Snapdragon works and on debian arm64 chromebook works with panfrost driver. Amazon Fire cube 'raven' doesnt work to

**Comment by user1121114685** [comment]
`--gpu-dumb-mode=<yes|no|auto>
This mode is extremely restricted, and will disable most extended features. That includes high quality scalers and custom shaders!

It is intended for hardware that does not support FBOs (including GLES, which supports it insufficiently), or to get some more performance out of bad or old hardware.

This mode is forced automatically if needed, and this option is mostly useful for debugging. The default of auto will enable it automatically if nothing uses features which require FBOs.

This option might be silently removed in the future.`

使用这个模式可以让有图像输出。
