### ISSUE TITLE
mpv-android seems to wrongly detect display resolution.

### ISSUE THREAD

**Issue by Kindzza** [mpv-android/mpv-android#293]
Model: X96Max+2 TV Box
OS: Stock Android 9
mpv-android seems to wrongly detect display resolution. Though 720p@60Hz was set as system resolution and 'getprop' output was [vendor.display-size]: [1280x720], mpv-android logcat shows 'android-surface-size=1920x1080' and that video is resized to 1920x1080, and it seems to be a bit blurry. The result is the same with both HW and SW decoding. Forcing android-surface-size to 1280x720 in mpv.conf changed nothing.
[mpv_hw.log](https://github.com/mpv-android/mpv-android/files/5014624/mpv_hw.log)
[mpv_hw_forced_surface_size.log](https://github.com/mpv-android/mpv-android/files/5014625/mpv_hw_forced_surface_size.log)
[mpv_sw.log](https://github.com/mpv-android/mpv-android/files/5014626/mpv_sw.log)

**Comment by sfan5** [comment]
If the surface size was incorrect then the picture would either be cut off or not fill the entire screen area, so the only possible conclusion here is that your system UI indeed renders at 1080p.
You can use `adb shell dumpsys display` to see what the OS thinks about the display device and available modes.

**Comment by Kindzza** [comment]
It seems the tv box OS really renders at 1920x1080 no matter what mode(1080i, 720p, 576p, 480p) is chosen in the display settings. 'dumpsys display' shows 1920x1080 as the only available resolution, though TV always switches to that mode which is set in the display settings of the TV box.

**Comment by Enivex** [comment]
Why is this issue closed?

**Comment by sfan5** [comment]
Because it won't be fixed.
mpv uses standard OpenGL output and if those cannot run at native resolution due to special stuff done by TV vendors then that's not our problem.

**Comment by Enivex** [comment]
> Because it won't be fixed.
> mpv uses standard OpenGL output and if those cannot run at native resolution due to special stuff done by TV vendors then that's not our problem.

I would argue that it is your problem if you claim that android tv is supported. This affects every single user with a 4k tv.
