### ISSUE TITLE
Repeat and Shuffle buttons

### ISSUE THREAD

**Issue by chromer030** [mpv-android/mpv-android#294]
Hi , thank you for this powerful and great app.

~~1- As requested in #176 Please add an option to only include media files in picker , but for both audio and video files , it's somehow hard to search for medias among non-media files.
will be great if mpv-android scan for media files in both internal and external storage and show them in picker.~~ (duplicate)

2- Repeat , Snuffle and lock is needed as a button or option.

Thanks again.

**Comment by rancidfrog** [comment]
Suggestion for the repeat button implementation:
- on tap - toggle repeat
- on long click - set how many times to repeat a video; I.E. repeat 10 x times
