### ISSUE TITLE
Add translation for pt_BR

### ISSUE THREAD

**Issue by aevw** [mpv-android/mpv-android#295]
Hello mpvandroid devs,

I translated strings for mpv-android into pt_BR.

Hope it can be useful.

Here are the files:
[Arrays-pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/mpv-arrays-pt_BR.xml) , [Strings-pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/mpv-strings-pt_BR.xml) 

Thanks

**Comment by sfan5** [comment]
Added in commit 41abba681735e9a0a645298b51a1612125392ffd, thanks.

For next time it would be useful if you could make a Pull Request with the files directly.
