### ISSUE TITLE
OP3T HW works bad

### ISSUE THREAD

**Issue by 532910** [mpv-android/mpv-android#298]
HW decoding works noticeably worse than SW on OP3T (Snapdragon 821)
On speed above 1x SW always works better than HW. On 1x HW works mostly good, but sometimes slows down.

LineageOS 15 16 17.1 (Android 8 9 10)

**Comment by 532910** [comment]
Is it possible to run `-vo=help` and `-hwdec=help` somehow?

**Comment by sfan5** [comment]
You can try putting `vo=help` in mpv.conf and look at the log output.
But there's nothing interesting there, the only possible hwdecs are `mediacodec` and `mediacodec-copy`, the former of which only works with `vo=mediacodec_embed`, which mpv-android does not support.

**Comment by 532910** [comment]
It looks like this is not an mpv bug.

1. vlc and other players works the same way.
2. mpv reports no errors for hw codec (`vo=mediacodec-copy hwdec=mediacodec`)

I played with options and the fastest is `vo=gpu` for me.
