### ISSUE TITLE
Allow setting of playback speed in UI

### ISSUE THREAD

**Issue by xylix** [mpv-android/mpv-android#30]

**Comment by alive4ever** [comment]
Bumped into this issue.

On desktop, one can just press `[` to slow down and `]` to speed up.

On mobile display, it's not possible to trigger the touch keyboard within the app, so it'll be convenient to have an ui to alter playback speed.

+1 vote for this.

**Comment by sfan5** [comment]
61d62b38bd4aee650ebefe8ceb8834946a254945

**Comment by alive4ever** [comment]
Thanks for fixing this issue.

Still waiting for a new test build to be released.

**Comment by lanbla** [comment]
> 
> 
> [61d62b3](https://github.com/mpv-android/mpv-android/commit/61d62b38bd4aee650ebefe8ceb8834946a254945)

I would be very thankful that a new test build be released with video speed control.

**Comment by alive4ever** [comment]
After viewing travis build log, the resulting apk file is uploaded to 0x0.st

http://0x0.st/slkY.apk
