### ISSUE TITLE
lut file can't be load by inbuilt ffmpeg (No such file or directory)

### ISSUE THREAD

**Issue by rhjdvsgsgks** [mpv-android/mpv-android#301]
mpv.conf
```
vf=lavfi=[lut3d=file="/storage/emulated/0/1.cube"]
```
crash log
```
[cplayer:v] Setting option 'vf' = 'lavfi=[lut3d=file="/storage/emulated/0/1.cube"]' (flags = 4)
[user_filter_wrapper:v] Setting option 'graph' = 'lut3d=file="/storage/emulated/0/1.cube"' (flags = 0)
[ffmpeg:error] Parsed_lut3d_0: "/storage/emulated/0/1.cube": No such file or directory
[ffmpeg:error] AVFilterGraph: Error initializing filter 'lut3d' with args 'file="/storage/emulated/0/1.cube"'
```
storage permission was granted, and video file is accessible

**Comment by sfan5** [comment]
There's no additional filesystem sandboxing or similar, are you sure the file exists at that location?

**Comment by rhjdvsgsgks** [comment]
Yes i promise the file exists at that path , i also tried put the file to `/data/data/is.xyz.mpv/files/1.cube` and set permission for mpv (via root) ， but still say "No such file or directory"
