### ISSUE TITLE
Shall hardware/software decoding switch be moved to "Advanced" popup?

### ISSUE THREAD

**Issue by vi** [mpv-android/mpv-android#305]
For me typically hardware decoding always works, so it just takes up button space.

Ideally UI should be a bit customisable, allowing to select which adjustments to promote to quick access buttons and which leave in advanced window. For example, for some broken videos you need to constrantly re-adjust A/V delay (or subtitle delay) for it to remain in sync. Or sometimes you want to manipulate Gamma for some scenes, but leave it default for most content.

**Comment by sfan5** [comment]
If you watch 10-bit content hardware decoding typically stays enabled but produces broken output, requiring you to manually disable it. Having it on the button bar also allows you to see if hwdec is working for this file at a glance.

I don't think it should be moved to a more obscure place but UI customisability is definitely something I want to have in the future.
