### ISSUE TITLE
Dropped frames with display-resample and hwdec

### ISSUE THREAD

**Issue by brucethemoose** [mpv-android/mpv-android#307]
Playing a 1080p video results in lots of dropped and mistimed frames when display-resample and hardware decoding is enabled. But playback is smooth when I switch to software decoding, or when I set video-sync to "audio".

Hardware: Razer Phone 2, SD845, display set to 120hz and 1080p, Android 9

Video: 1080p24 8 bit AVC, 6 channel AAC audio.

MPV settings: All default, except for AV sync and debug info.

Heres some logs with display-resample enabled. I start with hardware decoding, then switch to software decoding about half way through: 
[2020-09-08_16.44-hwdecbug.zip](https://github.com/mpv-android/mpv-android/files/5191103/2020-09-08_16.44-hwdecbug.zip)

This happens with the last couple of releases. However, going way back to the 2018.04.29 build results in flawless playback with hwdec and display-resample enabled, as mentioned here: https://github.com/mpv-android/mpv-android/issues/272

I created a new issue because this is specific to display-resample. And I know some hardware is too slow for display-resample, but I feel like an SD845 should be able to handle this, and there appears to be some kind of regression after the 2018 build.

Let me know if I should upload/test anything else.

**Comment by brucethemoose** [comment]
Ah so I was wrong about the build/timeframe!

1-30 performs perfectly with HW decoding and display-resample: 
![HW_OLD](https://user-images.githubusercontent.com/8422224/92815744-87f55b00-f392-11ea-8202-91eb62490ca1.jpg)

While 5-27 drops a ton of frames and looks noticably more stuttery: 
![HW_NEW](https://user-images.githubusercontent.com/8422224/92815916-b410dc00-f392-11ea-851b-e1d30e98aa64.jpg)

But performs and (mostly) looks fine with SW decoding: 
![SW_NEW](https://user-images.githubusercontent.com/8422224/92815973-d145aa80-f392-11ea-8c18-6132a160a153.jpg)


As it turns out, stats.lua was tripping me up in earlier testing. All builds drop frames with it enabled, while the native stats overlay appears to be much less problematic. This is from the 1-30 build:
![Old_Lua_HW](https://user-images.githubusercontent.com/8422224/92816101-0baf4780-f393-11ea-8edc-b50920a0344f.jpg)

**Comment by brucethemoose** [comment]
BTW I found 5-27 by testing the builds one at a time, starting with the 2018 one. So builds before 1-30 appear to perform fine as well.

The latest  build still has the issue: 
![newest_HW](https://user-images.githubusercontent.com/8422224/92820029-76fb1880-f397-11ea-9135-0d601d4ed5cc.jpg)

And it still happens with the stats overlay disabled.

**Comment by sfan5** [comment]
> As it turns out, stats.lua was tripping me up in earlier testing. All builds seem to drop frames with it enabled, while the native stats overlay appears to be much less problematic. 

Can reproduce that here.

> 5-27 drops some frames and looks WAY more stuttery than those stats suggest:

2020-05-27 has a known regression in hwdec performance, you should be testing 2020-06-02 instead.

<hr />

Is this issue about dropped frames or mistimed/delayed frames (which are only shown in stats.lua)?
And when the bug is present, the player constantly drops frames similar to the first GIFs I posted?

And these are your testing results, is that correct?
Version | Result
--------|--------
2020-09-04 | not okay
2020-06-02 | not okay
2020-01-30 | okay

**Comment by brucethemoose** [comment]
OK so there was another small misunderstandings on my part. I mistakenly equated the mistimed frames in stats.lua with dropped frames in the native overlay.

As you can see above, 1-30 is not dropping frames on my device with stats.lua enabled.

Anyway:

> And these are your testing results, is that correct?
> Version 	Result
> 2020-09-04 	not okay
> 2020-06-02 	not okay
> 2020-01-30 	okay

Correct. Additionally, all builds between 2020-01-30 and 2018-04-29 are OK.

> Is this issue about dropped frames or mistimed/delayed frames (which are only shown in stats.lua)?

Both? This is from the 2020-09-04 build:
![hw__lua_newest](https://user-images.githubusercontent.com/8422224/92942164-3e068680-f41f-11ea-8dd0-d8e01193910f.jpg)

It clearly has more dropped frames, more delayed/mistimed frames and more VSync jitter than the 1-30 build in stats.lua.


Additionally, I'm using a test scene where any kind of hiccup in frame delivery is very visible. Even with the stats overlay disabled entirely, I can see constant stutters in the 2020-09-04 build, and no visible stutters in the 1-30 build.

**Comment by brucethemoose** [comment]
> 2020-05-27 has a known regression in hwdec performance, you should be testing 2020-06-02 instead.

Good to know. The issue is still present in 2020-06-02: 
![06-hw-lua_1](https://user-images.githubusercontent.com/8422224/92947149-9c366800-f425-11ea-882a-d5ad1c6ba5e9.jpg)



I tested the same scene at 60hz instead of 120hz. Here is 09-04:
![09-lua-hw-60](https://user-images.githubusercontent.com/8422224/92947344-e0c20380-f425-11ea-8fb5-a7f9d85194bf.jpg)

And here is 01-30: 
![01-lua-hw-60_1](https://user-images.githubusercontent.com/8422224/92947624-3a2a3280-f426-11ea-9b28-dc2118e033b7.jpg)

Even at 60hz, there are fewer dropped frames, mistimed frames, and less VSync jitter in the 01-30 build.



I tried another clip with a different format: 1080p30 HEVC


At 60hz, performance in 1-30
![01-hw-60](https://user-images.githubusercontent.com/8422224/92947964-b15fc680-f426-11ea-802b-684774cdf9a6.jpg)

Is better than 09-04: 
![09-hw-60](https://user-images.githubusercontent.com/8422224/92948129-e8ce7300-f426-11ea-86f7-d481cde9b815.jpg)


At 120hz, the difference between 01-30: 
![01-hw-120_1](https://user-images.githubusercontent.com/8422224/92948310-2a5f1e00-f427-11ea-979a-0b483928bd84.jpg)

And 09-04: 
![09-hw-120](https://user-images.githubusercontent.com/8422224/92948368-3fd44800-f427-11ea-86ea-4197fdef632b.jpg)

Is much more dramatic.

**Comment by sfan5** [comment]
I can confirm that the amount of dropped mistimed/delayed frames is much higher on newer builds, but only when using hwdec.

<pre>
0c9ac5835be70ae26e4aa875e833fe2c7b3b3bf3 is the first bad commit
commit 0c9ac5835be70ae26e4aa875e833fe2c7b3b3bf3
Author: wm4 <wm4@nowhere>
Date:   Fri Apr 10 01:33:38 2020 +0200

    video: remove another redundant wakeup
    
    The wakeup at the end of VO frame rendering seems redundant, because
    after rendering almost no state changes. The player core can queue a new
    frame once frame rendering begins, and there's a separate wakeup for
    this. The only thing that actually changes is in->rendering. The only
    thing that seems to depend on it and can trigger a wakeup is the
    vo_still_displaying() function. Change it so that it needs an explicit
    call to a new API function, so we can avoid wakeups in the common case.
    
    The vo_still_displaying() code is mostly just moved around due to
    locking and for avoiding forward declarations.
    
    Also a somewhat risky change (tasty new bugs).

 player/video.c |  4 +++-
 video/out/vo.c | 61 ++++++++++++++++++++++++++++++++++++++++------------------
 video/out/vo.h |  1 +
 3 files changed, 46 insertions(+), 20 deletions(-)
</pre>

**Comment by brucethemoose** [comment]
Ahh, so this is a [MPV issue](https://github.com/mpv-player/mpv/commit/0c9ac5835be70ae26e4aa875e833fe2c7b3b3bf3), not necessarily an Android specific one. Should I post an issue there?

**Comment by brucethemoose** [comment]
As a workaround, adding this to mpv.conf fixes the stutter in the 24p video with display-resample:

`vd-queue-enable=yes
ad-queue-enable=yes
vd-queue-max-bytes=2000MiB`

It may not fix the performance regression, but it seems to give the decoder and vo more breathing room.

**Comment by sfan5** [comment]
I talked to wm4 to it but it wasn't clear if there was an obvious way to fix it.

Reverting the affected commit (+2 more) produces this build which should have identical performance to before:
https://kitsunemimi.pw/tmp/mpv-android-2020-09-25.apk

**Comment by brucethemoose** [comment]
That build performs well. No dropped frames:

![Screenshot_20200926-175922small](https://user-images.githubusercontent.com/8422224/94351076-fbe66300-0022-11eb-885e-9178e4077462.jpg)

Thanks!

**Comment by brucethemoose** [comment]
Is this fix going to be in builds going forward, or is it something that needs to be fixed in MPV?

Also, which 2 other commits did you omit? I think I'm going to just build MPV-Android myself.

**Comment by sfan5** [comment]
The bug fix will need to be in mpv, no idea if/when/how that's gonna happen.

The reverted commits are (in order):
<pre>
57462580180ecc9006b625b94e895a38e1118f69
6a13954d67143fb3c4ac8a4a7624c23e3ecb9a3c
0c9ac5835be70ae26e4aa875e833fe2c7b3b3bf3
</pre>
Since I'm pretty sure there was a conflict here are the patch files: [patch.zip](https://github.com/mpv-android/mpv-android/files/5607161/patch.zip)

**Comment by RAGEdemon** [comment]
Can confirm - 4k videos with display-resample are a stuttery mess. Disabling HW acceleration as a workaround degrades performance even further because 4k videos need HW acceleration due to high processing demand.

**Comment by sfan5** [comment]
Fixed upstream.
