### ISSUE TITLE
add an edit config file option

### ISSUE THREAD

**Issue by BrainDamage** [mpv-android/mpv-android#31]
the gui menu will always lag behind the configuration file in terms of flexibility and option support 
having an option to send a text editing intent to edit the config file manually for power users would be a good compromise to give full feature support in exchange for less than ideal common user interface

**Comment by sfan5** [comment]
done in #108

**Comment by Shamaoke** [comment]
Where's the file stored? Can it be edited outside of mpv?

**Comment by sfan5** [comment]
`/data/user/0/is.xyz.mpv/files/mpv.conf` (or `/data/data` on older Android, not sure). You can edit it if rooted.

**Comment by nedz25** [comment]
There is a folder called "is.xyz.mpv", but there is no mpv.conf in it.
.../storage/emulated/0/Android/is.xyz.mpv

**Comment by chrcoluk** [comment]
I have /data/data/is.xyz.mpv/files/ but no mpv.conf in there.

There is no is.xyz.mpv in the user storage area, and no option to edit the config in the app.

Am very confused.
