### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by random29** [mpv-android/mpv-android#310]
Please make socks5 or http proxy support.

**Comment by chromer030** [comment]
Yes , it's really useful , please add support.

**Comment by sfan5** [comment]
You can do this by editing mpv.conf: https://mpv.io/manual/master/#options-http-proxy

**Comment by random29** [comment]
> You can do this by editing mpv.conf: https://mpv.io/manual/master/#options-http-proxy

I tried adding http_proxy=http://xxx.xxx.xxx.xxx:xxxx to mpv.conf, but it doesn't seem to work

**Comment by sfan5** [comment]
Firstly the option is called `http-proxy` not `http_proxy`.
As mentioned in the manual the proxy setting also doesn't work for HTTPS connections (in case you tried that), but this is not something mpv-android could fix.

**Comment by random29** [comment]
> Firstly the option is called `http-proxy` not `http_proxy`.
Yea, sry, typo
> As mentioned in the manual the proxy setting also doesn't work for HTTPS connections (in case you tried that), but this is not something mpv-android could fix.
So, there is no possible option to watch e.g. youtube videos through proxy at the moment?

**Comment by sfan5** [comment]
> So, there is no possible option to watch e.g. youtube videos through proxy at the moment?

Correct, that's not currently possible.

**Comment by chromer030** [comment]
https://github.com/mpv-player/mpv/issues/3373
