### ISSUE TITLE
youtube-dl can't play youtube url video on some phones(Samsung phones)

### ISSUE THREAD

**Issue by fifa87** [mpv-android/mpv-android#311]
I try to play youtube videos on qt project using mpv-android.
It works well on windows and most android phones.
but it can't play on some phones(especially samsung phones)
I can't know reason.

I copied asset files correctly in configPath()(getApplicationContext().getFilesDir().getPath()) and give executable permissions for the following files 
"cacert.pem", "youtube-dl", "ytdl/python3", "ytdl/python38.zip", "ytdl/youtube-dl"

and
mpvSetProperty("ytdl", "yes");
mpvSetProperty("config", "yes");
mpvSetProperty("config-dir", configPath());
mpvSetProperty("tls-verify", "yes");
mpvSetProperty("tls-ca-file", configPath() + "/cacert.pem")

on most cases, it plays youtube videos well.
but on many sumsong phones, it can't play
It returns MPV_END_FILE_REASON_ERROR.

Could you help me?
Best Regards.

**Comment by sfan5** [comment]
Logfile/Logcat output or I can't help.

**Comment by fifa87** [comment]
> Logfile/Logcat output or I can't help.

mpv log: "found youtube-dl at: /data/user/0/com.*/files/youtube-dl"
mpv log: ""
mpv log: "youtube-dl failed: not found or not enough permissions"

But youtube-dl file and other asset files for youtube-dl have been copied correctly into /data/user/0/com.*/files
checked its permission-executable
and config path has been setted /data/user/0/com.*/files correctly.
What's problem?
Pls help me.
Best Regards.

**Comment by sfan5** [comment]
No idea if it still matters, but this might be what is described here: https://stackoverflow.com/questions/58565300/ffmpeg-doesnt-work-on-android-10-goes-strait-to-onfailurestring-message-with#answer-59695276
Android 10 (API level 29) does not allow applications to extract and run executables anymore.
