### ISSUE TITLE
How can mpv show log's messages on android?

### ISSUE THREAD

**Issue by fifa87** [mpv-android/mpv-android#312]
mpvSetProperty("terminal", "yes");
mpvSetProperty("msg-level", "all=debug");

It shows log's messages on windows.
But it can't show nothing on android. What is missing by me?
Could you help me?
Best Regards.

**Comment by sfan5** [comment]
Where do you expect them to show up? There is no tty on Android.

**Comment by fifa87** [comment]
> Where do you expect them to show up? There is no tty on Android.

Can't i see mpv's log messages on logcat of android studio? on windows, mpv outputs log messages on application output windows

**Comment by sfan5** [comment]
libmpv doesn't do that, mpv-android uses `mpv_wait_event()` to wait for log messages and writes them to logcat.

**Comment by fifa87** [comment]
I missed calling mpv_request_log_messages(mpv, "terminal-default");
on android, any log messages of mpv can't be shown without this calling.
Thank you.
