### ISSUE TITLE
"Result from an activity" Support for Jellyfin

### ISSUE THREAD

**Issue by vegedb** [mpv-android/mpv-android#316]
This is needed to implement with **jellyfin**'s new feature of using _external players_.  Apparently, while mpv is the **best player on android**, it has the inability to play thru jellyfin compared to MX-player and VLC which has **_"Result from an activity"_** feature.

 I've made a request on their issues page here, https://github.com/jellyfin/jellyfin-android/issues/149

I'll quote what the dev has said there, 
> In this case you need to go to https://github.com/mpv-android/mpv-android and open a new issue where you kindly ask if they can implement returning a result from an activity when using an Intent like in MX Player and VLC Player. Without this we cannot know if the playback was successful, failed or ended at some point, so playback tracking is not supported in your best FOSS minimalist player.
> 
> They have already implemented a part in [mpv-android/mpv-android#65](https://github.com/mpv-android/mpv-android/pull/65) based on the MX Player definition, only the other is missing with the result of the activity
> 
> Reference MX Player: https://mx.j2inter.com/api#:~:text=%5BResult%3A%20%20com.mxtech.intent.result.VIEW%5D
> Reference Android: https://developer.android.com/training/basics/intents/result?hl=en
> Reference VLC Implementation: https://code.videolan.org/videolan/vlc-android/-/commit/c66a40bb16d29cabf3b2dcf6371fc4c2e866187d

Hope you guys take a look.

**Comment by sfan5** [comment]
How does this look? https://github.com/mpv-android/mpv-android/commit/877df2f049ec74193b8bb3afa1a7a97e7a364fcf
