### ISSUE TITLE
Persian/Arabic default font problem

### ISSUE THREAD

**Issue by SSgumS** [mpv-android/mpv-android#318]
Hello

The default font that mpv-android uses on behalf of non-attached fonts in ass subtitles, has missing characters for Persian/Arabic language. When fonts are attached every thing is fine but if it's not, the default font ruins the sub.

You can see the issue in image bellow:
[corrupted line](https://files.catbox.moe/vsn69u.jpg)
The correct sentence for the image above is:
پس تجربه‌ی کار کردن با حرفه‌ای ها رو هم دارین، آره؟

Thanks in advance

**Comment by sfan5** [comment]
Can reproduce. But `U+0622` (آ) and `U+06CC` (ی) are present in the font, no idea why it isn't rendering them.

**Comment by SSgumS** [comment]
I tested the new font on mpv-android 2020-10-13-release. Unfortunately it was even worse.
Maybe you can get inspirations from these two fonts. Lalezar is broken in android players (like currently used font in mpv-android) but Vazir is excellent.
[Vazir Font](https://github.com/rastikerdar/vazir-font)
[Lalezar Font](https://github.com/BornaIz/Lalezar)

**Comment by sfan5** [comment]
The new font isn't what fixed this issue (not alone at least), it's the addition of harfbuzz.
