### ISSUE TITLE
never hide osc

### ISSUE THREAD

**Issue by disdaogitacc** [mpv-android/mpv-android#327]
hi and thank you. so far i've tried osc-visibility=always with no luck. is there anyway to make the on screen controller never hide?

sorry for my noobieness
cheers

**Comment by sfan5** [comment]
The user interface ("OSC") is done in Java so is not affected by mpv settings, hence this isn't currently possible.

**Comment by disdaogitacc** [comment]
could you also add feature-request label as i'd desperately need this one option?
much appreciated

**Comment by disdaogitacc** [comment]
wow thanks for the lock option. for real.
