### ISSUE TITLE
Are cplugins loadable without root access on system?

### ISSUE THREAD

**Issue by YggdrasiI** [mpv-android/mpv-android#329]
Hello, mpv-android is compiled with 'cplugin' option but if I try to load such plugin on an AndroidTV, 'logcat -s "mpv" | grep webui" shows

``
[libwebui:error] C plugin error: 'dlopen failed: library "/sdcard/mpv/libwebui.so" needed or dlopened by "/data/app/is.xyz.mpv-Ow2iy4ebNMKDU6ICMME17A==/lib/arm/libmpv.so" is not accessible for the namespace "classloader-namespace"'
11-14 15:33:09.464 17124 19380 V mpv     : [libwebui:error] Could not load SO plugin /sdcard/mpv/libwebui.so
``

Does a way exists which allows me to load such plug-in without a complete rebuild of mpv-android?

Regards

**Comment by sfan5** [comment]
There is nothing about mpv-android preventing you from loading cplugins, rather it is Android's [security model](https://developer.android.com/about/versions/nougat/android-7.0-changes#ndk).

**Comment by YggdrasiI** [comment]
Yes, the reason can be found in the security model, but maybe it exists an uncommon way to still load a library. 
Lets assume I enable the option which allows me to install apk's over adb. Then there is no big difference in terms of security between installing a enriched library by apk or 
tell the system it should extend the list of allowed libs of an already installed application by libXYZ.so

Well, I think it will just remain a dream to copy my tiny plugin from a Termux+mpv environment on a mpv-android environment without the hassle of installing/using NDK.

**Comment by sfan5** [comment]
If you have root you could copy the library to the same path mpv-android's libraries reside, then Android would allow them to be loaded.
Alternative you could bundle your plugin with the APK, resign it (no compiling required), Android will extract it to the same path as the other libs and it'd also be allowed to be loaded.

**Comment by YggdrasiI** [comment]
Unfortunately I can not open the plugin in mpv-android. Loading into Termux's mpv is ok, but if I load the [simple.c](https://raw.githubusercontent.com/mpv-player/mpv-examples/f2e24d5f8ab2237341d7435b0ba766e4bbc6bf3f/cplugins/simple/simple.c) example, dlopen fails: 

``
11-26 11:57:40.289 11975 12048 V mpv     : [simple:error] C plugin error: 'dlopen failed: cannot locate symbol "mpv_client_name" referenced by "/data/app/is.xyz.mpv-tOyL_orxPKqvRXGTK8ugxQ==/lib/arm64/simple.so"...'
``

Used version of mpv-android:
mpv-andoid 2020-11-16-release
mpv 0.32.0-812-g932c1ada0f

**Comment by sfan5** [comment]
Did you make sure to link the plugin to the exact libmpv.so that's in mpv-android?

**Comment by YggdrasiI** [comment]
> Did you make sure to link the plugin to the exact libmpv.so that's in mpv-android?

I thought there is no linking against libmpv/mpv during compiling time? I did not link, but just include the mpv/client.h header.
The example plugin contains this comment:
> // Warning: do not link against libmpv.so! Read:
> //    https://mpv.io/manual/master/#linkage-to-libmpv

**Comment by sfan5** [comment]
Uh right. No idea why that isn't working then, the symbol is present:
<pre>
app/src/main/libs/arm64-v8a $ readelf -a libmpv.so | grep mpv_client_name
0000000000362818  0000020100000402 R_AARCH64_JUMP_SLOT    000000000009d7b4 mpv_client_name + 0
   513: 000000000009d7b4     4 FUNC    GLOBAL DEFAULT   12 mpv_client_name
</pre>

**Comment by YggdrasiI** [comment]
(Crossposting)

This steps would be needed to reproduce the problem, I assume:
``
echo "Used cross compiler"
CLANG=[...]/termux-build/_cache/android-r21d-api-24-v3/bin/aarch64-linux-android-clang
echo "Path to Mpv's header files incl. client.h:"
MPV_INCLUDE_DIR="[git repo]mpv/libmpv/"
wget https://raw.githubusercontent.com/mpv-player/mpv-examples/f2e24d5f8ab2237341d7435b0ba766e4bbc6bf3f/cplugins/simple/simple.c
$CLANG  -o simple.so simple.c -shared -fPIC -I "$MPV_INCLUDE_DIR"

echo "Now copy simple.so on the android device, etc. E.g:"
[...]
su 
cd /data/app/is.xyz.mpv-tOyL_orxPKqvRXGTK8ugxQ==/lib/arm64 
cp [...]/simple.so .
chown system:system simple.so
chmod 755 simple so
``
Finally, edit mpv.conf and add 'script=simple.so'

**Comment by YggdrasiI** [comment]
> Uh right. No idea why that isn't working then, the symbol is present:

Ok, I will try a newer/other build. In my case no symbols are defined in libmpv.so

**Comment by YggdrasiI** [comment]
Hm, the assumption that missing symbols are the reason, was wrong. readelf shows:
``
/data/app/is.xyz.mpv-tOyL_orxPKqvRXGTK8ugxQ==/lib/arm64$ readelf -a libmpv.so  | grep mpv_client_name
00000032c830  020400000402 R_AARCH64_JUMP_SL 000000000009ed98 mpv_client_name + 0
   516: 000000000009ed98     4 FUNC    GLOBAL DEFAULT   12 mpv_client_name
``

**Comment by YggdrasiI** [comment]
I didn't found a solution yet but a kind person showed me the reason of the problem: https://github.com/android/ndk/issues/201
