### ISSUE TITLE
Time position in the center for double tap seek gestute

### ISSUE THREAD

**Issue by 532910** [mpv-android/mpv-android#332]
Time position should be shown for double tap seek gesture the same as for drag.

**Comment by sfan5** [comment]
This is a bit redundant since (double) tapping will automatically show the controls (including time position) too, but I implemented it anyway.

**Comment by 532910** [comment]
Multiple taps in a row seeks for some combined time (a minute for example). It's handy to see the result delta (total seek) you tapped in the center. The same as VLC does.

And this is redundant indeed, so I'm for not to show main OSD by double tap, the same as swipe left-fight does.
