### ISSUE TITLE
mpv stopped playing urls after update

### ISSUE THREAD

**Issue by krem** [mpv-android/mpv-android#337]
I installed mpv-android in July and recently have made it first update, after that it cannot play URLs anymore - just does nothing (local files is played ok) 
I use mpv on Linux a lot, but don't know how to debug the issue on android?
thanks.

**Comment by sfan5** [comment]
How are you playing URLs ("Open URL" function, from other app, ...)? How does the URL look, which protocol does it use?
If you're playing them from an external app, does playing them from "Open URL" work?

A [`logcat`](https://developer.android.com/studio/command-line/logcat) log would be useful too.

**Comment by krem** [comment]
Hi, thank you
I'm trying both mpv's "Open URL" dialog and sharing URL to mpv from external app, both without success for any youtube video https URL. Looking in the android docs for debug...

**Comment by sfan5** [comment]
The mpv-android version you install from the Play Store or the f-droid repo does not include youtube-dl support and won't play youtube videos.
If you need that take a look at the version [here](https://github.com/mpv-android/mpv-android/pull/58).
