### ISSUE TITLE
af = scaletempo2

### ISSUE THREAD

**Issue by 532910** [mpv-android/mpv-android#338]
Could `scaletempo2` be used by default instead of `scaletempo`? It sounds significant better.

Possible some controls could be added, but even just switching to scaletempo2 should be enough.

**Comment by sfan5** [comment]
By "by default" you mean the menu controls, right?

**Comment by 532910** [comment]
Currently `scaletempo` is used as `af`:

man mpv(1):
```
--audio-pitch-correction=<yes|no> 
           If this is enabled (default), playing with a speed different from normal automatically inserts the 
           scaletempo audio filter. For details, see audio filter section. 
```

> By "by default" you mean the menu controls, right?

Not sure if I understood the question correctly, but nope, I meant just add `af=scaletempo2` to the default configuration.

Menu controls could be added, but is it worth the effort to implement all audio (and video?) filter options.

**Comment by sfan5** [comment]
> Not sure if I understood the question correctly, but nope, I meant just add `af=scaletempo2` to the default configuration.

To my knowledge that doesn't actually use `scaletempo2` for audio speed. If you increase audio speed mpv will still insert a `scaletempo` filter. Haven't tested this however.

> Menu controls could be added

What I meant here is that mpv-android's speed controls could possibly directly use `scaletempo2`, without needing mpv to automatically insert the filter.

**Comment by 532910** [comment]
> To my knowledge that doesn't actually use `scaletempo2` for audio speed. If you increase audio speed mpv will still insert a `scaletempo` filter.

Yep, exactly.

> Haven't tested this however.

I added `af = scaletempo2=search-interval=20:window-size=10` to mpv.conf in advanced settings and it works fine for me.


> speed controls could possibly directly use `scaletempo2`

Hm, how exactly?

**Comment by 532910** [comment]
Hopefully this will be changed in the main repository: https://github.com/mpv-player/mpv/issues/8376

**Comment by 532910** [comment]
mpv uses scaletempo2 by default now: https://github.com/mpv-player/mpv/commit/b0b37df31faf01cd88e22ef5be882628b3d8d607
