### ISSUE TITLE
App crashes while picking the file 

### ISSUE THREAD

**Issue by purvagevaria** [mpv-android/mpv-android#340]
Hi, I am running the application in the android 10 device below is the stack trace. Am I doing anything wrong in compilation or any where else ? Below is the stack trace .

  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/is.xyz.mpv-Is-CVRHWv-WGIZvWg1dUjw==/base.apk"],nativeLibraryDirectories=[/data/app/is.xyz.mpv-Is-CVRHWv-WGIZvWg1dUjw==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libmpv.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at is.xyz.mpv.MPVLib.<clinit>(MPVLib.java:19)
        at is.xyz.mpv.MPVLib.create(Native Method)
        at is.xyz.mpv.MPVView.initialize(MPVView.kt:17)
        at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:183)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

-------------------------

In start while building the app I am getting below run time error 
Execution failed for task ':app:mergeDebugJniLibFolders'.
> java.lang.NullPointerException (no error message)

So I changed 
main {
            jniLibs.srcDirs = ['../../sdk/native/libs/']
            java.srcDirs = ['src']
        }

in build.gradle if gradle change is the cause of the error then let me know how to resolve this merge debug jni lib error .

**Comment by sfan5** [comment]
Did you run the build scripts as described in [here](https://github.com/mpv-android/mpv-android/tree/master/buildscripts)?

**Comment by purvagevaria** [comment]
Yes you are right I missed that part thanks for the update. Can I perform those steps in windows ? Or do I need to perform them with linux only ? I am not much aware about builing ndk .

**Comment by purvagevaria** [comment]
Hi @sfan5 can I have your mail id so that I can communicate with you?

**Comment by sfan5** [comment]
The build scripts are currently only supported on Linux. If you have any issues just post in this issue.

**Comment by purvagevaria** [comment]
I tried the command in linux enviroment ./download.sh it shows me :
 There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>

**Comment by purvagevaria** [comment]
@sfan5  is there any way to download sdk ndk anywhere else and spcify the path because I am not able to run  ./download.sh
 it shows me below error 
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>

**Comment by purvagevaria** [comment]
@sfan5  I have an update from my side I resolve yum config manager related issues 
now I am getting error at ./buildall.sh --clean
./buildall.sh --arch x86_64 mpv

May I know how to resolve this issue

**Comment by sfan5** [comment]
If the download scripts failed at any point you need to rerun them first with `./include/download-sdk.sh` or `./include/download-deps.sh` or both.

**Comment by purvagevaria** [comment]
@sfan5 download script worked as expected sdk folder created and sdk tools are included. I am facing issue in build command
/buildall.sh --clean

**Comment by sfan5** [comment]
Yes, but it looks like the dependencies are still missing so you need to run `./include/download-deps.sh` too.

**Comment by purvagevaria** [comment]
@sfan5  ./buildall.sh: line 102: ../../scripts/mbedtls.sh: Permission denied
Any reason behind it ? I want to give full permission to the path but I am not able to locate this file any idea where this file is located ?

**Comment by purvagevaria** [comment]
@sfan5  Log for command at the end it shows some error let me know if this is correct or not ?
 ./buildall.sh --arch arm64 mpv 
---------------------------------------------------------------------
Building mpv...
Dependencies: ffmpeg libass lua
Building ffmpeg...
Dependencies: mbedtls dav1d
Building mbedtls...
Dependencies:
/root/Purva/mpv-android-master/buildscripts/deps/mbedtls /root/Purva/mpv-android-master/buildscripts
  CC    aes.c
  CC    aesni.c
make[1]: aarch64-linux-android21-clang: Command not found
  CC    arc4.c
  CC    aria.c
  CC    asn1parse.c
make[1]: aarch64-linux-android21-clang: Command not found
Makefile:263: recipe for target 'aes.o' failed
make[1]: aarch64-linux-android21-clang: Command not found
make[1]: *** [aes.o] Error 127
make[1]: *** Waiting for unfinished jobs....
Makefile:263: recipe for target 'aesni.o' failed
make[1]: *** [aesni.o] Error 127
make[1]: aarch64-linux-android21-clang: Command not found
  CC    asn1write.c
  CC    base64.c
make[1]: aarch64-linux-android21-clang: Command not found
Makefile:263: recipe for target 'arc4.o' failed
make[1]: *** [arc4.o] Error 127
Makefile:263: recipe for target 'aria.o' failed
make[1]: *** [aria.o] Error 127
make[1]: aarch64-linux-android21-clang: Command not found
Makefile:263: recipe for target 'asn1parse.o' failed
make[1]: *** [asn1parse.o] Error 127
Makefile:263: recipe for target 'asn1write.o' failed
make[1]: *** [asn1write.o] Error 127
make[1]: aarch64-linux-android21-clang: Command not found
Makefile:263: recipe for target 'base64.o' failed
make[1]: *** [base64.o] Error 127
Makefile:17: recipe for target 'lib' failed
make: *** [lib] Error 2
make: *** Waiting for unfinished jobs....
  CC    src/helpers.c
  CC    src/random.c
make[1]: aarch64-linux-android21-clang: Command not found
Makefile:89: recipe for target 'src/helpers.o' failed
make[1]: *** [src/helpers.o] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: aarch64-linux-android21-clang: Command not found
Makefile:89: recipe for target 'src/random.o' failed
make[1]: *** [src/random.o] Error 127
Makefile:23: recipe for target 'mbedtls_test' failed
make: *** [mbedtls_test] Error 2

**Comment by sfan5** [comment]
It looks like your NDK is not installed correctly, I recommend deleting the mpv-android folder, cloning it again and following the steps from the beginning.

**Comment by purvagevaria** [comment]
@sfan5 I checked ndk folder is not generated. Can you provide me the code with all so included? To avoid this exersice ?

**Comment by purvagevaria** [comment]
@sfan5 as per your suggestion I downloaded all the packages again . But again stucked at same issue . @sfan5 any help on this?

**Comment by sfan5** [comment]
Do you have the output from running the download scripts? Are any errors visible in it?

**Comment by purvagevaria** [comment]
@sfan5  Here is the trace . Nothing like error in download-sdk.sh command 

./include/download-sdk.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g is already the newest version (1:1.2.8.dfsg-2ubuntu4.3).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g-dbg is already the newest version (1:1.2.8.dfsg-2ubuntu4.3).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.3).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlibc is already the newest version (0.9k-4.3).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib-gst is already the newest version (3.2.5-1build2).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libncurses5-dev is already the newest version (6.0+20160213-1ubuntu1).
libncursesw5-dev is already the newest version (6.0+20160213-1ubuntu1).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
bzip2 is already the newest version (1.0.6-8ubuntu0.2).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-9).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
m4 is already the newest version (1.4.17-5).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
pkgconf is already the newest version (0.9.12-1).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libtool is already the newest version (2.4.6-0.1).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-9).
libtool is already the newest version (2.4.6-0.1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
python3-setuptools is already the newest version (20.7.0-1).
ninja-build is already the newest version (1.5.1-0.1ubuntu1).
python3-pip is already the newest version (8.1.1-2ubuntu0.6).
The following packages were automatically installed and are no longer required:
  geoclue-2.0 gir1.2-keybinder-3.0 libappindicator1 libgeoclue-2-0 libgsound0 libindicator7 libkeybinder-3.0-0 libmysofa0 libunique-1.0-0 libx265-188
  qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-privatewidgets xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/jaydeep/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: meson in /home/jaydeep/.local/lib/python3.5/site-packages (0.54.1)
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
--2020-12-14 21:55:34--  https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
Resolving dl.google.com (dl.google.com)... 216.58.203.174, 2404:6800:4009:803::200e
Connecting to dl.google.com (dl.google.com)|216.58.203.174|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 86532348 (83M) [application/zip]
Saving to: ‘commandlinetools-linux-6609375_latest.zip.3’

commandlinetools-linux-6609375_latest.z 100%[============================================================================>]  82.52M  10.5MB/s    in 7.7s

2020-12-14 21:55:42 (10.7 MB/s) - ‘commandlinetools-linux-6609375_latest.zip.3’ saved [86532348/86532348]

mkdir: cannot create directory ‘android-sdk-linux’: File exists
jaydeep@AHMCPU2469:buildscripts$


--------
It would be great if you give me a solution related to this I have to integrate this library no any other option left with me

**Comment by purvagevaria** [comment]
@sfan5 download command give me error 
bin/gas-preprocessor.pl                 100%[============================================================================>]  43.47K  --.-KB/s    in 0.02s

2020-12-14 22:05:34 (2.73 MB/s) - ‘bin/gas-preprocessor.pl’ saved [44516/44516]

mkdir: cannot create directory ‘mbedtls’: File exists

Should I delete mbedtls and try again ?

**Comment by sfan5** [comment]
You should delete `deps` and `sdk` and run the download again, then you can try building.

> It would be great if you give me a solution related to this I have to integrate this library no any other option left with me

To make sure your expectations are accurate: mpv-android is a standalone app and cannot directly be integrated as a library (no .aar file).
You can however integrate `libmpv.so` in your own app in similar fashion, but this requires manual work.

**Comment by purvagevaria** [comment]
@sfan5  So what should I do to integrate this library code?

**Comment by purvagevaria** [comment]
@sfan5 I am getting below error after deleting sdk and all files

**Comment by sfan5** [comment]
That can happen if meson is too old, you might have to `sudo pip3 install -U meson`.

**Comment by purvagevaria** [comment]
@sfan5 Is there any other way to download all build packages without performing those commands?

**Comment by purvagevaria** [comment]
@sfan5 After complete compilation I am still getting the error 
Execution failed for task ':app:mergeDebugJniLibFolders'.
> java.lang.NullPointerException (no error message)

**Comment by purvagevaria** [comment]
@sfan5 Any update on the same ?

**Comment by purvagevaria** [comment]
@sfan5 Any update on the same ? I am seeking for your help.

**Comment by sfan5** [comment]
Did the compilation on Linux run correctly to its end? Make sure it has generated the APK at least once.

I don't know if copying the build project over to Windows works, check that you you have all the artifacts in `app/src/main/jniLibs/`

**Comment by purvagevaria** [comment]
@sfan5 yes build done successfully and two apk's where generated one is at debug and the other one is at the release folder. I want to import the project in android studio that's why I am copying it into windows .

**Comment by purvagevaria** [comment]
@sfan5 one more issue I am addressing here I am facing 500ms frame delay in the latest generated apk any idea how to reduce that delay ?

**Comment by purvagevaria** [comment]
@sfan5 I need help regarding the below points 

1. Changing 
sourceSets {
            main {
                jni.srcDirs = []
            }
        }
  **Replace** 
  sourceSets {
            main {
                jniLibs.srcDirs = ['libs']
            }

        }
        
  
I am able to run the project but as I mentioned in first comment I am getting crash 
**So is there any way to resolve that error ?**

2. **I am facing frame delay of 500ms in the current app so is there any way to reduce that delay if yes how? Kindly mention the files with the path to change those** 

3. I wan to integrate this code in the android studio any idea how to resolve 
Execution failed for task ':app:mergeDebugJniLibFolders'.
> java.lang.NullPointerException (no error message)

As I completed all the build related task and as mentioned earlier two apks are generated .

@sfan5 It would be great if are able to help me in these issues .

**Comment by purvagevaria** [comment]
@sfan5 Any update on the same ?

**Comment by sfan5** [comment]
1. You do not need to modify any build configuration/settings. Doing so will break it.

2. Hardware might be too slow or the settings to intensive, hard to say without exact details such as a log file.

**Comment by purvagevaria** [comment]
@sfan5
1. If I don't modify the setting then also it shows me an error 
I want to integrate this code in the android studio any idea how to resolve
Execution failed for task ':app:mergeDebugJniLibFolders'.

My all build tasks were completed successfully and two apks were generated. But when I am opening it I am facing a null pointer in Gradle build.

2. I don't have any log file but I performed udp hotspot streaming and I am facing a frame delay of 500ms. Attaching video of frame delay. Uploaded the 4 files please check each frame are having 5 milliseconds delay.

@sfan5 Is there any solution for both cases? 

For the build, my thinking is I reached the end level but I am not able to import it in android studio. 

<img width="960" alt="2" src="https://user-images.githubusercontent.com/28977633/102382897-ee70c180-3ff0-11eb-9aae-3d64eebad572.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/28977633/102382904-ef095800-3ff0-11eb-9c89-75619b020ca2.png">
<img width="960" alt="4" src="https://user-images.githubusercontent.com/28977633/102382910-f03a8500-3ff0-11eb-8293-c73a23879e9f.png">



<img width="960" alt="1" src="https://user-images.githubusercontent.com/28977633/102382884-eadd3a80-3ff0-11eb-8516-094776479d66.png">

**Comment by purvagevaria** [comment]
@sfan5 any update on my above comments?
It would be great if you provide some solution for that it's been pending for 3 days 
Kindly go through the above 3 points and do neefull.

**Comment by purvagevaria** [comment]
@sfan5 are you asking about fetching log from logcat ? Or is there any mechanism added for log? We are observing a 5000ms delay. And let me know your hardware and your app version so that we can cross-check and validate against it.  I am checking against your current - latest version from git. Hardware: Android 9 and android 7. 

Let me know how can I provide you debug details so that we  can resolve the issue . 

We performed this test run with GStreamer also we haven't faced 5000ms second delay and we want to continue with mpv android library so let us know best possible solution to reduce frame delay.

**Comment by sfan5** [comment]
> My all build tasks were completed successfully and two apks were generated. But when I am opening it I am facing a null pointer in Gradle build.

I have no idea or suggestion left what the problem could be here.

> I don't have any log file but I performed udp hotspot streaming and I am facing a frame delay of 500ms. 

Your description of "frame delay" wasn't very precise, the fact that you are doing streaming is important.
Because in that case you should read this manual section: https://mpv.io/manual/master/#low-latency-playback

> are you asking about fetching log from logcat ?

A "log file" would be one from logcat, yes.

**Comment by purvagevaria** [comment]
@sfan5 i perform test and share you the logcat. 
Framedelay in streaming means I am facing 5000ms delay then actual streaming. 

If actual streaming reaches at 1.10 mints same time that stram reaches in my device at 1.05 mits.

**Comment by purvagevaria** [comment]
@sfan5 Regarding frame delay one of the apk link 
[https://kitsunemimi.pw/tmp/mpv-android-2020-09-25.apk](https://kitsunemimi.pw/tmp/mpv-android-2020-09-25.apk)
Worked.

I have reimported whole project and tried to rerun in android studio but still getting the same error sending the file structure links for help. Let me know if I can resolve this issue? Importing in android studio is necessary for me so I am seeking for your help.
<img width="303" alt="file_1" src="https://user-images.githubusercontent.com/28977633/102769826-3143e800-43a9-11eb-84c3-e9f43c492b58.PNG">
<img width="305" alt="file_2" src="https://user-images.githubusercontent.com/28977633/102769831-330dab80-43a9-11eb-8728-c7d5894bf35b.PNG">
<img width="960" alt="sync_error_1" src="https://user-images.githubusercontent.com/28977633/102769833-330dab80-43a9-11eb-8810-8b27b7aacd82.png">

**Comment by purvagevaria** [comment]
@sfan5  Any update on the above? I really need help on this.

**Comment by purvagevaria** [comment]
@sfan5  I found that one of the commands ./include/download-sdk.sh causing the issue attaching the log file kindly revert with your comments. And let me know what are the further steps required.
[1_download_sdk.txt](https://github.com/mpv-android/mpv-android/files/5730060/1_download_sdk.txt)

**Comment by purvagevaria** [comment]
@sfan5 I tried wsl but still getting null pointer in build any suggestion on the same?

**Comment by sfan5** [comment]
Sorry, I have no further ideas that could solve your build issue. I use Android Studio / gradle on Linux successfully.

**Comment by purvagevaria** [comment]
I tried linux system also but facing the same issue. And another thing when I selct ndk is shows me warning 
ndk does not contain any platforms . Here is the file structure  of my ndk. 
![1](https://user-images.githubusercontent.com/28977633/102935379-0aca9d80-44cc-11eb-9dd9-9d086ad0ca23.PNG)

It would be great if you connect at any other platform or we can arrange some debug seession. As of now running this library in android studio is in top priority.

**Comment by purvagevaria** [comment]
@sfan5 let me know the sequence to build 

- ./include/download-sdk.sh

- ./include/download-deps.sh
- ./buildall.sh --arch arm64 mpv
./buildall.sh --arch x86_64 mpv
- ./buildall.sh

Above is my command sequence let me know if I am doing any thing wrong in this .

**Comment by sfan5** [comment]
Your command sequence is correct, I just confirmed that a full build runs successfully on Ubuntu 20.04.

Unfortunately I don't have further time to debug this, so you have to look for the cause of the issue on your own.

**Comment by purvagevaria** [comment]
@sfan5 ok thanks for the update.

**Comment by purvagevaria** [comment]
@sfan5 I tried same build system in **ubuntu 20.10** . Apk generated at the end and try to build the same in android studio fortunately I am to run the program but it causes crash here is the crash log. Any suggestion for the same ?
   Process: is.xyz.mpv, PID: 7823
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmpv.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at is.xyz.mpv.MPVLib.<clinit>(MPVLib.java:19)
        at is.xyz.mpv.MPVLib.create(Native Method)
        at is.xyz.mpv.MPVView.initialize(MPVView.kt:17)
        at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:183)

**Comment by purvagevaria** [comment]
@sfan5 now I am able to run the project issue was with ndk. I upgraded the ndk and now it's working as expected. Closing this issue now.

**Comment by purvagevaria** [comment]
@sfan5 One question from my side do I need to perform build steps every time? Or it's a one time process? Suppose there is any change in **buildscripts\deps\mpv** folder then I need to build the things and while changing the things in android's code I may not need to build the library. Please share the details about the same in brief so that I can get clear idea.

**Comment by sfan5** [comment]
That's correct, rebuilding using the scripts is not required if you make changes to the Java/Kotlin app code.
