### ISSUE TITLE
Custom commands for gestures

### ISSUE THREAD

**Issue by PrivatePasta** [mpv-android/mpv-android#342]
I'm trying to use touch controls to do different things. Is it possible to use it in input.conf to do different things? If so what keyword should I use for Double Tap (Center,Left and Right).

**Comment by sfan5** [comment]
Currently not possible, but mpv has some unused keycodes that'd make implementing this pretty easy.

**Comment by b3njibr0** [comment]
Thanks for the reply. Hope to see this implemented.

**Comment by Dexusan** [comment]
Is it not possible to adjust seek values set for double tap in `input.conf` because of this?

**Comment by sfan5** [comment]
If gestures allowed you to set custom commands you could also customize the seek value, so essentially yes.
