### ISSUE TITLE
mpv HarmonyOS

### ISSUE THREAD

**Issue by Chavahtem** [mpv-android/mpv-android#343]
Can we create mpv for HarmonyOS?

**Comment by sfan5** [comment]
HarmonyOS seems to be Huawei's upcoming mobile OS.
Despite marketing material saying that developers "can easily port their Android applications", for mpv the native code matters so porting effort will be necessary. From the documentation available online it's not even clear if they support EGL and OpenGL

**Comment by Chavahtem** [comment]
@sfan5 
Ok. When HarmonyOS is fully released can you test it?

Because I currently have a Huawei P30 Pro and when the HarmonyOS update comes it would be very great if mpv app works right away. Thank you.
