### ISSUE TITLE
The presence of MPVView in multiple activity causes a crash

### ISSUE THREAD

**Issue by MRDHR** [mpv-android/mpv-android#345]
For example,
Mpvview exists in activityA.
Mpvview also exists in activityB.
After playing the video on activitya, go to activityb to play another video. App will crash.

Output in log.
        "Mpv is already initialized"

**Comment by sfan5** [comment]
mpv-android's code is laid out to use libmpv as a singleton (one instance only).
If you need multiple concurrent instances you'll have to refactor the native code and `MPVLib` to support that.

Alternatively, skipping initialization if mpv is already initialized may suffice to achieve your goal.
