### ISSUE TITLE
hardware volume buttons pops up OSD

### ISSUE THREAD

**Issue by 532910** [mpv-android/mpv-android#350]
Not sure if this is an issue, but pressing HW volume buttons makes OSD visible.
![image](https://user-images.githubusercontent.com/14617699/104806770-ff2c7700-57ea-11eb-9a17-03de49063fee.png)

**Comment by sfan5** [comment]
Do other video players not do this?

**Comment by 532910** [comment]
No one that I know. VLC for example.
