### ISSUE TITLE
Heavy battery drain on Nvidia Tegra4 SoC

### ISSUE THREAD

**Issue by askasys-code** [mpv-android/mpv-android#351]
**Device:** Tegra Note 7  (it's like the Nvidia Shield Portable)
**SoC:** Nvidia Tegra 4 (5 cores)
**RAM:** 1 GB 933mhz
**Android:** 5.1.1  | CyanogenMod 12.1

SoC specification:
    – GeForce GPU with 72 custom cores
    – 4x ARM Cortex-A15 CPU, 1x ARM Cortex A9 (1.8 Ghz)
    – HDMI out 3840x2160 60hz

---------------------------------------------------------------------------

It's a pretty old tablet from 2013, but with pretty high specs and big battery.
I would like to use mpv to watch anime. I always used VLC and never had issues, battery is 8 hours of video decording.  But, with mpv and hardware decoding enabled, battery drain is heavy and tablet is hot, same with software decoding. 

I'm using mpv on pc and really like it, just want to use it on android too. 

Tried to set mpv.conf with `hwdec=nvdec` or `hwdec=cuda`, but even if it's a nvidia gpu, looks like doesn't support such things. 
The default `hwdec=mediacodec-copy` is the only working HW acceleration, but really, in comparison with VLC and same H264 file, there is something wrong here in mpv-android. 

Any suggestions?

**Comment by sfan5** [comment]
There isn't much to say here. mpv is written to provide high(er)-quality quality rendering using OpenGL instead of more primitive approaches.

Some improvements to rendering efficiency could probably be made (#110 or a newer approach) but these aren't reality right now.

**Comment by askasys-code** [comment]
About the quality I have no doubt, mpv-android is better than VLC, but I didn't expect such poor efficiency, and I'm more than sure it depends on the little or no optimization with this particular SoC, being quite unique and particular, it is not a SoC that typically mount smartphones or other tablets.
H.264 is the format I always use on this tablet, and only VLC has an efficiency of 8 hours. I don't expect to have the same efficiency as VLC on mpv-android overnight, but that would be nice.

Fun fact: Tegra 4 is an ancestor version of the Nintendo Switch SoC, the Tegra X1. Maybe one day mpv-android will be released also on that console, but it will be called mpv-switch XD

**Comment by Quackdoc** [comment]
definitely check the log to see if you are using hardware decode.

If not also see what decode is supported.  download aida64 from the store, send report in email (saving report saves it in aidas data folder so just email it to yourself). and copy the codec section and pastebin it

it could be a case where nvidia uses their own hardware decoding
