### ISSUE TITLE
torrent streaming like ytdl with webtorrent-hook lua script

### ISSUE THREAD

**Issue by sav1tarr** [mpv-android/mpv-android#356]

**Comment by sfan5** [comment]
While it would be technically possible to run webtorrent-mpv-hook (scripts work), you're not going to get all that javascript stuff running on Android.
Supporting torrent streaming is out of scope for mpv-android itself.

**Comment by z8512** [comment]
https://user-images.githubusercontent.com/100533380/163397510-4020169e-c4fb-4f2e-a422-c3e6787be6ee.mp4

**Comment by SkyD666** [comment]
> 
> https://user-images.githubusercontent.com/100533380/163397510-4020169e-c4fb-4f2e-a422-c3e6787be6ee.mp4
> 
> 

Can you share how to achieve this? thanks
