### ISSUE TITLE
Is it possible to display MPV controls on the lock screen?

### ISSUE THREAD

**Issue by Futureknows** [mpv-android/mpv-android#357]
VLC and other media players display controls on the lockscreen or at the least on the pulldown notification list. Is there any way to get MPV to do this? I'm on Android 8.

**Comment by sfan5** [comment]
Currently not, there is a feature request open for this: #212

**Comment by refriedfood** [comment]
How is this not implemented. It's a no-brainer. Without it is like a door without a knob. I can't believe this has been skipped, let alone ignored this long.

**Comment by sfan5** [comment]
If you look very closely you can see that the linked issue has been closed with the feature being implemented in 2022.

**Comment by refriedfood** [comment]
Really, what's the secret code, then? A different phone?
https://ptpimg.me/o6crr9.png
That's v12272025.

Foobar (for reference): https://ptpimg.me/e77ko8.png

**Comment by obscenelyvague** [comment]
Is there more than one file on that playlist? Buttons are enabled in accordance with items available on the playlist. Though play/pause should always be available even if it's just one file. 

![Image](https://github.com/user-attachments/assets/7c9abd91-e697-45cb-b6cc-a08e3f56073f)

**Comment by demeirgen** [comment]
🤷

![Screenshot_20260301_160313_One UI Home.png](https://github.com/user-attachments/assets/2f9c9777-bbbe-4277-882e-c0c475e38da9)

**Comment by refriedfood** [comment]
Yes, it's actually the entire directory or with one track. I will try an m3u and get back to you. Some phone information: 
Motorola Moto G 5G 2nd Gen 2022/23

```
Model: moto g 5G (2022)
Performance
    Operating System - Android™ 12
    Internal Storage - 256GB
    Sensors - Notification LED type, Fingerprint reader, Proximity sensor, Accelerometer, Ambient Light sensor, Gyroscope, e-compass, Barometer
    Processor - MediaTek Dimensity 700
    Expandable Storage - Up to 512GB microSD card expandable
    Memory (RAM) - 6GB
    Security - Fingerprint reader (Side), Face unlock

Battery
    Battery Size - 5000mAh
    Charging - 10W charging
    Battery Life - Up to 2 days of battery
    Charger Type - 10W rapid charger in box

Display
    Display Size - 6.5”
    Resolution - HD+ (1600x720) | 269ppi
    Screen to Body Ratio - Active Area-Touch Panel (AA-TP): 88%
    Display Technology - IPS TFT LCD | 90Hz refresh rate
    Aspect Ratio - 20:09

Design
    Dimensions - 165.4 x 75.8 x 9.44mm
    Body - Plastic
    Ports - Type-C port (USB 2.0)
    Weight - 204g
    Water Protection - IP52, water-repellent design
    Color - Moonlight Gray


```
