### ISSUE TITLE
Handle intents for more network streams

### ISSUE THREAD

**Issue by scottywz** [mpv-android/mpv-android#36]
Currently, intents are only handled for the `http` scheme.  More schemes, such as https, rtmp, etc., should be handled as well.

**Comment by sfan5** [comment]
Do you have any test pages for when `rtmp`/`rtmps` is passed in an intent?
(Is it just `<a href=...>` like with https?)

**Comment by andrew-shulgin** [comment]
Live RTMP URL example rtmp://tv-penza.ru/live/1

**Comment by sfan5** [comment]
was done in 113b12cf08d0eb9387e10028bae9544efade7b33
