### ISSUE TITLE
[Question] Can mpv stretch subtitles like Mx player and vlc?

### ISSUE THREAD

**Issue by AbdallahMehiz** [mpv-android/mpv-android#362]
adding an option to do this might help people who have screens with aspect ratios other than 16:9(like me)
Mpv:
![Screenshot_2021-02-04-23-19-29-706_is xyz mpv](https://user-images.githubusercontent.com/59295266/106962586-a2fca900-673f-11eb-969c-7b8e8e6947d8.jpg)
Mx Player:
![Screenshot_2021-02-04-23-18-50-990_com mxtech videoplayer pro](https://user-images.githubusercontent.com/59295266/106962617-ac861100-673f-11eb-905e-6274d3e75532.jpg)
Vlc:
![Screenshot_2021-02-04-23-21-54-872_org videolan vlc](https://user-images.githubusercontent.com/59295266/106962706-ccb5d000-673f-11eb-8cdb-105c1ae968a0.jpg)

**Comment by sfan5** [comment]
This sounds like a bug in subtitle rendering rather than missing stretch functionality. Do you have `video-aspect-override` set?
Sample file?

**Comment by AbdallahMehiz** [comment]
> Do you have `video-aspect-override` set?
actually i didn't, now that i am using it it fixed my problem, ty
