### ISSUE TITLE
[Bug] Looping video after some time begin to stutter and then stop completely while using hardware rendering. 

### ISSUE THREAD

**Issue by sombresu** [mpv-android/mpv-android#363]
I use loop-playlist=inf and loop-file=inf

And also some webm and mp4 video with length less than 1 second refuse to play, only black screen.

**Comment by sfan5** [comment]
possible duplicate #147
does this happen with hwdec disabled?

**Comment by sombresu** [comment]
No. It only happens when using HW decoder but I haven't played the loop longer than a couple of minutes.
