### ISSUE TITLE
H.264 10bit (Hi10P) hardware decoding on Android?

### ISSUE THREAD

**Issue by lavaplanetmircomposerspirit** [mpv-android/mpv-android#364]
Hello mpv developers is there any current Android devices that can hardware decode H.264 10bit (720p or 1080p) video codec?

**Comment by sfan5** [comment]
For various reasons (one of them being that no commercial content uses it) H.264 10-bit hardware support is very rare.
Even if you had it, FFmpeg's [`MediaCodec`](https://developer.android.com/reference/android/media/MediaCodec) support only does YUV 4:2:0 (no 10-bit), so you couldn't use it anyway.
