### ISSUE TITLE
--softvol or --volume command MPVLib.command(arrayOf("volume", value)) does not work

### ISSUE THREAD

**Issue by T-10001** [mpv-android/mpv-android#367]
Using `MPVLib.command(arrayOf("volume", value))` which should control the soft volume for mpv according to command [--volume=value](https://mpv.io/manual/master/#options-volume) does not work?

There is no change in volume, and player just uses device volume anyway.

**Comment by sfan5** [comment]
volume is a property, not a command. So it's `("set", "volume", value)` not `("volume", value)`.
