### ISSUE TITLE
 Seamless sound playback for video files always gone when returning to the app

### ISSUE THREAD

**Issue by dfv54gdmsnse** [mpv-android/mpv-android#370]
https://issuetracker.google.com/issues/179593132

Android device:

Samsung Galaxy S10 (Exynos 9820 processor) - Android 11 (OneUI 3)

Description of problem:

Video player apps on Android have major problems providing seamless sound playback for video files. In this case when returning from background playback to the video player app.

How reproducible:

Always: the issue is observed each time.

Steps to Reproduce:

1. Use an open source video player app that supports background playback and has integrated hardware decoder (MediaCodec). In this case mpv-android.

2. Install mpv-android (.apk file) on a Android device. https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2020-11-16

3. Make sure background playback for video files is enabled in mpv-android.
- Open mpv-android -> Settings -> General -> Background playback -> Always (Videos files too)

4. Make sure you can see hardware decoder in video playback.
- Open mpv-android -> Settings -> Developer -> Show stats -> stats.lua: General

5. Play any video file that your Android device with hardware decoder supports. It is best if the video is a music video so that you can hear the sound immediately.
You will immediately see the stats values in the playback and this is how it looks when hardware decoder is active:
Video: -> (hwdec: mediacodec-copy)
- Note: The playback bar also says "HW" instead of "SW". HW = Hardware decoding

6. Open "recents apps overview" = Android multitasking overview. In this case, tap the "Recents button" (square button).

7. You are now in Android multitasking overview and hear the sound of the video file in the background playback. So far an expected behavior, there is no short pause or something like that. It is seamless sound playback, no interruptions.

8. In Android multitasking overview, type mpv-android and you will return to the app. Now comes the problem, there is a short interruption of about 1 second or more. The seamless sound playback is gone.

9. You can reproduce this process over and over again. Simply test steps 6 to 8 several times.

Actual results:

Seamless sound playback for video files always gone when returning to the app.

Expected results:

Seamless audio playback for video files is always there when you return to the app.

Exactly the same behavior as on desktop operating systems like GNU/Linux or Windows 10. When I do the same with mpv for GNU/Linux or Windows 10, there are no problems. I can show and hide the windows with the mouse as fast and as much as I want and there is not a single interruption. This is seamless audio playback for video files.

Additional info:

This report can only be tested on real Android devices, because on real Android devices you have an integrated speaker and can hear the interruption immediately.

On Android emulators or similar it is not possible to reproduce it. It is also not possible to debug it, you have to use real Android devices.

I recommend to set the volume of Android device to high volume, so that you can hear the sound of video files immediately.

### **Answer from a Google developer**

This looks like an issue with the way the app is implementing backgrounding/resuming playback, not an issue with the Android platform. The YouTube app supports backgrounding and resuming playback seamlessly and that's implemented on MediaCodec, so we don't think there is a fundamental limitation of the Android media framework preventing the app from making this work. We recommend you reach out to the application developer.

**Comment by dfv54gdmsnse** [comment]
Hey mpv android developer,

do you know what the real cause is, I found this report in Android Bug Tracker and can reproduce this problem also in other video players app, like VLC Android, MX Player, so all video players app which support much more video codecs and have much more functions.

The report is closed in Android Bug Tracker and blames the video player app developers and it is not an Android platform problem, sure?

**Comment by sfan5** [comment]
I cannot speak for other video players, but the Google dev is correct about mpv-android.
Seamless playback is not impossible but it's currently "our fault" that it doesn't work, see https://github.com/mpv-android/mpv-android/issues/239#issuecomment-720157218.
