### ISSUE TITLE
10bit H264 with hardware decoder black video image

### ISSUE THREAD

**Issue by dfv54gdmsnse** [mpv-android/mpv-android#371]
According to this table the Mali V52, Mali-V76 and Mali-V77 video processors support H.264 10-bit (Decode & Encode)

https://www.anandtech.com/show/12835/arm-announces-maliv76-video-processor-planning-for-the-8k-video-future
![H 264 10-Bit](https://user-images.githubusercontent.com/79417240/108634952-a8b2f800-747c-11eb-9cb8-76532b8eabe6.PNG)

https://en.wikipedia.org/wiki/Mali_(GPU)

There is a thread in XDA forum https://forum.xda-developers.com/t/h-264-10bit-hardware-acceleration-hw-works.4144881/ where some users have tested it. I borrowed from a friend his Samsung Galaxy phone because it has an ARM Mali-G76 GPU.

I just tried this test file https://www.koi-sama.net/files/hi10/[720p][07_REF_L4.0]Sword%20Art%20Online%20BD%20Opening.mkv

Unfortunately it shows a black video image with artifacts, but HW is active. What did I do wrong? Maybe I have to set something in mpv-android to make it work, I just used the default setting.

Here is an adb logcat.
[adb logcat.txt](https://github.com/mpv-android/mpv-android/files/6018290/adb.logcat.txt)
![Screenshot_20210221-194942_mpv](https://user-images.githubusercontent.com/79417240/108635179-4955e780-747e-11eb-875e-d4f9c89fcc5c.jpg)

**Comment by sfan5** [comment]
The ability to hardware decode not only depends on hardware support but also on the manufacturer correctly wiring the decoding up to the API offered by Android (MediaCodec).
In the XDA thread you linked the guy claims working 10-bit hwdec on some devices (e.g. Xiaomi or Huawei) but it *not* working on others. In this context it'd be useful to know if 10-bit videos play in the standard Gallery/Video app on your test device.

Also if you get the chance please test using this APK: https://kitsunemimi.pw/tmp/mpv-android-2021-02-11.apk
It'll provide more debugging information on which codecs MediaCodec advertises support for and which decoder is picked (visible in logcat).

**Comment by dfv54gdmsnse** [comment]
> In this context it'd be useful to know if 10-bit videos play in the standard Gallery/Video app on your test device.

**Tested with Android 11 Samsung Galaxy phone and the standard Gallery app. Video playback does not work.**

<img src="https://user-images.githubusercontent.com/79417240/108638277-b6717900-748e-11eb-85ee-851c693060b3.jpg" width="200"> <img src="https://user-images.githubusercontent.com/79417240/108638451-9c846600-748f-11eb-915a-e6cda7049ebd.jpg" width="200"><img src="https://user-images.githubusercontent.com/79417240/108638462-ab6b1880-748f-11eb-95ab-884c87ef1e62.jpg" width="200"><img src="https://user-images.githubusercontent.com/79417240/108638523-eff6b400-748f-11eb-8006-dc9d6306c416.jpg" width="200">

**Comment by dfv54gdmsnse** [comment]
> Also if you get the chance please test using this APK: https://kitsunemimi.pw/tmp/mpv-android-2021-02-11.apk
It'll provide more debugging information on which codecs MediaCodec advertises support for and which decoder is picked (visible in logcat).

Here the adb logcat:
[adb logcat.txt](https://github.com/mpv-android/mpv-android/files/6018475/adb.logcat.txt)

**Comment by sfan5** [comment]
> standard Gallery app. Video playback does not work.

This is a good indicator that Samsung did **not** implement 10-bit hwdec via MediaCodec.

The logcat output also doesn't show anything indicating that 10-bit would work, the `OMX.Exynos.avc.dec` decoder advertises the usual 8-bit color formats. (Though I haven't yet seen which color formats would appear on hardware that *does* support 10-bit)

**Comment by dfv54gdmsnse** [comment]
> (Though I haven't yet seen which color formats would appear on hardware that does support 10-bit)
I'll go to a mobile store tomorrow and ask friends if they can lend me a Xiaomi or Huawei device, based on the XDA thread.

If I have a corresponding Android device, just install the mpv debug version again and create adb logcat again and upload it here, right?

**Comment by sfan5** [comment]
Yes. And test if it works in the default gallery/video app too.

**Comment by dfv54gdmsnse** [comment]
In the standard Gallery App, the video file could only be played if I changed the file extension from `.mkv` to `.mp4`. Then it will be shown in the standard Gallery App with a thumbnail. It's a Xiaomi phone (Android 10) and it also uses an ARM Mali-G76 like the Samsung Galaxy phone.

A couple of screenshots.
<img src="https://user-images.githubusercontent.com/79417240/108721917-d5b9e600-7522-11eb-9e41-83a3c7b8488a.jpg" width="200"> <img src="https://user-images.githubusercontent.com/79417240/108722192-26c9da00-7523-11eb-9b7e-ff0f37b8a7a6.jpg" width="200">  <img src="https://user-images.githubusercontent.com/79417240/108722553-95a73300-7523-11eb-8175-28c68be5564e.jpg" width="200">  <img src="https://user-images.githubusercontent.com/79417240/108722609-a2c42200-7523-11eb-9a98-d5e96ed92150.jpg" width="200"> <img src="https://user-images.githubusercontent.com/79417240/108722655-ad7eb700-7523-11eb-86a2-1d61f39d408f.jpg" width="200">

**Comment by dfv54gdmsnse** [comment]
In mpv android it also works, here the log file and a screenshot.
![Screenshot_2021-02-22-15-19-47-270_is xyz mpv](https://user-images.githubusercontent.com/79417240/108723027-15cd9880-7524-11eb-8b81-ace4d63acc7b.jpg)

[adb logcat.txt](https://github.com/mpv-android/mpv-android/files/6022653/adb.logcat.txt)

**Comment by sfan5** [comment]
Neat.

The logcat however confirms that the decoder only returns 8-bit output which is a bit weird(*) but at least good for performance at least:
<pre>
02-22 15:19:30.476 24803 24848 V mpv     : looking at info: OMX.MTK.VIDEO.DECODER.AVC
02-22 15:19:30.476 24803 24848 V mpv     :  looking at type: video/avc
02-22 15:19:30.477 24803 24848 V mpv     :   OK: any profile goes
02-22 15:19:30.477 24803 24848 V mpv     :   color format: 0x7f000001
02-22 15:19:30.477 24803 24848 V mpv     :   color format: 0x7f420888
02-22 15:19:30.477 24803 24848 V mpv     :   color format: 0x00000013
02-22 15:19:30.477 24803 24848 V mpv     :   color format: 0x7f00a000
</pre>
In order, these are: YUV420 (semi-planar, interlaced), YUV420 ("flexible"), YUV420; RGBA; none of which offer more than 8 bit per channel

(*) You won't get any of the benefits of 10-bit this way, such as proper output dithering.

**Comment by dfv54gdmsnse** [comment]
It's not a hardware problem and the hardware supports it? But the problem is a decoder problem, so the manufacturers did not create an H.264 10-bit hardware decoder or did not create it correctly or an Android problem because of MediaCodec?

How can it be fixed?

**Comment by sfan5** [comment]
Hardware decoding works fine, as you saw yourself.
I was just noting that the decoder is returning 8-bit output. There are in fact [no 10-bit YUV formats](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities?hl=en#constants_1) defined, so that'll be why.

**Comment by dfv54gdmsnse** [comment]
> Hardware decoding works fine, as you saw yourself.
> I was just noting that the decoder is returning 8-bit output. There are in fact [no 10-bit YUV formats](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities?hl=en#constants_1) defined, so that'll be why.

It feels like it's an Android issue and the Google developers didn't add it. If it's true, should I create feedback on Android Bug Tracker? But I'm not sure what to write in Android Bug Tracker.
