### ISSUE TITLE
Dramatically Improve performance by rescaling BEFORE processing... 

### ISSUE THREAD

**Issue by RAGEdemon** [mpv-android/mpv-android#372]
HQ media is all 4k nowadays. This post uses 4k resolution as an example, but really it can apply to any high resolution source. 

MPV (and perhaps all players) have great difficulty with this on a lot of devices due to the enormous processing power required, especially when combined with interpolation, leading to a jittery mess.

Processing 4k is a 'waste in processing power' because mobile devices very rarely have 4k displays - most people only use 4k content because it provides better quality than native quality sources, e.g. 4k looks far better on a 1080p screen than native 1080p content, if only due to less compression - or they have a display which sits between HD and UHD content.

A workaround to reduce the wasted processing power on HTPCs has been to simply rescale the input 4k video down to the device's native resolution BEFORE any processing/rendering/filtering takes place, e.g. using FFDSHOW with MPCHC. This ensures that although the input quality remains 4k, the processing/rendering/additional filtering takes place at the device's native resolution, e.g. 1080p, which would be 4x faster than 4k.

I believe currently, MPV first does processing/rendering/filtering etc at 4k, and only then rescales down to the device's native resolution at the end after all the processing power/resources have been 'wasted'.

It would be great to have an option to rescale down to a custom resolution BEFORE ANYTHING ELSE, or even a profile such as with SVP4 where we could make some kind of config amendment where we could write if input resolution is > display resolution then first thing to do BEFORE ANYTHING ELSE is to scale it down to the native resolution (using nearest neighbour/bilinear/lanczos etc).

Thank you for your time.

**Comment by sfan5** [comment]
Together with [auto profiles](https://mpv.io/manual/master/#runtime-profiles) which also work(?) on Android you have everything needed to automatically apply scaling before rendering:
<pre>
[downscale]
profile-desc="Downscale everything larger than 720p"
profile-cond=(dwidth or 0) > 720
vf-add=@downscale:scale=-1:720:flags=fast_bilinear

[downscale-inv]
profile-cond=(dwidth or 0) <= 720
vf-remove=@downscale
</pre>

`flags=fast_bilinear` might not be necessary, test and see how the performance is for you (FFmpeg [defaults to bicubic](http://ffmpeg.org/ffmpeg-scaler.html#Scaler-Options)).

**Comment by RAGEdemon** [comment]
Thank you very much for the reply - I am grateful for your insights...

Unfortunately, even though the video is being downscaled, there is significant stutter. It seems like the downscaling is causing more CPU usage than playing the content at its native resolution. This is opposite of the effect I was trying to achieve...

I am a newbie to mpv, please forgive my presumption, but for 720p (1280x720), should the code not then be:

`[downscale]
profile-desc="Downscale everything larger than 720p"
profile-cond=(dwidth or 0) > 1280
vf-add=@downscale:scale=1280:-1:flags=fast_bilinear

[downscale-inv]
profile-cond=(dwidth or 0) <= 1280
vf-remove=@downscale`

Even simply adding sharpen=5 and saturation=60 makes the 4k video stuttery - I am running on a snapdragon 865+ at 1800p.

Maybe there is a better/faster way to add sharpeness/saturation filters to 4k videos without them becoming stuttery?

Thank you.

**Comment by sfan5** [comment]
> It seems like the downscaling is causing more CPU usage than playing the content at its native resolution

Did you try with `flags=neighbor`? That's hopefully even lighter than fast_bilinear

> but for 720p (1280x720), should the code not then be:

You are correct that there's a mistake in it, but it'd be simpler to just change it to `dheight` (corrected now).

> Even simply adding sharpen=5 and saturation=60 makes the 4k video stuttery - I am running on a snapdragon 865+ at 1800p.

From experience I can say that mobile GPUs unfortunately don't cope well with the typical shader calculations mpv does. It's always possible to apply the same/similar filters in software but that's unlikely to be faster.
