### ISSUE TITLE
Control mpv from termux scripts using input-ipc-server

### ISSUE THREAD

**Issue by ferfebles** [mpv-android/mpv-android#374]
I would like to control mpv from termux scripts.

I've tried to specify the 'input-ipc-server' option inside mpv.conf, but it doesn´t seem to work.
I can see no socket file created.

I've searched for examples but didn't find any.

Is it implemented? Do you have any example?

**Comment by sfan5** [comment]
The IPC server probably does work if you find a path where mpv can create a socket, but you likely won't be able to access it from termux.
Someone with a similar usecase once proposed #187 but nothing came of that.

**Comment by awalgarg** [comment]
This would be quite useful with syncplay. See https://github.com/Syncplay/syncplay/issues/98 and https://github.com/mo3rfan/syncplayer for prior interest.

>  Someone with a similar usecase once proposed #187 but nothing came of that.

I don't think one-way command server would be enough for syncplay.

> but you likely won't be able to access it from termux.

I'm assuming this is because of the strict "containerization" android does for each app. I'm not much of an android dev but couldn't mpv bind on an IP socket instead of a unix domain socket? It could then be used in two ways:

1. Syncplay clients like that of @mo3rfan could talk to mpv directly over whatever port mpv binds to.
2. A termux script could run a reverse proxying socket which acts as a relay to mpv's listening port (a simple socat invocation would do). The official syncplay client (conveniently written in python and capable of running in headless mode) or any other program inside termux could then transparently use the relay socket.

Thoughts?

**Comment by awalgarg** [comment]
Took less than 5 minutes to test this out. First, from termux:

```
$ pkg install socat
[...]
$ socat UNIX-LISTEN:mpv-ipc,fork UDP:localhost:4444
```

Then from an adb root shell:

```
# cd /data/data/is.xyz.mpv/files
# echo 'input-ipc-server=/data/data/is.xyz.mpv/files/ipc' >> mpv.conf
# /data/data/com.termux/files/usr/bin/socat UDP-LISTEN:4444,fork,reuseaddr ./ipc
```

Leave that running. Now play something inside the mpv app. Then back in termux:

```
$ echo '{ "command": ["get_property", "playlist"] }' | socat - ./mpv-ipc
{"data":[{"filename":"...","current":true,"playing":true,"id":1}],"request_id":0,"error":"success"}
```

So it seems the app could have a setting which automatically enables input-ipc-server and runs a small proxy for it, binding on a user configurable port (or maybe host, defaulting to localhost). Might also be a good idea for the proxy to filter out the `run` and `subprocess` commands by default.

@sfan5 Would this be an acceptable addition?

**Comment by sfan5** [comment]
Sure.
The socket should bind to TCP and I don't think there should be an option to expose it the socket to the local network/internet.
Also, do multiple connections to the IPC socket work? Can they work here?

If anyone wants to contribute this feature that'd be appreciated. I'm a bit busy with other things at the moment.

> Might also be a good idea for the proxy to filter out the run and subprocess commands by default.

I'm not convinced that this is a good idea, there are probably other ways code execution could be achieved. It's better to warn the user clearly about the danger of an IPC server.

**Comment by awalgarg** [comment]
> Sure.
The socket should bind to TCP and I don't think there should be an option to expose it the socket to the local network/internet.

Agreed.

> Also, do multiple connections to the IPC socket work? Can they work here?

Yes, but some subtleties depend on the implementation. socat starts a new connection for every incoming connection so it's transparent proxying. Our proxy implementation can technically reuse the first socket connection with mpv for all future incoming connections. This could affect how events are sent to the clients.  
I think it'd be simplest to just copy what the socat example does so it's simple transparent proxying only.

> > Might also be a good idea for the proxy to filter out the run and subprocess commands by default.
> 
> I'm not convinced that this is a good idea, there are probably other ways code execution could be achieved. It's better to warn the user clearly about the danger of an IPC server.

Fair enough.

**Comment by ssnjrthegr8** [comment]
> Took less than 5 minutes to test this out. First, from termux:
> 
> ```
> $ pkg install socat
> [...]
> $ socat UNIX-LISTEN:mpv-ipc,fork UDP:localhost:4444
> ```
> 
> Then from an adb root shell:
> 
> ```
> # cd /data/data/is.xyz.mpv/files
> # echo 'input-ipc-server=/data/data/is.xyz.mpv/files/ipc' >> mpv.conf
> # /data/data/com.termux/files/usr/bin/socat UDP-LISTEN:4444,fork,reuseaddr ./ipc
> ```
> 
> Leave that running. Now play something inside the mpv app. Then back in termux:
> 
> ```
> $ echo '{ "command": ["get_property", "playlist"] }' | socat - ./mpv-ipc
> {"data":[{"filename":"...","current":true,"playing":true,"id":1}],"request_id":0,"error":"success"}
> ```

Is it possible to do this without adb shell root?

**Comment by awalgarg** [comment]
Without adb? No. Without root? Yes. You'll need to do two things
differently:

1. The mpv android package must be installed as a debuggable one. See the
releases tab for a prebuilt debuggable apk.
2. The socat binary must be owned by the mpv user. For this, you can
compile socat for arm64 and host it somewhere on the public internet.

After this, launch adb shell as non-root, and switch to mpv user shell via
`adb run-as is.xyz.mpv bash`. You can `wget` and `chmod +x` the socat
binary into the mpv app's files directory and run it from there. Rest of
the steps are the same.

**Comment by ssnjrthegr8** [comment]
Ah, I see. Sucks that it wont be possible without adb but anyway thanks for the superfast reply lol!
