### ISSUE TITLE
unrecognized options: --disable-docs

### ISSUE THREAD

**Issue by linsui** [mpv-android/mpv-android#376]
https://github.com/mpv-android/mpv-android/blob/55e60f7aefa25850bb86894a6b8cf48e314a9467/buildscripts/scripts/fribidi.sh#L21

This option is removed, see https://github.com/fribidi/fribidi/pull/73

**Comment by sfan5** [comment]
That's just a warning for me, the build still runs.
Since fridibi moved to meson anyway we should be doing that too in our scripts.
