### ISSUE TITLE
Android tunneled playback mode support 

### ISSUE THREAD

**Issue by rolandjon** [mpv-android/mpv-android#377]
HI,Is there a way to add tunneled playback mode to mpv? 

https://source.android.com/devices/tv/multimedia-tunneling

**Comment by sfan5** [comment]
Possible? Probably.

From the details it looks like this takes control over video output, playback and A/V sync from mpv which I heavily doubt works well with how mpv is designed. At that point one might even ask why use libmpv when all you're doing is demuxing and copying the data to MediaCodec?
