### ISSUE TITLE
[Feature Request] Costum commands with touch gestures

### ISSUE THREAD

**Issue by yatagan41** [mpv-android/mpv-android#380]
Could you allow custom options for touch gestures? To be able to run mpv commands with gestures can unveil mpv's full capacity. For example, changing secondary-sid or seeking by subtitle on double tap?

**Comment by sfan5** [comment]
duplicate of #342

**Comment by jvschiavo** [comment]
Is there a way to change the swiping gesture behavior? For example, I want to swipe vertically on the right of the screen to precisely change the speed instead of volume or brightness, like I can do with Tubular.

I didn't find a way to do that.

**Comment by sfan5** [comment]
> Is there a way to change the swiping gesture behavior?

no, see #811
