### ISSUE TITLE
How to use cookies.txt with android mpv?

### ISSUE THREAD

**Issue by erickyun** [mpv-android/mpv-android#382]
I know for pc version it can
But
Can mpv android also use cookies.txt files?

**Comment by sfan5** [comment]
Since that seems to be a ytdl option you can just put it in mpv.conf

**Comment by erickyun** [comment]
> Since that seems to be a ytdl option you can just put it in mpv.conf

I did put this command on the mpv.conf **ytdl-raw-options=cookies="/storage/emulated/0/download/cookies.txt** 
But it didn't work?

Also tried on termux **mpv "URL" --ytdl-raw-options=cookies="cookies.txt"**
But didn't also work?

**Comment by erickyun** [comment]
> > Since that seems to be a ytdl option you can just put it in mpv.conf
> 
> I did put this command on the mpv.conf **ytdl-raw-options=cookies="/storage/emulated/0/download/cookies.txt"**
> But it didn't work?
> 
> Also tried on termux **mpv "URL" --ytdl-raw-options=cookies="cookies.txt"**
> But didn't also work?

**Comment by erickyun** [comment]
> Since that seems to be a ytdl option you can just put it in mpv.conf

Thank you
