### ISSUE TITLE
Enable libarchive to e.g. read subs easily and from zip/rar/7z

### ISSUE THREAD

**Issue by NewUserHa** [mpv-android/mpv-android#384]
<s>### enhancement
* currently, mpv-android needs to start from `root(/sdcard)` directory every time when try to open/select an local ass/srt file. and if at in the right path(usually the `download` folder), the users always need to find the ass/srt file in a file list of all(*.*).</s>

### featrue requests
<s>* hope MPV can remember the last used directory for subtitles and can show the right files only(ass/srt for subtitles here).</s>

* mpv-android does nothing(include tip) after trying to open zip of subtitles from http.
Actually, subtitles are usually inside zip/rar, so hope mpv-android can open zip from http and put all available ass/srt into the subtitles listing window by the button on the On Screen Controller.

<s>* the subtitles window by the button on the On Screen Controller may also be able to open subtitles from local or online.</s>

https://github.com/mpv-player/mpv/issues/8651

**Comment by sfan5** [comment]
To read subtitles from archives, mpv-android would need to be built with `libarchive`, which it currently isn't.

**Comment by NewUserHa** [comment]
also, currently, mpv-android will do nothing include tip like "no subtitles in zip", if use a URL of `zipped subtitles` for `open subtitles from URL` button.

**Comment by sfan5** [comment]
Feature rejected, too much effort to integrate this.
