### ISSUE TITLE
mpv-android can use better user agent when access http source

### ISSUE THREAD

**Issue by NewUserHa** [mpv-android/mpv-android#385]
may use User Agent: mpv-android {version}/Libmpv {VERSION}

**Comment by sfan5** [comment]
Because?
The default `libmpv` works just fine, if users want to e.g. impersonate browser they can set a different one in mpv.conf.

**Comment by LetrixZ** [comment]
> Because?
> The default `libmpv` works just fine, if users want to e.g. impersonate browser they can set a different one in mpv.conf.

It's possible to do it programatically on runtime?

**Comment by sfan5** [comment]
Scripts like `auto-profiles.lua` can also set the user agent, if that's what you mean.

**Comment by NewUserHa** [comment]
because other applications use dedicated UA like VLC3.0/vlclib 3.0.

but this is not mandatory. so this may be just a topic or a question.
