### ISSUE TITLE
Fire TV 4K Doesn't fall back to SW automatically

### ISSUE THREAD

**Issue by vegedb** [mpv-android/mpv-android#386]
### Information
Using Fire TV 4K. HW plays fine, no stutters, but with **glitches**. After changing it to SW, it plays perfectly. I have ticked the option where it should fall back to SW, its **not detecting** the glitches therefore not changing to SW automatically. Hope you can fix it.

### HW

![image](https://user-images.githubusercontent.com/72070424/111591536-8c4b7680-8802-11eb-8499-5e9de9401798.png)

### SW
![image](https://user-images.githubusercontent.com/72070424/111591578-9a00fc00-8802-11eb-874c-82b88e811225.png)

### Video Codec Info
![image](https://user-images.githubusercontent.com/72070424/111591454-6f16a800-8802-11eb-80a8-0b32e4b8c913.png)

**Comment by sfan5** [comment]
This is the age old issue with 10-bit H.264, but it can't be fixed:
The decoder happily ingests the video data and returns broken pictures instead of reporting an error, mpv cannot judge what looks correct and has to rely on the decoder indicating issues.

**Comment by vegedb** [comment]
@sfan5 

Don't know if there's a thing using config files to use SW for H.264 10 bit, is there?

Similarly on MX player,
![image](https://user-images.githubusercontent.com/72070424/111909302-b8335a00-8a97-11eb-8c56-32442179e5ea.png)
