### ISSUE TITLE
Open URL Crashes

### ISSUE THREAD

**Issue by grravity** [mpv-android/mpv-android#389]
Upon loading a YouTube url via Open URL, I also tried through Termux using `am start -n is.xyz.mpv/is.xyz.mpv.MPVActivity -e filepath youtubeurl` (which opens mpv but crashes immediately), MPV crashes.

Android 10, MPV 03-10-2021 release Izzy Fdroid

**Comment by sfan5** [comment]
It doesn't "crash", it exits.
The build from the f-droid repo does not include youtube-dl support, take a look here: #58
