### ISSUE TITLE
No video if any scaling besides the default is used or if gpu debanding is activated.

### ISSUE THREAD

**Issue by Yaneca** [mpv-android/mpv-android#392]
On Huawei P30 Pro, Mali-G76, Android 10 there is no video if any scaling besides the default is used, if any shaders are applied or if GPU debanding is activated. Switching between Vulkan and OpenGL in mpv.conf doesn't help. Any solution to this issue?

I noticed that this issue was reported by several other users but has no response in that thread so far. Sorry if this is a duplicate, you can delete it and point me to the solution, or the acknowledged open issue. Thanks! 

_Originally posted by @Yaneca in https://github.com/mpv-android/mpv-android/issues/292#issuecomment-803551842_

**Comment by sfan5** [comment]
The original issue was just sitting there unacknowledged because this problem is hard to fix.
Mobile GPUs stop working for entirely unclear reasons when demanding tasks (like debanding) are given to them. mpv isn't doing anything wrong, the best it could do is work around it _if_ such a workaround can even be found after spending time analyzing a problem that shouldn't even exist.
 
> Switching between Vulkan and OpenGL in mpv.conf doesn't help.

Just FYI mpv-android currently does not support Vulkan and will silently ignore the setting.

**Comment by Yaneca** [comment]
> The original issue was just sitting there unacknowledged because this problem is hard to fix.
> Mobile GPUs stop working for entirely unclear reasons when demanding tasks (like debanding) are given to them. mpv isn't doing anything wrong, the best it could do is work around it _if_ such a workaround can even be found after spending time analyzing a problem that shouldn't even exist.
> 
> > Switching between Vulkan and OpenGL in mpv.conf doesn't help.
> 
> Just FYI mpv-android currently does not support Vulkan and will silently ignore the setting.

Thank you for your explanations and swift reaction! 

It is interesting that SPMC's lanczos based advanced scaling algorithms work on the same hardware and OS but unfortunately it is so touch-unfriendly. After getting used to mpv's HQ scaling and shaders it is really hard to switch to the lower quality of any other Android video player. In the future I will have to test mobiles for mpv-android compatibility before buying. 

I am cloing this issue as a duplicate. Thanks again!

**Comment by sfan5** [comment]
What is this "SPMC" you are referring to? Another video player?

**Comment by Yaneca** [comment]
SPMC is a no longer developed version of Kodi which unlike Kodi incorporates several spline and lanczos based scaling algorithms, lanczos3-optimized being the best opton in that software.

**Comment by Yaneca** [comment]
Here is a screenshot of the setting that SPMC has unlike Kodi:
![Screenshot_20210322_113116](https://user-images.githubusercontent.com/81073291/111961622-53f9b000-8b02-11eb-8bbe-f597e47f25b5.jpg)
