### ISSUE TITLE
in app youtube-dl --update does not work

### ISSUE THREAD

**Issue by Quackdoc** [mpv-android/mpv-android#393]
Verified using adb
1. Adb shell
2. run-as is.xyz.mpv
3. cd /data/user/0/is.xyz.mpv/files/
4. verify what binary to use via logcat;
> 3-22 14:19:44.670  7326  8129 V mpv     : [ytdl_hook:v] found youtube-dl at: /data/user/0/is.xyz.mpv/files/youtube-dl
5. ./youtube-dl --version = 2020.11.18
6. ./youtube-dl --update 
7. ./youtibe-dl --version = 2021.03.14

**Comment by sfan5** [comment]
Can you be more any specific than "doesn't work"?

**Comment by Quackdoc** [comment]
I simply mean that running the update from the settings (Settings > advanced > update youtube-dl) does not actually update youtube-dl. after running through the app, the version does not change, and only changed after I manually updated from an adb shell
