### ISSUE TITLE
Extension-specific settings don't work

### ISSUE THREAD

**Issue by Rult** [mpv-android/mpv-android#395]
If you specify an extension, a setting stops working.
`mpv.conf`
```
[extension.webm]
loop=inf
```
For example, just loop setting line works fine, but if you specify to use it only on webm files, it stops working entirely.

App version: 2021-03-10 (tried both F-Droid and Google Play)
OS version: Android 11

**Comment by sfan5** [comment]
Perhaps aliases don't get resolved in profiles(?), since the option is usually called `loop-file` (this would be a mpv bug however).
Works me tho, I have `[extension.jpg]` `pause` in my personal config.

Looking at logcat output should give you clarity on this issue in any case.

**Comment by Rult** [comment]
There is no similar issue on PC version.
Changing `loop` to `loop-file` didn't change the situation.
What's the logcat? Can't find this in the app settings.

**Comment by sfan5** [comment]
logcat can read app and system logs and requires you to connect to a PC:
https://developer.android.com/studio/command-line/logcat

**Comment by Rult** [comment]
Will try to look at that later, thanks.
