### ISSUE TITLE
Are subtitles off by default?

### ISSUE THREAD

**Issue by 07416** [mpv-android/mpv-android#397]
I've set `english, eng, en` as the sub language and the related tracks aren't selected  by default in my video files . How to ensure that the subtitle visibility. is on?

**Comment by sfan5** [comment]
Subtitles including their visibility are on by default, it might be that media files can influence the choice but I've never seen a media file force subs _off_.

**Comment by 07416** [comment]
mediainfo for the file (I don't see anything. wrong unless VOBSUB somehow is conflicting):

```
Text #1
ID                                       : 4
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 6
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 7
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Language                                 : French
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 8
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Language                                 : English
Default                                  : No
Forced                                   : No
```

**Comment by sfan5** [comment]
Here's a file I have that works:
<pre>
Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Duration                                 : 1 min 13 s
Compression mode                         : Lossless
Title                                    : ASS
Language                                 : English
Default                                  : Yes
Forced                                   : No
</pre>

I guess that the file(s) you have really force the subs to be off.

**Comment by yatagan41** [comment]
Maybe it is not the solution you looking for but if you use "sid" entry in your mpv.conf, it would select the default subtitles to show. For example, "sid=4" makes 4.th subtitle visible everytime you play a file
