### ISSUE TITLE
is mpv able to change track in playing m3u8?

### ISSUE THREAD

**Issue by NewUserHa** [mpv-android/mpv-android#398]
m3u8 content:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1648786,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2"
3000000-1280x720.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=3586044,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2"
6000000-1920x1080.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=208525,RESOLUTION=320x180,CODECS="avc1.4d400c,mp4a.40.2"
145000-320x180.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=425339,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2"
365000-640x360.m3u8
```
FFmpeg can recognize those tracks.

**Comment by sfan5** [comment]
> FFmpeg can recognize those tracks.

So does mpv.
You can also look at `--hls-bitrate` to automatically select a track with a certain bitrate.

**Comment by NewUserHa** [comment]
ffmpeg does be able to do that. but.. what about mpv-android

**Comment by NewUserHa** [comment]
could `select track` be in mpv-android UI?

**Comment by NewUserHa** [comment]
ok. I checked https://mpv.io/manual/stable/#options-hls-bitrate, and mpv and mpv-android behavior are right. this issue can be closed.

what if the bandwidth is not enough to play the max(default) bitrate stream?

by the way, found ffplay should use `ffplay -vst v:int url` to select stream, since its default is not the best.
