### ISSUE TITLE
About software renderer

### ISSUE THREAD

**Issue by shinchiro** [mpv-android/mpv-android#40]
First, thanks for bringing mpv to android!

I've xiaomi mi pad 2 which has powerful cpu where playing 1080p 10bit hevc is smooth on win10 (without `hwdec`). But sadly, I cannot get same performance on android. My question is will mpv-android will get benefit from using `sdl2` or `angle` as vo? Or is there any trick to improve this problem?

**Comment by sfan5** [comment]
mpv-android uses OpenGL ES through `opengl-cb`, no software rendering.
Using `sdl2` definitely isn't going to improve anything
Not sure about `angle` (probably not though)

**Comment by shinchiro** [comment]
I see. So there will never software rendering support in future?

>
