### ISSUE TITLE
Incorrect display of Japanese characters

### ISSUE THREAD

**Issue by Nabokov86** [mpv-android/mpv-android#400]
![Screenshot_20210411-154546](https://user-images.githubusercontent.com/26260168/114304718-63ef2900-9add-11eb-9db4-ecce609ae3e5.png)
Tested on android 9

**Comment by sfan5** [comment]
Must be an encoding issue, you would have to set [`--metadata-codepage`](https://mpv.io/manual/master/#options-metadata-codepage) but mpv-android is compiled without iconv so that doesn't work (#260).

**Comment by Nabokov86** [comment]
Yeah, you're right, it's an encoding issue.

I close the issue since it is a duplicate.
