### ISSUE TITLE
About the player

### ISSUE THREAD

**Issue by cyberwick011** [mpv-android/mpv-android#406]
How to enable full screen display for android phone?

**Comment by sfan5** [comment]
mpv-android always displays fullscreen.

**Comment by cyberwick011** [comment]
what about the black bars on both sides?

**Comment by sfan5** [comment]
Video is scaled to fit the screen (*without* cropping or stretching).
You might want to look at the Zoom gesture.

**Comment by cyberwick011** [comment]
There is no zoom gesture, I tried everything, can we enable it by editing mpv config?

**Comment by sfan5** [comment]
Settings > Touch Gestures > select any of "Double tap" > Zoom

You can also set [`panscan=1.0`](https://mpv.io/manual/master/#options-panscan) in mpv.conf to enable it permanently.

**Comment by cyberwick011** [comment]
is there also a way to move the subtitles up and down?

**Comment by cyberwick011** [comment]
it's still not working, what exactly should I put in the mpv config?

**Comment by sfan5** [comment]
e.g. `sub-pos=90` to have to higher than normal
`sub-pos=110` to have it lower than normal
