### ISSUE TITLE
Subtitle delay is only limited to 20 seconds

### ISSUE THREAD

**Issue by mzn928** [mpv-android/mpv-android#408]
Using mpv-android 2021-03-10-release \ 24
GUI wont let the user to add more than ± 20 second delay to the subtitle as shown in the image below:
https://i.imgur.com/ScCrfBY.jpg
it would be nice if we could add more delay. some releases cut the opening/ending or other parts of the video and that makes the subtitle go out of sync for a lot more than 20 seconds.

**Comment by sfan5** [comment]
How much delay do you think would be good?

Initially the delay was +/- 10s, then I read user review(s) saying that wasn't enough and changed it to +/- 20s and now that's evidently not enough either.

**Comment by mzn928** [comment]
> How much delay do you think would be good?
> 
> Initially the delay was +/- 10s, then I read user review(s) saying that wasn't enough and changed it to +/- 20s and now that's evidently not enough either.

i think around 100 seconds would be good. cause for example when releases cut the openings from anime episodes you need 90 second delay to make the subtitle sync. add 10 more seconds to that to be safe and i think its good enough.

**Comment by SSgumS** [comment]
Having a number/text field is better. Choosing the desired number in a slider is so hard. I prefer having a number field with support of 2 decimal places without any boundaries.

**Comment by AbdallahMehiz** [comment]
> > How much delay do you think would be good?
> > Initially the delay was +/- 10s, then I read user review(s) saying that wasn't enough and changed it to +/- 20s and now that's evidently not enough either.
> 
> i think around 100 seconds would be good. cause for example when releases cut the openings from anime episodes you need 90 second delay to make the subtitle sync. add 10 more seconds to that to be safe and i think its good enough.
> 
> although a better solution would be to somehow implement the desktop version's z and x shortcut keys. like adding - and + buttons that increase or decrease the subtitle delay by 500ms every time the user presses it.

Yea agreed, + there some openings longer than 90s like serial experiments lain which is 120s iirc, so i think its a good idea to just make people input their own dub delay values without sliders, this can also help with delays better with decimals which can make it even more precise
