### ISSUE TITLE
How to use shaders on android?

### ISSUE THREAD

**Issue by AbdallahMehiz** [mpv-android/mpv-android#410]
Trying to use [Anime4k](https://github.com/bloc97/Anime4K) shaders on my phone, i followed the instructions, however i have one question, where do i put the shaders and how do i add them to mpv.conf afterwards? All help is appreciated

**Comment by sfan5** [comment]
You can put shader files at locations accessible to all apps (e.g. Internal storage which has the `/sdcard/` path) and then configure them in mpv.conf with `glsl-shader=`.
But note that upscaling shaders are unlikely to work on mobile devices, their GPU's are just too weak/low-powered for this.

**Comment by AbdallahMehiz** [comment]
Yea my phone doesn't like shaders, the screen keeps flashing and mpv crashes after a while

**Comment by Rubberxgum** [comment]
> You can put shader files at locations accessible to all apps (e.g. Internal storage which has the `/sdcard/` path) and then configure them in mpv.conf with `glsl-shader=`.
> But note that upscaling shaders are unlikely to work on mobile devices, their GPU's are just too weak/low-powered for this.

How to determine if the shader is working or not? Mine doesn't seem to be working.
