### ISSUE TITLE
Is there an easy to set osc hidetimeout?

### ISSUE THREAD

**Issue by idnsunset** [mpv-android/mpv-android#411]
Hello, I want to shorten the default OSC hidetimeout, is it possible to adjust it via config file? On other platforms, we can put a  ` script-opts/osc.conf ` file, how could I achieve this on Android? Do I have to write my own script?

**Comment by sfan5** [comment]
You can change script options via `script-opts` in mpv.conf <b>but</b> this won't do anything for the OSC.
mpv-android's OSC is provided by Java and not configurable beyond what the settings menu offers.
