### ISSUE TITLE
Mpv subtitle shows weird characters?

### ISSUE THREAD

**Issue by erickyun** [mpv-android/mpv-android#412]
Hi,

I'm trying to watch a show with external subtitles in turkish language but some foreign characters show weird symbols?

I tried in the mpv.conf

```
sub-codepage=+Cp-1254
Or
sub-codepage=+ISO-8859-9
```

But both didn't work could someone help please?

**Comment by sfan5** [comment]
mpv-android currently doesn't support character conversions, see #260.
You could fix this by converting the subtitle file into UTF-8 but I don't know of any convenient way to do this on Android.

**Comment by erickyun** [comment]
> mpv-android currently doesn't support character conversions, see #260.

I understand Thank you for your answer. Hope it will be supported someday.

> You could fix this by converting the subtitle file into UTF-8 but I don't know of any convenient way to do this on Android.

I do the coverting with termux ffmpeg will write the command here if it will help someone:
`ffmpeg -sub_charenc ISO8859-9 -i subs.srt sub.srt`

**Comment by Zud96** [comment]
> I do the coverting with termux ffmpeg will write the command here if it will help someone: `ffmpeg -sub_charenc ISO8859-9 -i subs.srt sub.srt`

Thank you. I have been wondering about this for quite some time. I think I can do that for multiple files at once.
