### ISSUE TITLE
input.conf how to make newline / multiple commands

### ISSUE THREAD

**Issue by neoborn1337** [mpv-android/mpv-android#413]
using mpv for android 2021-03-10-release on nvidia shield

I have tried to edit the in-app input.config with my Nvidia SHIELD remote but can only input one single command. I can't make a new line and input another command. When I just put all commands that I need after each other they don't work anymore.
I have also tried to connect my PC Keyboard to the SHIELD and use the ENTER key on that one but there won't ever be a new line on the input.config screen.

How can you do a newline in that input.config window or input multiple commands?
Is there a way to edit the input.config file through my PC (access to the install of mpv through network)? I tried to find the install path on the Shield but I couldnt fine it or any trace of an input.config file which lets me believe there isnt one and the commands are stored elsewhere.

**Comment by sfan5** [comment]
I don't know how text input works on the SHIELD but you can just use the the Return key as usual in a multiline text field.

**Comment by neoborn1337** [comment]
I tried every single button on my remote and on my pc keyboard possible but couldn't do it.  In the end I just left it with the one command for _one chapter forward_ as this is the one I need the most.

See pictures below that show the Shield remote and the onscreen keyboard. If anybody has any suggestions for me to try I'm happy to try.

![shield remote](https://user-images.githubusercontent.com/66872658/119262205-aa569e00-bbda-11eb-9611-d4de75b843fb.jpg)
![keyboard 1](https://user-images.githubusercontent.com/66872658/119262207-ab87cb00-bbda-11eb-8560-06905cd8628d.jpg)
![keyboard 2](https://user-images.githubusercontent.com/66872658/119262208-ac206180-bbda-11eb-9c0b-8f80904264b9.jpg)

**Comment by yatagan41** [comment]
Try hitting the "FINISHED" button. It  sould make a newline

**Comment by yatagan41** [comment]
I don't have an android box but you could give this a shot:
https://www.youtube.com/watch?v=E2ifM7oXdLg
