### ISSUE TITLE
How run from termux?

### ISSUE THREAD

**Issue by tyusha0** [mpv-android/mpv-android#416]
Hi. Can i run MPV from termux and pass a file (m3u or mp4) as an argument?

**Comment by AbdullahM0hamed** [comment]
`am start -a android.intent.action.VIEW -d file:///path/to/file.mp4 -t video/* is.xyz.mpv`

Tested and working as of the latest mpv-android

**Comment by tyusha0** [comment]
thanx a lot

**Comment by Rendevior** [comment]
> Hi. Can i run MPV from termux and pass a file (m3u or mp4) as an argument?

You can even pass arguments to it by using this [wrapper](https://github.com/Rendevior/mpv-android-argparse)
