### ISSUE TITLE
names in file selection dialogues need to be displayed fully

### ISSUE THREAD

**Issue by mzn928** [mpv-android/mpv-android#417]
Using mpv-android 2021-03-10-release \ 24
using subtitles as an example. if a subtitle's file name is long, users cant read information like episode numbers, etc from the name shown in subtitle selection dialogue as shown in this image:
![photo_2021-06-10_14-14-21](https://user-images.githubusercontent.com/16765128/121503274-2b44d080-c9f6-11eb-9708-12111d5e9358.jpg)
its basically impossible to differentiate one file from another if they have the same name but differ in episode numbers.

Note: This problem affects video selection menu as well.

**Comment by sfan5** [comment]
I agree, but how do you suggest this should be done?
In your screenshot even if the file picker covered the entire screen the filename would likely still be too long (alternatively imagine you have a file named `[Underwater] Panty and Stocking with Garterbelt 09 - If the Angels Wore Swimsuits - Ghost The Phantom of Daten City (BD 720p) [AE875227].mkv`, it won't fit).

**Comment by mzn928** [comment]
I wanted to see what solution popular players use for this problem so i chose 3 popular players. MX Player , VLC for Android and KMPlayer. here are some screenshots from them. i think they can give us a good perspective.

MX Player:
![photo_2021-06-11_12-01-44](https://user-images.githubusercontent.com/16765128/121648652-f9db0c00-caac-11eb-808c-c68963ac88f5.jpg)

**here a filename takes as much space as it needs to be displayed fully, no matter how long is it.**

VLC:
![photo_2021-06-11_12-03-58](https://user-images.githubusercontent.com/16765128/121648802-23943300-caad-11eb-989b-f8ebe18c0a73.jpg)
![photo_2021-06-11_12-04-02](https://user-images.githubusercontent.com/16765128/121648909-3f97d480-caad-11eb-86e2-39d54f6eaf12.jpg)

**they use this sliding animation to fully display the name of the file once, then the animation stops**

KMPlayer is similar to MX Player:
![photo_2021-06-11_11-54-03](https://user-images.githubusercontent.com/16765128/121649176-8c7bab00-caad-11eb-81e8-3de299cc2786.jpg)

I guess there's also the option of displaying the full filename in a separate dialogue if users holds down their finger on it, but I personally prefer the MX Player's approach here.

**Comment by SSgumS** [comment]
Before anything else, I think font size of the interface in both main file picker and other file pickers like subtitle selection section, should be smaller.

Some other approaches for file pickers (in general; not only subtitle selection section):
1. We can have an info button (ℹ️) at right side of each entry and when the user touches that button, all file information such as name, size, format and etc. will be shown to the user.
2. Combination of approach 1 and VLC approach. As a side note, I personally prefer that the sliding effect only occurs when user touches and holds the entry.
---
I thought now that we are discussing readability issues, maybe it's not bad to have some other opinions on other similar section:
- The toolbar on top of the screen in the main file picker which shows the current folder name can have some auto-sliding movement in case of long folder name.
- mpv shows music name on top of control section (the section that has play/pause) while the music plays. I just wondering why video names are not shown like music files? A solution is like music. Another solution is that the movie name get displayed on top left of the screen. If the name was longer than the empty space, it can have an auto-sliding effect. I personally usually have to try 2 or 3 files to find the episode I want to watch.

**Comment by sfan5** [comment]
> I just wondering why video names are not shown like music files? 

it's optional, see 0e2f8af8e61479c1bac35545009b2e98c7f800b5

**Comment by Pentaphon** [comment]
Marquee or KMPlayer's solutions work pretty well, I think.

**Comment by sfan5** [comment]
There you go. No more ellipses, no matter how long:
![a](https://user-images.githubusercontent.com/1042418/135722563-d3af28c5-9c99-470f-86d5-4afcb69c032e.png)
