### ISSUE TITLE
volume-max and softvol-max not available, how to boost audio volume instead

### ISSUE THREAD

**Issue by wutr** [mpv-android/mpv-android#420]
From previous open and closed issues it appears both volume-max and softvol-max are not available. How can I boost the audio volume instead? It's for an rtsp camera stream so I don't mind a degradation in quality, I'd just like to hear it in the first place.

**Comment by sfan5** [comment]
`volume-max` is available, you just can't use it from the UI.
The only way currently is to put e.g. `volume=200` `volume-max=200` into the config. You could could put this into a `[protocol.rtsp]` to not impact normal use.

**Comment by wutr** [comment]
You're a star! That works. Not very intuitive but mpv isn't in general so happy enough with this for a solution.

This also answers/fixes/applies to #320 and #253

**Comment by shockergit** [comment]
> `volume-max` is available, you just can't use it from the UI. The only way currently is to put e.g. `volume=200` `volume-max=200` into the config. You could could put this into a `[protocol.rtsp]` to not impact normal use.

how do i add sharpness filter in mpv android
