### ISSUE TITLE
Can't play common 4K movie smoothly

### ISSUE THREAD

**Issue by Lijingze2019** [mpv-android/mpv-android#421]
when i play common 4k hdr movies, it cant play it smoothly. so i wonder if theres any better config
heres my config for now
```
vo=gpu
hwdec=mediacodec-copy 
gpu-context=android

#hwdec=mediacodec
#vo=mediacodec_embed
#wid=(intptr_t)(*android.view.Surface)

video-latency-hacks=yes
#video-aspect-override=16:9
```

i have to use mpv because its the only player on android that support custom http headers (referer). if i use the second decoding method(second section in my config that i disabled), it decodes much smoother but the video aspect ratio is wrong(it just stretch to cover whole screen)

Device: Redmi K20
![avatar](https://z4a.net/images/2021/06/16/IMG_20210616_111000.jpg)

**Comment by sfan5** [comment]
You have a scaler, debanding and interpolation enabled for 4K which are quite intensive operations. Disable one of them and it should play fine.

**Comment by Lijingze2019** [comment]
> You have a scaler, debanding and interpolation enabled for 4K which are quite intensive operations. Disable one of them and it should play fine.

oh shoot. yes i also noticed that the debanding was abled somehow and i didnt put any option about it in the mpv.conf. i checked again and find i didnt turn off that in the option->video (ima chinese so sometimes cant automatically match the option between two languages in my mind lol).

but still, i find it still lagy when i play a 4K 60fps  vp9 youtube video [such as this video](https://www.youtube.com/watch?v=btdtkN00O70)
![image](https://user-images.githubusercontent.com/52600662/122250796-8e55cc00-cefc-11eb-94a6-65784b4d8ee2.png)
while if i use the second decoding method, it plays much smoother but the aspect ratio is wrong. so is there a way to correct the video aspect even if just override it manually. or can i make the first decoding method config better?

**Comment by hooke007** [comment]
https://github.com/mpv-android/mpv-android/issues/307

hwdec for mpv-android is ... Usually I won't use it because using hwdec will make anything not smooth in my device.
