### ISSUE TITLE
Screen turns black for 1-2 seconds when switching back to mpv from another app

### ISSUE THREAD

**Issue by bahaaza** [mpv-android/mpv-android#424]
When I play a video on mpv then I switch to another application, note taking app for example then when I switch back to mpv the screen will turn black for a 1-2 seconds, which is very annoying issue.

When I am on "play in background" mode, the behaviour is the same but in addition to this the audio will fade for 1-2 seconds as well.

The issue occurs with and without hardware decoding.
I observed the issue or Galaxy Tab S7 Plus and on Galaxy S20 running android 11.

**Comment by bahaaza** [comment]
I think it is similar issue to this:
https://github.com/mpv-android/mpv-android/issues/239#issuecomment-720157218

**Comment by sfan5** [comment]
Yes, that's exactly it.
