### ISSUE TITLE
Sometimes, .opus files via BT are played with weird crackling distortions

### ISSUE THREAD

**Issue by goto-engineering** [mpv-android/mpv-android#429]
I don't know what exactly causes this. It doesn't seem to happen all the time, but most of the time.

I have a folder with around 15 songs. I hold down on it to have MPV play it as a playlist. The first 2 are mp3s/m4as and always play perfect. Then there are a couple of .opus files. When I am connected to a bluetooth device, and play the entire folder like this, these are usually scrambled and there are weird crackling noises. Not always, but almost every time.

Weirdly, quitting MPV, restarting it, and playing the same songs (still connected to the same BT audio device) often times fixes the issue. Not every time, but often.

Observation:
1) when not connected to BT, this never happens
2) this never happens to non-opus files
3) it seems to happen more often when the opus files are played as part of a playlist, not as often when they are played on their own
4) while it's "inconsistent," it happens almost every single time when I simply play the entire folder

Is there some kind of logging I could do to find out what might be happening?

**Comment by sfan5** [comment]
I can make a guess here: The issue with Bluetooth audio occurs when the sample rate switches.
The reason for this is that your Opus music files are 48kHz while other formats are almost always 44.1kHz. It doesn't happen when playing files on their own since there's no switch.

Will test myself as time permits.

**Comment by goto-engineering** [comment]
Interesting! You're right that the troublemaker files are 48kHz.

1st file (fine): 48kHz (mp3)
2nd file (fine): 44.1kHz (m4a)
3rd file (troublemaker): 48kHz (opus)
4th file (troublemaker): 48kHz (opus)

So maybe it can down regulate but not up? Not sure.
Please let me know if I can test anything else that might be helpful.

**Comment by goto-engineering** [comment]
Ok I tried it again. I can make the noises appear by manually playing the mp3 and then one of the opus files, individually. When I restart mpv, sometimes it works again after, but sometimes the opus files are still broken (all individually). It didn't seem as predictable as I had thought.
Often times though, quitting mpv and restarting it, and then individually playing the opus files will fix it.

**Comment by sfan5** [comment]
Btw, could you check whether the issue is still present on the newest version (2021-10-28)?

**Comment by goto-engineering** [comment]
I can't check it right now, but I will when I have the chance.

**Comment by goto-engineering** [comment]
I tried it and I think it's still there, but only on some songs. Some that had it before, I can no longer hear it. And even on those that still have it, it's much, much lower. I only noticed it in quiet parts that are interrupted by loud parts (like a quiet part with a loud, slow beat).

So definitely a massive improvement! Thanks!

**Comment by sfan5** [comment]
If this still exists please provide a log alongside.
