### ISSUE TITLE
mpv doesn't act as a normal video player with other apps

### ISSUE THREAD

**Issue by alabrand** [mpv-android/mpv-android#43]
NewPipe, a free, open-source YouTube parser has the ability to use external video and/or audio apps to play movies and/or music. I would like to use mpv with this function, however that is not possible for some reason.

In the screenshot I have provided you can see that when I press the big play button on the video, a menu pops up at the bottom asking me to select an app to play the video. However mpv can't be found here no matter what I do.

Would this be possible to fix?
![screenshot](https://cloud.githubusercontent.com/assets/6384915/25496949/3e333382-2b83-11e7-925b-c4886614c5f6.png)

**Comment by sfan5** [comment]
Would be nice knowing what kind of URL that app expects the video player to open.

If it's HTTPS then you'll want to use a build with https support (which isn't merged to `master` yet).

**Comment by alabrand** [comment]
I think the chance of it being HTTPS is very high. The build is the one from Google Play Store, so from 20th February.

**Comment by sfan5** [comment]
Here's a more recent build of mine which includes HTTPS support:
https://kitsunemimi.pw/tmp/mpv-android-2017-04-23.apk

**Comment by alabrand** [comment]
I downloaded it and tried, but it didn't show up. I think maybe NewPipe has to support mpv?

First I thought it was because Android didn't recognize mpv as a video player, but I can play movies completely fine by going into the file manager, selecting a video and choosing to open with mpv. So that can't be the issue.

**Comment by sfan5** [comment]
Okay then it's a different protocol.
Any idea how I'd find out which one it is?

**Comment by alabrand** [comment]
I wish I knew what they used. I do maybe think they have to add support for it.

**Comment by ksala** [comment]
This is where the Intent is generated: https://github.com/TeamNewPipe/NewPipe/blob/affd23b14ec87fffb8c7b8213a50f9f5c99a9603/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L940

```MediaFormat.getMimeById``` is implemented here: https://github.com/TeamNewPipe/NewPipeExtractor/blob/5907c35dfb0f23db2b6f6f864940e6535ad9abd5/MediaFormat.java

So i think it is broadcasted with a 'video/*' or 'audio/*' mimetype.

From a quick look at how VLC does it (https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/AndroidManifest.xml#L98) I think that adding the 
```<data android:scheme="http" />
<data android:scheme="https" />
<data android:host="*" />```
In this ```<intent-filter>``` https://github.com/mpv-android/mpv-android/blob/master/app/src/main/AndroidManifest.xml#L24 should work.

Can't build this to check right now tho :/

**Comment by itspull** [comment]
@kslala would you care to share your android mpv apk build here? I'm experiencing the very same issue you were having to use it with newpipe. it seems you have it fixed :)

**Comment by itspull** [comment]
@ksala would you care to share your mpv apk build here? I'm experiencing the very same issue as @alabrand, mpv is not listed for playback in newpipe. my install of the @sfan5 build doesn't work either :(

**Comment by sfan5** [comment]
The one I posted earlier does not include the fix for this yet, I can upload a fresh build later today.

**Comment by itspull** [comment]
@sfan5 perfect! thank you :)

**Comment by sfan5** [comment]
@itspull
here's a new one: https://kitsunemimi.pw/tmp/mpv-android-2017-06-05.apk

**Comment by itspull** [comment]
@sfan5 it works! :DD
