### ISSUE TITLE
[feature request] Screen rotation use sensor

### ISSUE THREAD

**Issue by jerryn70** [mpv-android/mpv-android#431]
The screen should rotate according to the phones position. If the phone is in portrait mode the video must play in portrait even if it is a landscape video . And if the phone is kept landscape the video should play in landscape mode . 
For reference you can check the 'just player' open source video player. 
https://github.com/moneytoo/Player
This player works like I said. I rotates according to our device movements.

**Comment by sfan5** [comment]
The option to do this exists in settings.

**Comment by jerryn70** [comment]
@sfan5 but it will not work if screen  orientation is locked. My suggestion is, it should work even if the orientation is locked.

**Comment by frasty** [comment]
> The option to do this exists in settings.

I can't find this option in the setting. Where is it supposed to be?

I am unable to see a portrait recorded video in portrait mode. MPV always rotate the screen in landscape mode, no matter if the phone orientation is locked or not.

**Comment by sfan5** [comment]
Settings > User Interface > Screen Orientation > "Device"

**Comment by frasty** [comment]
> Settings > User Interface > Screen Orientation > "Device"

Thank you, I overlooked that menu entry. Anyway I found it under ... General > User interface ...
