### ISSUE TITLE
Feature request: List media folders only

### ISSUE THREAD

**Issue by mizzunet** [mpv-android/mpv-android#435]
I'd love to see an option to hide folders that don't have media files. Like most media player apps such as VLC?
Could you make this option under settings?

I'm sorry if this has been requested already, I searched the issues, couldn't fine one :)

**Comment by sfan5** [comment]
I could expand the media filter to also look in folders (it does that anyway) and hide them if no media files are inside. Doing this recursively would be a bit much I think, does VLC really do that?

**Comment by mizzunet** [comment]
>I could expand the media filter to also look in folders 

Awesome 🤗

>Doing this recursively would be a bit much I think

I'm not sure. Perhaps an alpha version with this feature would be better, then let users say their feedback on its performance and all, what do you think?

>does VLC do that?

Well, VLC does scanning every once it's opened
https://user-images.githubusercontent.com/10193999/132039031-4e00d22b-7e06-4ed7-9930-0b7589432b25.mp4

And this runs slowly

**Comment by mizzunet** [comment]
>I could expand the media filter to also look in folders 

Awesome 🤗

>Doing this recursively would be a bit much I think

I'm not sure. Perhaps an alpha version with this feature would be better, then let users say their feedback on its performance and all, what do you think?

>does VLC do that?

Well, VLC does scanning every once it's opened

https://user-images.githubusercontent.com/10193999/132039565-b69b689f-eece-4e7b-93c4-186839f231c4.mp4

And this runs slowly

**Comment by Pentaphon** [comment]
> I'd love to see an option to hide folders that don't have media files

This seems too complicated a solution for a simple problem. We just need to have the file picker make media files more obvious, like with thumbnails or icons.

**Comment by oceanusxiv** [comment]
I want to add my 2c here that I find VLCs behavior of scanning every folder on startup to search for media to be downright undesirable. Maybe just allowing users to manually filter folders (ala designate media folders)?

**Comment by Pentaphon** [comment]
> I want to add my 2c here that I find VLCs behavior of scanning every folder on startup to search for media to be downright undesirable. Maybe just allowing users to manually filter folders (ala designate media folders)?

I second this. Scanning is for a much bigger project. mpv is more of a simple video player. The only issue is that it's a little too simple right now and something like picking media folders/icons/thumbnails would be "just right".

**Comment by sfan5** [comment]
There are no plans to implement media scanning.
