### ISSUE TITLE
How could load external subtitle from url when call app from website?

### ISSUE THREAD

**Issue by xqdoo00o** [mpv-android/mpv-android#441]
Hi,
  I read this issue https://github.com/mpv-android/mpv-android/issues/366 , and does it successful.
  Could I add a external subtitle url in the intent url? 
  Just like (intent://mpv.io/images/mpv-logo-128-0baae5aa.png#Intent;type=video/any;package=is.xyz.mpv;**subtitleurl=https://&&.com/video/film.ass**;scheme=https;end;) 
  Thanks!

**Comment by sfan5** [comment]
A `subs` parameter is supported but it needs to be an Array of `Uri`, which I don't think is possible from a web browser...
https://github.com/mpv-android/mpv-android/blob/fc12c46f432b49d939835f36b78697a44db8c63a/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L892-L903

**Comment by xqdoo00o** [comment]
> A `subs` parameter is supported but it needs to be an Array of `Uri`, which I don't think is possible from a web browser...
> https://github.com/mpv-android/mpv-android/blob/fc12c46f432b49d939835f36b78697a44db8c63a/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L892-L903

I will try, if url could not work, I will try to load from Intent code. Thanks!

**Comment by elyeandre** [comment]
Hello, do you make it work? I have same problem
