### ISSUE TITLE
how to hide the controls when enabling double tap

### ISSUE THREAD

**Issue by largeword** [mpv-android/mpv-android#442]
Hi, is there any way to hide the controls through a single tap when configuring the double tap to pause/start?

**Comment by sfan5** [comment]
Double-tap gestures more or less conflict with the "tap to hide" functionality (double tapping would show/hide the UI wildly).
If you think the hide timeout is too long perhaps an option can be added for that.

**Comment by largeword** [comment]
> Double-tap gestures more or less conflict with the "tap to hide" functionality (double tapping would show/hide the UI wildly).
> If you think the hide timeout is too long perhaps an option can be added for that.

Thanks for your reply. An option to config the timeout is find,  rather than that, is it possible like setting the double tap on the right side of screen to none then I can use the single tap on the right to show/hide the controls?

**Comment by rohitghali** [comment]
![Screenshot_20220422-015154~01](https://user-images.githubusercontent.com/42379398/164547214-2d08414a-79e2-4f28-b366-f29644cb1a20.jpg)

**Comment by rohitghali** [comment]
![Screenshot_20220422-015209~01](https://user-images.githubusercontent.com/42379398/164547245-30eb774e-7f17-48d5-9cdd-d4cceb5bd0b8.jpg)
