### ISSUE TITLE
Issues with buildall.sh on Windows / WSL2 Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jakedowns** [mpv-android/mpv-android#445]
Hello, I'm attempting to test a modification to the android app. But when I build via Android Studio, the app crashes upon selecting a video. It appears this is because I need to build libmpv.so

I've run `download-sdk` & `download-deps` however when I attempt to run `buildall.sh --arch arm64 mpv` I get what appears to like... a somehow malformed output from the sh script? 

It's a lot of lines like this:
```
=yes: not found: eval: aac_adtstoasc_bsf
=yes: not found: eval: av1_frame_merge_bsf
=yes: not found: eval: av1_frame_split_bsf
=yes: not found: eval: av1_metadata_bsf
=yes: not found: eval: chomp_bsf
=yes: not found: eval: dump_extradata_bsf
=yes: not found: eval: dca_core_bsf
=yes: not found: eval: eac3_core_bsf
=yes: not found: eval: extract_extradata_bsf
```

The whole output is here:
https://gist.github.com/jakedowns/0bc0cd34b79ed05af279e4e9b9d07636

I did run `dos2unix` to fix another error, perhaps dos2unix butchered something. 

I'm gonna try a fresh clone & build.

Also, if anyone has any tips on building for windows. I wasn't having much luck in regular Command Prompt or PowerShell or Windows Terminal, nor Cygwin... so I tried Ubunu-18.04 running on WSL2, which you know, for the most part seemed to work, until this build script failed. (I think  I read elsewhere that mingw64 might work? but I didn't try that)

I'm on an AMD64 Windows 10 box, targeting `arm64-v8a` (snapdragon 835 and 845 chips)

FWIW, If I revert dos2unix, using unix2dos on `/deps/ffmpeg/config`
I get this error:
```
/mnt/j/Code/mpv-android/buildscripts/deps/ffmpeg /mnt/j/Code/mpv-android/buildscripts
../../scripts/ffmpeg.sh: ../configure: /bin/sh^M: bad interpreter: No such file or directory
```
Full output here: https://gist.github.com/jakedowns/fabeed1400d9a65ded964132239916c8

---

FWIW, I tried again with a fresh clone of the repo in a WSL2 Ubuntu 20.04 environment. So far so good.

**Comment by sfan5** [comment]
Building on Windows is indeed not supported, WSL is just Linux so that should work.
If the build runs successfully on Ubuntu 20.04 please report back and close this issue.

> I did run dos2unix to fix another error, perhaps dos2unix butchered something.

Uh yeah that doesn't sound like a good idea.

**Comment by jakedowns** [comment]
well I made it further, here is my latest error

```
> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
Build-tool 30.0.2 is missing AAPT at /mnt/j/Code/mpv-android/buildscripts/sdk/android-sdk-linux/build-tools/30.0.2/aapt
Build-tool 30.0.2 is missing AAPT at /mnt/j/Code/mpv-android/buildscripts/sdk/android-sdk-linux/build-tools/30.0.2/aapt

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Installed Build Tools revision 30.0.2 is corrupted. Remove and install again using the SDK Manager.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Full output here: https://gist.github.com/jakedowns/bbbf5e40396d5049350994833547df74

**Comment by jakedowns** [comment]
i eventually got this working by some combination of the following:

- upgraded build tools to 31.0.0
- using ubuntu 20.04 on wsl2 instead of 18
- mapping jnilibs to the src libs folder that is generated. the symlink provided didnt seem to work
