### ISSUE TITLE
Adding option to dynamically toggle shaders

### ISSUE THREAD

**Issue by jakedowns** [mpv-android/mpv-android#446]
Hello, I'm working on a modified fork of the app that includes support for LitByLeia displays (Lume Pad, RED Hydrogen One)

Simply put, my question is:

**TLDR; What would be the most straightforward way in MPVActivity to get MPVLib to reload mpv.conf without losing playback location?**

More context:
Support for Leia's 4-View light-field displays involves two steps:
1) including a library and necessary hooks for toggling the devices backlight mode between 2D and 4V(3D).
This i've got working.

2) toggling mpv to reference a special interlacing shader i've written which interlaces SBS or 2x2 videos to display properly in 3D when the special backlight mode is enabled 

In order to accomplish #2, ive added a button to the cog menu during playback, when you press the togge button I add/remove a glsl-shader line from mpv.conf added which points to shader files i copy to storage using the existing copyAssets method.

If I hit my toggle button, and leave the app, then re-start the video, mpv.conf is reloaded and it is using my shader as expected.
I'd like it to apply the conf change without the user losing whatever place they are in the video currently.

I'll keep looking around, just wondering if there's any ideas

**Comment by sfan5** [comment]
Writing to mpv.conf to change properties is the wrong approach, you can do all of this via `MPVLib.setOptionString` or `MPVLib.command` for fancier ways.
E.g. `MPVLib.command(arrayOf("change-list", "glsl-shaders", "append", "/some/where/shader.glsl")`

**Comment by jakedowns** [comment]
thanks so much @sfan5 , I'll give that a shot
