### ISSUE TITLE
mpv-android does not use Trusted Credentials Store

### ISSUE THREAD

**Issue by erri120** [mpv-android/mpv-android#452]
### Important information

Android version: 11

mpv-android version: 2021-10-28

Which version of mpv-android introduced the problem (if known): has always been there

### Description

https://github.com/mpv-android/mpv-android/blob/bf0aa4b88db75a788823be1c5b2757a145bf6ec2/app/src/main/java/is/xyz/mpv/MPVView.kt#L108-L109

Due to how mpv-android uses mpv itself, it has to supply a certificate authority database file to mpv with the `--tls-ca-file` option. The file it supplies is stored in this repository and apparently auto-generated.

This is not only a security risk but also a problem if the Trusted Credentials Store in Android itself differs from the db in this repo. In my case I added a new CA to the Store which signes x509 certificates of my internal services, but mpv-android doesn't use it meaning the tls handshake will fail and I can't use mpv-android.

Not an Android expert but from [this post](https://stackoverflow.com/questions/40363553/list-certificate-stored-in-user-credentials) post it looks like you can access the store and then maybe generate the db file on startup?

**Comment by sfan5** [comment]
Using Android's trust store or even its TLS implementation would of course be possible but it'd be lots of extra work, using a shipped CA file is painless and works out of the box with libmpv.

> but mpv-android doesn't use it meaning the tls handshake will fail and I can't use mpv-android.

If you don't particularily care about verification you can also put `tls-verify=no` into your config.

**Comment by erri120** [comment]
> Using Android's trust store or even its TLS implementation would of course be possible but it'd be lots of extra work, using a shipped CA file is painless and works out of the box with libmpv.
> 
> > but mpv-android doesn't use it meaning the tls handshake will fail and I can't use mpv-android.
> 
> If you don't particularily care about verification you can also put `tls-verify=no` into your config.

What about #453? I've added a new option to the Advanced Settings that will generate a new file.

**Comment by erri120** [comment]
Also using `tls-verify=no` doesn't work:

```
10-31 15:16:20.385 26057 17407 V mpv     : [cplayer:v] Reading config file /data/user/0/is.xyz.mpv/files/mpv.conf
10-31 15:16:20.385 26057 17407 V mpv     : [cplayer:v] Applying profile 'default'...
10-31 15:16:20.385 26057 17407 V mpv     : [cplayer:v] Setting option 'tls-verify' = 'no' (flags = 4)
...
10-31 15:16:20.705 26057 17407 V mpv     : [ffmpeg:error] tls: mbedtls_ssl_handshake returned -0x2700
```

**Comment by erri120** [comment]
Setting `tls-ca-file` solved this issue.

**Comment by sfan5** [comment]
> What about #453? I've added a new option to the Advanced Settings that will generate a new file.

Did you verify that it works? Just looking at the code I have a bit of doubt.

> Also using `tls-verify=no` doesn't work

Can confirm. Looks like a mistake in ffmpeg:
https://github.com/FFmpeg/FFmpeg/blob/9d4989f2e17c11d4ee9daa489b6e4f5195d80b99/libavformat/tls_mbedtls.c#L225-L226

**Comment by erri120** [comment]
> Did you verify that it works? Just looking at the code I have a bit of doubt.
> 

Sadly no, I don't have an Android dev environment set up and I had hoped that the CI would spit out a debug apk artifact.

**Comment by sfan5** [comment]
I have submitted a fix for `tls-verify=no` not working: http://ffmpeg.org/pipermail/ffmpeg-devel/2021-December/289544.html

Since disabling verification seems to be a satisfactory solution for you I will close this and the PR.
