### ISSUE TITLE
"Default File Manager Path" setting does not work: value is ignored

### ISSUE THREAD

**Issue by Nojevah** [mpv-android/mpv-android#454]
I'm trying to change the default path from /sdcard/ to /sdcard/MyVideos/ folder, but it does not work. I've tried different paths, but without success.
To be sure I well understood this option, my goal is to open mpv directly in this folder when I click on mpv icon.
(unsuccessfull) Paths I've tried:
/MyVideos/
MyVideos
/internal storage/MyVideos
/storage/emulated/0/MyVideos

### Additional information

I've tried with 2 Samsung smartphones: S8 (Android 9) & S20 FE (Android 11) with mpv 2021-10-28 release.

**Comment by sfan5** [comment]
Hmm you're correct. That setting doesn't seem to work at all.
`/storage/emulated/0/MyVideos` would have been the correct path btw, `/sdcard` is legacy.
