### ISSUE TITLE
The new version of mpv android is not working on mibox S android tv

### ISSUE THREAD

**Issue by jason3120** [mpv-android/mpv-android#455]
The mpv android on mibox S is not working, the app can open, but it cannot play the video. When I click the video, the app flash one time and go back.

**Comment by sfan5** [comment]
Maybe fill out the issue template?

**Comment by kerimcem** [comment]
the latest version does not work for me,mibox ,i'm back to the old version 10.10.

**Comment by sfan5** [comment]
That's great. Maybe *you* can fill out the issue template?

**Comment by jason3120** [comment]
### Important information

Android version: **android 9** **MiBox PI.3933**

mpv-android version: **10.28**




### Description

The mpv android on mibox S is not working, the app can open, but it cannot play the video. When I click the video, the app flash one time and go back.

**Comment by Amanse** [comment]
can you tell me how did you fix this? i am still facing this on the latest version

**Comment by sfan5** [comment]
It's not fixed because I don't have enough information to fix the issue.
If you want to help test please install this APK and report back: https://kitsunemimi.pw/tmp/mpv-android-2021-12-15.apk
