### ISSUE TITLE
silenceremove lavfi-complex filter stops working after a while

### ISSUE THREAD

**Issue by Fortis-one** [mpv-android/mpv-android#457]
`lavfi-complex='[aid1] silenceremove=1:0:-65dB:0:any:-1:0:-65dB:0:any:rms:0.002 [ao]'`
This used to work fine on  `1507b02` build. Since  `e4a9d0c`, it works for like 30 seconds and then stops skipping silences.

**Comment by sfan5** [comment]
mpv commits between the builds: https://github.com/mpv-player/mpv/compare/564f3db..4a80de9
ffmepg commits between the builds: https://github.com/ffmpeg/ffmpeg/compare/d115eec..e84c83e

This'll be an upstream issue.

**Comment by richardpl** [comment]
Use named options, because syntax was changed, by adding new options in middle to allow keep some silence
