### ISSUE TITLE
stretch button/fit screen button

### ISSUE THREAD

**Issue by ZeoGOD4** [mpv-android/mpv-android#458]
a stretch video option where the video perfectly fits my screen

Describe the wanted behaviour of the new feature and potential usecases for it here.

### Additional information

 
![Screenshot_2021-11-07-00-07-50-862_is xyz mpv](https://user-images.githubusercontent.com/76849057/140620526-1356e9e1-1d67-41f9-b033-93f1e0c58792.jpg)
As you can see here there are black bars up and down

**Comment by sfan5** [comment]
Settings > Touch Gestures > 'Zoom' or `panscan=1` in your mpv.conf.

**Comment by Pentaphon** [comment]
> Settings > Touch Gestures > 'Zoom'

I feel like this would be more obvious to new users (and even some current users like me who didn't find it) if the zoom button were put into the player UI instead of being hidden away in the gesture settings.

**Comment by sfan5** [comment]
I agree. Perhaps zoom should also just be a gesture in itself as suggested in #428.

**Comment by Pentaphon** [comment]
> Perhaps zoom should also just be a gesture in itself

That and adding a zoom function next to the aspect ratio cycler would make it so intuitive that no new user can miss it. Yes, please!

**Comment by waseemhehe** [comment]
@sfan5  pinch to zoom is removed in new update ?? I didn't see in settings zoom or panscan
