### ISSUE TITLE
cursor-autohide doesn't do anything on chrome os

### ISSUE THREAD

**Issue by Keith94** [mpv-android/mpv-android#461]
### Important information

Android version:

mpv-android version:
2021-10-28

### Description

1. Install mpv-android on chrome os.
2. Add cursor-autohide=always to mpv.conf
3. Play a video in fullscreen

Result: Cursor stays at default timeout setting approx ~8-10 seconds to fully disappear

**Comment by sfan5** [comment]
Pretty much none of the windowing related mpv options will work since all that is managed by mpv-android.
From a quick I couldn't see a way to control this behaviour from Android APIs either.
