### ISSUE TITLE
Video output is 1080p on Google TV with 4K tv

### ISSUE THREAD

**Issue by mrnoname1000** [mpv-android/mpv-android#465]
### Important information

Android version: 10

mpv-android version: 2021-20-28 (F-Droid)

Which version of mpv-android introduced the problem (if known): Unknown

### Description

On a Google TV connected to a 4K TV, mpv outputs 1080p, even if the video being played is higher resolution.

### Log output

Playing a 1080p video: https://0x0.st/-hpV.txt
Playing a 2160p video (doesn't play at full speed): https://0x0.st/-hpW.txt

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/293#issuecomment-667973890

**Comment by mrnoname1000** [comment]
Yup, looks like that's exactly my problem. I found [an article](https://www.flatpanelshd.com/news.php?subaction=showfull&id=1638414453) that says Android 12 will add a 4K UI; when/if my device gets it I'll post a comment here saying if it fixes the issue.
