### ISSUE TITLE
mpv-andriod playing video blinks when debanging is turned on

### ISSUE THREAD

**Issue by erickyun** [mpv-android/mpv-android#467]
### Important information

Android version: Android 11, Xiaomi redmi note 8 pro

mpv-android version:
 21-10-28-release

### Description

 mpv-andriod playing video blinks
 when debanging is turned on also there is no framedrop
the playing video blinks like turning lights on off fast 

[Example-video-Screenrecorder-2021-12-08-14-03-07-267.zip](https://github.com/mpv-android/mpv-android/files/7675635/Screenrecorder-2021-12-08-14-03-07-267.zip)

### EDİT1: 
Setting I use:
Settings > Video > debanding mode CPU

mpv.conf
deband=yes
deband-iterations=2
deband-threshold=55
deband-range=20
deband-grain=5

### EDİT2:
I did notice this problem happens when I edit mpv.conf deband=yes and with debanding mode GPU

when I leave mpv.conf empty and and set debanding mode CPU the flicker doesn't happen video plays normal but I can't see with shift+I 2(toggle stats 2) that deband is running

**Comment by sfan5** [comment]
This is caused by bugs in your GPU drivers. Not much we can do to fix this.
If you have a recent build please also try gpu-next.
