### ISSUE TITLE
No fallback to SW decoding (thus no successful playback) on Exynos Samsung tablet with 10-bit HEVC file

### ISSUE THREAD

**Issue by Pentaphon** [mpv-android/mpv-android#468]
### Important information

Android version:

mpv-android version: 2021-10-28 Build

Which version of mpv-android introduced the problem (if known): Not known

### Description

When playing 10-bit HEVC files on a Samsung SM-T510 tablet, mpv will not fall back to SW decoding and simply not play the file at all. However, I am able to successfully play that kind of file with the latest VLC on that same device.  

### Log output

[mpv.txt](https://github.com/nova-video-player/aos-AVP/files/7699522/mpv.txt)

### Additional information

Here's a clip of the file that won't play on mpv but does play on VLC. https://gofile.io/d/eTxqEJ

I've also been investigating this same issue with the Nova Video Player dev and he noticed the following in my log:

>Thanks for the logs, I notice that both for nova and mpv we get:

>E/libexynosv4l2( 3705): failed to ioctl: VIDIOC_G_FMT (11 - Try again)

>not for the other players.`

Here's a link to the Nova bug report if you are curious.

https://github.com/nova-video-player/aos-AVP/issues/516#issuecomment-992279602

**Comment by sfan5** [comment]
Known issue.
Unless ffmpeg's support code has a bug I'd say the blame is on MediaCodec (or rather the hwdec implementation) for not returning an error. I don't think this will ever be fixed.

If it works in VLC that is interesting though, a possible workaround would be to not attempt hwdec at all if 10-bit video is detected.

**Comment by Pentaphon** [comment]
> If it works in VLC that is interesting though, a possible workaround would be to not attempt hwdec at all if 10-bit video is detected.

Yep, here's the log from playing the same file on a clean install of VLC. 

[vlc.txt](https://github.com/nova-video-player/aos-AVP/files/7699528/vlc.txt)

**Comment by sfan5** [comment]
That looks more like they somehow determine ahead of time using codec/profile information(?) whether MediaCodec can read it. I'll have to check what ffmpeg does.

**Comment by sfan5** [comment]
Haha yes it's fixable inside FFmpeg. Thanks for telling me that it works in VLC, otherwise I would have dismissed it.

**Comment by sfan5** [comment]
Fix landed in ffmpeg.
