### ISSUE TITLE
How to download with yt-dlp in the input.conf?

### ISSUE THREAD

**Issue by erickyun** [mpv-android/mpv-android#470]
Hi,

in Windows I can download videos with editing the `input.conf`
and adding this command
```
Ctrl+e run yt-dlp --no-config -f best --fragment-retries "infinite" "${path}" -o %USERPROFILE%\Desktop\%(title)s.%(ext)s; show_text "Downloading ${filename}"
```

how can I do this with mpv-android?
tried adding this command but it didn't work?
`
0 run yt-dlp --no-config -f best --fragment-retries "infinite" "${path}" -o "/storage/emulated/0/Download/%(title)s.%(ext)s"; show_text "Downloading ${filename}"
`

**Comment by sfan5** [comment]
This is a bit tricky because you have to specify the absolute path to the executable which might vary by Android version or even installation.
On my phone the correct path is `/data/user/0/is.xyz.mpv/files/youtube-dl` (even if you have yt-dlp the path stays the same).

**Comment by erickyun** [comment]
> /data/user/0/is.xyz.mpv/files/youtube-dl

Thank you that worked for me. 👍 

but it seems it needs ffmpeg to merge bestvideo+bestaudio sad
can I specify ffmpeg path that I did download with termux maybe?
if so could you write where ffmpeg path is in termux?

**Comment by sfan5** [comment]
That wouldn't work, mpv can't access private files of other apps.
If you want a workflow like this that works try figuring if/how you can send the yt-dlp command to termux to execute.

**Comment by erickyun** [comment]
I understand will try figuring it out or try asking termux git about this.
also if I figure out how I will edit here.

I thank again for your help I will close this issue now.
