### ISSUE TITLE
Allwinner H616 hardware decoding is not available.

### ISSUE THREAD

**Issue by Masir01** [mpv-android/mpv-android#473]
The software you transplanted is great！
However, In my Android TV, its hard decoding function cannot be used.
So I came to ask for help.
I hope developers can adapt it.

**Comment by Masir01** [comment]
CPU | Allwinner H616 64-bit high-performance Quad-core Cortex-A53 processor
-- | --
GPU | Mali G31 MP2Supports OpenGL ES 1.0/2.0/3.2、OpenCL 2.0
Video decoding | • H.265 Main10@L5.1 decoder up to 4K@60fps or 6K@30fps• VP9 Profile 2 decoder up to 4K@60fps• AVS2 JiZhun 10bit decoder up to 4K@60fps• H.264 BP/MP/HP@L4.2 decoder up to 4K@30fps

http://www.orangepi.cn/Orange%20Pi%20Zero2/index.html

**Comment by sfan5** [comment]
mpv uses the hardware decoding API provided by the OS, on Android it's called [MediaCodec](https://developer.android.com/reference/android/media/MediaCodec). Supporting these is responsibility of the manufacturer.

If by not available you mean that it works in *other* apps (such as a the built-in player) but not in mpv then we can do some debugging.
