### ISSUE TITLE
Android TV cloud streaming not playing!

### ISSUE THREAD

**Issue by jack009j** [mpv-android/mpv-android#480]
In latest version Playing videos from cloud storage through mixplorer is not playing in Android TV(while opening the file, mpv opening and then closing immediately), but it is playing fine in Android mobile.
NOTE: I tried previous releases 10/10/21 in Android TV where in that version video playing from cloud storage but playback is not smooth.

Android TV: MI TV 4a 43imch Android 9
Hope will get fix in the latest version.

**Comment by sfan5** [comment]
issue template?

**Comment by jack009j** [comment]
Can I share recording of issues?

**Comment by sfan5** [comment]
That would unfortunately not be useful. What would help is log output from [`logcat`](https://developer.android.com/studio/command-line/logcat).
Alternatively you can test a newer APK: https://kitsunemimi.pw/tmp/mpv-android-2022-01-02.apk. Perhaps the issue is already solved.

**Comment by jack009j** [comment]
Thanks newer apk work great, also when the newer apk will be available in Play Store?
Then I also noticed video output from mpv Android TV is dull(colour and sharpness is less) compared to mpv Android Mobile.. is any thing I want to change to get good output in TV as mobile?

**Comment by mariarti** [comment]
same here with android tv box mini m8sII
since summer '21 mpv was broken and can't play stream video
also just installed newer app and it works!

**Comment by sfan5** [comment]
If it works that'd good.
It will take some more time until an update can be made in the Play Store, Google's new policies force mpv-android to deal with new storage APIs first.
