### ISSUE TITLE
AV1 hardware decoder not working on AMLogic S905X4

### ISSUE THREAD

**Issue by AH12A** [mpv-android/mpv-android#481]
### Important information

Android version: 10
mpv-android version: 0.33.0-397-g4a80de90d2

### Description

MPV for android does not make use of S905X4's hardware decoder when decoding AV1 video streams. 
S905X4 does indeed support AV1 hardware decoding and AV1 video streams are hardware decoded on other media players such as MX Player.

### Log output
Relevant log entries:
```
01-04 17:06:06.841  9646 24315 V mpv     : [vd:v] Opening decoder libdav1d
01-04 17:06:06.841  9646 24315 V mpv     : [vd:v] Not trying to use hardware decoding: codec av1 is not on whitelist.
01-04 17:06:06.841  9646 24315 V mpv     : [vd:v] Using software decoding.
```

Full log:
[mpv_log.txt](https://github.com/mpv-android/mpv-android/files/7808024/mpv_log.txt)

**Comment by sfan5** [comment]
AV1 hardware decoding depends upon support in [FFmpeg](https://github.com/ffmpeg/ffmpeg/). I don't know if this has been brought to their attention or if this is being worked on.

**Comment by AH12A** [comment]
Thank you for your comment
I ran a quick search in ffmpeg's mailing list but couldn't find much information regarding av1 hw decoding.
Does this mean FFmpeg did not implement android hardware decoding for AV1 at all, or is it just an issue with this particular chip?

**Comment by sfan5** [comment]
> Does this mean FFmpeg did not implement android hardware decoding for AV1 at all?

Yes. The [news page](http://ffmpeg.org/index.html#news) for example mentions that AV1 hwdec is possible via VAAPI, but there is no such support for Android's MediaCodec API.

**Comment by AH12A** [comment]
That's unfortunate to hear.
Thank you

**Comment by sfan5** [comment]
Someone(\*) just whipped up an experimental patch for AV1 MediaCodec support.
I have compiled an APK so you can give it a try: https://kitsunemimi.pw/tmp/mpv-android-2022-01-08.apk

\* You can thank @tmm1

**Comment by AH12A** [comment]
Thanks for the patch
I gave it a try but unfortunately it ran into issues when trying to use hardware decoding

Log:
```
01-08 19:52:32.867  3935  4053 V mpv     : [vd:v] Opening decoder libdav1d
01-08 19:52:32.867  3935  4053 V mpv     : [vd:v] Looking at hwdec av1_mediacodec-mediacodec-copy...
01-08 19:52:32.867  3935  4053 V mpv     : [vd:v] Trying hardware decoding via av1_mediacodec-mediacodec-copy.
01-08 19:52:32.867  3935  4053 V mpv     : [vd:v] Using underlying hw-decoder 'av1_mediacodec'
01-08 19:52:32.868  3935  4053 V mpv     : [vd:v] Pixel formats supported by decoder: mediacodec
01-08 19:52:32.868  3935  4053 V mpv     : [vd:v] Codec profile: unknown (0xffffff9d)
01-08 19:52:32.868  3935  4053 V mpv     : [vd:v] Requesting pixfmt 'mediacodec' from decoder.
01-08 19:52:32.869  3935  4053 V mpv     : [ffmpeg/video:v] av1_mediacodec: Using surface 0x0
01-08 19:52:32.869  3935  4053 V mpv     : [ffmpeg/video:warn] av1_mediacodec: Unsupported or unknown profile
01-08 19:52:33.054  3935  4053 V mpv     : [ffmpeg/video:error] av1_mediacodec: MediaCodec 0x0 failed to start
01-08 19:52:33.055  3935  4053 V mpv     : [vd:error] Could not open codec.
01-08 19:52:33.055  3935  4053 V mpv     : [vd:v] Falling back to software decoding.
```
Full log: [mpv_patched_log.txt](https://github.com/mpv-android/mpv-android/files/7833565/mpv_patched_log.txt)

**Comment by sfan5** [comment]
If you don't mind here's another one: https://kitsunemimi.pw/tmp/mpv-android-2022-01-08-2.apk

**Comment by AH12A** [comment]
I certainly appreciate the effort.
I tried the second build and it gave the same error. I noticed the build time didn't differ with the last build. is that correct?
If there is any other way I can help, let me know.

[mpv_patched_log2.txt](https://github.com/mpv-android/mpv-android/files/7834622/mpv_patched_log2.txt)

**Comment by sfan5** [comment]
Thanks for testing, looks like this'll need more work.

> I noticed the build time didn't differ with the last build. is that correct?

Yes, the only code changes were inside ffmpeg.

**Comment by tmm1** [comment]
I guess the patch needs more work, then. Here is the latest if someone wants to pick it up and experiment further: https://github.com/FFmpeg/FFmpeg/compare/master...tmm1:mediacodec-dec-av1

**Comment by Lovedeep96** [comment]
Any update on this?

**Comment by sfan5** [comment]
Apparently I forgot that codecs have to be whitelisted for this to work automatically.
As of the [release today](https://github.com/mpv-android/mpv-android/releases/tag/2023-06-04) this is the case, testing is welcome.
