### ISSUE TITLE
[Question] Best way to build with libplacebo support

### ISSUE THREAD

**Issue by epicfilmmaker93** [mpv-android/mpv-android#482]
I'm trying to build this with libplacebo support, but I'm not sure how to do that

Edit: seems like I need to add --enable-libplacebo to waf configure in buildscripts/scripts/mpv.sh, but after git cloning libplacebo to deps I get the "libplacebo not found" error

**Comment by sfan5** [comment]
Are you sure you actually want to *build* with libplacebo?
It would be much easier for me just to upload a build that has working libplacebo support. In fact I have an APK lying around from last time.

**Comment by epicfilmmaker93** [comment]
Well, I want to try the new tone mapping from https://github.com/mpv-player/mpv/pull/9666, but for a start an apk with current features only would be nice as well

**Comment by sfan5** [comment]
Here's a relatively recent build: https://kitsunemimi.pw/tmp/mpv-android-2021-12-19-vulkan.apk

The branch is here: https://github.com/mpv-android/mpv-android/tree/sfan5/vk
Make sure to read the `REQUIRED_PATCHES.txt`, you have to patch mpv, libplacebo and the NDK by hand to get a successful build.

**Comment by epicfilmmaker93** [comment]
Thanks for pointing to the patches.

The apk crashes on opening a video for me, however

**Comment by sfan5** [comment]
If you want to find out why that is look at logcat, the bug report template explains it.

**Comment by epicfilmmaker93** [comment]
Sorry, got to my computer only now. Anyway, not sure if I should create an issue or the problem is my device, but I get:
Selected vulkan device does not support timeline semaphores!
 mpv     : [vo/gpu-next/vulkan/libplacebo:fatal] Failed creating logical device!
mpv     : [vo/gpu-next/vulkan/libplacebo:fatal] Failed initializing vulkan device

**Comment by epicfilmmaker93** [comment]
After installing a new GPU driver, I either get the same thing or this:
[vo/gpu-next:error] Failed initializing any suitable GPU context!
mpv     : [cplayer:fatal] Error opening/initializing the selected video_out (--vo) device.
mpv     : [vo/gpu-next:error] Failed initializing any suitable GPU context!
mpv     : [cplayer:fatal] Error opening/initializing the VO window.

**Comment by sfan5** [comment]
You can try `vo=gpu` `gpu-context=androidvk` instead of whatever that APK has, but I'd say your device just does not support Vulkan 1.1 (which libplacebo requires).

**Comment by sfan5** [comment]
Sure there is, here's a patch file: [0001-add-in-epoxy-for-extra-testing.patch](https://github.com/mpv-android/mpv-android/files/7892531/0001-add-in-epoxy-for-extra-testing.txt)

**Comment by epicfilmmaker93** [comment]
Thanks, is there an apk with this patch, maybe an older build?

**Comment by epicfilmmaker93** [comment]
Edit: git cloned your branch, patched everything, compiled and signed, now I get this on both drivers:
[vo/gpu-next:v]     GL_SHADING_LANGUAGE_VERSION: OpenGL ES GLSL ES 3.20
mpv     : [vo/gpu-next:v] GPU does not seem to support lossless texture readback, restricting readback capabilities! This is a GLES/driver limitation, there is little we can do to work around it.
mpv     : [vo/gpu-next:error] pl_gpu_create_gl: OpenGL error: GL_INVALID_OPERATION
mpv     : [vo/gpu-next:fatal] Failed initializing opengl context!
mpv     : [cplayer:fatal] Error opening/initializing the VO window.

**Comment by haasn** [comment]
> VK_ERROR_OUT_OF_HOST_MEMORY when using Vulkan

Try with `--vd-lavc-dr=no`

>  mpv : [vo/gpu-next:error] pl_gpu_create_gl: OpenGL error: GL_INVALID_OPERATION

Try with this patch:

```diff
diff --git a/src/opengl/gpu.c b/src/opengl/gpu.c
index 4269ab0d..8efa9266 100644
--- a/src/opengl/gpu.c
+++ b/src/opengl/gpu.c
@@ -256,8 +256,11 @@ pl_gpu pl_gpu_create_gl(pl_log log, pl_opengl gl, const struct pl_opengl_params
     if (gl_test_ext(gpu, "GL_EXT_unpack_subimage", 11, 30))
         limits->align_tex_xfer_pitch = 4;
 
-    if (!gl_check_err(gpu, "pl_gpu_create_gl"))
-        goto error;
+    if (!gl_check_err(gpu, "pl_gpu_create_gl")) {
+        PL_WARN(gpu, "Encountered errors while detecting GPU capabilities... "
+                "ignoring, but expect limitations/issues");
+        p->failed = false;
+    }
 
     // Filter out error messages during format probing
     pl_log_level_cap(gpu->log, PL_LOG_INFO);
```

**Comment by sfan5** [comment]
BTW note that when applying a patch it's safest to do a full rebuild after deleting `buildscripts/prefix/`.
And also a copy of the *full* output of an mpv-android run from logcat is generally better to diagnose issues.

**Comment by BlueSwordM** [comment]
So, how feasible would it be to add in full libplacebo support?

I have some egotistical incentive to actually get it working inside of mpv-android, but I've been told there are some build tool limitations causing some problems...

**Comment by sfan5** [comment]
What do you mean by "full" support? The steps referenced in my second reply still work.

**Comment by BlueSwordM** [comment]
@sfan5 If you want to know why, it's because I've heard from Quackdoc over on IRC/Matrix that there are some Vulkan toolsets that need to be updated if we want to get the full power of Vulkan libplclacebo to work.

I have a selfish reason for wanting to know if it works or not, and that is libplacebo GPU AV1 grain synthesis :p
