### ISSUE TITLE
Exynos compatibility problems after last update

### ISSUE THREAD

**Issue by nonaggressive** [mpv-android/mpv-android#484]
Android 11
Samsung galaxy note 10+
Exynos 9825

MPV VERSION 2021-10-28

After the last update almost nothing works.
Seems to be a compatibility problem with exynos since mpv works on my Snapdragon based devices.
Trying to play anything results in a black screen and only poor audio playback.
In the past I still had playback issues with some video codecs but worked otherwise. Now it doesn't work at all with any video.

**Comment by Pentaphon** [comment]
Might be related to https://github.com/mpv-android/mpv-android/issues/468

All files or just some files?

**Comment by nonaggressive** [comment]
Its all Including hevc. I cant change it to sw or hw decoding and this will cause a brief flash on the screen and then nothing playing thereafter.

**Comment by nonaggressive** [comment]
Oh, let me try that build. I was only looking at what's on the releases here and the play store.

**Comment by nonaggressive** [comment]
Thanks the version you linked works better.

**Comment by nonaggressive** [comment]
Oh from here https://kitsunemimi.pw/tmp/

**Comment by nonaggressive** [comment]
Only Hevc video works h264 hi10 cause the app to freeze on a black screen

**Comment by sfan5** [comment]
likely fixed by ffd1e8f5e0bb40a9014481a41ae9bad48866381e
