### ISSUE TITLE
How do i resize the output from mpv.conf, if i am using hwdec=mediacodec?

### ISSUE THREAD

**Issue by 00surya00** [mpv-android/mpv-android#486]
I want to know, how i should resize the output of from **mpv.conf** or set the right aspect ratio, if i use **mediacodec** for demuxing.
My mpv.conf is as follows -
```
hwdec=mediacodec
vo=mediacodec_embed
```
Please also suggest something to optimize the player as i'm experiencing framedropes if i try to play 4k 60fps video(unless i use mediacodec). If i use the following without **mediacodec_embed**,
```
hwdec=medicodec-copy
vo=gpu
gpu-context=android
```
Even then i experience frame dropes. Please either tell me what i am doing wrong or tell me how to resize the output from mediacodec_embed.
**Thank you**

**Comment by sfan5** [comment]
I'm sure it's possible _in principle_ but I'm not aware of an ffmpeg or mpv option that does this. Sorry.
