### ISSUE TITLE
Wrong scaled resolution in Android TV

### ISSUE THREAD

**Issue by jack009j** [mpv-android/mpv-android#489]
From the closed issue #480 , upon checking the given apk from that thread or official apk from Android TV playstore, in both apk ,MPV gives wrong scaled resolution.
My tv is Mi 4a pro 43" FHD running on Android 9 ,
My tv native resolution is 1080p, but while playing both 1080p and 2160p file I am getting 720p output.
By checking MPV stats it also shows scaled resolution wrongly as 1280*720p, but my tv is FHD and video source I played also FHD and 4k.
But at same time the both apk upon using in Android mobile give correct scaled resolution.
Kindly resolve the issue, thanks.

MPV stats pic from Android TV attached below.
![IMG20220115105839](https://user-images.githubusercontent.com/79247377/150683832-796212f1-e64f-4a4d-b34e-92b8d6cd14c5.jpg)

**Comment by jack009j** [comment]
MPV stats comparison of same file with Android mobile and Android TV.
1.android mobile-(Streaming url file)
![Screenshot_2022-01-25-11-59-38-04](https://user-images.githubusercontent.com/79247377/150925061-8e361db6-f224-4e3f-beb2-521aa7cd015f.jpg)
![Screenshot_2022-01-25-12-01-28-83](https://user-images.githubusercontent.com/79247377/150925087-896eb239-7877-40d0-8210-f3b078735d23.jpg)
![Screenshot_2022-01-25-11-59-57-55](https://user-images.githubusercontent.com/79247377/150925118-20c45643-d77a-4e06-913c-40c625bed235.jpg)
2.android TV-(streaming url file)
![IMG_20220125_115334](https://user-images.githubusercontent.com/79247377/150925276-08409062-2e60-4065-a5fb-655dbe10dee8.jpg)
![IMG_20220125_115544](https://user-images.githubusercontent.com/79247377/150925306-a8369e2f-0b9c-4dba-a272-286c3a3e7891.jpg)
![IMG_20220125_115604](https://user-images.githubusercontent.com/79247377/150925353-c76df949-7015-42f9-a251-f535ab8e8d66.jpg)

Android TV- playing from external storage.
![IMG_20220125_115632](https://user-images.githubusercontent.com/79247377/150925416-a7f5c67f-57f9-49aa-843a-1999ef8c8d5b.jpg)
![IMG_20220125_115724](https://user-images.githubusercontent.com/79247377/150925445-c4997f06-051b-4dc6-b3f2-0a41e5e04d35.jpg)
![IMG_20220125_115733](https://user-images.githubusercontent.com/79247377/150925511-4e103338-270c-48a7-8b80-b6e25c2c2a4a.jpg)

I also guessing

**Comment by jack009j** [comment]
I need to tell some of my observation.
All the release of MPV Android TV, I get video output of 720p resolution and less colour even the source file is 1080p or 2160p, but from latest release of app only I get know that, from stats scaled resolution mentioned is 720p, that it is getting downscale.

Please provide solution for this, thanks.

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/293#issuecomment-667973890
Even if your TV is of higher resolution, the system UI (and thus mpv's output) can be rendered at a lower resolution. This is a manufacturer/hardware limitation.

**Comment by jack009j** [comment]
Thanks for letting know that it is hardware limitation and ui render limitation.
I curious about how YouTube or other video player are playing 1080p whether they render at 720p then upscale to 1080p (display resolution)?, I am asking because in YouTube also show view port as 1280*(720*1.5) but it's playing 1080p correctly and other video player also player 1080p and even 4K at 1080p display resolution.
