### ISSUE TITLE
HW acceleration not working with 6-channel AC-3

### ISSUE THREAD

**Issue by brucethemoose** [mpv-android/mpv-android#49]
I apologize in advance, I know this is a bad bug report. 

A few months ago, my HTC 10 (SD820/Android 7) + MPV played some videos with 6-channel Dolby AC-3 audio with hardware acceleration just fine. 

This is remarkable, as even now MX Player mutes the audio while VLC just stutters like crazy with no acceleration on the same videos. 

Anyway, with a reset phone, unlocked bootloader, and the latest Mpv apk from Github, hardware decoding no longer works. SW works OK, but creates more heat/drains more battery than I like. 

Way I see it, either A: unlocking my bootloader broke whatever AC3 decoder Mpv uses, B: some change in Mpv broke it. 

I'm not very familiar with Android hardware decoding... I'm assuming it's supposed to decode and downmix the audio in software while decoding the video in hardware, right? Are there any arguments I can add to get more information about why it's falling back?

**Comment by brucethemoose** [comment]
Also, hardware decoding works fine with no audio and stereo AAC.

**Comment by brucethemoose** [comment]
http://i.cubeupload.com/0sarlX.png

http://i.cubeupload.com/YXV0O0.png

**Comment by sfan5** [comment]
TIL mediacodec support hwdec for audio
`logcat` output would be nice

**Comment by brucethemoose** [comment]
Error log:

https://drive.google.com/file/d/0Bw8Qfkjm1-GiYTFUUUFZanREWHM/view?usp=drivesdk

Log from a working video:

https://drive.google.com/file/d/0Bw8Qfkjm1-GiN3dCOW1XQ2E1LW8/view?usp=drivesdk


That was a short capture from starting the video and clicking the HW decoding button a few times, same videos as the screen shots. Ask if u need more.

**Comment by brucethemoose** [comment]
Looks like the decoding error pops up around 13:20:02.495

Hardware decoding starts around 15:36:00:212 for the working log. 

When I get access to a desktop, I'll demux the audio out just to make sure it's not the video, and I can upload a video sample if you want.

**Comment by sfan5** [comment]
Relevant part about audio decoding (it's not using hwdec, ffmpeg does not even support that):
<pre>
06-17 13:20:02.487 13747 14225 V mpv     : [ad:v] Codec list:
06-17 13:20:02.487 13747 14225 V mpv     : [ad:v]     ac3 - ATSC A/52A (AC-3)
06-17 13:20:02.487 13747 14225 V mpv     : [ad:v]     ac3_fixed (ac3) - ATSC A/52A (AC-3)
06-17 13:20:02.487 13747 14225 V mpv     : [ad:v] Opening audio decoder ac3
06-17 13:20:02.487 13747 14225 V mpv     : [ad:v] Requesting 1 threads for decoding.
06-17 13:20:02.487 13747 14225 V mpv     : [ad:v] Selected audio codec: ac3 (ATSC A/52A (AC-3))
</pre>

here's what happens to video decoding:
<pre>
06-17 13:20:02.495  2433 14247 E OMX-VDEC-1080P: OMX_COMPONENT_GENERATE_HARDWARE_ERROR
06-17 13:20:02.495  2433 14247 E OMX-VDEC-1080P: ERROR: Sending OMX_ErrorHardware to Client
06-17 13:20:02.495 13747 14245 E ACodec  : [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
06-17 13:20:02.495 13747 14245 E ACodec  : signalError(omxError 0x80001009, internalError -2147483648)
06-17 13:20:02.496 13747 14244 E MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to dequeue input buffer (status=-542398533)
06-17 13:20:02.502 13747 14225 V mpv     : [vd:warn] Error while decoding frame!
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to dequeue input buffer (status=-542398533)
06-17 13:20:02.502 13747 14225 V mpv     : [vd:warn] Error while decoding frame!
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to dequeue input buffer (status=-542398533)
06-17 13:20:02.502 13747 14225 V mpv     : [vd:warn] Error while decoding frame!
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
06-17 13:20:02.502 13747 14225 V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to flush codec
</pre>

what caught my eye is the 
`06-17 13:20:02.547 13747 14225 V mpv     : [ffmpeg/video:v] h264: Reinit context to 1920x1088, pix_fmt: yuv420p10le`
which suggests that your file contains 10-bit H.264 (which is rarely/never supported by hardware).

comparing this to the working log:
`06-17 15:36:02.471 17522 17729 V mpv     : [ffmpeg/video:v] h264: Reinit context to 1920x800, pix_fmt: yuv420p`
yup, suspicion confirmed


<b>TL;DR</b>: It's the files you play, not mpv.

**Comment by brucethemoose** [comment]
...Huh. It is 10-bit, thanks. Earlier seasons were 8-bit, which is where my confusion came from. 

Franky,  I'm surprised I get decent playback with 1080p 10 bit h.264 on an Android phone.
