### ISSUE TITLE
Allow streaming torrent files( magnet links)

### ISSUE THREAD

**Issue by nikhilCad** [mpv-android/mpv-android#492]
Allow streaming torrent files from magnet link. This means sequentially download the torrents(temporarily) and then play them

### Additional information

Not relevant

**Comment by Pentaphon** [comment]
Isn't this best left to another application like webtorrent?

**Comment by sfan5** [comment]
Indeed, this is definitely out of scope for mpv.

**Comment by nikhilCad** [comment]
@z8512 is this dev build?

**Comment by z8512** [comment]
@nikhilCad no

**Comment by nikhilCad** [comment]
Then how did you open it? Mine crashes

**Comment by z8512** [comment]
Termux magic

**Comment by nikhilCad** [comment]
I thought it was native :( Streaming can be done on Libretorrent using sequential download without termux magic anyways. Also Stremio.

**Comment by z8512** [comment]
But I don't need to install extra apps like Stremio/libtorrent. Mpv plays local files/blu-ray_dvd disc/https url/scraps from various websites using yt-dlp and now torrent also. All in one

**Comment by z8512** [comment]
@sfan5 since it supports torrent now, please add support for opening magnet url in mpv. If I click any magnet url, then I should get mpv option in "Open With" pop-up at bottom of phone screen

**Comment by sfan5** [comment]
I can't add an intent filter to AndroidManifest for something you hacked up on your phone, lol.

**Comment by z8512** [comment]
I'll build my own, Can you please tell what to add in AndroidManifest.xml?

**Comment by z8512** [comment]
@sfan5 please tell🙏

**Comment by sfan5** [comment]
idk, maybe this
```xml
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="magnet" />
            </intent-filter>
```
