### ISSUE TITLE
Android TV Play Store page doesn't have the banner, just a screenshot of the player UI

### ISSUE THREAD

**Issue by Pentaphon** [mpv-android/mpv-android#493]
Not a bug but a minor thing to be addressed. The Android TV Play Store page just shows a screenshot of the Player UI instead of the banner that would show up on your launcher, making the Play Store page look like it's for some generic, shoddy video player when you browse the store in the "video players" section. 

![mpv](https://user-images.githubusercontent.com/49374058/152994557-3cefb888-1d76-49e1-b7aa-212c02440d85.jpg)

**Comment by sfan5** [comment]
Replaced.
