### ISSUE TITLE
How to load scripts-opts folder?

### ISSUE THREAD

**Issue by erickyun** [mpv-android/mpv-android#494]
Hi,

İn my pc I have an lua scripts example name.lua that needs name.conf to load credential info

How can I in android make mpv load/see name.conf?

**Comment by sfan5** [comment]
Don't think there's a way to point it to a folder but you can include the settings inline in mpv.conf:

`deadzonesize=0` in `script-opts/osc.conf`:
_is equivalent to_
`script-opts=osc-deadzonesize=0` in `mpv.conf`
