### ISSUE TITLE
On android 12 mpv does not appear anymore as an option to stream media from network drives in file managers

### ISSUE THREAD

**Issue by user000003** [mpv-android/mpv-android#497]
### Important information

Android version: 12

mpv-android version: 0.33.0-397-g4a80de90d2 2021-10-28-release / 26

Which version of mpv-android introduced the problem (if known):

### Description

In SMB network file manager apps like Solid Explorer and Synology DS File when opening a video file mpv does not show up as an option to stream the video from the network drive. 

I had this happen when I updated my Samsung tablet to android 12, it has previously worked fine on android 11 and before. I confirmed this after updating my phone to android 12 the same problem appeared.

I've tested this on multiple file types, forcing Solid Explorer to show all apps that can open video mpv still doesn't appear. 

Mpv will still appear as an option if I try to open a local fbugile from the file manager.

**Comment by moneytoo** [comment]
Had similar issue and resolved it by removing `<data android:host="*" />` from intent filters.

**Comment by sfan5** [comment]
I originally only added `android:host="*"` because the linter complained about it. I'll check if it still works without and remove it if possible.

**Comment by moneytoo** [comment]
If removing is no go, then why not have two versions of that intent filter? (If it really solves both use cases.)

**Comment by sfan5** [comment]
If that works sure.
Can you clarify if you meant the one annotated `HTTP(S) with MIME type (#43)` or `HTTP(S) with extension (e.g. Chrome)`? (or both?!)

**Comment by moneytoo** [comment]
To my understanding it is only needed for intent filter with mime types. Intent filters with extensions are not really working on Android 12 unless the host is verified (app link) so these should stay as is.

**Comment by sfan5** [comment]
869fb226a5f97d8e3355187f2138e5900510b654

**Comment by YanceyChiew** [comment]
For me, the problem remains in 2022-03-06-release. Meanwhile another project from **moneytoo** above works fine in the same context.

**Comment by and101** [comment]
A workaround is to use an intent interceptor and redirect to mpv.
