### ISSUE TITLE
Smart tv running Android 7 Mpv version 28/10/21  release  /26 debug  Blank Screen on selecting stream

### ISSUE THREAD

**Issue by jamie-203** [mpv-android/mpv-android#500]
Not sure if this is the correct place for my question- my apologies if not.
Also tried the debug version details above
Vlc runs fine but MPV just gives me a blank screen. Can someone help?
Thanx

**Comment by sfan5** [comment]
Try this APK: https://kitsunemimi.pw/tmp/mpv-android-2022-01-02.apk
this could be a duplicate of an already fixed issue (I haven't got around to preparing a new release with those fixes yet)

**Comment by jamie-203** [comment]
Many thanx 
Works like a charm
Again many and keep up the great work!
