### ISSUE TITLE
Possible to add subtitle scroll feature

### ISSUE THREAD

**Issue by rohitghali** [mpv-android/mpv-android#503]
Expected behavior of the wanted feature
Swipe on the subtitle to go to next or previous subtitle position.

It is currently present in windows and Linux version known as sub-step. Implementation on MX player Android is good. Check it out for inspiration.

[MX Player's implementation of sub-step](https://youtu.be/NeCAybjYRMk)

**Comment by Ahmad-f79** [comment]
you can set the left and right double tap gestures to custom and then add these lines to input.conf (using edit input.conf in advanced settings menu):
0x10003   no-osd sub-seek  1
0x10001   no-osd sub-seek -1

and as result double tapping on the right and side will seek to next and previous line, which does the trick for me

**Comment by rohitghali** [comment]
I did long back actually. Working fine. But OSD keeps showing on every tap. That's a different issue... Closing this...
