### ISSUE TITLE
mpv-android doesn't always "begin playing" songs in playlist while in background

### ISSUE THREAD

**Issue by goto-engineering** [mpv-android/mpv-android#506]
### Important information

Android version: 12

mpv-android version: 0.34.0-222 / 2022-03-06

### Description

This doesn't happen all the time. I haven't found a pattern.

I often play folders as playlists in the background by holding down on the folder, then locking the phone. Sometimes this is via bluetooth, but sometimes it happens with audio jack headphones, too.

The phenomenon is that a song will end, and the next song doesn't start playing automatically. When I unlock the phone, therefby bringing mpv to the foreground, the song begins playing. So it's not stopped per se, it just.. doesn't begin playing? I'm not pressing any buttons in mpv to make it start again, just unlocking the phone.

It seems like it's happening more and more. I first noticed it happening a few months ago, only rarely. Now it's more common, happening 2-3 times per playlist. Might be imagining that though, or getting unlucky with whatever causes it..

**Comment by sfan5** [comment]
Haven't had this happen to me yet.
If you could capture a log of this happening that'd be useful (logcat goes up to a few hours if you attach your phone to your PC afterwards).

**Comment by goto-engineering** [comment]
It hasn't happened a single time since the last Android update, so maybe it got fixed on the OS side? :crossed_fingers:

**Comment by goto-engineering** [comment]
Just happened again even with the new OS update :(

**Comment by sfan5** [comment]
You don't happen to be using Bluetooth do you?
