### ISSUE TITLE
mpeg-ts hevc 4k  stream stutters 

### ISSUE THREAD

**Issue by wazerstar** [mpv-android/mpv-android#510]
### Important information

Android version: 11
Shield Android TV SW Version
9.0.1(33.1.0.283)

mpv-android version:
2022-03-06-release / 27
mpv 0.34.0-222-g7f67a553f6

### Description

Stutters right away when starting playing mpeg-ts hevc 4k stream

### Log output
https://pastebin.com/Q8R9WJWX

### Additional information

Clip sample ts packed with zip.
https://mega.nz/file/UJA1zCzR#rA-EpsVTij4bAIjYmz65xpoWOy9KCbmOZVWgR8JCdLg

(https://i.imgur.com/iiXwTQj.jpeg)

(https://i.imgur.com/Vstm55U.jpeg)

**Comment by sfan5** [comment]
Your content is 10-bit HEVC which is more heavy than usual, though I don't know why it would drop frames with hwdec enabled (your second screenshot shows it *disabled* btw).
Not directly related but you can try with `vd-lavc-dr=no` in your mpv.conf and see if the performance improves any.

**Comment by wazerstar** [comment]
> Your content is 10-bit HEVC which is more heavy than usual, though I don't know why it would drop frames with hwdec enabled (your second screenshot shows it _disabled_ btw). Not directly related but you can try with `vd-lavc-dr=no` in your mpv.conf and see if the performance improves any.

I tested with and without

Exoplayer internal on android TV works fine and has no problem playing this channel

I will try vd-lavc-dr=no and report back.

**Comment by wazerstar** [comment]
Using vd-lavc-dr=no did not do anything
