### ISSUE TITLE
H.265 video black screen and audio jitter

### ISSUE THREAD

**Issue by physics121** [mpv-android/mpv-android#512]
Android version: 11
mpv-android version: 0.34.0-222-g7f67a553f6
### Description

Describe your issue in detail here.

If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.

when playing some H.265 videos(mostly any video) the whole screen goes black and the audio also jitters. While the same video is playing smoothly in vlc.

**Comment by sfan5** [comment]
Possibly the same problem as #508. Please test the new release (once it's out) and report back if it's _not_ fixed.
