### ISSUE TITLE
 Strange intent filter effect on Android 12, cannot be used when host is an ipv4 address

### ISSUE THREAD

**Issue by YanceyChiew** [mpv-android/mpv-android#514]
### Important information

Android version: 12

mpv-android version: 2022-03-23-release

Which version of mpv-android introduced the problem (if known): 2022-03-06-release
_Strictly speaking, the bug is not **introduced** in this version, but has not yet been resolved. After all, the previous version did not adapt to Android 12._

### Description

When upgrading to Android 12, I found that mpv as default streaming player no longer works in my personal case. 

By querying past issues([#497](https://github.com/mpv-android/mpv-android/issues/497#issue-1144644505)), I found that this problem should be caused by incompatible intent filter configuration, and should have been resolved in 2022-03-06-release. However, until 2022-03-23-release, my mpv still cannot be opened by the intent of Bubble Upnp.

So I used other apps to controllably send the intent, to compare the intent content and whether the mpv appeared in the menu, and finally identified a specific and very puzzling problem:

**If and only if the host of the url in the intent is an ipv4 address, the system(or something else) will prevent all intents who's mimeType is also claimed by another intent filter which containing `<data android:host="*"/> `being passed to the app.** 

I have absolutely no idea what this has to do with ipv4 addresses, and haven't found any useful documentation. However, through experimental comparison, the above-mentioned situation will only happen when the host is a legal (0-255.0-255.0-255.0-255) ipv4 address. There is no problem with an ipv6 address or domain name or simply empty host.

### Additional information

The problem described above is resolved for me after removing [`another intent filter which containing <data android:host="*"/>`](https://github.com/mpv-android/mpv-android/blob/e4e8ca0aff62107b210be08a73bedc36c8301b7d/app/src/main/AndroidManifest.xml#L68-L80).

Even if the host is an ipv4 address, I have accidentally opened it several times without modifying the manifest, but the probability is extremely low, and I have no clue about it.

**Comment by linpinger** [comment]
got similar problem, recently upgrade to Android 12, use normal code to call mpv to play online video, but failured, it works find on old version of Android
try bellow code, still can not play:

`Intent itt = new Intent().setComponent(new ComponentName("is.xyz.mpv", "is.xyz.mpv.MPVActivity"));
itt.setDataAndType(Uri.parse("http://example.com/aaa.m3u8"), "video/*");
try {
	startActivity(itt);
} catch(Exception e) {
	System.err.println( e.toString() );
}`

**Comment by sfan5** [comment]
Maybe Google should just fix bugs in their OS because working around all of them is becoming infeasible...

**Comment by YanceyChiew** [comment]
### Reproduce:

```bash
adb shell am start -a android.intent.action.VIEW -d 'http://10.0.0.1:8001/r/a.mp4' -t 'video/*'
```
_and mpv dosen't appear in resolverlist._

```bash
adb shell am start -a android.intent.action.VIEW -d 'http://10.0.0.256:8001/r/a.mp4' -t 'video/*'
```
_and mpv dose appear in resolverlist._

_The Shortcut Maker app can also be used to reproduce this._

### Notice:

- This strange event doesn't always happen, it can't be reproduced for a period of time after I uninstalled mpv for a few days and then reinstalled it. But, after trying to open mpv from Bubble upnp to play online video, it becomes always reproducible again.
- For me, mpv was able to appear in the resolverlist when the host was `example.com`, unlike [what](https://github.com/mpv-android/mpv-android/issues/514#issuecomment-1084326444) happened to [linpinger](https://github.com/linpinger).
- The adb log shows that mpv received the intent, whether it ended up in the resolverlist or not.
- After removing [another filter](https://github.com/mpv-android/mpv-android/blob/e4e8ca0aff62107b210be08a73bedc36c8301b7d/app/src/main/AndroidManifest.xml#L68-L80) containing `<data android:host="*"/>` and the same mimeType(`<data android:mimeType="video/*" />`) in the manifest, the repackaged mpv always appears in the resolverlist normally.

**Comment by f1vefour** [comment]
Why does the difference between these two IP addresses allows mpv to show? I verified the behavior using the am command.

> http://10.0.0.1:8001/r/a.mp4 - no show
> 'http://10.0.0.256:8001/r/a.mp4 - show

**Comment by YanceyChiew** [comment]
> Why does the difference between these two IP addresses allows mpv to show? I verified the behavior using the am command.

---

@f1vefour I have no clue about this. The only difference between them is whether it is a legitimate ipv4 address, it doesn't distinguish between public or private ip, and also has no restrictions on ipv6 addresses.

> Uri.parse("http://example.com/aaa.m3u8")

@linpinger Is `example.com `actually the url used in the test code or just a mask pronoun for talking?

---

> Maybe Google should just fix bugs in their OS because working around all of them is becoming infeasible...

@sfan5 Maybe so, but even if it turns out to be a system bug and Google fixed it in the future, a lot of devices won't benefit from that anyway. So, is it possible to replace [another](https://github.com/mpv-android/mpv-android/blob/e4e8ca0aff62107b210be08a73bedc36c8301b7d/app/src/main/AndroidManifest.xml#L68-L80) intent filter that produces conflicts with other matching rules?

**Comment by sfan5** [comment]
You mean removing the intent filter you linked will make it work on Android 12 *without* breaking anything on previous versions? If it doesn't cause any problems then sure I can do that.

**Comment by YanceyChiew** [comment]
> You mean removing the intent filter you linked will make it work on Android 12 _without_ breaking anything on previous versions? If it doesn't cause any problems then sure I can do that.

I'm not really sure, but according to the [dev docs](https://developer.android.com/guide/components/intents-filters#DataTest) there seems to be no need to specify host when no path matching is required. I tested it on another Android 9 device, without `<data android:host="*"/>` it works as expected.

Except when the mimeType is literally `video/*`, I don't know why but on my Android 9 device it doesn't evoke mpv, `video/foobar` or `video` works, but the real weird thing is that `audio/*` also works fine. Looks like there should be no additional negative effects.

**Comment by linpinger** [comment]
@YanceyChiew Is example.com actually the url used in the test code or just a mask pronoun for talking?
the url is a mask pronoun for talking

but you can try bellow real url, dont know whether you can play with

http://record.vod.yy.com/xcrs/15013_215038381_10299121_1648036820896.m3u8

**Comment by f1vefour** [comment]
It's the same issue, mpv does not appear in the list even though it does appear in the matching activities intent.

**Comment by YanceyChiew** [comment]
> but you can try bellow real url, dont know whether you can play with
> 
> http://record.vod.yy.com/xcrs/15013_215038381_10299121_1648036820896.m3u8
> 

Confirmed, it cannot be opened.

One of the problems with my previous tests was that the fabricated domain names used a format like `[a.b.c.d]`, while in a legitimate domain name, the top-level segment should contain at least two letters(no matter which language they belong to) and no arabic numeral.

Also, like I mentioned above, this behavior is not always reproducible, `example.com` opened in yesterday's test, but after trying the link you gave above it didn't work anymore.

**Comment by YanceyChiew** [comment]
> It's the same issue, mpv does not appear in the list even though it does appear in the matching activities intent.

So, one possibility is that the intent calling mpv was successfully captured by one of the filters, which containing `host="*"`, but in API31, the application needs to apply for permission to open the specified host first, and `host="*"` already belongs to the default browser.

And yes, whether or not my assumption above is correct, Path-based filtering rules have already failed.

**Comment by YanceyChiew** [comment]
As far as the apps I already have on my device, the path-based intent filters all fail on Android 12. 

Intents that do not specify mimeType can only open browser applications, and none of them specify the host field in the intent filter. But if host is not specified, the path filtering rules will be ignored.

Maybe new matchers like [pathSuffix](https://developer.android.com/reference/android/R.attr#pathSuffix) introduced in API31 will help or not, it also needs to specify the host so I am not optimistic.

**Comment by sfan5** [comment]
Applied the suggested change in 7a277d8100256f55d05735890af7b8ec6cc8c53c.
