### ISSUE TITLE
Smoother seeking is actually making the seeking much jagged. Details below.

### ISSUE THREAD

**Issue by rohitghali** [mpv-android/mpv-android#515]
### Important information

Android version: 11

mpv-android version:
2022-03-23-release-oldapi / 28 (release)
mpv 0.34.0-235-g84821dbcb6
built on Wed Mar 23 22:42:15 CET 2022

### Description

Smoother seeking feature is supposed to make seeking smoother, but is more jagged when enabled. Previews wont show while seeking. Only time shows. 

Please do let me know about any additional information required.

**Comment by sfan5** [comment]
How well the "smoother" seeking works depends on the keyframe interval and codec of the file.
It indeed take a bit of time until previews show, I haven't investigated whether this could be improved inside libmpv.
