### ISSUE TITLE
Ui opening when not intended. Details below. 

### ISSUE THREAD

**Issue by rohitghali** [mpv-android/mpv-android#516]
### Important information

Android version: 11

mpv-android version:
2022-03-23-release-oldapi / 28 (release)
mpv 0.34.0-235-g84821dbcb6
built on Wed Mar 23 22:42:15 CET 2022

### Description

Basically I've assigned custom shortcuts to doubletaps on the left and right. It is a sub-seek shortcut. Now, as soon as I doubletap, the ui, play/pause buttons all show up obstructing the movie I'm watching. 
Ui should not be visible while sub-seeking.

### Additional information

Below is my input.conf:

0x10001 no-osd sub-seek -1
0x10003 no-osd sub-seek 1

**Comment by sfan5** [comment]
This issue was already reported in #387.
