### ISSUE TITLE
can we not build arm 32bit and split APKs?

### ISSUE THREAD

**Issue by Quackdoc** [mpv-android/mpv-android#517]
It would be nice to skip building arm 32bit support. I am currently working on getting github CI support for building MPV-Android and it seems to be working well for the yt-dl branch as well apk signing works too.

however I would like to decrease the run time of the builds. currently the total run time is about 15-20 min for x86_64 and arm64, and 9-11 min for just arm32. I'm not expecting a 10min improvement or anything, (already decreased the run time from 30 min to 20 min by building x64 and arm64 separately), however I would like to cut the time down a tad bit more if at all possible. 

EDIT: as an appendage, would it be possible to set it up to split the APKs? seems like it would be preferred for fdroid.

https://gitlab.com/fdroid/fdroiddata/-/issues/2643

**Comment by linsui** [comment]
@sfan5 This scheme of the version code doesn't work well with F-Droid because F-Droid only keep the apks with the highest version code in the main repo. So after some releases only the x86-64 apks are kept. Could you please use the abi codes as suffix instead so that newer version always have higher version code? Thanks!

**Comment by sfan5** [comment]
The version scheme is the [official recommendation from Google](https://developer.android.com/studio/build/configure-apk-splits#configure-APK-versions). I could probably swap the places of the two components.
But surely this isn't the only project which does this, maybe f-droid can just patch it out?

**Comment by linsui** [comment]
This is the second app I have seen with this scheme though. I thought it's not a good idea to allow the user update to an old version.
Yes, we can patch it. I would like to keep the same version code with your release but it's not a big problem.  :ok_hand:

**Comment by linsui** [comment]
I opened an [issue](https://gitlab.com/fdroid/fdroidserver/-/issues/1011) to track this problem in F-Droid.

**Comment by sfan5** [comment]
Thanks, I'm interested to know what comes of it.
