### ISSUE TITLE
Lua script isn't working for only on android but for pc it works? 

### ISSUE THREAD

**Issue by erickyun** [mpv-android/mpv-android#529]
### Important information

Android version: 11

mpv-android version: 2021.10.28

### Description

Hi,

This Lua script which does let play gdrive videos directly on mpv does work fine on my pc but on android it won't work? I did also try to ask the script [creator](https://github.com/nhanb/mpv-gdrive/issues/5#issuecomment-1118607226).
 İf you could help me I would appreciate it.

[Lua Script](https://github.com/nhanb/mpv-gdrive/blob/master/gdrive.lua)

mpv.conf
```
script="/storage/emulated/0/scripts/gdrive.lua"
script-opts="gdrive-gdrive_client_id=xxxxx,gdrive-gdrive_client_secret=xxxxx,gdrive-gdrive_refresh_token=xxxxx"
```

### Log output

[log.txt](https://github.com/mpv-android/mpv-android/files/8644716/log.txt)

**Comment by sfan5** [comment]
The script requires curl installed (system-wide, this could only be the case on a rooted device): https://github.com/nhanb/mpv-gdrive/blob/master/gdrive.lua#L94
