### ISSUE TITLE
Does it play HD Audio without downgrading?

### ISSUE THREAD

**Issue by lamyergeier** [mpv-android/mpv-android#530]
I am using Android 11 with Samsung One UI 3.1

I want to play Audio frequency 192 kHz, 24 bit depth flac files. The app plays it successfully, but does it or android downgrades the quality while processing to standard CD quality 44.1 kHz and 16 bit depth?

Or, is the output truly HD Audio?

**Comment by sfan5** [comment]
I think that should work in principle but it's not easy at all to find out. If you have access to logcat output you can look for the lines with `[af] [in]` and `[af] [out]` to see the details.
Here's an example where the output quality is the same as what is in the file:
<pre>
[af] [in] 96000Hz stereo 2ch s32
[...]
[af] [out] 96000Hz stereo 2ch s32
</pre>

**Comment by lamyergeier** [comment]
How can I access the logcat?

**Comment by sfan5** [comment]
https://github.com/mpv-android/mpv-android/blob/master/.github/ISSUE_TEMPLATE/1_bug_report.md#log-output
