### ISSUE TITLE
set watch-later-directory to the disk of the video automatically

### ISSUE THREAD

**Issue by louis-19** [mpv-android/mpv-android#531]
When video files are in external disk, I would like to have an option to set the watch-later-directory to the external disk automatically. This can help to reduce internal flash memory wear out.

Thank you for the great app!

**Comment by sfan5** [comment]
> This can help to reduce internal flash memory wear out.

The files that mpv writes are less than Kilobyte and infrequently written. Any automated processes or Google Play updates will produce more flash wear than mpv ever will.
So if it's for that reason alone then there is no need for such a feature.
