### ISSUE TITLE
Better Motion Interpolation 

### ISSUE THREAD

**Issue by jewelsonn** [mpv-android/mpv-android#536]
![Screenshot_2022-05-17-12-32-33-71_5a59df913d2733f96eade15416e2c157](https://user-images.githubusercontent.com/32433717/168749700-6fe74808-c760-4b09-9026-121f3b36d894.jpg)

SVPlayer has achieved this better smooth motion interpolation using mpv itself included. It has no competition right now. 

I was wondering if mpv can do something similar and add this feature in the app itself. That would change a lot as an open source project in the development of better compatibility accross various devices including Android/iOS for future development.

Plus if you do so implement such feature, let's make sure there is a config file to fine tune it.

**Comment by rohitghali** [comment]
I was actually surprised when I used svplayer. I tried digging into svplayer settings to find their interpolation configs. Found none. I tried replicating it on mpv-android and it is next to impossible. How are they even achieving it?

**Comment by Gemini88** [comment]
@rohitghali it's svflow/avisynth from my knowledge it's the engine used your can use vapoursynth but it's not as smooth as avisynth imho

**Comment by sfan5** [comment]
FWIW my opinion on this hasn't changed and I consider Vapoursynth support as out-of-scope.
see also https://github.com/mpv-android/mpv-android/issues/38#issuecomment-279524687
