### ISSUE TITLE
It is normal that mpv is more battery-hungry than vlc?

### ISSUE THREAD

**Issue by askasys-code** [mpv-android/mpv-android#537]
I was thinking to use mpv on my Huawei MatePad to watch anime, instead of vlc, and I noticed that there is more battery drain in comparison. 
I tried then to analyze if it's true with an application called AccuBattery, I played a simple 1080p H264 video, 5 minutes, first on mpv then on vlc and this is the result:  https://i.imgur.com/9b1SKF0.jpg
vlc is 28 mAh and mpv is 30 mAh. 
Obviously with a 25 minutes of videos this difference increase.

### Additional information

Hardware Accecelartion enabled on both mpv and vlc.
Also tried the low quality decoding feature of mpv, no noticeable difference in battery drain.

Android version:  EMUI 10 (Android 10)
SoC: Kirin 710A
mpv version: 2022-03-23 Build

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/351#issuecomment-763673215 (tl;dr yes)

**Comment by askasys-code** [comment]
So, it is definitely not worth using mpv on Android to watch anime. 
I thought that by changing devices and buying a more modern one and with the various mpv updates, maybe the same efficiency as vlc was achieved. 
I somekind hate vlc both on pc and android, especially on android because of a strange behavior on the audio output. (But this is not the place to talk about it).

Anyway, thanks for the confirmation, I have to search another video player, very sad about I'm huge fan of mpv on pc
