### ISSUE TITLE
Terrible performance on H.265

### ISSUE THREAD

**Issue by nulledone** [mpv-android/mpv-android#54]
Doesn't switches to hardware decoding and it results with a terrible performance.

**Comment by sfan5** [comment]
It's one of these:
* device does not support h265 hwdec
* file is 10/12-bit h265
* file is yuv422/yuv444 h265

**Comment by nulledone** [comment]
As far as I see none of all, also if MX player can play it without ANY issues, why couldn't mpv though?

> Video
> ID                          : 1
> Format                      : HEVC
> Format/Info                 : High Efficiency Video Coding
> Format profile              : Main@L4@Main
> Codec ID                    : V_MPEGH/ISO/HEVC
> Duration                    : 43 min 37 s
> Bit rate                    : 807 kb/s
> Width                       : 1 920 pixels
> Height                      : 1 080 pixels
> Display aspect ratio        : 16:9
> Frame rate mode             : Constant
> Frame rate                  : 23.976 (24000/1001) FPS
> Color space                 : YUV
> Chroma subsampling          : 4:2:0
> Bit depth                   : 8 bits
> Bits/(Pixel*Frame)          : 0.016
> Stream size                 : 252 MiB (85%)
> Writing library             : x265 1.9+54-291beccb6760:[Windows][GCC 5.3.0][64 bit] 8bit+10bit+12bit
> Encoding settings           : wpp / ctu=64 / min-cu-size=8 / max-tu-size=32 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / rdpenalty=0 / no-tskip / no-tskip-fast / strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / no-temporal-layers / interlace=0 / keyint=250 / min-keyint=23 / scenecut=40 / rc-lookahead=20 / lookahead-slices=6 / bframes=4 / bframe-bias=0 / b-adapt=2 / ref=3 / limit-refs=3 / limit-modes / weightp / no-weightb / aq-mode=1 / qg-size=32 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=3 / psy-rd=2.00 / rdoq-level=0 / psy-rdoq=0.00 / no-rd-refine / signhide / deblock / sao / sao-non-deblock / b-pyramid / cutree / no-intra-refresh / rc=2 / pass / bitrate=806 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ipratio=1.40 / pbratio=1.30
> Default                     : Yes
> Forced                      : No

**Comment by sfan5** [comment]
Hm, that file should play fine.
Do you have the logcat output?

**Comment by nulledone** [comment]
> I/MaliEGL ( 5481): [Mali]window_type=1, is_framebuffer=0, errnum = 0
> I/MaliEGL ( 5481): [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
> I/MaliEGL ( 5481): [Mali]max_allowed_dequeued_buffers=3
> I/Timeline( 5481): Timeline: Activity_idle id: android.os.BinderProxy@37a10318 time:276364
> W/Resources( 5481): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f060000}
last line repeats like 30-40 times.

**Comment by sfan5** [comment]
without the full logcat output including mpv-android's output this won't be useful
