### ISSUE TITLE
Android TV video is capped at 1080p

### ISSUE THREAD

**Issue by hribeiro-net** [mpv-android/mpv-android#545]
### Important information

Android version: 11 (nvidia shield tv pro)
![image](https://user-images.githubusercontent.com/29986810/173904747-60b18f63-0bea-4a3b-b69e-c5b56e87dbbc.png)

mpv-android version: 2022-03-23-release
![image](https://user-images.githubusercontent.com/29986810/173905041-8996d828-a108-4b86-b7f9-f42d93ea0410.png)

### Description

MPV on the shield android tv seems to be capped at 1080p, even with video sources with higher resolution than that.
This is strange since the shield is configured to output a 4k resolution. I've attached some screen caps that illustrate the issue.
At first I though it was a configuration issue but I can't seem to find anything related to this on the menus. 
I've also tried to set up _window-scale=1_ and _autofit-larger=3840x2160_ with no better result, I'm not really sure what these do.

![image](https://user-images.githubusercontent.com/29986810/173905548-78f7e423-fcee-479e-bb38-f78f381f7369.png)

![image](https://user-images.githubusercontent.com/29986810/173905620-6554b08c-0164-4407-8a8a-22a5ae1c5c60.png)

I've also experienced this behavior on a Samsung S22+ device, dunno if it is related.
![image](https://user-images.githubusercontent.com/29986810/173906860-eaa09b84-ef62-4d48-a3e6-68435165c86c.png)

**Comment by sfan5** [comment]
The likely explanation here is https://github.com/mpv-android/mpv-android/issues/293#issuecomment-667973890, the manufacturer is "cheating" by rendering the system UI at a lower resolution. mpv is also bound by the limitations.

**Comment by hribeiro-net** [comment]
Ok thanks for the explanation, could this be considered a mpv-android limitation?

It feels very weird because apps like netflix and vlc do ouput 4k :/

Is there a workaround for this issue? or is there a fix planned for a latter release?

From another point of view, would android tv 12 fix this issue? Since its suposed to render the main ui in 4k. (although a official release for the shield won't come any time soon)

Cheers :)

**Comment by jan-kleks** [comment]
@sfan5 I have found this info in a Kodi thread about Android downscaling 4k: https://github.com/google/ExoPlayer/issues/6083#issuecomment-504982714

Could it be of any use?
