### ISSUE TITLE
Video player not extending across the screen (over the notch/camera cutout)

### ISSUE THREAD

**Issue by RafeeDaBoy** [mpv-android/mpv-android#548]
### Important information

Android version:
11
mpv-android version:
2022-03-23-release-oldapi

### Description

When playing back a local/url video the video player doesn't span across the screen. Rather it stays in it's original aspect ratio and can't be zoomed in to fill the whole screen on my phone which has a camera cutout and a display of resolution of 1080x2400 (20:9)

Current situation:

https://user-images.githubusercontent.com/69535896/175349124-b1963800-e86d-4f15-b1e0-a0f95d55f7d1.mp4

Expected behaviour:

https://user-images.githubusercontent.com/69535896/175349154-2e79bef1-b7c5-4ac7-92cb-a050b57af284.mp4

**Comment by sfan5** [comment]
I think the option you want is Pan-Scan (gesture) or `panscan=1.0` (mpv.conf) to set it by default.
I guess this could be made more easily discoverable.

**Comment by RafeeDaBoy** [comment]
It works now, thanks.
