### ISSUE TITLE
UTF encoding?

### ISSUE THREAD

**Issue by nulledone** [mpv-android/mpv-android#55]
I have yet to see some characters shown as squares. Any chance adding UTF-8 encoding in next releases?

**Comment by sfan5** [comment]
**Need a sample file**.
mpv has no problem with unicode subtitles/metadata and the included `Droid Sans Fallback Full` font should provide all the needed character coverage.

**Comment by nulledone** [comment]
I am unable to provide you a sample file but if you try to copy paste these characters into a subtitle you will probably see 'ı' 'İ' 'ş' 'Ş' 'ğ' 'Ğ'.

**Comment by sfan5** [comment]
Seems like those characters are missing from the included Droid Sans
<pre>
7-29 00:50:50.390 22611 22655 V mpv     : [sub/ass:v] Glyph 0x130 not found, selecting one more font for (Droid Sans, 400, 0)
07-29 00:50:50.390 22611 22655 V mpv     : [sub/ass:info] fontselect: Using default font: (Droid Sans, 400, 0) -> /data/user/0/is.xyz.mpv/files/subfont.ttf, 0, (none)
07-29 00:50:50.390 22611 22655 V mpv     : [sub/ass:v] fontselect: (Droid Sans, 400, 0) -> /data/user/0/is.xyz.mpv/files/subfont.ttf, 0, (none)
07-29 00:50:50.390 22611 22655 V mpv     : [sub/ass:v] Got a font face that already is available! Skipping.
07-29 00:50:50.390 22611 22655 V mpv     : [sub/ass:info] Glyph 0x130 not found, broken font? Trying all charmaps
07-29 00:50:50.390 22611 22655 V mpv     : [sub/ass:warn] Glyph 0x130 not found in font for (Droid Sans, 400, 0)
</pre>
sample file: http://0x0.st/kKJ.mkv

**Comment by nulledone** [comment]
Well seems like most german characters don't work too, "ö" "Ö" "ç" "Ç" etc.

**Comment by sfan5** [comment]
well this is interesting:
According to [lsfont](http://torinak.com/font/lsfont.html), Droid Sans includes `LATIN SMALL LETTER U WITH DIAERESIS` (U+00FC) but not `LATIN SMALL LETTER O WITH DIAERESIS` (U+00F6).
The respective uppercase chars (`Ä` `Ö` `Ü`) are missing entirely.

**Comment by sfan5** [comment]
I have merged `Droid Sans Regular` with `Droid Sans Fallback Full` to fix the missing glyphs.

Can you check whether the problem persists with this build of mpv-android?
https://kitsunemimi.pw/tmp/mpv-android-2017-07-29.apk

**Comment by nulledone** [comment]
It shows up, but wrong. 
Chars are "-şŞ öÖ çÇ ıİ ğĞ üÜ"
![screenshot](https://user-images.githubusercontent.com/29547468/28751450-9e3023b8-7510-11e7-8673-f90e29d329b1.png)

**Comment by sfan5** [comment]
That's an encoding issue with your subtitles then

![screenshot_20170730-120651](https://user-images.githubusercontent.com/1042418/28752446-dcc5be3a-751f-11e7-8793-579d3412a42b.png)
(sample file: http://0x0.st/kAC.mkv)

**Comment by nulledone** [comment]
Well my subtitles aren't hardcoded so that might be the reason I think? Could you try a file with this subtitle not hardcoded into. To do this you need to rename any video to match the subtitle file.
[test.zip](https://github.com/mpv-android/mpv-android/files/1188301/test.zip)

**Comment by sfan5** [comment]
Your subtitles are encoded as `ISO-8859-9`, but also happen to form valid UTF-8 sequences.
manually converting them to UTF-8 yields correct results:
![bildschirmfoto_2017-07-31_19-43-09](https://user-images.githubusercontent.com/1042418/28790243-9507921c-7628-11e7-8d56-c76a0793321a.png)

**Comment by nulledone** [comment]
So no way to force the app to use UTF-8 always?

**Comment by sfan5** [comment]
It is using `UTF-8`, but your subtitles are encoded in a different encoding (namely `ISO-8859-9`).
