### ISSUE TITLE
[Feature Request] Ability to stretch the image to full screen/fill the entire screen

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#550]
It would be great to be able to stretch the image to full screen (fill the entire screen) as it is, for example, implemented in VLC. Also, it would be wonderful to have a corresponding button on the panel itself, for hot change of the aspect ratio, because it is not very convenient to change every time in the settings item.

![1_1_GOT](https://user-images.githubusercontent.com/108337138/176161113-1cc0a560-75b1-44ce-8ffc-8f019dd3812e.png)

**Comment by sfan5** [comment]
this is already possible (but not very obvious), see #548

**Comment by SerggIvanenko** [comment]
> this is already possible (but not very obvious), see #548

Thanks, it works. But in the future, would be like to get a separate button for this (to switch between other aspect ratios).
