### ISSUE TITLE
[Feature Request] Add manual theme change mode

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#551]
For some reason, a light theme is used in the settings, although the theme in the system itself is set to dark (in the screenshots I saw that the dark theme is supported). Perhaps it would be better to add an appropriate menu item to force (manual) the selected mode, as it is implemented in other applications (theme mode: system; light; dark).

![2_1_GOT](https://user-images.githubusercontent.com/108337138/176161479-50a00b6a-fcfb-45c9-98be-65063ffd2698.png)

![2_2_GOT](https://user-images.githubusercontent.com/108337138/176161498-c8516ba6-68c4-4c74-b380-c4f2a74454c4.png)

**Comment by sfan5** [comment]
also requested in #265
