### ISSUE TITLE
[Feature Request] The file manager when it is not full screen, does not look very pleasant

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#553]
The file manager when selecting subtitles/alternate audio tracks, etc., when it is not full screen, does not look very pleasant, it may be better to use it in standard full screen mode (on top of the player).

![4_1_GOT](https://user-images.githubusercontent.com/108337138/176161911-d5cf8a10-c9f0-4ea3-a310-97609bbcced1.png)

**Comment by sfan5** [comment]
duplicate of #247
