### ISSUE TITLE
[Feature Request] Use one type of version numbering

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#557]
If allowed, I have the following remark, if the mobile version of the application is based on the desktop version, I think it would be logical to use one type of version numbering. If the current mobile version is based on version 0.34.1, then let the mobile version also be numbered as v0.34.1, because the current numbering of the build is not entirely logical in my opinion.

![2022-07-01_18-28](https://user-images.githubusercontent.com/108337138/176924599-986a238c-ec4d-47b9-a366-667a42f40dc7.png)

**Comment by sfan5** [comment]
mpv-android is released more often than mpv itself, it can't possibly use the same version numbers.
The app also uses varying versions of libmpv (see the [release page](https://github.com/mpv-android/mpv-android/releases)) so there is no relation to stable releases of mpv.

**Comment by SerggIvanenko** [comment]
> mpv-android is released more often than mpv itself, it can't possibly use the same version numbers. The app also uses varying versions of libmpv (see the [release page](https://github.com/mpv-android/mpv-android/releases)) so there is no relation to stable releases of mpv.

Okay, got it. Thanks for the answer.
