### ISSUE TITLE
Android TV touchups

### ISSUE THREAD

**Issue by pkly** [mpv-android/mpv-android#559]
Describe the wanted behaviour of the new feature and potential usecases for it here.

Currently the application is close to unusable on android TV. A lot of the options are inaccessible with a remote, the ui is obviously a phone ui and so on.

VLC for android (tv) has a pretty comfortable UI for all needs TV. (https://github.com/videolan/vlc-android) and is an open source project, maybe consider doing something similar?

SMB support would also be a great boon, as file managers on tv are rather... bad. While selecting files to play from them works with mpv it's not a great experience. VLC supports that out of the box.

### Additional information

MPV has better performance and does not suffer from the issues vlc does on android, so if possible I'd like to see it get better.

**Comment by sfan5** [comment]
I agree the UI is not well suited for TV usage but I tested it in the emulator and (almost) all parts should be reachable with the remote dpad. Can you give an example for one that isn't?

As for SMB support you can read #496 for some reasons why this isn't likely to happen.

**Comment by pkly** [comment]
There is a menu in the settings that creates a popup with some fields inside of it, those fields cannot be reached with the remote.
Obviously the UI as a whole is... not great for tvs. Which is horribly unfortunate since mpv is always my go-to.

That's a terrible shame, I do understand how annoying it is to implement things over and over instead of relying on internal apis to do some heavy lifting for the app, but it's pretty bad in this case lmao.

**Comment by sfan5** [comment]
Hmm indeed, the filter dialog doesn't work on TV at all.

**Comment by pkly** [comment]
also this is unrelated more or less, but I felt like making a new issue isn't entirely appropriate, since it still relates to ATV, but are there any plans to support atmos/vision/hdr10/+ formats?
I yearn for something that'll play that finally since nothing feels like doing it correctly it seems

**Comment by pkly** [comment]
I was looking around to see if I could maybe get Vision/Atmos to play nice and found something interesting.
On a known good video I launched with MPV that contained a eac3 track, I set audio-spdif=eac3 in the app settings - from that moment on the video would not play at all.
If I changed the audio track it'd start playing again, but no sound would play.
Video does play fine without the option, and does work fine (with atmos) in another player I've tried a while back on android (don't remember which one).

I also tried changing the audio output driver (ao) to pcm, but nothing.

**Comment by Pentaphon** [comment]
> As for SMB support you can read #496 for some reasons why this isn't likely to happen.

People can use mpv as an external player for https://github.com/nova-video-player/aos-AVP if they want an SMB UI for it. 

I do however also wish mpv were 100% Android TV friendly despite the lack of media center connectivity.

**Comment by pkly** [comment]
Since then I just use Kodi (modified, with DV/DA) and it's been pretty alright
