### ISSUE TITLE
ewa_lanczossharp scaling problems

### ISSUE THREAD

**Issue by nonaggressive** [mpv-android/mpv-android#560]
Setting the scaling to ewa_lanczossharp causes aliasing. It also does it severely to subs. When 
blend-subs=video is added to config.
I assumed this would be a good scaling option since I see it recommended for PC. If there is a better scaler for android please let me know. 
The aliasing is very noticeable on lines in animation. 
I've been trying jinc and ewa_lanczos these also look aliased.  It seems only bilinear and spline36 doesn't look terrible. 

Mpv Android 22-03-2022
Samsung Tab s7 
Snapdragon 865

**Comment by sfan5** [comment]
There's nothing wrong with `ewa_lanczos` except that it's pretty intensive on the GPU, the issues you're seeing are probably a driver or GPU bug (not unusual for mobile).

**Comment by TeoTotoro** [comment]
I have the same issue on my S7+. What scaling are you using now?
