### ISSUE TITLE
The item "Search by subtitles" is not centered

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#563]
When adding external subtitles, the "Search by subtitles" item appears in the settings menu, but it is not centered, unlike other items.

![1](https://user-images.githubusercontent.com/108337138/179365857-529f1afb-86da-4faf-8519-076d55fedf3d.png)

**Comment by sfan5** [comment]
It is centered correctly, it just appears to not be since the width differs from the other buttons:
![grafik](https://user-images.githubusercontent.com/1042418/179400663-cb3a825a-b679-4557-b343-04abdd0efd53.png)

**Comment by SerggIvanenko** [comment]
> It is centered correctly, it just appears to not be since the width differs from the other buttons: ![grafik](https://user-images.githubusercontent.com/1042418/179400663-cb3a825a-b679-4557-b343-04abdd0efd53.png)

It is not important in principle that these are buttons, they are displayed as just text without a frame; I don't see any problem if the width of these buttons will be the same as the others.
