### ISSUE TITLE
[Feature Request] Click on the total time to see how much time is left

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#564]
It would be great to be able to see how long the video will last when clicking on the video duration itself, like how it is implemented in the desktop version. It would also not hurt to add to the settings what to display by default, whether the duration of the video itself (the current variant), or whether to display the remaining time. Perhaps you can also add a third variant to display both options through a fraction (/).

![2](https://user-images.githubusercontent.com/108337138/179365900-08b22f61-934e-4b4b-a222-53b75d39837f.png)

**Comment by LesnikM4** [comment]
Feature has already been implemented. By clicking on the file time, it shows the remaining time of the file. This setting is saved when the application relaunched.

The remaining playback time does not take into account speed, as in the desktop version. Can this be added please?

desktop
![desktop](https://github.com/mpv-android/mpv-android/assets/43413219/28cdf240-bf8a-4758-b4af-13b0c4f99bd8)
phone
![phone](https://github.com/mpv-android/mpv-android/assets/43413219/5772f4c7-0590-4354-8260-1183f191e15a)
