### ISSUE TITLE
[Feature Request] Add an item to the settings menu "Show how many videos are currently in the cache"

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#565]
Add a corresponding item in the settings menu to display how much video (time) is cached (for streaming video), like how it is implemented in the desktop version.

![3](https://user-images.githubusercontent.com/108337138/179365946-934f6635-df81-4210-bbe0-83f186a4cbd6.png)

**Comment by sfan5** [comment]
already requested in #430
