### ISSUE TITLE
How to do something everytime there is a millisecond or frame change in the video position?

### ISSUE THREAD

**Issue by T-10001** [mpv-android/mpv-android#568]
The function
```
private fun eventPropertyUi(property: String, value: Long) { 
if (!activityIsForeground) return
        when (property) {
            "time-pos" -> {}
}
}
```
can only get the "time-pos" changes every second?

How to track every millisecond or frame change in video position and then do something?

**Comment by sfan5** [comment]
You can potentially change time-pos to be observed as a float or register the `tick` event. Both will be bad for performance.
