### ISSUE TITLE
Real random read for mp3 file in network stream

### ISSUE THREAD

**Issue by zyzhoull** [mpv-android/mpv-android#571]
Describe the wanted behaviour of the new feature and potential usecases for it here.

### Additional information

This product is amazing to me becasue it's almost the only app to open mp3 file with a internel cover phote exhibited which is very larger than the normal cover. 

I real appreciate your effort to expand mpv to android, hovever the biggest barrier for me to enjoy mpv-android is that it seems not support the random read mp3 file coming from network steam. I have tried many times and found when I open a mp3 file (webdav of my server, the android client is ES) , jumping the progress of mp3, then the mpv would took lot of times to download files containing the point I listen former to the point I jumped to, instead of just read the data at the point i jumped to. So I think it better to add a random read in mp3 file.

Thanks!

**Comment by sfan5** [comment]
FFmpeg already does this for HTTP URLs, if mpv is opened by a file manager this possibility does not exist.
