### ISSUE TITLE
External file picker won't show subtitles / lack of alternative

### ISSUE THREAD

**Issue by CptnLevi69** [mpv-android/mpv-android#573]
I was able to open external subtitles up until I updated the application to the latest version. 

It seems like the app does not recognize them for some reason.
Earlier it used to recognize all sorts of subtitle files but now it somehow isn't able to read those files.

I checked with .ass files and .mks files but got the same results.

Also I tried checking the app settings and my device app permissions but couldn't find anything that caused this problem.

P.S. ‐ I also did check if I was only getting filtered media files results but it was set to show all files and yet I couldn't see the subtitle file being recognized by the app.

**Comment by sfan5** [comment]
Can you be more specific as to whether you can't find the subtitles files in the file picker _or_ you can find them but they don't work when opened?

**Comment by CptnLevi69** [comment]
I can't find the sub files in the file ficker.

**Comment by CptnLevi69** [comment]
Tried the api29 build and it doesn't seem to have the issue so I suppose it's due to the restictions in the regular version that was causing the issue?

**Comment by sfan5** [comment]
In that case it's "normal" for this to happen. This is due to the Android's restrictions.
Alternative ways to get this to work are planned.
