### ISSUE TITLE
Playlist enchantment

### ISSUE THREAD

**Issue by Learner00100** [mpv-android/mpv-android#576]
Kindly include total time of playlist and remaining time in playlist, to display either in playlist window or in stats, it is great feature which is missing.

Also include rearrange (by long press on file name in playlist and move or by sliding file number in playlist)
And remove item in playlist option.

Don't know why this feature is still in stalled, #126  kindly implement in this feature, as it. Would be great.
Thank you.

**Comment by sfan5** [comment]
Time calculations on the playlist are not possible because mpv has no knowledge of the files before they're actually played.

Rearranging playlist items is already planned.

**Comment by Learner00100** [comment]
> Time calculations on the playlist are not possible because mpv has no knowledge of the files before they're actually played.
> 
> Rearranging playlist items is already planned.

Thanks for reply, as time calculation is not possible before file is opened.
Also m3u8 not have some Metadata.

But in pls playlist format which as additional information like total time of playlist and some other metadata too.
So displaying total time in pls playlist is possible?
