### ISSUE TITLE
Incorrect file names are displayed

### ISSUE THREAD

**Issue by CptnLevi69** [mpv-android/mpv-android#578]
In the latest version of mpv, instead of displaying the file name specified in the video file itself, it just shows a random number in place of the file name. 

Due to this, it's also really hard to organize/distinguish between screenshots as the screenshot file is just named as that number and not the file name.

**Comment by sfan5** [comment]
fundamentally the same issue as #542, see the explanations there
use the legacy file picker if it works for you.

**Comment by CptnLevi69** [comment]
Using the legacy file picker resolves the issue completely so I assume it has to do with how the document picker handles files?

**Comment by Ultra-Code** [comment]
How do you set the legacy file picker as the default? I am opening the video file from telegram and not directly from mpv.

**Comment by sfan5** [comment]
If you don't open the video from mpv-android's file picker this advice does not apply.

**Comment by Ultra-Code** [comment]
For my case is there any suggestion?

**Comment by BrendonIrwan** [comment]
Hi all. It appears to be fixed with the latest build. Tested and confirmed on two devices.
