### ISSUE TITLE
Remark on new changes in the graphical interface

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-android/mpv-android#579]
![8](https://user-images.githubusercontent.com/108337138/182126693-d5f66e9e-5155-4881-93e0-590105835ea2.png)

1* The icons are pressed to the very top with the text in the center, it looks terrible, is it so difficult to center the elements so that the interface at least has some appearance; The mpv icon itself looks fuzzy and blurry.

2* Despite the fact that support for the use of the system theme (light and dark options) has been added, the settings elements in the player itself, for some reason, use the light option, although the system theme is dark.

3* Chaotic use of colors again (the previous version is shown on the left). Why is it necessary to use purple everywhere, even where it is not legible at all (purple underline, purple blinking cursor)? White + purple + turquoise on a gray background, what kind of rainbow is this? Have you tried seeing/finding the cursor without straining your eyes? I understand that standard system panels are used, and the color of the inscriptions is standard for Android, but what the hell? If you are already making changes, it is so difficult to make a normal combination, and not so that you can just at least read it (use white/black inscriptions, depending on the theme of the interface itself, yes, it will look a bit flatly, but at least some combination of colors). It seems that you simply do not use the player, or you simply do not pay any attention to graphic design.

4* Centering problems again, yes, I remember that when viewing the panels/frames themselves, everything is centered and you closed the topic, but this does not change anything in the global plan, it looked skewed, and it still looks.

** One last annoyance I ran into, which is not entirely/not directly related to the design of the GUI, but related to the GUI itself, was that if you need to shift the audio track (add delay/acceleration), You need to go to the menu, then to the submenu (while the video is paused) and already there manually set the necessary value in the digital/numerical version, then return to the video, press play, and see if everything matches, and if not, then repeat the same procedure several times, which is not entirely convenient, until you achieve the desired result; It would be good to have some kind of slider when choosing the delay/acceleration on the player screen itself, so that you can choose the necessary option in real time when playing the video. vlc can be an ideal reference for all such moments of convenience of the graphical interface.

I understand that funding vlc and mpv projects are simply incomparable things (and for android, this is a completely different project), but to use vlc as a reference to gradually lay a convenient foundation for use (mpv has significantly fewer functions, compared to vlc, therefore, the work in general is slightly less), which can be laid little by little, this is not the worst option in my opinion, especially in those moments that are not difficult to implement.

**Nevertheless, I am still grateful to you for the work done.**

**Comment by matteocoder** [comment]
I have found another problem related to the new interface: if the main menu is viewed in landscape mode, the icons and labels are larger than the text boxes and are cut off, as you can see in this screenshot:

![mpv-android-landscape](https://user-images.githubusercontent.com/22897138/183290084-e31c92aa-f8d3-43f2-8715-a64c5d7538fb.png)

**Comment by n-buna404** [comment]
Another issue about this graphical interface is after finishing playing a file. It would go back to this interface instead of the original folder that I navigated to, so I had to renavigate from interface to the files in same folder. Though it could be avoid by using a file manager to open the file instead of mpv android

**Comment by sfan5** [comment]
> 1* The icons are pressed to the very top with the text in the center, it looks terrible, is it so difficult to center the elements so that the interface at least has some appearance

Yes it is "too difficult". If it's easy for you (have you ever done Android development?) then by all means do it yourself and send a pull request.

> 2* Despite the fact that support for the use of the system theme (light and dark options) has been added

I don't remember adding system theme support, you must have imagined it. The player theme is and remains light.

> 3* Chaotic use of colors again (the previous version is shown on the left). Why is it necessary [...]? [...], what kind of rainbow is this? Have you tried seeing/finding the cursor without straining your eyes? [...] what the hell? It seems that you simply do not use the player, or you simply do not pay any attention to graphic design.

Despite what you seem to think I am not blind or ignorant. The coloring issue was fixed in exactly this version.
If you still have it then I don't know where the dialogue is and/or it does not happen on any of my test devices.

> Nevertheless, I am still grateful to you for the work done.

Spare your empty words.
