### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [mpv-android/mpv-android#580]
### Important information

Android version:

mpv-android version:

Which version of mpv-android introduced the problem (if known):

### Description

The freetype2 introduced [a change](https://gitlab.freedesktop.org/freetype/freetype/-/commit/0d34386366c93835501e98d643586eb32dbda1fa) in 2-12-0 which breaks backward-compatiblity. Before this change if zlib is not found it will be disabled. But after the change the `auto` is used by default. When zlib is not found it fallbacks to external which tries to download the zlib. But `wrap_mode = 'nodownload'` is set so the build failed. The zlib is installed but I thought it doesn't work for cross-compilation.

Could you please take a look? Thanks!

### Log output
```
Run-time dependency zlib found: NO (tried pkgconfig and cmake)
meson.build:298:2: ERROR: Automatic wrap-based subproject downloading is disabled
```

**Comment by sfan5** [comment]
zlib is part of the ndk:
<pre>
% find android-ndk-r25 -name 'libz.a' 
android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a
android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/libz.a
android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/libz.a
android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libz.a
</pre>

IIRC meson has had issues with detecting it in the past, so make sure you have an up-to-date version.
If that doesn't work then you can work around it by manually creating a pkgconfig file for zlib.

**Comment by linsui** [comment]
We are using python 3.5 on debian stretch. I build python 3.9 and it works. Thanks!

**Comment by eli-schwartz** [comment]
The version of Python should not matter though... what does matter is that Meson since 0.61.0 checks for an android NDK zlib even without a pkg-config file, but mpv supports Meson 0.60.0 as well.

**Comment by linsui** [comment]
> NOTICE: You are using Python 3.5 which is EOL. Starting with v0.57, Meson will require Python 3.6 or newer

I have to update Python to use newer meson...
