### ISSUE TITLE
What settings "Low-quality video decoding" does it look like to configure mpv.conf?

### ISSUE THREAD

**Issue by samqplays** [mpv-android/mpv-android#582]
I was trying to find out what settings "Low-quality video decoding" does it look like to configure this setting for `mpv.conf`. So I will use this settings for my low-powered devices such as mobile phones and chromebook (crostini) to play efficiently with SW decode only.
![image](https://user-images.githubusercontent.com/80607823/182738820-db69d1be-202c-4704-abcd-7ca0a7dfc283.png)

I find everything in the manual page, and some comments in the community, not on GitHub, seems can't find the result. 
This setting is helpful for me when playing the video, even low-quality that works with SW decode on every format.

### Additional information
_no response_

**Comment by sfan5** [comment]
Enabling the checkbox will configure the following settings automatically:

https://github.com/mpv-android/mpv-android/blob/44627be4df089f7c692759bd38db7d879451d32f/app/src/main/java/is/xyz/mpv/MPVView.kt#L98-L101
