### ISSUE TITLE
Lua file Permission denied error in 2022-07-30 build

### ISSUE THREAD

**Issue by superuser789** [mpv-android/mpv-android#585]
I tried the latest [2022-07-30 Build](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2022-07-30). mpv settings menu is visible on both the devices. But, it does not load lua scripts and shows 'Permissioon denied error' when I press ` key to check its console. How do I make it access lua files ?

Thanks.

**Comment by sfan5** [comment]
Please don't mix multiple issues in one report, this makes it hard to keep track.

> But, it does not load lua scripts and shows 'Permissioon denied error'

The new storage changes only apply to opening files via the file picker.
Lua scripts are still impacted and stopped working due to Android's restrictions, you can use the `api29` build in the meantime.
