### ISSUE TITLE
support more options from intent extras

### ISSUE THREAD

**Issue by pepeloni-away** [mpv-android/mpv-android#587]
The ability to set media title is useful when opening urls, both VLC and MX player support this
VLC wiki reference: https://wiki.videolan.org/Android_Player_Intents/#Extras_.28optional.29

Being able to pass some common headers (like -referrer and -user-agent options in mpv) in the same way as title would also be great. I know you can set them in mpv.conf in the current state of the app but it is annoying to have to open settings and change refferer manually.

**Comment by sfan5** [comment]
Closing this as a duplicate of #427.
I have plans to implement at least media title, user agent and referrer.
