### ISSUE TITLE
Support for opening a directory (creating a queue)

### ISSUE THREAD

**Issue by TheChymera** [mpv-android/mpv-android#59]
In mpv I can run `mpv /path/to/my_dir` , where `my_dir` contains a bunch of media files - whereby mpv will play theme as a queue. I have not been able to obtain this functionality on Android. Is it supported?

**Comment by sfan5** [comment]
directories can now be opened as "queue" (playlist) by long-pressing them in the file picker
a71c7b78b2ff5e3b2081e7d944eda60c456d1d9f
