### ISSUE TITLE
Video jump to later time when launching app switcher

### ISSUE THREAD

**Issue by goduck777** [mpv-android/mpv-android#591]
### Important information

Android version: 12

mpv-android version: 2022-07-30-release

### Description

I am trying to play a mkv file remotely (through http server). The video plays well on first open. However, when I turn on the app switcher on Android, the video suddenly jump to a later time, and it does not recover when I switch back to mpv.

I tried to turn on the option to keep the video playing when switching app, but the issue still persist. VLC does not have this issue.

It seems that it always jump to the time at the end of the buffer. I can try to turn off the buffer, but it is not an ideal solution.

**Comment by sfan5** [comment]
likely closely related to #239

**Comment by sfan5** [comment]
Okay yeah I'll just close this as a duplicate.
