### ISSUE TITLE
Issues with buildall.sh on Windows / WSL2 Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by gitlzq** [mpv-android/mpv-android#592]
Everything is ready, but the problem still occured.How should i solve the problem？
gcc and g++ seem to be working well.

root@PC-MiniSnk:/home/lzq/env/buildscript# ./buildall.sh
Preparing mpv-android...
Dependencies: mpv
Preparing mpv...
Dependencies: ffmpeg libass lua
Preparing ffmpeg...
Dependencies: mbedtls dav1d
Preparing mbedtls...
Dependencies:
Building mbedtls...
/home/lzq/env/buildscript/deps/mbedtls /home/lzq/env/buildscript
  CC    aes.c
  CC    src/helpers.c
  CC    aesni.c
  CC    src/asn1_helpers.c
  CC    arc4.c
  CC    src/psa_crypto_helpers.c
  CC    aria.c
  CC    src/psa_exercise_key.c
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
make[1]: *** [Makefile:103: src/helpers.o] Error 126
make[1]: *** Waiting for unfinished jobs....
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
make[1]: *** [Makefile:283: aes.o] Error 126
  CC    asn1parse.c
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:103: src/asn1_helpers.o] Error 126
make[1]: *** [Makefile:283: aesni.o] Error 126
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
make[1]: *** [Makefile:103: src/psa_crypto_helpers.o] Error 126
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
make[1]: *** [Makefile:284: arc4.o] Error 126
make[1]: *** [Makefile:103: src/psa_exercise_key.o] Error 126
make[1]: *** [Makefile:284: aria.o] Error 126
make: *** [Makefile:23: mbedtls_test] Error 2
make: *** Waiting for unfinished jobs....
/home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang: line 4: /home/lzq/env/buildscript/sdk/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
make[1]: *** [Makefile:284: asn1parse.o] Error 126
make: *** [Makefile:17: lib] Error 2
root@PC-MiniSnk:/home/lzq/env/buildscript# gcc
gcc: fatal error: no input files
compilation terminated.
root@PC-MiniSnk:/home/lzq/env/buildscript# g++
g++: fatal error: no input files
compilation terminated.
root@PC-MiniSnk:/home/lzq/env/buildscript# meson

ERROR: Must specify at least one directory name.
root@PC-MiniSnk:/home/lzq/env/buildscript# meson -v
0.63.1

**Comment by sfan5** [comment]
Your build environment is 32-bit and also the paths cannot possibly be correct (you moved or renamed files).
