### ISSUE TITLE
New homepage unusable with TV remote (Android 6)

### ISSUE THREAD

**Issue by KaKi87** [mpv-android/mpv-android#593]
### Important information

Android version: 6.0.1

mpv-android version: 2022 07 30 / 29

Which version of mpv-android introduced the problem (if known): -

### Description

The new homepage is unusable with a TV remote, while the old one fully was.

### Log output

Seems unnecessary, also I wouldn't be able to, anyway.

### Additional information

Although "file picker (legacy)" can still be set as default homepage and works just like it used to, settings still can't be accessed with a TV remote.

---
Thanks

**Comment by sfan5** [comment]
I tested the redesign in the emulator for Android TV with Android 11 or so and it worked fine.

**Comment by KaKi87** [comment]
I don't know what to say.

Before the redesign, I could browse files with up/down arrow buttons and access settings using the *menu* button and browse options with up/down arrow buttons.

Since the redesign, I must use a mouse (or mouse simulator) to click "file picker (legacy)" or "settings" and then be able to browse using up/down arrow buttons.

I'm not running Android 11 though.

**Comment by Quackdoc** [comment]
various remotes report their buttons differently, some report similar to a gamepad, some report like keyboard arrow keys, and some report like keypad arrow keys. all of the above work for me on android 10. 
I just tested arrow keys, numberpad keys ps4 dpad and xbox one dpad

there is an app called key event display (it's open source if you would rather compile yourself) on google playstore you can use to get the keycodes that the remote uses. it might be that the remote uses something unique

**Comment by sfan5** [comment]
To add to this: mpv-android only implements its own key handling inside the player, everything else relies on Android handling GUI interactions as it normally does.

**Comment by KaKi87** [comment]
> there is an app called key event display [...] you can use to get the keycodes that the remote uses. it might be that the remote uses something unique

I installed the app, then pressed up/right/down/left, each press generated two lines.

![](https://i.goopics.net/v4ht58.jpg)

> mpv-android only implements its own key handling inside the player, everything else relies on Android handling GUI interactions as it normally does.

Well, as I said, I can navigate properly once "file picker (legacy)" is opened, but I need a mouse to open it.

**Comment by moneytoo** [comment]
To my knowledge the SAF file picker (DocumentsUI) doesn't really work with navigation keys on any Android device, as well as Android TV devices supporting SAF (basically only [nVidia Shield](https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/494556/storage-access-framework-picker-ui-doesnt-work-wit/?topicPage=2)).

**Comment by KaKi87** [comment]
I know, but that's not my problem.

My problem is about selecting any of those :

![](https://cdn.discordapp.com/attachments/723185786794803252/1019990831031140452/PXL_20220915_171907622.NIGHT.jpg)

I just can't do it using arrow buttons.

So, I'm forced to use a mouse :

![](https://cdn.discordapp.com/attachments/723185786794803252/1019991441868607568/PXL_20220915_172003081.NIGHT.jpg)

Then, I'm able to get here :

![](https://cdn.discordapp.com/attachments/723185786794803252/1019991442292211802/PXL_20220915_172124677.NIGHT.jpg)

From there, arrow buttons work fine, just like they used to.

I hope it's clear this time.

Thanks

**Comment by Quackdoc** [comment]
your buttons properly correlate to keyboard "arrow keys". im not sure if I have any android 6.0 devices, but I can see if I can find one.

**Comment by sfan5** [comment]
Tested this today in the Android emulator with 6.0, no issues controlling the homepage with the directional pad.
