### ISSUE TITLE
Settings do not take effect after updating to Android 12

### ISSUE THREAD

**Issue by h0ld0** [mpv-android/mpv-android#599]
Android version: Android 12

mpv-android version:
2022-7-30-release

Which version of mpv-android introduced the problem (if known):
2022-7-30-release

Description
After updating my Galaxy a12 to android 12, settings like remember choice on next startup, save position on quit, display media title, and perhaps a couple more doesn't take effect. it may be caused by a tightened security update on the OS. reinstalled and cleared cache/data yields no difference.

**Comment by sfan5** [comment]
But you can see the values you set in the settings? And if you set them again it makes no difference?

**Comment by h0ld0** [comment]
> But you can see the values you set in the settings? And if you set them again it makes no difference?

yes. they're toggled on, but it doesn't seem to take effect. also, the UI randomly generates 3 digits as their media title when set to display their file names. 

![Screenshot_20220914-211102_mpv](https://user-images.githubusercontent.com/113484063/190163397-9818ab5b-92de-4a27-9d96-880ce48b1f5c.jpg)
![Screenshot_20220914-210735_mpv](https://user-images.githubusercontent.com/113484063/190163413-aecbe0d1-c321-4a3e-a916-42f370730644.jpg)

**Comment by YanceyChiew** [comment]
I believe this is related to issue #542. When the current version of mpv-android opens a content uri, what is passed to libmpv is just a file descriptor, or put another way, a number that has nothing to do with the filename. So, of course all settings related to filename or path will be invalid.

**Comment by sfan5** [comment]
> yes. they're toggled on, but it doesn't seem to take effect.

In your screenshots it's clearly showing that the "show media title" option is taking effect. This doesn't fit with your bug report.
