### ISSUE TITLE
After Video Goes Back To Root 

### ISSUE THREAD

**Issue by AwkwardOne** [mpv-android/mpv-android#600]
### Important information

Android version:Android TV 10

mpv-android version:2022/07/30 release oldapi 29

Which version of mpv-android introduced the problem (if known):

### Description

Describe your issue in detail here.
I'm using an external SSD with videos on it, whenever a video finishes or I hit back in sent all the way back to the root of the internal storage instead of just going back to the folder the video was in.
If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s 'mpv:*' '*:F'

You can attach text files on Github directly or use sites like https://0x0.st/ to upload your logs.
Depending on the nature of the bug, a log file might not be required and you can *omit this section*. If in doubt provide one, it will help us find possible

**Comment by sfan5** [comment]
Already fixed.
