### ISSUE TITLE
how to get the lowest quality to improve performance on old phone

### ISSUE THREAD

**Issue by emacs25** [mpv-android/mpv-android#606]
i use mpv-android on old phone and it is the best choice to play with software decode.

so i want to know the lowest quality options which can be added into mpv.conf file

i have found a similar issue,#582, but it seems not very helpful in mpv.conf.
```
video_fastdecode, false
vd-lavc-fast, yes
vd-lavc-skiploopfilter, nonkey
```
can anyone give me some advice please?

### Additional information

nothing more

**Comment by sfan5** [comment]
You can simply enable "low-quality video decoding" in the settings and it will apply the right config.

**Comment by emacs25** [comment]
i won't send issue if i do that.

i just want to know the exact options of low quality,and maybe i should read mpv manual instead.

**Comment by sfan5** [comment]
The options are called `vd-lavc-fast` and `vd-lavc-skiploopfilter`, you can look them up in the mpv manual.

**Comment by emacs25** [comment]
thanks for your advice.

by the way,does a video get the same performance when using mpv-android and mpv-x both with software decode?
