### ISSUE TITLE
Problem with subtitle rendering!??

### ISSUE THREAD

**Issue by CptnLevi69** [mpv-android/mpv-android#607]
mpv version -  2022-07-30 release (api29)

So, I loaded external subtitles for a video file but the subs look far from what they actually should look  like.

How the subs should look:--

![c0HkJ2P9.jpg](https://user-images.githubusercontent.com/100019341/194206989-3590b6e1-e35e-4ede-8114-c11230e4044d.jpg)

![[Arrow] Mob Psycho 100 II - OVA (BD 1080p) [B98444BA]-683.474.png](https://user-images.githubusercontent.com/100019341/194208152-50ed0b5f-8a8e-4951-be97-a924cfb5e1ea.png)

How the subs actually look:--

![Mob Psycho 100 - OVA-164.797.png](https://user-images.githubusercontent.com/100019341/194206765-db36c027-d2c2-48f9-8b47-15eb3fd56a0b.png)

![Mob Psycho 100 - OVA-683.106.png](https://user-images.githubusercontent.com/100019341/194208249-85f84505-7e34-4c64-986e-5966fa54b60f.png)

I don't know if it's a problem with the sub file or with the player itself. In either case, any help will be appreciated.

**Comment by sfan5** [comment]
A subtitle file only contains the text and formatting, what you are missing here are the fonts.
The way this usually works is that the font files are muxed into the .mkv file which mpv will pick up automatically. Of course if you use external subs this won't be the case.
