### ISSUE TITLE
Interpolation not working ?

### ISSUE THREAD

**Issue by dcmaxl** [mpv-android/mpv-android#608]
my device is note20u, latest version of mpv. Interpolation was turned on with display-resample, but the fps of video was still 23.976, how to make Interpolation work? anymore guide of setting? thanks!

**Comment by sfan5** [comment]
what do you mean fps is still 23.976? how do you tell?

**Comment by dcmaxl** [comment]
i've turn on FPS counter in developer>show stats>, the counter stats shows  fps is 23.976. it is the same with the frame rate of oringal video, does it  mean that Interpolation is not working?

**Comment by sfan5** [comment]
"FPS" shows the original fps of the file.
Check the "VSync Ratio" to confirm that display sync is working. Interpolation can be seen in the frame timings on stats page 2 if enabled.
