### ISSUE TITLE
Open-Url dialog  should remember last / latest URLs

### ISSUE THREAD

**Issue by DirkSchmitt** [mpv-android/mpv-android#612]
It would be nice if the Open-Url dialogue can remember at least the last entered URL.

Alternatively a favourite list of  URLs would be nice.

### Additional information

My use case is to use mpv-android as sink for a *mpd* based audio stream.
In the current UI i have to enter the url every time. 
This can be very annoying if e.g. the streaming stopped due to bad WiFi connection

**Comment by sfan5** [comment]
This is on my TODO list, also some has requested this before: #188
