### ISSUE TITLE
Implement Sort by Date in Subtitle File Picker

### ISSUE THREAD

**Issue by Fmoment1** [mpv-android/mpv-android#615]
As of now, if we want to load an external subtitle, we have to go to the folder where that subtitle is and select it. The problem is, the list is always sorted alphabetically, so it can be a little annoying to find the subtitle if it's all the way down. Could there be a "sort by date" or "sort by recent" option where it shows the most recently downloaded/modified files at the top? I think picking subtitles would be easier this way. You could also implement this for the entire file picker as a whole.

### Additional information

Android version: 11
mpv-android version: 2022-07-30 release

**Comment by qgustavor** [comment]
Is it still needed after this? ["Can now use native file dialog to load external subtitle or audio"](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2023-02-27)

**Comment by sfan5** [comment]
Not really.
