### ISSUE TITLE
mpv-android's Strange behavior for the same site URLs

### ISSUE THREAD

**Issue by gsool9988** [mpv-android/mpv-android#618]
I installed mpv-android to my android tv, which brand is "Tivo Stream 4K".
I tested mpv-android for m3u file in which many IPTV urls are included.
Generally mpv-android works well, but I found a strange behavior of mpv-android for same site URLs.
Below urls are examples for you. **The first url only works in mpv-android**, but **exoplayer**(embeded in LiveChannels+TVirl ) works for all urls of this example.  
https://kr-streams.onrender.com/scraper?channel=283
https://kr-streams.onrender.com/scraper?channel=407
https://kr-streams.onrender.com/scraper?channel=449
https://kr-streams.onrender.com/scraper?channel=921
https://kr-streams.onrender.com/scraper?channel=923
https://kr-streams.onrender.com/scraper?channel=925

### Why did this strange behavior be occurred in mpv-android for same site urls ? How can I fix this and make it works for all urls of same site ?
Of course, **mpv cli** in ubuntu20.04 works well for all urls of this example. It seems make use of ffmpeg rather than youtube-dl.
`mpv 'url'`

mpv-android version: latest version(2022.7.30)
android tv : android 10

**Comment by rozari0** [comment]
Check #58 .

**Comment by sfan5** [comment]
I tested this and mbedtls sometimes fails to verify the certificate, not sure what's going on and I couldn't reproduce the problem outside of mpv.
