### ISSUE TITLE
Don't reset video position on screen lock

### ISSUE THREAD

**Issue by msxmine** [mpv-android/mpv-android#62]
Currently when the screen is turned off while a video is playing, if it is turned on again mpv-android seems to quit. If it is called again from the multitasking card view, the video starts playing from begining.
It would be good to not quit the app on screen off (It returns me to launcher/home screen), and maybe even remember the last position on all played files, so that they can be resumed from this point in the future, even if the app quits/is killed by android memory management

**Comment by wiiaboo** [comment]
+1'ing this issue+request.

Would make mpv-android a great toilet time player for long videos.

**Comment by ajyotirmay** [comment]
mpv-android is good, but with this feature enhancement it will be better. Please consider implementing this :)

**Comment by sfan5** [comment]
9272cc7049f0edbd123b528edfbc87a56d85fd7b prevents video pos resetting during a simple screen lock
However Android is still allowed to kill mpv due to e.g. memory pressure, ideally [these](https://developer.android.com/guide/topics/resources/runtime-changes.html) should be implemented.

**Comment by sfan5** [comment]
Saving video progress on quit is now possible by editing mpv.conf directly.
As noted in my previous comment, mpv might still lose the current position when Android kills it.

**Comment by ajyotirmay** [comment]
@sfan5 what is the location of the config file?

**Comment by sfan5** [comment]
`Settings` > `Advanced` > `Edit mpv.conf`

**Comment by ajyotirmay** [comment]
Thanks, that worked. Is there a way to force `software decoding`?

**Comment by ajyotirmay** [comment]
Using `save-position-on-quit` flag, and switching between applications makes mpv use `hw decoding` by default, and there is no video, it's just the audio that's played.

**Comment by sfan5** [comment]
Video position should not reset when switching apps/locking the screen anymore.
Additionally "Save position on quit" is not properly implemented.

**Comment by KaKi87** [comment]
Hello,

How to enable this feature **exactly** ?

I got to `Settings` > `Advanced` > `Edit mpv.conf` then I tried adding a new line containing `save-position-on-quit` or `save-position-on-quit=true` or `save-position-on-quit=1` but none worked.

Thanks
