### ISSUE TITLE
Hope to support the function of casting screen.

### ISSUE THREAD

**Issue by SONGjiemo** [mpv-android/mpv-android#621]
I use it on TV TV, and it feels very easy to use. 
So I want to have a DLNA screen function, that is, the mobile phone is projected to the TV TV.

### Additional information
Function description: 
After MPV has developed the DLNA function, if the DLNA function is enabled, the mobile device can scan to the DLNA device to cast the screen.

**Comment by sfan5** [comment]
This will never be supported.
