### ISSUE TITLE
External subtitles aren't loaded at all, when starting mpv via "Open with" intent (v2022-07-30).

### ISSUE THREAD

**Issue by DanielKonopka** [mpv-android/mpv-android#625]
### Important information

Android version: 10

mpv-android version: 2022-07-30

### Description

Subtitles aren't loaded when media is played via "Open with" intent or default filetype association. I have tried Total Commander (com.ghisler.android.TotalCommander) and Simple Gallery Pro (com.simplemobiletools.gallery.pro). The issue is there in both cases. The only app that allows to invoke mpv playback straight from it (with subtitles loaded properly), is Huawei's file manager (com.huawei.hidisk).

**Comment by sfan5** [comment]
Known limitation, not really fixable (would have to teach libmpv about lots of Android-specific APIs, since Google decided direct file access is evil).
