### ISSUE TITLE
Autoplay local movie file on app startup

### ISSUE THREAD

**Issue by masmu** [mpv-android/mpv-android#626]
I am trying to make mpv-android play a certain mp4 file on application startup without the user to manually select the video file.
The video file is suppose to be on the phone at any location not requiring root. The goal is not to do a single click after launching the app.

The application which is suppose to start mpv (a kiosk like app) is hosting a webview which can either
- start an android activity directly (no support for intents) or
- embed a customizable HTTP link

So, I tried various ways to far.

- editing `mpv.conf` and added `external-file=/path/to/file.mp4` config option
The idea is that the kiosk application just starts the activity and mpv plays the file on startup since we configured it via `mpv.conf` to do so.

- using an android intent link
so that android starts mpv and passes on the URI to the local file.
Like:
```html
<a href="intent://file:///storage/emulated/0/Download/loop.mp4#Intent;type=video/any;package=is.xyz.mpv;scheme=file;end;">loop video</a>
```

I tried dozens of path combination but nothing worked for neither of those 2 ways. I guess my attempt on passing a local path is part of the problem, because since android API 24 dealing with "file://" or "/" seems to be out of fashion.

Maybe someone can point me in the right direction here.

**Comment by sfan5** [comment]
The correct HTML is
```html
<a href="intent:///storage/emulated/0/Download/loop.mp4#Intent;type=video/any;package=is.xyz.mpv;scheme=file;end;">loop video</a>
```
but chances are that file is not allowed anyway.

If your kiosk app does not support intents then in my opinion that is something it should fix.

**Comment by dbojan** [comment]
I would like to play web url on startup. Similar to this request.
Perhaps some option could be added to mpv.conf, like play-on-startup=https://www...
On starting popup would show: starting https://www in 3 seconds, click on cancel to stop. 

So people can edit option if there is some problem.
Thanks.
