### ISSUE TITLE
Subtitle isn't showing 

### ISSUE THREAD

**Issue by Swadhin05** [mpv-android/mpv-android#629]
### Important information

Android version: Android 10

mpv-android version:
2022-07-30-release / 29 (release)

### Description

This is a SRT subtitle file
Secondary texts are showing but the main dialogues are missing.
Sorry I couldn't explain it better hope you get it

### Additional information

Mpv:
![Screenshot_2022-12-16-19-21-37-688_is xyz mpv](https://user-images.githubusercontent.com/105983671/208115633-60af562b-3fe6-48ef-8f23-48f11da1d86e.jpg)

MX player:
![Screenshot_2022-12-16-19-20-33-903_com mxtech videoplayer ad](https://user-images.githubusercontent.com/105983671/208116173-7f3170a0-bdd2-4f1b-bfec-0af819b5f8cb.jpg)

**Comment by sfan5** [comment]
Need the subtitle file to debug this in any way.

**Comment by Swadhin05** [comment]
That subtitle file is weird. I use an external subtitle and it works fine
