### ISSUE TITLE
Videos not playing well - nokia box 8010

### ISSUE THREAD

**Issue by AwkwardOne** [mpv-android/mpv-android#636]
So today I upgraded from the nokia streaming box 8000 to the 8010. On the 8000 I could run videos fine besides the 265x hevc videos. This is the difference between the 8010 and 8000, the newer one does support these formats.
When I tried to play a video in mpv on the 8010, it has massive slowdown and sometimes even a slideshow. When playing a 265x videomit looksmlike the image below.

[![16718118863518475044572842670720.jpg](https://i.postimg.cc/KcKdrBHL/16718118863518475044572842670720.jpg)](https://postimg.cc/DmTj7JFy)
Im using latest version of mpv on Google play store.

**Comment by sfan5** [comment]
No issue template - no help.
