### ISSUE TITLE
Number keys in keypad (`KP*`) unable to be triggered via `input.conf` (?)

### ISSUE THREAD

**Issue by kuanyui** [mpv-android/mpv-android#648]
# Important information

Android version:  `13`

mpv-android version: `2022-07-30-release / 29 (release)` (from Google Play)

Which version of mpv-android introduced the problem (if known): N/A

# Description
## `input.conf` + keyboard without number pad
I gladly and suddenly found `mpv-android` can custom `input.conf`. I did some tests on my existed Bluetooth keyboard [Logitech K380](https://www.logitech.com/en-us/products/keyboards/k380-mac-multi-device-keyboard.920-009729.html) and confirmed the number keys can be used in the `input.conf` of `mpv-android`:

![Screenshot_20230121_233902](https://user-images.githubusercontent.com/1370070/213874521-4e5d5596-8901-498c-ab15-83d1b51703a0.png)

## `input.conf` + number pad keyboard
Therefore, I bought a Bluetooth [Microsoft Number Pad](https://support.microsoft.com/en-us/topic/use-microsoft-number-pad-ddc5eb8b-1368-fadf-dc5d-92e0bde0a745) and meant to make it as a remote controller for `mpv-android`: 

![image](https://user-images.githubusercontent.com/1370070/213874227-c4076353-a68d-4219-8541-6b2ad3618304.png)

I wrote my `input.conf` like this for this  `Microsoft Number Pad`:

```conf
KP1 playlist-prev
KP2 cycle pause
KP3 playlist-next
KP4 seek -5
KP5 ab-loop
KP6 seek  5
KP7 multiply speed 1/1.1
KP8 set speed 1.0
KP9 multiply speed 1.1
* seek 5   # Works on Android
/ seek -5   # Works on Android
```

I tested this on Linux desktop and all keys works. 

Unfortunately, `KP*` has no response on `mpv-android`, while `*` and `/` works both on Linux and `mpv-android`.

# Log output

After struggling for 30 minutes I still didn't find any logs about key-pressed, so omitted.

# Additional information
1. I've tested this `Microsoft Number Pad` and it indeed can input numbers on this Android device.
2. I know there's an option `--input-test` for `mpv` on Linux desktop, but I don't know if there's any way to enable this on `mpv-android`.

**Comment by sfan5** [comment]
I tested this with an USB keyboard and it worked fine regardless of numlock state, here's a logcat excerpt:
<pre>
01-22 11:07:34.748 30738 30738 D mpv     : Unmapped non-printable key 143
01-22 11:07:34.793 30738 30738 D mpv     : Unmapped non-printable key 143
01-22 11:07:40.963 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP2'.
01-22 11:07:41.714 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP4'.
01-22 11:07:41.962 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP7'.
01-22 11:07:42.187 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP8'.
01-22 11:07:42.418 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP5'.
01-22 11:07:42.666 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP2'.
01-22 11:07:42.881 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP3'.
01-22 11:07:43.122 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP6'.
01-22 11:07:43.338 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP9'.
01-22 11:07:43.593 30738 31857 V mpv     : [input:warn] No key binding found for key 'KP7'.
01-22 11:07:44.067 30738 30738 D mpv     : Unmapped non-printable key 143
01-22 11:07:44.106 30738 30738 D mpv     : Unmapped non-printable key 143
01-22 11:07:45.355 30738 30738 D mpv     : Unmapped non-printable key 143
01-22 11:07:45.392 30738 30738 D mpv     : Unmapped non-printable key 143
01-22 11:07:46.723 30738 30738 D mpv     : Unmapped non-printable key 143
</pre>
(143 is just the NumLock being toggled)

**Comment by kuanyui** [comment]
I know this sounds bizarre and even ridiculous.... But I just casually removed the battery of this Microsoft Number Pad and place it back again, then saw your reply, so I test again, now two of my Android 13 devices + `mpv-android` become able to recognize `KP*` keys, and `adb logcat` can also show logs of `KP*` ... (These 2 Android 13 devices really could not recognize `KP*` key event before this... Totally don't know what's wrong with it...)

I have no USB-C to USB-A adapter so cannot test a USB keyboard before.

After all, sorry for wasting your time and thanks for your reply!
