### ISSUE TITLE
Seamless loop video is no more (since 2018-04-29)

### ISSUE THREAD

**Issue by sombresu** [mpv-android/mpv-android#656]
### Important information

Android version: 
Android 12 
MIUI 13.0.5

mpv-android version: 
2022-07-30-release

Which version of mpv-android introduced the problem (if known):
Since a couple of updates ago

### Description

I have videos in which they should be played on infinite loop.  Whenever I play them, at the end there's always a milliseconds pause before continue looping. 

Mpv-android had been the ONLY video player for android which had seamless loop. Now it just like any other video player. I've been using mpv on windows since ancient time and it has been very seamless experience and the only video player I use. 

Edit: 
I tried installing old released one by one and it still the same, no seamless loop. Is it caused by android update?! But I was using android 11 before and it's the same. 

I still remember how long ago when there's no pause between loop. 

Edit2:
I remember now, I was using this version the last time. Version 2018-04-29 test build is the last version to have perfect seamless loop. 

Edit3:
Now that I'm using the test build version above, I need help for changing orientation through mpv.config. 

Edit4:
I've been trying to tweak the config to rotate the video to make it portrait using "video-rotate=270" but this looks wrong. 

https://imgbox.com/JbW1Y5er

**Comment by sfan5** [comment]
Are you using `loop-file` or `loop`?
In either case 2018 us a long time ago and I can't really help you with getting anything to work there.

**Comment by sombresu** [comment]
> Are you using `loop-file` or `loop`?
> In any case 2018 us a long time ago and I can't really help you with getting anything to work there.

Yes, I've been using loop-file=inf

**Comment by sombresu** [comment]
> In any case 2018 us a long time ago and I can't really help you with getting anything to work there.

Can you help me to make the latest version to have seamless loop without pause?
