### ISSUE TITLE
How to set --af=superequalizer=1b=1:2b=1 programmatically?

### ISSUE THREAD

**Issue by T-10001** [mpv-android/mpv-android#657]
How to set `--af=superequalizer=1b=1:2b=1` programmatically?

Would it be `MPVLib.setOptionString("af", "superequalizer=1b=1:2b=1")`?

**Comment by sfan5** [comment]
Did you try that? Does it not work?

**Comment by T-10001** [comment]
I haven't tried it yet. If it should work then it would be good.
