### ISSUE TITLE
I can't see MPV in the slider that shows my recent audio/video applications

### ISSUE THREAD

**Issue by oren** [mpv-android/mpv-android#659]
When I swipe vertically from the top, I see a screen that shows me the audio or video applications that I recently opened. For example I see my Google Podcasts app and a Youtube video I watched on Firefox. I can than swipe right or left to continue listening or watching the content from those apps.

From some reason, I don't see the MPV video on that screen. Is that a missing feature or maybe there is a setting I need to enable?

### Additional information
* mpv-android version 2022-07 30-release
* Pixel 4a, Android version 13

**Comment by sfan5** [comment]
This sounds different from the usual applications slider.
I haven't seen this on my Android 11 phone so I can't really comment on what might cause mpv to not show up there.

**Comment by oren** [comment]
Here is a screenshot of the slider. You can see that I can control my podcast from there and if MPV was available there I would be able to slide horizontally and control the MPV video I recently played.

![image](https://user-images.githubusercontent.com/6517/217963765-584d6588-8ac2-402f-8e1a-34f4e14443a6.png)

**Comment by sfan5** [comment]
this is a feature request. closing in favor of #1031
