### ISSUE TITLE
VP9, no video/crashing(?)

### ISSUE THREAD

**Issue by 1sad** [mpv-android/mpv-android#660]
### Important information

Android version:
10 QP1A.190711.020
MIUI Global 12.0.4 Stable

mpv-android version:
2022-07-30-release

### Description
Basically VP9 video doesn't work at all.
I can hear audio, and if i pause, after a couple of seconds i can see a frame the video (only if show info is on, without it it just black screen all the way)
Toggling HW and SW doesn't do anything. 
Sometimes it crashes but I haven't been able to catch it or make it repeatable. (maybe it just closes because it lags out and video ends)

### Log output
adb command just does
--------- beginning of system
--------- beginning of crash
--------- beginning of main
and then hangs forever

so i installed a logcat app but the highest error level was E
[2023-02-08-16-39-26.txt](https://github.com/mpv-android/mpv-android/files/10686798/2023-02-08-16-39-26.txt)
[2023-02-08-16-43-45.txt](https://github.com/mpv-android/mpv-android/files/10686799/2023-02-08-16-43-45.txt) verbose

### Additional information
[1674646158609.webm](https://user-images.githubusercontent.com/23120024/217566524-ff95f065-5be9-4c4d-a607-e959b243d156.webm) sample file

some way other apps react:
KurobaEx (uses mpv-android as plugin): same way as mpv-android
KurobaEx (if switched to stock android player): "Failed to load video: (reason: Decoder failed: OMX.MTK.VIDEO.DECODER.VP9)
KurobaexLite (also uses mpv, but gives ffmpeg errors):
![217362577-7a18710c-527a-4049-9460-140dd905313c](https://user-images.githubusercontent.com/23120024/217568012-7b5c4483-36e8-488c-8831-f559a07e1f35.png)
Just (Video) Player (exoplayer based): 
![Capture](https://user-images.githubusercontent.com/23120024/217569414-eee0b066-00b7-49c4-8030-fcd127f72e7c.PNG)

codec info says my phone has also c2.android.vp9.decoder, not sure if thats useful information.
the phone is Xiaomi Redmi 9, stock firmware, not rooted, vlc android can play these files, and so can some other players
if theres anything more i can provide ill be glad to

**Comment by sfan5** [comment]
Your video is 10-bit. The decoding works fine in your case but Mali GPUs are known to have weird issues (incl. flickering of the GUI) with how mpv tries to render 10-bit.
see #198
