### ISSUE TITLE
Play local file via intent termux and enqueue playlist via intent termux

### ISSUE THREAD

**Issue by tathastu871** [mpv-android/mpv-android#661]
Type the contents of your question here.
1) How to play local m3u8 or other media file via intent
tried
```
am start is.xyz.mpv/.MPVActivity  -a android.intent.action.VIEW -d file:///sdcard/file.m3u8
```
Also Tried :
-e filepath file:///sdcard/file.m3u8 -t video/* --user 0

But nothing working

2) How to enque multiple urls or multiple local files as playlist using intent

Tried 
to add
playlist="/emulated/storage/0/playlist.txt"

playlist.txt contains
url1.m3u8
url2.m3u8

3) How to set video title when playing url using intents

**Comment by sfan5** [comment]
> 1. How to play local m3u8 or other media file via intent

Not sure if `file:` URLs are still allowed in recent Android or if there is another issue but since you didn't give me any information I can't really help you.

> 2. How to enque multiple urls or multiple local files as playlist using intent

Just start multiple intents.

> 3. How to set video title when playing url using intents

You can't.
