### ISSUE TITLE
Bug while playing Local m3u8 file when played using netcat or python or darkhttpd server and hosted. Played as indivdual .ts files and not as single file

### ISSUE THREAD

**Issue by tathastu871** [mpv-android/mpv-android#662]
### Important information

Android version:
10
mpv-android version:

Which version of mpv-android introduced the problem (if known):
version: n5.1
Downloded from github latest release as universal debug apk

### Description
I am trying to play a local m3u8 file via activity manager on termux.
**Now if file is in /sdcard it can be played using**
```am start -n is.xyz.mpv/.MPVActivity -a android.intent.action.mpv -d "file:///sdcard/file.m3u8"```
**Above Works**

**But if file in inaccesible location which mpv cannot access i use locally hosted http server either using ```cat file.m3u8 | nc -l 8000``` or ```python3 -m http.server 8000``` or ```darkhttpd```**
Then Played using
```am start -n is.xyz.mpv/.MPVActivity -a android.intent.action.mpv -d "http://127.0.0.1:8000/file.m3u8"```

**Problem:**
*When played as locally hosted m3u8, it just opens and black screen no video or audio played.*
** But when i add**
**demuxer-lavf-o=protocol_whitelist=[file,tcp,tls,https,crypto,data]**
**to mpv.conf it plays m3u8 file but as playlist.**

**Without whitelisting m3u8 does not play only black screen. With whitelisting m3u8 is splitted into individual index.ts and played as playlist not as single file.**

**NOTE: SAME ISSUE IS NOT OCCURING WITH VLC-ANDROID. VLC-ANDROID AND MXPLAYER CAN EASILY PLAY LOCALLY HOSTED M3U8 FILE AS SINGLE FILE. ITS THE ISSUE WITH MPV-ANDROID ONLY. SO I OPENED THIS BUG REPORT**
Describe your issue in detail here.

If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s 'mpv:*' '*:F'

You can attach text files on Github directly or use sites like https://0x0.st/ to upload your logs.
Depending on the nature of the bug, a log file might not be required and you can *omit this section*. If in doubt provide one, it will help us find possible issues later.

### Additional information

If your issue is only reproducible with a specific (type of) file, provide a short sample file that can be used to reproduce the problem.
You can again use https://0x0.st/ or other cloud storage to share it.

If your issue relates to a certain set of configuration options, provide a full copy of your `mpv.conf` below.

If no additional information is provided please *delete this section*.

**Comment by sfan5** [comment]
No log file = no help

**Comment by tathastu871** [comment]
> No log file = no help

i dont have laptop to enable adb and use logcat
