### ISSUE TITLE
Add Feature to Use Locally hosted mpv.conf on /sdcard location to be used on non rooted phones.

### ISSUE THREAD

**Issue by tathastu871** [mpv-android/mpv-android#663]
Describe the wanted behaviour of the new feature and potential usecases for it here.

Trying to use media-title option on non rooted device when playing via adb am start intent
Currently requires hardcoding title in mpv.conf
but if we want custom title for each video or url played. we can echo "media-title=custom" >> /sdcard/mpv.conf

and makr mpv-android use that custom mpv.conf

**Comment by sfan5** [comment]
FYI since Android 11 or so there's a whitelist of file extensions mpv can read from the sdcard, `.conf` is not one of them so this wouldn't even work.
