### ISSUE TITLE
Please return panscan also for gestures

### ISSUE THREAD

**Issue by moonjihwan87** [mpv-android/mpv-android#672]
Please return panscan also for gestures. It is very convenient. I see you've moved it to the aspect ratio menu, but I used it in the double-tap on screen gesture, it is much faster than going to the menu, sub-menu. Let them exist in parallel for both menus and gestures. It would be great if you added a two finger zoom gesture like on Android or iOS, it would be very handy just to turn on/off panscan. Thx.

**Comment by sfan5** [comment]
Bind a custom gesture to `cycle panscan 1.0 0.0`, no need for me to do anything.
