### ISSUE TITLE
Automatic Refresh Rate Switching Not Working/Doesn't Exist

### ISSUE THREAD

**Issue by dark-swordsman** [mpv-android/mpv-android#673]
### Important information

**Android version:** 12 - STTE.220920.016.H1.9408258

**mpv-android version:** 2023-02-07 release / 30 (release)

**Device:** Google Chromecast 4K with Google TV

### Description

When using MPV as an external player for Jellyfin, it does not automatically switch refresh rate. It does work for VLC (internal on Jellyfin Client) and VLC as a separate app (has setting for content rate switching).

I believe it works in Jellyfin for VLC and ExoPlayer because they are bundled with **Jellyfin for Android TV** and JF can trigger the refresh rate. But for external apps, the app itself would need to be able to trigger the refresh rate switch.

### Additional information

As far as I can see, the only option is frame interpolation, but this would ruin the quality of the video experience and doesn't really solve the issue. Given mpv-android has now been added to Android TV and that other software supports refresh rate switching through Android 12, this feature would be useful.

This feature should be easily implemented with the following Android API method:

https://developer.android.com/reference/android/view/Surface#setFrameRate(float,%20int,%20int)

**Comment by sfan5** [comment]
This is indeed not implemented, see #12.
