### ISSUE TITLE
Pan and Scan mode for 2.35:1 videos cuts subtitles in half?

### ISSUE THREAD

**Issue by Pentaphon** [mpv-android/mpv-android#679]
@sfan5 On a phone, when I enable pan and scan mode to zoom in on 2.35.1 videos in 16:9 ratio with black bars, I can only see half the subtitles. How do I fix this with mpv.conf? Or is this not intended?

**Comment by sfan5** [comment]
Best open an issue on the mpv repo. I can confirm that this happens but don't know whether it's intentional.

**Comment by Pentaphon** [comment]
> Best open an issue on the mpv repo. I can confirm that this happens but don't know whether it's intentional.

@sfan5 the solution is apparently https://github.com/mpv-player/mpv/issues/11705#issuecomment-1564290774 not sure if you want to add this to mpv-android by default
