### ISSUE TITLE
Can't play folders in Total Commander anymore (?)

### ISSUE THREAD

**Issue by biopsin** [mpv-android/mpv-android#686]
### Important information

Not shure if the label text is fitting..

Android version: LineageOS-18.1
mpv-android version: mpv-android-2023-03-05 (-ytdl branch)
Which version of mpv-android introduced the problem (if known): this one

### Description

On the previous version I could select a folder with or without subfolders in TotalCommander (android) and open as music or video and all files would be added to playlist and play.

In this version I have to "Open with" then select file://url then find mpv and this plays the folder content.

I did look over Androidmanifest.xml changes but I could not pinpoint why this is happening now.

<details>
<summary>Log output</summary>
04-13 11:53:58.109  6443  6443 V mpv     : Resolving content URI: content://com.ghisler.files/tree/primary%3A/document/primary%3Astorage%2F7489-9A91%2FAudio%2FAbstract.Podium
04-13 11:53:58.119  6443  6443 V mpv     : Display 0 reports FPS of 60.000004
04-13 11:53:58.123  6443  6443 V mpv     : You're using the 64-bit build of mpv!
04-13 11:53:58.124  6443  6443 W MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
04-13 11:53:58.127  6443  6443 W AudioManager: Use of stream types is deprecated for operations other than volume control
04-13 11:53:58.127  6443  6443 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
04-13 11:53:58.128  1444  1510 I MediaFocusControl: requestAudioFocus() from uid/pid 10178/6443 clientId=android.media.AudioManager@a9a862is.xyz.mpv.MPVActivity$$ExternalSyntheticLambda30@756bdf3 callingPack=is.xyz.mpv req=1 flags=0x0 sdk=28
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v] mpv 0.35.0-306-g291e05ec1a Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]  built on Sun Mar 05 03:47:17 2023
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v] FFmpeg version: N-109961-gad17e29224
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v] FFmpeg library versions:
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]    libavutil       58.3.100
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]    libavcodec      60.6.100
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]    libavformat     60.4.100
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]    libswscale      7.2.100
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]    libavfilter     9.4.100
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v]    libswresample   4.11.100
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v] 
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v] Configuration: meson configure build -Dprefix=/usr/local -Dbuildtype=release -Doptimization=3
04-13 11:53:58.129  6443  9141 V mpv     : [cplayer:v] List of enabled features: android android-media-ndk av-channel-layout build-date cplugins egl-android egl-helpers ffmpeg gl glibc-thread-name gpl jpegxl libass libavdevice libdl libm linux-fstatfs lua noexecstack opensles posix stdatomic threads vector vt.h zlib
04-13 11:53:58.130  6443  9141 V mpv     : [cplayer:v] Waiting for scripts...
04-13 11:53:58.134  6443  9141 V mpv     : [osd/libass:v] libass API version: 0x1701000
04-13 11:53:58.134  6443  9141 V mpv     : [osd/libass:v] libass source: commit: 0.17.0-41-g23c71d8810b8fd6ffa804dfbaa83ceacee1f1242
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:v] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 7.0.1 (COMPLEX)
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:v] Setting up fonts...
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Thin.ttf#0, weight: 100, slant: 0
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-ThinItalic.ttf#0, weight: 100, slant: 100
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Light.ttf#0, weight: 300, slant: 0
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-LightItalic.ttf#0, weight: 300, slant: 100
04-13 11:53:58.135  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Regular.ttf#0, weight: 400, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Italic.ttf#0, weight: 400, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Medium.ttf#0, weight: 500, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-MediumItalic.ttf#0, weight: 500, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Black.ttf#0, weight: 900, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-BlackItalic.ttf#0, weight: 900, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-Bold.ttf#0, weight: 700, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif' @ /system/fonts/Roboto-BoldItalic.ttf#0, weight: 700, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-thin' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-light' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-medium' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-black' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'arial' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'helvetica' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'tahoma' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'verdana' to 'sans-serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-Light.ttf#0, weight: 300, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-LightItalic.ttf#0, weight: 300, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-Regular.ttf#0, weight: 400, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-Italic.ttf#0, weight: 400, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-Medium.ttf#0, weight: 500, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-MediumItalic.ttf#0, weight: 500, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-Bold.ttf#0, weight: 700, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-condensed' @ /system/fonts/RobotoCondensed-BoldItalic.ttf#0, weight: 700, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-condensed-light' to 'sans-serif-condensed'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-condensed-medium' to 'sans-serif-condensed'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'serif' @ /system/fonts/NotoSerif-Regular.ttf#0, weight: 400, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'serif' @ /system/fonts/NotoSerif-Bold.ttf#0, weight: 700, slant: 0
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'serif' @ /system/fonts/NotoSerif-Italic.ttf#0, weight: 400, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] found font 'serif' @ /system/fonts/NotoSerif-BoldItalic.ttf#0, weight: 700, slant: 100
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'serif-bold' to 'serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'times' to 'serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'times new roman' to 'serif'
04-13 11:53:58.136  6443  9141 V mpv     : [osd/libass:info] adding alias from 'palatino' to 'serif'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'georgia' to 'serif'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'baskerville' to 'serif'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'goudy' to 'serif'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'fantasy' to 'serif'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'ITC Stone Serif' to 'serif'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'monospace' @ /system/fonts/DroidSansMono.ttf#0, weight: 400, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'sans-serif-monospace' to 'monospace'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'monaco' to 'monospace'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'serif-monospace' @ /system/fonts/CutiveMono.ttf#0, weight: 400, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'courier' to 'serif-monospace'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'courier new' to 'serif-monospace'
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'casual' @ /system/fonts/ComingSoon.ttf#0, weight: 400, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'cursive' @ /system/fonts/DancingScript-Regular.ttf#0, weight: 400, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'cursive' @ /system/fonts/DancingScript-Bold.ttf#0, weight: 700, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'sans-serif-smallcaps' @ /system/fonts/CarroisGothicSC-Regular.ttf#0, weight: 400, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'source-sans-pro' @ /system/fonts/SourceSansPro-Regular.ttf#0, weight: 400, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'source-sans-pro' @ /system/fonts/SourceSansPro-Italic.ttf#0, weight: 400, slant: 100
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'source-sans-pro' @ /system/fonts/SourceSansPro-SemiBold.ttf#0, weight: 600, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'source-sans-pro' @ /system/fonts/SourceSansPro-SemiBoldItalic.ttf#0, weight: 600, slant: 100
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'source-sans-pro' @ /system/fonts/SourceSansPro-Bold.ttf#0, weight: 700, slant: 0
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] found font 'source-sans-pro' @ /system/fonts/SourceSansPro-BoldItalic.ttf#0, weight: 700, slant: 100
04-13 11:53:58.137  6443  9141 V mpv     : [osd/libass:info] adding alias from 'source-sans-pro-semi-bold' to 'source-sans-pro'
04-13 11:53:58.139  6443  9141 V mpv     : [osd/libass:v] Using font provider androidfonts
04-13 11:53:58.139  6443  9141 V mpv     : [osd/libass:v] Done.
04-13 11:53:58.140  6443  6443 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
04-13 11:53:58.140  6443  9141 V mpv     : [cplayer:v] Done loading scripts.
04-13 11:53:58.141  6443  9141 V mpv     : event: idle
04-13 11:53:58.152  6443  6443 W mpv     : attaching surface
04-13 11:53:58.154  6443  9141 V mpv     : event: start-file
04-13 11:53:58.159  6443  9141 V mpv     : [cplayer:v] Set property: android-surface-size="1096x2560" -> 1
04-13 11:53:58.159  6443  9141 V mpv     : [cplayer:v] Running hook: ytdl_hook/on_load
04-13 11:53:58.159  6443  9141 V mpv     : [ytdl_hook:v] ytdl:// hook 
04-13 11:53:58.159  6443  9141 V mpv     : [ytdl_hook:v] not a ytdl:// url 
04-13 11:53:58.159  6443  9141 V mpv     : [fd:v] Opening fdclose://66
04-13 11:53:58.159  6443  9141 V mpv     : [fd:info] This is a directory - adding to playlist.
04-13 11:53:58.159  6443  9141 V mpv     : [demux:v] Trying demuxers for level=normal.
04-13 11:53:58.161  6443  6443 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
04-13 11:53:58.161  6443  9141 V mpv     : [lavf:v] No format found, try lowering probescore or forcing the format.
04-13 11:53:58.161  6443  9141 V mpv     : [demux:v] Trying demuxers for level=unsafe.
04-13 11:53:58.166  6443  6443 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
04-13 11:53:58.167  1027  1064 I BpBinder: onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
04-13 11:53:58.168  6443  9141 V mpv     : [lavf:v] No format found, try lowering probescore or forcing the format.
04-13 11:53:58.168  6443  9141 V mpv     : [cplayer:v] Opening failed or was aborted: fdclose://66
04-13 11:53:58.168  6443  9141 V mpv     : [cplayer:v] Running hook: ytdl_hook/on_load_fail
04-13 11:53:58.168  6443  9141 V mpv     : [ytdl_hook:v] full hook 
04-13 11:53:58.168  6443  9141 V mpv     : event: end-file
04-13 11:53:58.168  6443  9141 V mpv     : [cplayer:v] finished playback, unrecognized file format (reason 4)
04-13 11:53:58.169  6443  9141 V mpv     : [cplayer:error] Failed to recognize file format.
04-13 11:53:58.169  6443  9141 V mpv     : [cplayer:info] 
04-13 11:53:58.169  6443  9141 V mpv     : [vo/gpu/opengl:v] Initializing GPU context 'android'
04-13 11:53:58.169  6443  9141 V mpv     : [vo/gpu/opengl:v] EGL_VERSION=1.5 Android META-EGL
04-13 11:53:58.169  6443  9141 V mpv     : [vo/gpu/opengl:v] EGL_VENDOR=Android
04-13 11:53:58.169  6443  9141 V mpv     : [vo/gpu/opengl:v] EGL_CLIENT_APIS=OpenGL_ES
04-13 11:53:58.169  6443  9141 V mpv     : [vo/gpu/opengl:v] Trying to create GLES 2.x + context.
04-13 11:53:58.170  6443  9141 V mpv     : [vo/gpu/opengl:v] GL_VERSION='OpenGL ES 3.2 V@0502.0 (GIT@191610ae03, Ic907de5ed0, 1600323700) (Date:09/17/20)'
04-13 11:53:58.170  6443  9141 V mpv     : [vo/gpu/opengl:v] Detected GLES 3.2.
04-13 11:53:58.170  6443  9141 V mpv     : [vo/gpu/opengl:v] GL_VENDOR='Qualcomm'
04-13 11:53:58.170  6443  9141 V mpv     : [vo/gpu/opengl:v] GL_RENDERER='Adreno (TM) 650'
04-13 11:53:58.170  6443  9141 V mpv     : [vo/gpu/opengl:v] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 3.20'
04-13 11:53:58.171  6443  9141 V mpv     : [vo/gpu/opengl:v] Loaded extension GL_EXT_texture_norm16.
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu/opengl:v] Loaded extension GL_EXT_disjoint_timer_query.
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu/opengl:v] Loaded extension GL_EXT_buffer_storage.
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Testing FBO format rgba16f
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Using FBO format rgba16f.
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=1).
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] No advanced processing required. Enabling dumb mode.
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Assuming 60.000004 FPS for display sync.
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] reconfig to 960x480 yuv444p auto/auto/auto/auto/auto CL=unknown
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Resize: 1096x2560
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Window size: 1096x2560 (Borders: l=0 t=0 r=0 b=0)
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Video source: 960x480 (1:1)
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Video display: (0, 0) 960x480 -> (0, 1006) 1096x548
04-13 11:53:58.172  6443  9141 V mpv     : [vo/gpu:v] Video scale: 1.141667/1.141667
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] OSD borders: l=0 t=1006 r=0 b=1006
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Video borders: l=0 t=1006 r=0 b=1006
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Reported display depth: 8
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Texture for plane 0: 960x480
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Texture for plane 1: 960x480
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Texture for plane 2: 960x480
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Testing FBO format rgba16f
04-13 11:53:58.173  6443  9141 V mpv     : [vo/gpu:v] Using FBO format rgba16f.
04-13 11:53:58.173  6443  9141 V mpv     : event: video-reconfig
04-13 11:53:58.173  6443  9141 V mpv     : event: idle
04-13 11:53:58.174  1444  1554 I ActivityTaskManager: Displayed is.xyz.mpv/.MPVActivity: +139ms
04-13 11:53:58.186  1444  2118 I WindowManager: Queue is too deep! Purged item with taskid=166
04-13 11:53:58.189  6443  9141 V mpv     : [vo/gpu:v] No advanced processing required. Enabling dumb mode.
04-13 11:53:58.201  6443  6443 E mpv     : mpv_get_property(video-format) format 1 returned error property unavailable
04-13 11:53:58.210   946   946 I QTI PowerHAL: Power setBoost: 0, duration: 0
04-13 11:53:58.256  1444  1978 W ActivityTaskManager: Finishing task with all activities already finished
04-13 11:53:58.256  1444  1978 W ActivityTaskManager: Duplicate finish request for r=ActivityRecord{176227f u0 android/com.android.internal.app.ResolverActivity t166 f}}
04-13 11:53:58.243   946   946 I QTI PowerHAL: Power setBoost: 0, duration: 0
04-13 11:53:58.264  1248  4081 D BufferPoolAccessor2.0: bufferpool2 0xe67c0a48 : 0(0 size) total buffers - 0(0 size) used buffers - 37/45 (recycle/alloc) - 8/86 (fetch/transfer)
04-13 11:53:58.264  1248  4081 D BufferPoolAccessor2.0: evictor expired: 1, evicted: 1
04-13 11:53:58.265  1296  2468 D BufferPoolAccessor2.0: evictor expired: 1, evicted: 0
04-13 11:53:58.396   946   946 I QTI PowerHAL: Power setBoost: 0, duration: 0
04-13 11:53:58.409  6443  6443 W mpv     : detaching surface
04-13 11:53:58.410  6443  9141 V mpv     : [vo/gpu:v] Resize: 1096x2560
04-13 11:53:58.410  6443  9141 V mpv     : [vo/gpu:v] Window size: 1096x2560 (Borders: l=0 t=0 r=0 b=0)
04-13 11:53:58.410  6443  9141 V mpv     : [vo/gpu:v] Video source: 960x480 (1:1)
04-13 11:53:58.410  6443  9141 V mpv     : [vo/gpu:v] Video display: (0, 0) 960x480 -> (0, 1006) 1096x548
04-13 11:53:58.410  6443  9141 V mpv     : [vo/gpu:v] Video scale: 1.141667/1.141667
04-13 11:53:58.411  6443  9141 V mpv     : [vo/gpu:v] OSD borders: l=0 t=1006 r=0 b=1006
04-13 11:53:58.411  6443  9141 V mpv     : [vo/gpu:v] Video borders: l=0 t=1006 r=0 b=1006
04-13 11:53:58.411  6443  9141 V mpv     : [vo/gpu:v] Reported display depth: 8
04-13 11:53:58.413  6443  9141 V mpv     : event: video-reconfig
04-13 11:53:58.414  6443  9141 V mpv     : [cplayer:v] Set property: vo="null" -> 1
04-13 11:53:58.433  6443  6443 V mpv     : Exiting.
04-13 11:53:58.434  1444  2118 I MediaFocusControl: abandonAudioFocus() from uid/pid 10178/6443 clientId=android.media.AudioManager@a9a862is.xyz.mpv.MPVActivity$$ExternalSyntheticLambda30@756bdf3
04-13 11:53:58.542  1444  1461 W System  : A resource failed to call release. 
</details>

**Comment by sfan5** [comment]
> Not shure if the label text is fitting..

That log message has nothing to do with it.

> On the previous version I could select a folder with or without subfolders in TotalCommander (android) and open as music or video and all files would be added to playlist and play.

> In this version I have to "Open with" then select file://url then find mpv and this plays the folder content.

Not sure I understand how exactly it worked before. Can you describe in more detail, maybe with screenshots? I have never used Total Commander.

Do you know which older mpv-android version worked correctly?

**Comment by biopsin** [comment]
>Not sure I understand how exactly it worked before.
>Can you describe in more detail

In [previous](https://github.com/mpv-android/mpv-android/pull/58#issuecomment-1281326407) ytdl-testversion you had available a while back I could select folders (in TC) and from longclick menu select "open as" >music and mpv-android would just play it all.
In this version it just exits when a folder is sent to mpv. I have to spesify file://url to make mpv add all to playlist and play. [video](https://www.mediafire.com/file/7uenzjhk2q0949z/20230413_170940.mp4/file)
Let me know how else to put it :)

**Comment by biopsin** [comment]
Thats what my initial logcat showed when exiting, I was hoping those
`E mpv ... format 1 returned error property unavailable` 
was the deal, but I'll redo it with all TC open/send alternatives and see if it differs.
Anyways thank you for your time.

**Comment by sfan5** [comment]
You can download old APKs from here https://github.com/mpv-android/mpv-android/releases

**Comment by biopsin** [comment]
Ok so the thing is none of the official realeases work with sending folders at all, only the testversion reacts as shown in the video and on only with the "Open with" - option ticking of file://url box and selecting mpv.
Since I've only used the -ytdl version I dont know if this have ever worked with the official realeases and I also downgraded to a older TC just to check. Im at this stage confused :)

**Comment by sfan5** [comment]
There's no changes in the ytdl variant that should directly cause these changes
.It can simply be the case however that newer API levels tightened the restrictions for e.g. sharing file:// URIs between applications so it no longer works "naturally". (The ytdl variant is stuck on an old API level.)
Can't do anything to fix this in any case.
