### ISSUE TITLE
Gpu-next android 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#687]
Type the contents of your question here.

Hi there I was wondering about the support of gpu -next when using the latest version downloaded from this site on android and whether the use of gpu-next is supported or not as when I try to use it any video I want to play just crashes I am interested as I would like to use the extra hdr tonemapping options it gives you and if it is not yet supported on android I was wondering if there was any chance it could be added when the next release version is released on here thanks

**Comment by hooke007** [comment]
WIP https://github.com/mpv-android/mpv-android/pull/596
