### ISSUE TITLE
More message for MPV_EVENT_END_FILE

### ISSUE THREAD

**Issue by kllkko** [mpv-android/mpv-android#690]
I have a video file, the playback fails, and the player exits immediately. How do I know what caused the playback failure? I see an MPV_EVENT_END_FILE event. I need to know what caused the error. Is there mpv_end_file_reason? for example the video file is  corrupted

**Comment by sfan5** [comment]
mpv_end_file_reason exists on the C side but is not passed through to Java. If you need this you will need to implement it.
