### ISSUE TITLE
Mpv crashes when playing videos

### ISSUE THREAD

**Issue by Mndq** [mpv-android/mpv-android#691]
Hello, I have an android tv and recently it received a new system update and with this update it broke the mpv application I can no longer watch anything using mpv when I try to play a video it crashes simply the video freezes and I can't move the interface mpv I have to go back to the beginning of the tv, would anyone have an idea to solve it? Does any developer read the posts on this reddit to try to solve problems in the applications with user feedback?

**Comment by Mndq** [comment]
> If you want me to take a look at this you need to provide all information according to the issue template.

What information do you need? does mpv for android tv have any system logs?

**Comment by sfan5** [comment]
https://github.com/mpv-android/mpv-android/blob/master/.github/ISSUE_TEMPLATE/1_bug_report.md?plain=1
