### ISSUE TITLE
HEVC video not playing

### ISSUE THREAD

**Issue by Scarletfly** [mpv-android/mpv-android#699]
Android version:EMUI version 12.0.0

mpv-android version:2023-02-27 

Which version of mpv-android introduced the problem (if known): no

### Description

I was watching anime episodes on other players and when i tried to play it on mpv player the video blacked out and audio was playing.
![Screenshot_20230427_022500_is xyz mpv](https://user-images.githubusercontent.com/131969200/234848065-85ecb73a-3e8b-4140-a3c6-1fb740339b5b.jpg)
Additional information :
I downloaded anime from animekaizoku
But when it came to run the files mpv bugged. 
File download link: https://kuro-vongola.animekaizoku.com/Vongola/Bungo%20Stray%20Dogs%20WAN!/[AnimeKaizoku]%20Bungo%20Stray%20Dogs%20WAN!%201080p%20Dual%20Audio%20[dedsec]/01.%20Bungo%20Stray%20Dogs%20REAL%20-%20What's%20Inside%20the%20Locker%20-%20-%20An%20Unfruitful%20Exchange.mkv?r=rNKDAnkJ&tid=MEFDZFRhNTEydUhsR1VrOVBWQQ==&t=cf6a0&e=1682627

**Comment by sfan5** [comment]
You left out half of the template.

**Comment by Scarletfly** [comment]
> You left out half of the template.

Yeah I'm new at this so got overwhelmed.
Ask me any information you need

**Comment by tmm1** [comment]
all this information is needed: https://github.com/mpv-android/mpv-android/blob/master/.github/ISSUE_TEMPLATE/1_bug_report.md

**Comment by Scarletfly** [comment]
> all this information is needed: https://github.com/mpv-android/mpv-android/blob/master/.github/ISSUE_TEMPLATE/1_bug_report.md

I added the things i understood.

**Comment by shockergit** [comment]
is debanding on?

**Comment by Scarletfly** [comment]
> is debanding on? try disabling it

It is disabled natively but putting it at CPU worked. Thanks
