### ISSUE TITLE
Audio boost not working

### ISSUE THREAD

**Issue by shockergit** [mpv-android/mpv-android#703]
volume-max=150
i used this command in mpv config and audio is not boosting.
Am i using the wrong command can someone help.

**Comment by sfan5** [comment]
`volume-max` does nothing on its own, you'd also have to set `volume`. Note that the touch gestures adjust the system volume and not the mpv volume.

**Comment by shockergit** [comment]
> `volume-max` does nothing on its own, you'd also have to set `volume`. Note that the touch gestures adjust the system volume and not the mpv volume.

how to adjust mpv volume by touch gesture
