### ISSUE TITLE
secondary subtitle support

### ISSUE THREAD

**Issue by rhjdvsgsgks** [mpv-android/mpv-android#704]
for some anime. user will need to load 2 subtitle. one for translate. one for bullet comment (danmaku) which generated by [danmaku2ass](https://github.com/m13253/danmaku2ass).

### Additional information

make the single select in pop up menu when long pressing subtitle button become multi select. and set `secondary-sid`.

**Comment by qgustavor** [comment]
Like my fork? I set up so pressing the subtitle button opens the main subtitle selection, long pressing open the secondary. The only issue I had is that I had to patch mpv because of [this issue](https://github.com/mpv-player/mpv/issues/3022) that messes up the secondary subtitle styling. It is an easy patch, just comment one line, I wonder why it was not set as an option yet.

**Comment by PanderMusubi** [comment]
MPV is (as far as I know) the only mainstream FOSS video player that supports secondary subtitles. For Kodi some hacks exist but no actual support and VLC supports it in version 4 which is still in beta.

For learning a new language, using secondary subtitles is very useful and MPV could really cater to these needs also for Android.

Using a long press might hide this feature too much. Could you make an implementation that simply adds an extra menu item as in the mockup below?

![mpv](https://github.com/mpv-android/mpv-android/assets/198964/006ba09f-ca9c-41e1-975a-536d32f6b0ce)

**Comment by PanderMusubi** [comment]
Perhaps trivial, but the desired default behavior should be as in the non-Android version, the primary subtitle at the bottom and the secondary subtitle at the top of the screen.

**Comment by qgustavor** [comment]
While I understand those who prefer this way, I don't understand why that's not a configurable option. Overriding style is useful for those learning languages (and only in this case), but makes it impossible to use separate song tracks with separate dialogue tracks (which is something some weird groups do).

In a parallel universe where the default was not overriding someone would just comment "just edit the secondary subtitle to be above, it's too easy", but I think the best is it being an option.

**Comment by PanderMusubi** [comment]
I agree with being able to edit subtitle positions and style, just looking forward to getting choosing secondary external subtitle supported and similar defaults between MPV on different platforms.

**Comment by qgustavor** [comment]
Style aside mpv already supports secondary-sid, mpv-android just lacks a UI for that. You don't need to add an "Open external secondary subtitle", the normal one just adds a new subtitle to the list, the only thing missing is a way to set the secondary-sid from this list, which is that I did in my fork.

Sadly I'm not a Kotlin developer (neither C developer, in fact I'm just someone who codes JavaScript as a hobby) so my code is really bad. If it was not for that then I would implement both a --secondary-sid-override-style option (defaulting to true) or something similar and a GUI for --secondary-sid and this option.

**Comment by PanderMusubi** [comment]
Yes, in non-Android I have it already working via a script:

    cd $1
    BASE=$(basename "$PWD")
    mpv $BASE.mp4 --sub-files=$BASE.Spanish.srt:$BASE.English.srt --secondary-sid=2

where `$1` is the name of the directory containing the movie and the subtitle files.

Super that in Android it already adds it to the list of available external subtitles. Perhaps could even get improved if `Open external subtitle...` allows for multi file selection. Would that be a valid extra feature request?

**Comment by PanderMusubi** [comment]
See also https://github.com/mpv-player/mpv/issues/11687#issuecomment-1546721186 to show two subtitles with the current version of MPV for Android.

**Comment by mrfragger** [comment]
> MPV is (as far as I know) the only mainstream FOSS video player that supports secondary subtitles. For Kodi some hacks exist but no actual support and VLC supports it in version 4 which is still in beta.

I believe your right...PotPlayer isn't FOSS just free on windows and IINA on MAC and SMPlayer (Linux) is mpv under hood. There is only a paid option on iphone / android (won't mention) that does dual subs and use it currently.  Quick question...on this android version can you set brightness to -100 easily?  Reason I ask is I decided to put a black cover image for all hundreds of audiobooks so subtitles can easily display on whatever player is being used.  Linux mpv / smplayer works great and can completely black out a bright cover image.

**Comment by sfan5** [comment]
This is now possible by long pressing the subtitle button on the UI. you will get a choice between choosing the primary or secondary subtitle track.
