### ISSUE TITLE
XSPF playlist support

### ISSUE THREAD

**Issue by KaKi87** [mpv-android/mpv-android#705]
Describe the wanted behaviour of the new feature and potential usecases for it here.

MPV would open [XSPF](https://en.wikipedia.org/wiki/XML_Shareable_Playlist_Format) files just like it opens M3U8 files.

### Additional information

None

---
Thanks

**Comment by sfan5** [comment]
This would be a feature request for mpv itself.
Unlikely to be implemented however because nobody wants to include an XML parser just for this.

**Comment by KaKi87** [comment]
> nobody wants to include an XML parser just for this

"just" as in it wouldn't be a good enough reason to do it ? Why ?

Anyway, if there is no intention to parse anything else than URLs, which I don't mind, then substring-based or regex-based parsing could be enough.

**Comment by sfan5** [comment]
> "just" as in it wouldn't be a good enough reason to do it ? Why ?

Yes. Aside from XML being annoying to deal with in code, adding a dependency always has fixed overhead (even if small) plus e.g. libxml2 often had security issues in the past which is not optimal when you're parsing essentially untrusted input.
When you weigh that against support for some niche playlist format it's not hard to decline.

**Comment by KaKi87** [comment]
> XML being annoying to deal with in code

Ah yes, because M3U8 directives sure look more intuitive than XML to parse.

> some niche playlist format

VLC uses it by default.
