### ISSUE TITLE
one video differentspeed while  playing  on different  phone 

### ISSUE THREAD

**Issue by saiwaishitou** [mpv-android/mpv-android#71]
I have tyied  to play one video  with two phone  , Redmi 3S(android 6.0) and HUAWEI NXT-TL00(android 6.0),
 sometimes,the speed on the HUAWEI NXT-TL00(android 6.0) is normal,while  faster or lower with Redmi 3S(android 6.0) .what's wrong with it,

**Comment by sfan5** [comment]
hwdec enabled? logcat output? sample?
