### ISSUE TITLE
Dolby Vision support

### ISSUE THREAD

**Issue by zhengqwe** [mpv-android/mpv-android#717]
Dolby Vision support well on mpv Windows by using `vo=gpu-next`, but this app not supports it.
### Additional information
None

**Comment by sommio** [comment]
vo_gpu_next exists in the [vulkan test version](https://github.com/mpv-android/mpv-android/pull/596)

**Comment by qq528** [comment]
Is there any plan to support Dolby Vision for android device？

**Comment by sommio** [comment]
You should be able to use software decoding, the developers of mpv-android should not be able to solve the mediacodec problem

**Comment by zhengqwe** [comment]
> > But the mpv pc version can use vo=gpu-next  to play dolby vision 。

And hardware decoding is available, use `hwdec=d3d11va`

**Comment by qq528** [comment]
> 

Unsupported hwdec: d3d11va

**Comment by qq528** [comment]
Exo can play dolby vision on android supported devices

**Comment by sfan5** [comment]
Supporting gpu-next is planned (#753).
It's unlikely that it will ever play nice with mediacodec.

**Comment by markg85** [comment]
> Exo can play dolby vision on android supported devices

Still want to respond to this in-context.
Exo Player by default plays the files that your device has the hardware extensions for to support it.
Dolby Vision is an extension that some devices do (and others don't) support. One of my devices for instance has the `c2.dolby.decoder.hevc` which does make Exo Player **try** to play Dolby Vision data. However, it only supports a limited subset of DV and for some media will just display a black screen. You can find out which extension you have with an app like [this one](https://play.google.com/store/apps/details?id=net.tyniw.mediacodecinfo.application&hl=en_US).

**Comment by markg85** [comment]
No clue what you're taking about with hwaccel and hwaccel, nobody mentioned it here before you just did.

Anyway.

If your device has the **hardware extensions** like `c2.dolby.decoder.hevc` then it _can_ play Dolby Vision content (aka, HEVC with DoVI metadata). This would **require** for mpv to play media through a different code path (not through ffmpeg) till the ffmpeg side of things gets proper support for these codecs too. A player like [Next Player](https://github.com/anilbeesetti/nextplayer) does this. It heavily leans on the Exo Player demo code which is the actual source that combines ffmpeg + hardware extensions.
