### ISSUE TITLE
Multi Part Archive Playback support

### ISSUE THREAD

**Issue by MVasuki1** [mpv-android/mpv-android#720]
The desktop variant of mpv supports playing multipart archive
It automatically reads the subsequent parts of the multipart archive and plays continuously without any issues (other than seeking)

mpv-android fails to open a multi part archive file.
Is this intended, or can we expect support for multi part archive in mpv android in the future

**Comment by sfan5** [comment]
functionally identical to #384

It's however worth noting that even with libarchive support due to the new file access methods / sandboxing enforced by Google since a few years multi-part archive play will likely not work well (as libmpv cannot see the files).

**Comment by MVasuki1** [comment]
how about streams and not files, say for example I'm running a file server on my local network that serves
http://192.168.0.10:9094/1947326400/11/Silo.S01E01.1080p.Web.H264-Ggwp.mkv.7z.001

the desktop variant automatically loads
http://192.168.0.10:9094/1947326400/11/Silo.S01E01.1080p.Web.H264-Ggwp.mkv.7z.002
http://192.168.0.10:9094/1947326400/11/Silo.S01E01.1080p.Web.H264-Ggwp.mkv.7z.003

I was expecting mpv-android to work the same way.

**Comment by sfan5** [comment]
If that works with desktop mpv it would work with mpv-android too (once libarchive is integrated).
