### ISSUE TITLE
result intent at complete video playback lacks "playback_completion" and returns position 0 not complying with mxplayer behavior

### ISSUE THREAD

**Issue by courville** [mpv-android/mpv-android#723]
### Important information

Android version: all android version

mpv-android version: 2023-02-27 0.35.0-2566

Which version of mpv-android introduced the problem (if known): unknown

### Description

Some of my Android video player application ([nova video player)](https://github.com/nova-video-player/aos-AVP) users are using mpv-android as external video player.

When using mpv-android and watching entirely a video file (i.e. till the end), mpv-android provides as returned intent extra `position` value 0 and no indication that video is watched completely interfering with nova's way of tracking videos "marked as watched".
Cf. https://github.com/nova-video-player/aos-AVP/issues/891

### Log output

What I see in my application (not mpv):
```
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: requestCode=989, resultCode=-1, mVideoDbInfo!=null true, mPlayerUri http://localhost:44617/Succession.S04E07.720p.HEVC.x265-MeGusta[eztv.re].srt
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: data.getData()=null
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: JUSTPLAYER_RESULT_EXTRA_end_by=null, VLC_RESULT_EXTRA_position=-1, JUSTPLAYER_RESULT_EXTRA_duration=-1, VLC_RESULT_EXTRA_duration=-1, requestCode=989, resultCode=-1
com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: position=0, duration=11348000
```

### Suggested fix

Comply with http://mpv-android.github.io/mpv-android/intent.html that uses extra `end_by`: `playback_completion` or report extra`position` as end of video (vlc/justplayer behavior).

I know that I could implement a hack that marks video watched when only mpv returns 0 as extra `position` but I do not believe this "is the way".

Please let me know if there is an alternative that I missed.

**Comment by sfan5** [comment]
I'm having trouble identifying where exactly you are describing the problem to be.
Does mpv-android not comply with its own specification (note that there is no `end_by` field specified)? 
Does mpv-android differ from MXPlayer behaviour that you expect?

**Comment by courville** [comment]
The problem I have is how to infer from the return intent of mpv-android that a file has been watched entirely when mpv-android application does plays it to the very end.
The current behavior of mpv-android is to return intent extra with position reported to 0 without any other extra specifying complementary information indicating playback completion.
As a consequence an external application like mine infers that the video has not been watched.
Is this any clearer?

**Comment by sfan5** [comment]
I investigated this issue and found some minor problems but fundamentally it works correctly.
If I exit a video in the middle an intent with extras: `Bundle[{duration=90000, position=45000}]` is returned, if I let the video end naturally `null` is returned.
Doesn't this match what nova expects?

**Comment by courville** [comment]
@sfan5 thanks for taking the time to investigate. I will thus implement `null` as video playback complete when video is played to the end.

**Comment by sfan5** [comment]
Worth noting that mxplayer has the exact same behavior:
![grafik](https://github.com/mpv-android/mpv-android/assets/1042418/ee1a66b2-b437-4f04-8733-0ba3ce9b6457)

> This extra will not exist if playback is completed.

**Comment by courville** [comment]
* mxplayer: `data.getData()` is not null, it is a bundle that contains the extra `playback_completion` when fully watching the video to the end:
```
2023-06-03 15:05:21.579 22178-22178 com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: data.getData()=Bundle[mParcelledData.dataSize=108]
2023-06-03 15:05:21.579 22178-22178 com.archos.media...erResultListener org.courville.nova                   D  onActivityResult: data end_by : playback_completion
```
* same with justplayer:
```
D/com.archos.mediacenter.video.utils.ExternalPlayerResultListener( 5710): onActivityResult: data end_by : playback_completion
D/com.archos.mediacenter.video.utils.ExternalPlayerResultListener( 5710): onActivityResult: data.getData()=Bundle[{end_by=playback_completion}]
```
Anyway, I adapted the code of nova to current mpv behavior.
