### ISSUE TITLE
Option to loop gifs and videos

### ISSUE THREAD

**Issue by SleepzCat** [mpv-android/mpv-android#724]
It would be nice to have an option to play gifs and videos on repeat. This would be especially useful for gifs since viewing them in MPV is difficult because many are only a second or two long and are meant to play on repeat.

**Comment by sfan5** [comment]
How would you like this option to look?
You can do this from the playlist dialog already (admitted this takes a lot of clicks).
You can also use profiles in mpv.conf to enable this automatically for `.gif`'s.
