### ISSUE TITLE
Extend video into the notch cutout area setting missing

### ISSUE THREAD

**Issue by slashdragos** [mpv-android/mpv-android#727]
Android version: 13

mpv-android version: 2023-06-04

Which version of mpv-android introduced the problem (if known): 2023-06-04

The option to extend the video into the notch area is gone on the latest version. It was present before. I will attach two screenshots comparing 2023-06-04 with the previous release on Play Store, 2023-02-27.

![Untitled](https://github.com/mpv-android/mpv-android/assets/106933291/d84e9824-7b7d-4030-b68d-240db8521f47)

**Comment by sfan5** [comment]
This option was intentionally removed, it is now always enabled.

**Comment by slashdragos** [comment]
With Extend video into the notch cutout area enabled, it should fill the entire screen. Using 2023-06-04 I get a black line where the camera is. I use this config:
loop-playlist
panscan=1.0
sub-use-margins=yes
sub-ass-force-margins=yes
audio-display=no
It should make the video fill the entire screen. I will attach screenshots from both versions.

![Untitled](https://github.com/mpv-android/mpv-android/assets/106933291/da972a80-049b-4fb6-adb4-a21e016417e2)

**Comment by sfan5** [comment]
this is a new bug, see #726
