### ISSUE TITLE
Fix broken fuzzy subtitles 

### ISSUE THREAD

**Issue by PanderMusubi** [mpv-android/mpv-android#729]
### Important information

Android version: 13

mpv-android version: 2023-06-04

### Description

Fuzzy subtitle support is broken. Please make new relaxed with this fix https://github.com/mpv-player/mpv/issues/11749

**Comment by sfan5** [comment]
The fix will automatically be in the next release but this is not a priority for me right now.

**Comment by PanderMusubi** [comment]
Thanks. For me it is a priority but workaround with F-Droid is to uninstall and install previous version. note that youbdo loose all your settings. For some reason reverting directly in F-Droid doesn't work.
