### ISSUE TITLE
Navigation to file manager after video playback 

### ISSUE THREAD

**Issue by yohanilluminated** [mpv-android/mpv-android#730]
I have observed that when I play a video from the file manager with mpv, if I press back or the video ends  it returns to mpv home screen instead of going back to the file manager where the video was selected.

### Additional information
Also a button to select the screen orientation in player interface will be also great.

**Comment by sfan5** [comment]
duplicate of #647

> Also a button to select the screen orientation in player interface will be also great.

This button will appear if you set the orientation in settings to anything except "Auto".

**Comment by yohanilluminated** [comment]
What about the first request?

**Comment by sfan5** [comment]
It's a duplicate of the other issue I linked, there is no known solution.
