### ISSUE TITLE
Allow access to manage all files

### ISSUE THREAD

**Issue by Azithro721** [mpv-android/mpv-android#734]
Can u add permission to allow access to manage all files...
I'm using A12 and A13 devices... 
I want to use shaders and scripts but mpv only reads media files and not storage files...

P.s. Even an unofficial build would do cuz I know Google hardly approves all files permission to apps

**Comment by sfan5** [comment]
Now done in b4dbfced7fdb79cae6e7a8d891e252b52e97e3bf
