### ISSUE TITLE
Subtitles not showing on mpv-android for TV

### ISSUE THREAD

**Issue by kidfrombellwood** [mpv-android/mpv-android#736]
### Important information

Android version: Android TV OS v11

mpv-android version:
2023-06-04-release / 31 (release)

Which version of mpv-android introduced the problem (if known): I think all

### Description

So for a while now, I've been trying to play 10bit, x265 anime encodes through mpv on Sony Bravia Android TV, but the video always lags when playing. Some files have few lags throughout the episodes (particularly panning shots and fast/action scenes), while other encodes just lags throughout, even without panning shots and action scenes. This is not the case with 8bit files, so I can play 8bit videos just fine using vf=format=yuv420p on mpv.conf. As a fallback, I tried vo=mediacodec_embed
hwdec=mediacodec in mpv.conf, and it worked, the previously lagging 10bit, x265 files now play smoothly, but then another problem occured.
This time, the subtitles are now not showing anymore, even when the subs are on and forced. It's a shame because mpv is the only app on Android that shows particular fancy subs especially for anime files at a smooth rate and at the "exact timestamps", which is not the case for other apps like VLC and MX, which doesn't show the subs as smoothly as mpv and at the exact time. Please help me deal with this issue. Thank you

### Additional information

If this helps, this is what's currently in the mpv.conf:

vf=format=yuv420p
vo=mediacodec_embed
hwdec=mediacodec

**Comment by syphyr** [comment]
Use these settings:

vo=gpu
hwdec=mediacodec-copy

The problem is that `vo=mediacodec_embed` does not support any window overlay, like subtitles and screenshots.

**Comment by sfan5** [comment]
mediacodec_embed does not support subtitles. Do not use random settings you don't fully understand.

Clear your mpv.conf and fill out the issue template, maybe I can then find a clue what's wrong.

**Comment by kidfrombellwood** [comment]
> Use these settings:
> 
> vo=gpu hwdec=mediacodec-copy
> 
> The problem is that `vo=mediacodec_embed` does not support any window overlay, like subtitles and screenshots.

It didn't work, the subs still aren't showing

**Comment by kidfrombellwood** [comment]
> Use these settings:
> 
> vo=gpu hwdec=mediacodec-copy
> 
> The problem is that `vo=mediacodec_embed` does not support any window overlay, like subtitles and screenshots.

I tried, and while the subs are now showing, this time no video, only green screen

**Comment by sfan5** [comment]
This is possible a known issue like #198 but :shrug:
