### ISSUE TITLE
How to handle the premature closure for growing `.m2ts` files?

### ISSUE THREAD

**Issue by Aymkdn** [mpv-android/mpv-android#739]
Hello,

My set-top box can record TV programs. The program is saved to a `.m2ts` file. MPV can read this file without issues, however if I play the file while the box is still recording the program, the end time is not updated.

Let's get an example:
  1. The box starts a 1-hour program record;
  2. I start playing the file 10 minutes after the box started to record it;
  3. When I open the `.m2ts` file with MPV, I can see the duration is 10 minutes;
  4. While watching the video, the file will keep growing because the record is not over;
  5. When I reach 10 minutes of playing the file, MPV thinks it's the end, and closes the player, returning no `position` or `duration` because it things the video is over.
  6. I have to reopen the file and fast-forward until I find where I was in the video.

Is there a way to either:
- have MPV to update the end-time while the file is growing?
- or have MPV to return some information when the video is over, this way I could reopen at the time it closed it;
- or any other suggestion to handle this case?

Thank you very much!

**Comment by sfan5** [comment]
the duration staying fixed sure sounds like the demuxer is caching this value but not sure
Look into the `appending://` protocol [here](https://mpv.io/manual/master/#protocols), though the UI probably prevents you from using it (currently).

**Comment by Aymkdn** [comment]
Thanks for the reply. The file is not local, but I access it with `http` protocol (the record/file is saved on the server part of the set-top box while I read it using a player box, through the local network).

Any other idea?

**Comment by sfan5** [comment]
Ah, mpv has nothing to handle such cases with HTTP.
Your best bet is to write a script that reopens the stream before it gets too close to the end.

**Comment by Aymkdn** [comment]
And what about if the file is served from a SMB? Will it change anything, you think? But I'm not even sure we can open a `smb://` in MPV Android…

**Comment by sfan5** [comment]
`smb://` won't work but in any case the solution using `appending://` I mentioned only works for local files.
