### ISSUE TITLE
Android kitkat support

### ISSUE THREAD

**Issue by Q3CPMA** [mpv-android/mpv-android#74]
Hello,
I wanted to know if Kitkat could be supported, or if mpv-android depends on Android 5 too much for this to happen.

**Comment by sfan5** [comment]
i think mpv-android does not actually use much from 5, the reason it was targeted in the beginning was the support for OpenGL ES 3.0 IIRC
oh also arm64 and x86_64 both require at least android 5

**Comment by sebma** [comment]
Hi,

Yes, it would be really great if one could build mpv on Andoid KitKat ( and even Jelly Bean :-) ) !

**Comment by sfan5** [comment]
Here's a quick test build targeting KitKat ([branch](https://github.com/mpv-android/mpv-android/tree/sfan5/kitkat_test)):
[mpv-android_kitkat-test.zip](https://github.com/mpv-android/mpv-android/files/1882054/mpv-android_kitkat-test.zip)


We certainly don't plan to support this officially.

**Comment by sebma** [comment]
@sfan5 Thanks

Actually my android Kitkat device is down because of filesystem full but I don't want to do a factory reset because that would erase all my data.

I have another device with android 4.1.2, can you please rebuilt this test build for android 4.1.2 ?

It would be really great :)

**Comment by sebma** [comment]
@sfan5 I've just tried it. I didn't have the time to browse (with mpv file manager ?) to my `/Removable/MicroSD/` directory that android said : 

`Unfortunately, mpv has stopped.`

**Comment by sfan5** [comment]
Our file manager library is probably using some too-new API.
¯\\\_(ツ)_/¯

**Comment by sfan5** [comment]
Maybe, but I'm not going to bother.
You can directly open videos in mpv from your native file app anyway.

**Comment by sebma** [comment]
@sfan5 If I use another file manager such as `Amaze` to do an "Open with" and the select the `mpv` application, mpv crashes with the same error message : 

`Unfortunately, mpv has stopped.`

Any idea why ?

**Comment by sfan5** [comment]
I'd need a logcat to answer that

**Comment by sebma** [comment]
@sfan5 I don't know how to generate a logcat.

I think my mpv pb. has  something to do with my RAM, because 96% unto 98% of (1GB) is already used.

Do you know a good program to find out what applications are consuming the most of the RAM ?

**Comment by unresolvedsymbol** [comment]
A "legacy" branch/fork of mpv-android similar to NewPipe-Legacy would be quite nice as a youtube-dl player. I can't even use NewPipe-Legacy on my older devices because the kernel source is no longer available to enable swap and it eats too much memory. Right now I've resorted to VLC 3.0.13 as that is the latest version with minsdk that allows 4.1.
