### ISSUE TITLE
Set multiple dynamic in stream-lavf-o

### ISSUE THREAD

**Issue by markg85** [mpv-android/mpv-android#740]
Hi,

I'm trying to build a modified version of mpv-android that:

1. Sets the IPFS gateway (stream-lavf-o=gateway=http://...)
2. Sets a crypto key (stream-lavf-o=key=supersecretkey)
3. Sets the IV for that key (stream-lavf-o=iv=keyiv)

All of this can be set with a code line like:
`MPVLib.setOptionString("stream-lavf-o", "key=supersecretkey,iv=keyiv,gateway=http://blabla")`

I tried this and it works just as expected.
You can try the same on the command line with mpv, the play command then would be:
`mpv lavf://crypto:ipfs://<ipfs cid>`

However, this is static and overrules anything the user would have set in `stream-lavf-o` (in mpv.conf).
So i'm looking for an option that **updates** values in `stream-lavf-o` or adds them if they don't exist yet. But such functionality doesn't seem to exist yet. Or is there API for this in `MPVLib` that i have missed?

Of these values you can assume the gateway to be static.
The key and IV come from a keyserver. The mechanism is unrelated to mpv but the flexibility needed in mpv to support this. As you can probably imagine that each file/url will have a different key and iv. The easiest way i can imagine to get this working is by having a way to update values in `stream-lavf-o`.

Alternatively, a different syntax could be supported perhaps?
Like for example:
```
MPVLib.setOptionString("stream-lavf-o[key]", "supersecretkey")
MPVLib.setOptionString("stream-lavf-o[iv]", "ivkey")
MPVLib.setOptionString("stream-lavf-o[gateway]", "[supersecretkey](http://blabla)")
```

A syntax like that would very cleanly allow updates to `stream-lavf-o`.

Sidenote: I do plan make a PR soon that adds ipfs support in mpv-android. It's there in plain mpv already but a bit difficult to use in the android app. It would whitelist the `ipfs` and `ipns` protocols, add a general config to set a gateway and put that gateway in `stream-lavf-o` when one of these protocols is used. There too i'm puzzling in the logic of how to modify `stream-lavf-o` to add the gateway without overwriting it completely.

Best regards,
Mark

**Comment by sfan5** [comment]
https://mpv.io/manual/master/#string-list-and-path-list-options

**Comment by markg85** [comment]
Thank you for the link @sfan5!
`-set` appears to be what i'm looking for.
