### ISSUE TITLE
Some way to force desired CJK variation for external subtitles.

### ISSUE THREAD

**Issue by not-nocturnal** [mpv-android/mpv-android#741]
If I play a video file using external subtitles with Han characters, it will always display them using the Chinese variation. I'd like some way to force it to use the Japanese variation from within mpv instead. (I tried changing my system language as well as including .jp at the end of the subtitle filename but that didn't seem to make a difference.)

Alternately, some way to specify a subtitle font from within mpv (that doesn't require root) would work, as then I could just supply a font that only has the variation I'm after.

Right now the only workaround I have is to manually remux any video file I want to play back on my device to include the subtitles and appropriate font (and convert + style any .srt).

**Comment by sfan5** [comment]
To be clear this is WONTFIX for me. Good luck with the config solution.
Maybe some day mpv-android will have a font chooser for subtitles.
