### ISSUE TITLE
Backup or restore the content of `config_dir` in internal storage with zip files

### ISSUE THREAD

**Issue by stumpedatwork** [mpv-android/mpv-android#742]
#### Settings->Advanced->Backup: Zip all the content of `config_dir` in internal storage and allow the user to save it somewhere.

Use cases:
- Let the user backup configuration files
- Allow the user to create a log file in internal storage with the option `log-file=~~home/mpv.log` and export it.

#### Settings->Advanced->Restore: Replace all the content of `config_dir` in internal storage with the content of a zip file the user has chosen.

Use cases:
- Let the user restore configuration files
- Allow the user import scripts into internal storage by editing the zip file 

Would you consider the addition of the above feature to `mpv-android` ? Thank you!

**Comment by sfan5** [comment]
My vision for this was to
* always write a log file and allow users to easily export/view it
* add some basic file editing so people can populate the script folder if they want to

Given the current speed of development I'll never get to implementing especially the second point.
