### ISSUE TITLE
Crash with AC3 passthrough

### ISSUE THREAD

**Issue by sfan5** [mpv-android/mpv-android#750]
### Important information

Android version: ?

mpv-android version: 2023-06-04

### Description

Segfault when `--audio-spdif=dts,ac3` is used, reported on IRC.

### Log output

https://pastebin.com/raw/cFRCuMUx
addr2line says `mp_set_av_packet at av_common.c:?`

### Additional information

sample: https://files.catbox.moe/nsgzc7.avi

**Comment by Hackerpcs** [comment]
Android version is 11 (Android TV)

![sdd](https://github.com/mpv-android/mpv-android/assets/17467335/4575eada-511f-450d-9676-33eca093db16)

the sample in case the above link goes down is from here
https://tfm.ro/win32-projects/test-avi-ac3/
direct link that works from archive.org
https://web.archive.org/web/20150330090418/http://download.tfm.ro/w32/test_ac3.rar

**Comment by sfan5** [comment]
I fixed the crash here: https://github.com/mpv-player/mpv/commit/4c3ed843dc8bde419d8c08565159a83cee9e3b9b
but it still freezes, this seems to be a "normal" symptom of the AO rejecting spdif output
