### ISSUE TITLE
Gpu-next master android 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#753]
Type the contents of your question here.
Hi there just a quick question I was just wondering if there was any news on if gpu-next will be coming to the next update for the android version of MPV I understand that it is present in the vulkan test version however it Is clear now in that version that it is stable enough to add for android users using gpu-api=opengl and gpu- context = android so was wondering if this compatibility will be added to the master version I am only asking as I'm sure others will agree that we would like to be able to use the new HDR tonemapping options and other options which are gpu-next only when android is the only device we have to use MPV and it is now been tested that it can be used and is stable with opengl despite vulkan not being stable yet thanks

**Comment by Jamie666123** [comment]
I would like to see the gpu-next functionality moved to the master build as it is very stable with gpu-api=opengl and gpu-context= android and at least then me and others will have the option to swap between gpu and gpu-next as we would like to and Vulkan support can continue to be tested in the test version

**Comment by rohitghali** [comment]
Where can I find the test versions?

**Comment by Jamie666123** [comment]
> Where can I find the test versions?

The test version is located in the pull requests section it is called Vulkan APL included download the apk which is linked and it is a version of mpv where gpu-next is supported

**Comment by sfan5** [comment]
This is planned.

**Comment by sfan5** [comment]
402f29e45281a1a386d10d59d976124588c5b5b5
