### ISSUE TITLE
Basic auth for networked videos

### ISSUE THREAD

**Issue by rahlhar** [mpv-android/mpv-android#755]
### Important information

Android version: omni-10-20210515-beryllium-MICROG
(at end of supported life)

mpv-android version: 2023-06-04-release [via fdroid]

Which version of mpv-android introduced the problem (if known): This is my first usage.

#### Basic auth in the URI

- Select `Open URL`
- Input basic auth formatted uri:
  e.g. `https://user:pass@domain.tld/foo/bar.mkv`
- Expect: video should play
- Expect: some useful message should be displayed if there's an error
- Actual: silent failure

#### Request user/pass if necessary

This is more of a feature request than a bug, but related. Can always submit something separate later if necessary.

- Select `Open URL`
- Input uri for a basic auth protected location
  e.g. `https://domain.tld/foo/bar.mkv`
- Expect: Prompt for user and pass
- Actual: silent failure

### Log output

Using `matlog` app on the device directly. Set to `verbose` logging.

Following the above process, the silent failure appears to yield nothing via `logcat`.

### Additional information

The URI I'm actually testing with works as expected with `mpv` when run on my desktop command line, using the basic auth embedded URI.

`mpv` fails with `401 unauthorized` when run without auth in the URI.
This further makes me think that my second use case above is more of a feature request :).

**Comment by sfan5** [comment]
The auth data probably gets lost somewhere during parsing.

> Using `matlog` app on the device directly. Set to `verbose` logging.
> 
> Following the above process, the silent failure appears to yield nothing via `logcat`.

Then that app does not work, mpv-android always logs a bunch of lines.

**Comment by rahlhar** [comment]
> Then that app does not work, mpv-android always logs a bunch of lines.

Tried `adb logcat -s "mpv"` and did indeed get better output. Thanks, and sorry for being lazy.

> The auth data probably gets lost somewhere during parsing.

While testing with `logcat`, the auth and link worked as expected and the video began playing.

So now I'm doubly confused :).

**Comment by rahlhar** [comment]
I can only assume I was an idiot and mistyped user:pass.

In which case, this is downgraded to being a request to display such errors to the user.

In this case, `401 unauthorized` would be sufficient, and it's present in the `logcat` output via `ffmpeg` apparently.

**Comment by sfan5** [comment]
I'll consider this solved then.
