### ISSUE TITLE
Building on archlinux possible? 

### ISSUE THREAD

**Issue by Infinitytreacher** [mpv-android/mpv-android#756]
I tried building arm64 on arch linux and got the following error
ERROR: Neither source directory '_build-arm64' nor build directory None contain a build file meson.build.
Is it possible to build on arch?

**Comment by sfan5** [comment]
I build on Arch, it works fine. You must have skipped part of the instructions.

**Comment by sfan5** [comment]
What does `./download.sh` output if you run it again?

**Comment by sfan5** [comment]
Delete `buildscripts/deps` and check again, harfbuzz was probably not downloaded correctly.
