### ISSUE TITLE
Target-trc question 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#757]
Type the contents of your question here.

Hi there I was using mpv to tonemap hdr movies however when I add target-trc=pq to the image it seems to greatly improve the colour of the picture and the colours show up a lot brighter and stronger however if I add target-prim=bt.2020 it makes the picture washed out it only seems to improve the colour when target-trc is used on its own without setting a target-prim does this mean this is hdr pass through or not I can show screenshots of content with and without target-trc=pq
Thanks

**Comment by sfan5** [comment]
HDR passthrough is not supported, setting `target-trc` or `target-prim` might do random things that are not necessarily correct.
