### ISSUE TITLE
Volume Vertical Drag seems to be limited to one half of the screen (unlike seek horizontal drag)

### ISSUE THREAD

**Issue by hasezoey** [mpv-android/mpv-android#761]
### Important information

Android version: Android 13 (LineageOS 20)

mpv-android version: 2023-06-04 (F-Droid)

Which version of mpv-android introduced the problem (if known):

Device: OnePlus 9 Pro (lemonadep)

### Description

When having the following configuration in touch gestures:
- Horizontal Drag: Seek
- Vertical Drag: (left) None ~~(or also Volume)~~
- Vertical Drag: (right): Volume
- Double Tap (left and right): None
- Double Tap (center): Play/Pause

It seems like volume vertical drag (i have not tested other settings for vertical drag) seem to be limited to one half of the display, whereas the `Horizontal` `Seek` will work on either half of the display

The volume (or vertical) drag seems to be limited to always the right side (starting from exactly half) of the displayed contents orientation

### Log output

there are seemingly no logs for dragging up / down for volume (only seek has events)

### Additional information

happens on all types of videos (audio is untested, but i expect the same)

config (input and mpv) are basically default and empty

note: both having `Smoother Seeking` enabled or disabled does not have a effect
note: content aspect ratio (mpv black borders) do not seem to be related, because both filling and non-filling contents have the same behavior

Edit: in case more information can be gained (like screen sizes), [mpv.log](https://gist.github.com/hasezoey/147315aa997ed6cb0231952ed29aaae9)

**Comment by sfan5** [comment]
The mechanism is intentional of course
https://github.com/mpv-android/mpv-android/blob/master/app/src/main/java/is/xyz/mpv/TouchGestures.kt#L143-L146
but are you saying volume doesn't work if you configure it for "Vertical Drag (left)"?

**Comment by hasezoey** [comment]
>  but are you saying volume doesn't work if you configure it for "Vertical Drag (left)"?

no, my testing was not correct

---

i was under the assumption that it meant *dragging left(*(/up) and *dragging right*(/down), not limiting to *device half left* and *device half right*

that is also why i created #761
