### ISSUE TITLE
Poor performance using sw decoder

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#763]
Type the contents of your question here.
Hi I am trying to use sw decoder when tonemapping hdr to sdr however it is still slow play back I have added yuv420p format and vd-lavc-dr=no which really improved playback but still lagging is there anything else I can add or do

**Comment by sfan5** [comment]
Provide more information.

**Comment by Jamie666123** [comment]
My device is a Lenovo tab p11 plus and it’s improved with those two settings I have mentioned above but it still isn’t playing through smoothly
