### ISSUE TITLE
Figure out app bundle building

### ISSUE THREAD

**Issue by sfan5** [mpv-android/mpv-android#764]
Google is now forcing this

https://developer.android.com/build/building-cmdline#build_bundle

**Comment by da3dsoul1** [comment]
Google is being google again, are you sure you want to work with them? I mean fdroid and standalone compiled apks enough for most people using mpv-android as of now.

**Comment by sfan5** [comment]
mpv has about 95k installation base on Google Play. As annoying it may be I don't plan to leave those users behind.
