### ISSUE TITLE
Improve sw decoding playback 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#765]
Type the contents of your question here.
Hey I was trying to watch hdr to sdr tonemapped content using just sw decoding however the playback is stuttering I heard that setting vd-lavc-dr=no can help and it does however is there anything else I can add to this to get smooth sw decoding playback my device is a Lenovo tab p11 plus

**Comment by sfan5** [comment]
That's what the "Low-quality video decoding" option is for.
