### ISSUE TITLE
how to...

### ISSUE THREAD

**Issue by idontveapc** [mpv-android/mpv-android#767]
add a new input set in advaced>input.conf FOR SPEEDING UP VIDEO PLAYBACK when tapped or pressed(long), like i want video to play fast-forward when i press(left/centre/right) 2x times? :bowtie:

**Comment by bitingsock** [comment]
it would probably have to be a script since I think mpv only supports doubles input for mouse click:
https://mpv.io/manual/master/#command-interface-*-dbl

**Comment by sfan5** [comment]
You can bind one of the custom gestures to e.g. `cycle-values speed 1.0 2.0`
