### ISSUE TITLE
How do you get access to a file under a `content://` URI that you already have permissions for?

### ISSUE THREAD

**Issue by StratusFearMe21** [mpv-android/mpv-android#769]
I'm really sorry to have to ask this question here, which I acknowledge has a *very* loose relation to this project, but I've tried getting answers to this on StackOverflow, ChatGPT, Android Dev Discord, and I've spent hours reading docs. I am completely stumped on this, and I am very thankful for any time that you might give to my question

In an Android app that I'm developing, I ask the user to give my app permission to access a folder with this code
```kotlin
documentTreeOpener = registerForActivityResult(ActivityResultContracts.OpenDocumentTree()) {
    it?.let { root ->
        requireContext().contentResolver.takePersistableUriPermission(
            root, Intent.FLAG_GRANT_READ_URI_PERMISSION)

        Log.v("SettingsFragment", "${root.toString()}")
    }
}
documentTreeOpener.launch(null)
```
Once my app has gained that permission, from what I've seen in this codebase, I should just be able to use this code to access a file in any subdirectory of the URI I have permissions for right?
```kotlin
private fun openContentFd(uri: Uri): String? {
    val resolver = applicationContext.contentResolver
    Log.v("ForegroundService", "Resolving content URI: $uri")
    val fd = try {
        val desc = resolver.openFileDescriptor(uri, "r")
        desc!!.detachFd()
    } catch(e: Exception) {
        Log.e("ForegroundService", "Failed to open content fd: $e")
        return null
    }
    // See if we skip the indirection and read the real file directly
    val path = findRealPath(fd)
    if (path != null) {
        Log.v("ForegroundService", "Found real file path: $path")
        ParcelFileDescriptor.adoptFd(fd).close() // we don't need that anymore
        return path
    }
    // Else, pass the fd to mpv
    return "fd://${fd}"
}

private fun findRealPath(fd: Int): String? {
    var ins: InputStream? = null
    try {
        val path = File("/proc/self/fd/${fd}").canonicalPath
        if (!path.startsWith("/proc") && File(path).canRead()) {
            // Double check that we can read it
            ins = FileInputStream(path)
            ins.read()
            return path
        }
    } catch(e: Exception) { } finally { ins?.close() }
    return null
}
```

The problem is, say the user grants permissions on `content://com.android.externalstorage.documents/tree/1234-5678:Android/media/Music`, and I use the code above to access `content://com.android.externalstorage.documents/tree/1234-5678:Android/media/Music/Artist/Album/song.flac`. For whatever reason, I get this error
```
Failed to open content fd: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{ee6b253 25661:com.example.listenbrainzpoweramp/u0a290} (pid=25661, uid=10290) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
```
I'd really like to know what I'm missing here. Thanks so much in advance for taking the time out to help me if you do!

**Comment by StratusFearMe21** [comment]
IDK, apparently you have to be in scope of the activity result contract to use the ***"""persisted"""*** URI. Sooo... IDK

**Comment by sfan5** [comment]
> and I use the code above to access `content://com.android.externalstorage.documents/tree/1234-5678:Android/media/Music/Artist/Album/song.flac`.

I don't think you can just append components to the path like usual.
My code uses `DocumentsContract.buildChildDocumentsUriUsingTree` to do that.

**Comment by StratusFearMe21** [comment]
Yep, that was it! Thank you for the response!
