### ISSUE TITLE
Fire TV Stick 4K HWDEC not working

### ISSUE THREAD

**Issue by bitingsock** [mpv-android/mpv-android#770]
### Important information

Android version: 
Fire TV Stick 4k (1st gen 2018, mantis): Fire OS 6.2.9.8 (NS6298/4751)

mpv-android version:
2023-08-27 Build

Which version of mpv-android introduced the problem (if known):
I don't think it was a mpv-android version because I tried every build going back to [2022-03-23 Build](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2022-03-23) and still had issue.

### Description

I think a Fire OS update broke it because it use to work just fine about a month ago before my Stick got updated. ~This could be the same as https://github.com/mpv-android/mpv-android/issues/540~

### Log output

[log.txt](https://github.com/mpv-android/mpv-android/files/12459389/log.txt)

### Additional information

testing this file: http://0x0.st/H9FD.mkv

also tested a couple of [these](https://github.com/mpv-android/mpv-android/issues/540#issuecomment-1686425935) supposedly working files and still got the same problems.

here are the full traces for those attempts:
[log.txt](https://github.com/mpv-android/mpv-android/files/12461308/log.txt)
[log2.txt](https://github.com/mpv-android/mpv-android/files/12461309/log2.txt)

**Comment by bitingsock** [comment]
I'm just going to close this and move my findings there.

**Comment by bitingsock** [comment]
looking into it a bit,
```
[ffmpeg] AVHWDeviceContext: Disable createPersistentInputSurface
```
and
```
[ffmpeg/video] hevc_mediacodec: Both surface and native_window are NULL
[ffmpeg/video] hevc_mediacodec: Using surface 0x0
```
seem to be pretty relevant. Obviously hwdec will fail if it tries to draw to a null surface.
https://ffmpeg.org/doxygen/trunk/structAVMediaCodecDeviceContext.html
maybe enabling the auto create feature would work though I don't know from the description (or in general) if that would work for surfaces and not just windows

**Comment by bitingsock** [comment]
setting
```
vo=mediacodec_embed
```
succeeds in establishing a surface and a working hwdec but of course has all the drawbacks of using that vo
[log.txt](https://github.com/mpv-android/mpv-android/files/13230529/log.txt)

**Comment by sfan5** [comment]
Those messages are normal when using a copy hwdec, here's how that normally looks:
<pre>
11-20 18:24:27.441 20056 22017 V mpv     : [ffmpeg/video:error] h264_mediacodec: Both surface and native_window are NULL
11-20 18:24:27.441 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Using surface 0x0
11-20 18:24:27.548 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output crop parameters top=0 bottom=1079 left=0 right=1919, resulting dimensions width=1920 height=1080
11-20 18:24:27.548 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: MediaCodec started successfully: codec = OMX.Exynos.avc.dec, ret = 0
11-20 18:24:27.711 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output MediaFormat changed to {crop-right=1919, color-format=21, slice-height=1088, image-data=java.nio.HeapByteBuffer[pos=0 lim=104 cap=104], mime=video/raw, stride=1920, crop-bottom=1079, crop-left=0, width=1920, crop-top=0, height=1088}
11-20 18:24:27.711 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output crop parameters top=0 bottom=1079 left=0 right=1919, resulting dimensions width=1920 height=1080
11-20 18:24:27.770 20056 22017 V mpv     : [vd:info] Using hardware decoding (mediacodec-copy).
</pre>

and zero-copy hwdec for comparsion:
<pre>
11-20 18:22:51.890 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Using surface 0x712559e470
11-20 18:22:52.188 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output crop parameters top=0 bottom=1079 left=0 right=1919, resulting dimensions width=1920 height=1080
11-20 18:22:52.188 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: MediaCodec started successfully: codec = OMX.Exynos.avc.dec, ret = 0
11-20 18:22:52.381 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output MediaFormat changed to {crop-right=1919, color-format=261, slice-height=1088, mime=video/raw, stride=1920, color-standard=1, color-transfer=3, crop-bottom=1079, crop-left=0, width=1920, color-range=2, crop-top=0, height=1088}
11-20 18:22:52.382 20056 22017 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output crop parameters top=0 bottom=1079 left=0 right=1919, resulting dimensions width=1920 height=1080
11-20 18:22:52.383 20056 22017 V mpv     : [vd:info] Using hardware decoding (mediacodec).
</pre>

If you can get vo=mediacodec_embed working the zero-copy mode of vo=gpu (what mpv-android calls "<i>HW+</i>") should be working too.

**Comment by bitingsock** [comment]
```
vo=gpu
hwdec=mediacodec
```
fails with 
```
[  33.064][v][vd] Codec list:
[  33.064][v][vd]     hevc - HEVC (High Efficiency Video Coding)
[  33.064][v][vd]     hevc_v4l2m2m (hevc) - V4L2 mem2mem HEVC decoder wrapper
[  33.064][v][vd]     hevc_mediacodec (hevc) - H.265 Android MediaCodec decoder
[  33.064][v][vd] Opening decoder hevc
[  33.068][v][vd] Looking at hwdec hevc_mediacodec-mediacodec...
[  33.068][v][vo/gpu] Loading hwdec drivers for format: 'mediacodec'
[  33.068][v][vo/gpu] Loading hwdec driver 'aimagereader'
[  33.074][w][vo/gpu/aimagereader] Could not resolve symbol AImageReader_newWithUsage
[  33.075][v][vo/gpu] Loading failed.
[  33.077][v][vd] Could not create device.
[  33.077][v][vd] Using software decoding.
```
using defaults: HW+ does not show up as an option when trying to switch.
![image](https://github.com/mpv-android/mpv-android/assets/6302101/0bd64438-38b3-42d9-aa5d-4bfe1c244352)
[log.txt](https://github.com/mpv-android/mpv-android/files/13418007/log.txt)

**Comment by sfan5** [comment]
Ah I totally forgot, you need at least Android 8 for that.

Given these circumstances I don't see any bug here.
