### ISSUE TITLE
Shader failed to open when including two of them in mpv.conf 

### ISSUE THREAD

**Issue by gingercookies** [mpv-android/mpv-android#771]
Android version: Android 11 (MIUI Global 13.0.1)

mpv-android version:
![image](https://github.com/mpv-android/mpv-android/assets/77981365/817b9b4c-bb83-4398-a4bb-64aaa7f4f531)
Configuration: -Diconv=disabled -Dlua=enabled -Dlibmpv=true -Dcplayer=false -Dmanpage-build=disabled -Ddefault_library=shared --cross-file=/var/tmp/mpv-android/buildscripts/prefix/arm64/crossfile.txt

### Description

Included two shaders with glsl-shader option in mpv.conf file will cause: 
>mpv : [file:error] Cannot open file '/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl': No such file or directory
08-29 10:35:32.816 7610 7694 V mpv : [stream:error] Failed to open /storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl.

Included just one works fine

### Additional information

My mpv.conf:

> glsl-shaders="/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl"

### Log output

> --------- beginning of main
--------- beginning of system
08-29 10:35:22.352  7610  7610 V mpv     : FilePickerActivity: created
08-29 10:35:22.405  7610  7610 V mpv     : FilePickerActivity: showing file picker
08-29 10:35:22.645  7610  7610 W mpv     : default path set to "/sdcard" but no such storage volume
08-29 10:35:32.223  7610  7610 V mpv     : FilePickerActivity: file picked "/storage/5E83-B3C1/YTV/Tes.mp4"
08-29 10:35:32.448  7610  7610 V mpv     : Skipping copy of asset file (exists same size): subfont.ttf
08-29 10:35:32.448  7610  7610 V mpv     : Skipping copy of asset file (exists same size): cacert.pem
08-29 10:35:32.628  7610  7610 V mpv     : Display 0 reports FPS of 60.000004
08-29 10:35:32.641  7610  7610 V mpv     : You're using the 64-bit build of mpv!
08-29 10:35:32.641  7610  7694 V mpv     : [cplayer:v] mpv v0.36.0-184-ga19aefac37 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]  built on Aug 27 2023 22:25:00
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v] FFmpeg version: N-111830-gc48ec95ba3
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v] FFmpeg library versions:
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]    libavutil       58.17.100
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]    libavcodec      60.23.100
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]    libavformat     60.10.101
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]    libswscale      7.3.100
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]    libavfilter     9.11.100
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]    libswresample   4.11.100
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v]
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v] Configuration: -Diconv=disabled -Dlua=enabled -Dlibmpv=true -Dcplayer=false -Dmanpage-build=disabled -Ddefault_library=shared --cross-file=/var/tmp/mpv-android/buildscripts/prefix/arm64/crossfile.txt
08-29 10:35:32.642  7610  7694 V mpv     : [cplayer:v] List of enabled features: android android-media-ndk av-channel-layout avif_muxer build-date cplugins egl-android egl-helpers ffmpeg gl glibc-thread-name gpl jpegxl libass libavdevice libdl libm linux-fstatfs lua noexecstack opensles posix stdatomic threads vector vt.h zlib
08-29 10:35:32.650  7610  7694 V mpv     : [cplayer:v] Reading config file /data/user/0/is.xyz.mpv/files/mpv.conf
08-29 10:35:32.650  7610  7694 V mpv     : [file:v] Opening /data/user/0/is.xyz.mpv/files/mpv.conf
08-29 10:35:32.650  7610  7694 V mpv     : [cplayer:v] Applying profile 'default'...
08-29 10:35:32.650  7610  7694 V mpv     : [cplayer:v] Setting option 'glsl-shaders' = '/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl' (flags = 4)
08-29 10:35:32.650  7610  7694 V mpv     : [cplayer:v] Waiting for scripts...
08-29 10:35:32.654  7610  7694 V mpv     : [osd/libass:v] libass API version: 0x1701000
08-29 10:35:32.654  7610  7694 V mpv     : [osd/libass:v] libass source: commit: 0.17.0-55-g5c15c883a4783641f7e71a6a1f440209965eb64f
08-29 10:35:32.654  7610  7694 V mpv     : [osd/libass:v] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 8.1.1 (COMPLEX)
08-29 10:35:32.655  7610  7694 V mpv     : [osd/libass:v] Setting up fonts...
08-29 10:35:32.660  7610  7694 V mpv     : [osd/libass:info] can't find selected font provider
08-29 10:35:32.660  7610  7694 V mpv     : [osd/libass:v] Done.
08-29 10:35:32.666  7610  7694 V mpv     : [cplayer:v] Done loading scripts.
08-29 10:35:32.666  7610  7694 V mpv     : event: idle
08-29 10:35:32.747  7610  7610 W mpv     : attaching surface
08-29 10:35:32.749  7610  7694 V mpv     : event: start-file
08-29 10:35:32.761  7610  7694 V mpv     : [cplayer:v] Running hook: ytdl_hook/on_load
08-29 10:35:32.761  7610  7694 V mpv     : [ytdl_hook:v] ytdl:// hook
08-29 10:35:32.761  7610  7694 V mpv     : [cplayer:v] Set property: android-surface-size="1080x2400" -> 1
08-29 10:35:32.761  7610  7694 V mpv     : [ytdl_hook:v] not a ytdl:// url
08-29 10:35:32.761  7610  7694 V mpv     : [file:v] Opening /storage/5E83-B3C1/YTV/Tes.mp4
08-29 10:35:32.761  7610  7694 V mpv     : [demux:v] Trying demuxers for level=normal.
08-29 10:35:32.765  7610  7694 V mpv     : [lavf:v] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
08-29 10:35:32.770  7610  7610 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
08-29 10:35:32.771  7610  7610 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
08-29 10:35:32.800  7610  7694 V mpv     : [demux:v] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
08-29 10:35:32.800  7610  7694 V mpv     : [cplayer:v] Opening done: /storage/5E83-B3C1/YTV/Tes.mp4
08-29 10:35:32.801  7610  7694 V mpv     : [find_files:v] Loading external files in /storage/5E83-B3C1/YTV/
08-29 10:35:32.802  7610  7694 V mpv     : [cplayer:v] Running hook: ytdl_hook/on_preloaded
08-29 10:35:32.802  7610  7694 V mpv     : [lavf:v] select track 0
08-29 10:35:32.802  7610  7694 V mpv     : [lavf:v] select track 1
08-29 10:35:32.803  7610  7694 V mpv     : [cplayer:info]  (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
08-29 10:35:32.803  7610  7694 V mpv     : [cplayer:info]  (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
08-29 10:35:32.803  7610  7694 V mpv     : [vo/gpu/opengl:v] Initializing GPU context 'android'
08-29 10:35:32.803  7610  7694 V mpv     : [vo/gpu/opengl:v] EGL_VERSION=1.5 Android META-EGL
08-29 10:35:32.803  7610  7694 V mpv     : [vo/gpu/opengl:v] EGL_VENDOR=Android
08-29 10:35:32.803  7610  7694 V mpv     : [vo/gpu/opengl:v] EGL_CLIENT_APIS=OpenGL_ES
08-29 10:35:32.803  7610  7694 V mpv     : [vo/gpu/opengl:v] Trying to create GLES 2.x + context.
08-29 10:35:32.807  7610  7694 V mpv     : [vo/gpu/opengl:v] GL_VERSION='OpenGL ES 3.2 V@0502.0 (GIT@5eaa426211, I07ee46fc66, 1633700387) (Date:10/08/21)'
08-29 10:35:32.807  7610  7694 V mpv     : [vo/gpu/opengl:v] Detected GLES 3.2.
08-29 10:35:32.808  7610  7694 V mpv     : [vo/gpu/opengl:v] GL_VENDOR='Qualcomm'
08-29 10:35:32.808  7610  7694 V mpv     : [vo/gpu/opengl:v] GL_RENDERER='Adreno (TM) 610'
08-29 10:35:32.808  7610  7694 V mpv     : [vo/gpu/opengl:v] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 3.20'
08-29 10:35:32.812  7610  7694 V mpv     : [vo/gpu/opengl:v] Loaded extension GL_EXT_texture_norm16.
08-29 10:35:32.813  7610  7694 V mpv     : [vo/gpu/opengl:v] Loaded extension GL_EXT_disjoint_timer_query.
08-29 10:35:32.814  7610  7694 V mpv     : [vo/gpu/opengl:v] Loaded extension GL_EXT_buffer_storage.
08-29 10:35:32.815  7610  7694 V mpv     : [vo/gpu:v] Testing FBO format rgba16f
08-29 10:35:32.815  7610  7694 V mpv     : [vo/gpu:v] Using FBO format rgba16f.
08-29 10:35:32.815  7610  7694 V mpv     : [vo/gpu:v] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=1).
08-29 10:35:32.816  7610  7694 V mpv     : [file:error] Cannot open file '/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl': No such file or directory
08-29 10:35:32.816  7610  7694 V mpv     : [stream:error] Failed to open /storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl.
08-29 10:35:32.816  7610  7694 V mpv     : [vo/gpu:v] Assuming 60.000004 FPS for display sync.
08-29 10:35:32.817  7610  7694 V mpv     : [vd:v] Container reported FPS: 23.976024
08-29 10:35:32.819  7610  7694 V mpv     : [vd:v] Codec list:
08-29 10:35:32.820  7610  7694 V mpv     : [vd:v]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
08-29 10:35:32.820  7610  7694 V mpv     : [vd:v]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
08-29 10:35:32.820  7610  7694 V mpv     : [vd:v]     h264_mediacodec (h264) - H.264 Android MediaCodec decoder
08-29 10:35:32.820  7610  7694 V mpv     : [vd:v] Opening decoder h264
08-29 10:35:32.820  7610  7694 V mpv     : [vd:v] Looking at hwdec h264_mediacodec-mediacodec...
08-29 10:35:32.820  7610  7694 V mpv     : [vo/gpu:v] Loading hwdec drivers for format: 'mediacodec'
08-29 10:35:32.820  7610  7694 V mpv     : [vo/gpu:v] Loading hwdec driver 'aimagereader'
08-29 10:35:32.823  7610  7694 V mpv     : [vd:v] Trying hardware decoding via h264_mediacodec-mediacodec.
08-29 10:35:32.823  7610  7694 V mpv     : [vd:v] Using underlying hw-decoder 'h264_mediacodec'
08-29 10:35:32.824  7610  7694 V mpv     : [vd:v] Pixel formats supported by decoder: mediacodec
08-29 10:35:32.824  7610  7694 V mpv     : [vd:v] Codec profile: High (0x64)
08-29 10:35:32.824  7610  7694 V mpv     : [vd:v] Requesting pixfmt 'mediacodec' from decoder.
08-29 10:35:32.824  7610  7694 V mpv     : [ffmpeg/video:v] h264_mediacodec: Using surface 0x7049c7ae60
08-29 10:35:32.979  7610  7694 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output crop parameters top=0 bottom=719 left=0 right=1279, resulting dimensions width=1280 height=720
08-29 10:35:32.979  7610  7694 V mpv     : [ffmpeg/video:v] h264_mediacodec: MediaCodec started successfully: codec = OMX.qcom.video.decoder.avc, ret = 0
08-29 10:35:32.979  7610  7694 V mpv     : [vd:v] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
08-29 10:35:32.979  7610  7694 V mpv     : [vf:v] User filter list:
08-29 10:35:32.979  7610  7694 V mpv     : [vf:v]   (empty)
08-29 10:35:32.980  7610  7694 V mpv     : event: audio-reconfig
08-29 10:35:32.981  7610  7694 V mpv     : [ad:v] Codec list:
08-29 10:35:32.981  7610  7694 V mpv     : [ad:v]     aac - AAC (Advanced Audio Coding)
08-29 10:35:32.981  7610  7694 V mpv     : [ad:v]     aac_fixed (aac) - AAC (Advanced Audio Coding)
08-29 10:35:32.981  7610  7694 V mpv     : [ad:v] Opening decoder aac
08-29 10:35:32.981  7610  7694 V mpv     : [ad:v] Requesting 1 threads for decoding.
08-29 10:35:32.984  7610  7694 V mpv     : [ad:v] Selected codec: aac (AAC (Advanced Audio Coding))
08-29 10:35:32.984  7610  7694 V mpv     : event: audio-reconfig
08-29 10:35:32.985  7610  7694 V mpv     : event: file-loaded
08-29 10:35:32.985  7610  7694 V mpv     : [af:v] User filter list:
08-29 10:35:32.985  7610  7694 V mpv     : [af:v]   (empty)
08-29 10:35:32.985  7610  7694 V mpv     : [cplayer:v] Starting playback...
08-29 10:35:33.076  7610  7610 E mpv     : mpv_get_property(track-list/0/lang) format 1 returned error property unavailable
08-29 10:35:33.077  7610  7610 E mpv     : mpv_get_property(track-list/0/title) format 1 returned error property unavailable
08-29 10:35:33.078  7610  7694 V mpv     : event: audio-reconfig
08-29 10:35:33.078  7610  7694 V mpv     : event: video-reconfig
08-29 10:35:33.078  7610  7694 V mpv     : event: video-reconfig
08-29 10:35:33.078  7610  7694 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output MediaFormat changed to {crop-right=1279, color-format=2141391876, slice-height=1024, mime=video/raw, hdr-static-info=java.nio.HeapByteBuffer[pos=0 lim=25 cap=25], stride=1536, color-standard=1, color-transfer=3, crop-bottom=719, crop-left=0, width=1280, color-range=2, crop-top=0, height=720}
08-29 10:35:33.078  7610  7694 V mpv     : [ffmpeg/video:v] h264_mediacodec: Output crop parameters top=0 bottom=719 left=0 right=1279, resulting dimensions width=1280 height=720
08-29 10:35:33.078  7610  7694 V mpv     : [vd:info] Using hardware decoding (mediacodec).
08-29 10:35:33.078  7610  7694 V mpv     : [vd:v] Decoder format: 1280x720 [0:1] mediacodec bt.709/bt.709/bt.1886/limited/auto CL=unknown
08-29 10:35:33.078  7610  7694 V mpv     : [vf:v] [in] 1280x720 mediacodec bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [userdeint] 1280x720 mediacodec bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [userdeint] (disabled)
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [autorotate] 1280x720 mediacodec bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [autorotate] (disabled)
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [convert] 1280x720 mediacodec bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [convert] (disabled)
08-29 10:35:33.079  7610  7694 V mpv     : [vf:v] [out] 1280x720 mediacodec bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
08-29 10:35:33.079  7610  7694 V mpv     : [af:v] [in] 44100Hz stereo 2ch floatp
08-29 10:35:33.079  7610  7694 V mpv     : [af:v] [userspeed] 44100Hz stereo 2ch floatp
08-29 10:35:33.079  7610  7694 V mpv     : [af:v] [userspeed] (disabled)
08-29 10:35:33.079  7610  7694 V mpv     : [af:v] [convert] 44100Hz stereo 2ch floatp
08-29 10:35:33.079  7610  7610 E mpv     : mpv_get_property(track-list/1/title) format 1 returned error property unavailable
08-29 10:35:33.079  7610  7694 V mpv     : [ao:v] Trying audio driver 'audiotrack'
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v] requested format: 44100 Hz, stereo channels, floatp
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v] AudioTrack.nativeOutputSampleRate = 48000
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v] Channel layouts:
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v]  - mono
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v]  - stereo
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v]  - 3.0
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v]  - quad
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v]  - 5.0
08-29 10:35:33.079  7610  7694 V mpv     : [ao/audiotrack:v]  - 5.1
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v]  - 6.1(back)
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v]  - 7.1
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] result: stereo
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] Setting bufferSize = 52920 (driver=28288, min=26460, max=52920)
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] Using NIO ByteBuffer
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] Using API21 initializer
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] AudioTrack.getBufferSizeInFrames = 6615
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] device buffer: 6615 samples.
08-29 10:35:33.080  7610  7694 V mpv     : [ao/audiotrack:v] using soft-buffer of 8820 samples.
08-29 10:35:33.080  7610  7694 V mpv     : [cplayer:info] AO: [audiotrack] 44100Hz stereo 2ch float
08-29 10:35:33.080  7610  7694 V mpv     : [cplayer:v] AO: Description: Android AudioTrack audio output
08-29 10:35:33.080  7610  7694 V mpv     : [autoconvert:v] inserting resampler
08-29 10:35:33.080  7610  7694 V mpv     : [swresample:v] format change, reinitializing resampler
08-29 10:35:33.080  7610  7694 V mpv     : [swresample:v] 44100Hz stereo floatp -> 44100Hz stereo float
08-29 10:35:33.080  7610  7694 V mpv     : [af:v] [out] 44100Hz stereo 2ch float
08-29 10:35:33.080  7610  7694 V mpv     : [cplayer:info] VO: [gpu] 1280x720 mediacodec
08-29 10:35:33.080  7610  7694 V mpv     : [cplayer:v] VO: Description: Shader-based GPU Renderer
08-29 10:35:33.080  7610  7694 V mpv     : [vo/gpu:v] reconfig to 1280x720 mediacodec bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
08-29 10:35:33.080  7610  7694 V mpv     : [vo/gpu:v] Resize: 1080x2400
08-29 10:35:33.080  7610  7694 V mpv     : [vo/gpu:v] Window size: 1080x2400 (Borders: l=0 t=0 r=0 b=0)
08-29 10:35:33.080  7610  7694 V mpv     : [vo/gpu:v] Video source: 1280x720 (1:1)
08-29 10:35:33.080  7610  7610 V mpv     : auto rotation: aspect ratio = 1.7777778
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] Video display: (0, 0) 1280x720 -> (0, 896) 1080x607
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] Video scale: 0.843750/0.843056
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] OSD borders: l=0 t=896 r=0 b=897
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] Video borders: l=0 t=896 r=0 b=897
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] Reported display depth: 8
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] Testing FBO format rgba16f
08-29 10:35:33.081  7610  7694 V mpv     : [vo/gpu:v] Using FBO format rgba16f.
08-29 10:35:33.082  7610  7694 V mpv     : [file:error] Cannot open file '/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl': No such file or directory
08-29 10:35:33.082  7610  7694 V mpv     : [stream:error] Failed to open /storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl;/storage/5E83-B3C1/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl.
08-29 10:35:33.082  7610  7694 V mpv     : [cplayer:v] first video frame after restart shown
08-29 10:35:33.082  7610  7694 V mpv     : [cplayer:v] audio ready
08-29 10:35:33.082  7610  7694 V mpv     : [cplayer:v] starting audio playback
08-29 10:35:33.159  7610  7694 V mpv     : event: playback-restart
08-29 10:35:33.160  7610  7694 V mpv     : [cplayer:v] playback restart complete @ 0.000000, audio=playing, video=playing
08-29 10:35:33.163  7610  7694 V mpv     : [cplayer:warn] Audio device underrun detected.
08-29 10:35:33.163  7610  7694 V mpv     : [cplayer:v] restarting audio after underrun
08-29 10:35:33.263  7610  7610 E mpv     : mpv_get_property(track-list/0/lang) format 1 returned error property unavailable
08-29 10:35:33.263  7610  7610 E mpv     : mpv_get_property(track-list/0/title) format 1 returned error property unavailable
08-29 10:35:33.264  7610  7610 E mpv     : mpv_get_property(track-list/1/title) format 1 returned error property unavailable
08-29 10:35:33.461  7610  7610 E mpv     : mpv_get_property(track-list/0/lang) format 1 returned error property unavailable
08-29 10:35:33.462  7610  7610 E mpv     : mpv_get_property(track-list/0/title) format 1 returned error property unavailable
08-29 10:35:33.463  7610  7610 E mpv     : mpv_get_property(track-list/1/title) format 1 returned error property unavailable
08-29 10:35:33.464  7610  7610 V mpv     : auto rotation: aspect ratio = 1.7777778
08-29 10:35:33.475  7610  7610 V mpv     : auto rotation: aspect ratio = 1.7777778
08-29 10:35:33.602  7610  7694 V mpv     : [vo/gpu:v] Resize: 1080x2400
08-29 10:35:33.602  7610  7694 V mpv     : [vo/gpu:v] Window size: 1080x2400 (Borders: l=0 t=0 r=0 b=0)
08-29 10:35:33.602  7610  7694 V mpv     : [vo/gpu:v] Video source: 1280x720 (1:1)
08-29 10:35:33.603  7610  7694 V mpv     : [vo/gpu:v] Video display: (0, 0) 1280x720 -> (0, 896) 1080x607
08-29 10:35:33.603  7610  7694 V mpv     : [vo/gpu:v] Video scale: 0.843750/0.843056
08-29 10:35:33.603  7610  7694 V mpv     : [vo/gpu:v] OSD borders: l=0 t=896 r=0 b=897
08-29 10:35:33.603  7610  7694 V mpv     : [vo/gpu:v] Video borders: l=0 t=896 r=0 b=897
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Reported display depth: 8
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Resize: 2400x1080
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Window size: 2400x1080 (Borders: l=0 t=0 r=0 b=0)
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Video source: 1280x720 (1:1)
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Video display: (0, 0) 1280x720 -> (240, 0) 1920x1080
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Video scale: 1.500000/1.500000
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] OSD borders: l=240 t=0 r=240 b=0
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Video borders: l=240 t=0 r=240 b=0
08-29 10:35:33.607  7610  7694 V mpv     : [vo/gpu:v] Reported display depth: 8
08-29 10:35:33.607  7610  7694 V mpv     : [cplayer:v] Set property: android-surface-size="2400x1080" -> 1
08-29 10:35:45.556  7610  7694 V mpv     : [cplayer:v] Set property: pause -> 1

**Comment by sfan5** [comment]
`;` is not the list separator, `,` is.

**Comment by gingercookies** [comment]
> `;` is not the list separator, `,` is.

Oops, my fault.
Turn out i download the wrong version of mpv.conf of anime4k for windows
And it isn't `,` , it's `:` to separate shaders path
