### ISSUE TITLE
add .exo files extension support

### ISSUE THREAD

**Issue by idontveapc** [mpv-android/mpv-android#772]
Describe the wanted behaviour of the new feature and potential usecases for it here.

## Feature req.

add exo files support.

> they're cache files for caching videos, in the chunks of exo files, by youtube(but many other apps too).
> usually these files are playable, but only vlc or few file openers can play 
them.

**Comment by sfan5** [comment]
Without any sort of description what "exo" files really contain this isn't any useful.

**Comment by sfan5** [comment]
I mean technical documentation, not rough guesses.
This is something [ffmpeg](http://ffmpeg.org/) needs to implement anyway.
