### ISSUE TITLE
Fast forward/back forward pictures cannot be rendered in time

### ISSUE THREAD

**Issue by nabbenbi** [mpv-android/mpv-android#775]
mpv player

https://github.com/mpv-android/mpv-android/assets/144125138/7c466ae5-dc5d-4019-9212-79e9d131b894

mx player

https://github.com/mpv-android/mpv-android/assets/144125138/13e9fb2a-2c54-4a96-b75a-80ac0a6b9914
Both players use hw decoding. Is there any code I can add to the config to solve this problem? Because I personally don’t like using mx player very much.
My device is Android 12 Snapdragon 865

**Comment by sfan5** [comment]
Do not report bugs using the "question" template.
