### ISSUE TITLE
Build failed ../configure: line 5990: aarch64-linux-android-nm: command not found 

### ISSUE THREAD

**Issue by mandagod** [mpv-android/mpv-android#779]
### Important information

Android version:
android-ndk-r25c

mpv-android version:
mpv-android-2023-02-27

Which version of mpv-android introduced the problem (if known):
../configure: line 5990: aarch64-linux-android-nm: command not found
ERROR: dav1d >= 0.5.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

### Log output
../configure: line 5990: aarch64-linux-android-nm: command not found
ERROR: dav1d >= 0.5.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by sfan5** [comment]
The first message is merely a warning but has already been fixed (4905c4013d401f93043526c2db58364dc600b9f9), you're not using up-to-date sources.
The second could be caused by just about anything. Please provide the full build log.

**Comment by mandagod** [comment]
> The first message is merely a warning but has already been fixed ([4905c40](https://github.com/mpv-android/mpv-android/commit/4905c4013d401f93043526c2db58364dc600b9f9)), you're not using up-to-date sources. The second could be caused by just about anything. Please provide the full build log.

Fixed in master branch, Thanks
