### ISSUE TITLE
Build failed ERROR: dav1d >= 0.5.0 not found using pkg-config

### ISSUE THREAD

**Issue by mandagod** [mpv-android/mpv-android#781]
### Important information

Android version:
android-ndk-r25c

mpv-android version:
master branch
ci(4905c4013d401f93043526c2db58364dc600b9f9)

Which version of mpv-android introduced the problem (if known):

### Description

Building ffmpeg...
~/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/ffmpeg ~/Documents/Develop/BaseLib/mpv-android/buildscripts
ERROR: dav1d >= 0.5.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by mandagod** [comment]
Noticed that $PATH added the /opt/homebrew/bin/pkg-config.

**Comment by sfan5** [comment]
As I said, please provide the full build log.

**Comment by mandagod** [comment]
> As I said, please provide the full build log.

1. ./buildall.sh --arch arm64 mpv2
2. log is following
Preparing mpv...
Dependencies: ffmpeg libass lua
Preparing ffmpeg...
Dependencies: mbedtls dav1d
Preparing mbedtls...
Dependencies: 
Building mbedtls...
~/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/mbedtls ~/Documents/Develop/BaseLib/mpv-android/buildscripts
  CC    arc4.c
  CC    aes.c
  CC    asn1parse.c
  CC    aesni.c
  CC    src/asn1_helpers.c
  CC    base64.c
  CC    asn1write.c
  CC    bignum.c
  CC    aria.c
  CC    src/fake_external_rng_for_test.c
  CC    blowfish.c
  CC    src/helpers.c
  CC    src/psa_crypto_helpers.c
  CC    src/psa_exercise_key.c
  CC    camellia.c
  CC    src/random.c
  CC    ccm.c
  CC    chacha20.c
  CC    src/threading_helpers.c
  CC    chachapoly.c
  CC    src/drivers/hash.c
  CC    src/drivers/platform_builtin_keys.c
  CC    cipher.c
  CC    src/drivers/test_driver_aead.c
  CC    src/drivers/test_driver_cipher.c
  CC    src/drivers/test_driver_key_management.c
  CC    src/drivers/test_driver_mac.c
  CC    src/drivers/test_driver_signature.c
  CC    cipher_wrap.c
  CC    src/drivers/test_driver_size.c
  CC    src/test_helpers/ssl_helpers.c
  CC    cmac.c
  CC    constant_time.c
  CC    ctr_drbg.c
  CC    des.c
  CC    dhm.c
  CC    ecdh.c
  CC    ecdsa.c
  CC    ecjpake.c
  CC    ecp.c
  CC    ecp_curves.c
  CC    entropy.c
  CC    entropy_poll.c
  CC    error.c
  CC    gcm.c
  CC    havege.c
  CC    hkdf.c
  CC    hmac_drbg.c
  CC    md.c
  CC    md2.c
  CC    md4.c
  CC    md5.c
  CC    memory_buffer_alloc.c
  CC    mps_reader.c
  CC    mps_trace.c
  CC    nist_kw.c
  CC    oid.c
  CC    padlock.c
  CC    pem.c
  CC    pk_wrap.c
  CC    pk.c
  CC    pkcs12.c
  CC    pkcs5.c
  CC    pkparse.c
  CC    pkwrite.c
  CC    platform.c
  CC    platform_util.c
  CC    poly1305.c
  CC    psa_crypto.c
  CC    psa_crypto_aead.c
  CC    psa_crypto_cipher.c
  CC    psa_crypto_client.c
  CC    psa_crypto_ecp.c
  CC    psa_crypto_driver_wrappers.c
  CC    psa_crypto_hash.c
  CC    psa_crypto_mac.c
  CC    psa_crypto_rsa.c
  CC    psa_crypto_se.c
  CC    psa_crypto_slot_management.c
  CC    psa_crypto_storage.c
  CC    psa_its_file.c
  CC    ripemd160.c
  CC    rsa.c
  CC    rsa_internal.c
  CC    sha1.c
  CC    sha256.c
  CC    sha512.c
  CC    threading.c
  CC    timing.c
  CC    version.c
  CC    version_features.c
  CC    xtea.c
  CC    ../3rdparty/everest/library/everest.c
  CC    ../3rdparty/everest/library/x25519.c
  CC    ../3rdparty/everest/library/Hacl_Curve25519_joined.c
  CC    certs.c
  CC    pkcs11.c
  CC    x509.c
  CC    x509_create.c
  CC    x509_crl.c
  CC    x509_crt.c
  CC    x509_csr.c
  CC    x509write_crt.c
  CC    x509write_csr.c
  CC    debug.c
  CC    net_sockets.c
  CC    ssl_cache.c
  CC    ssl_ciphersuites.c
  CC    ssl_cli.c
  CC    ssl_cookie.c
  CC    ssl_msg.c
  CC    ssl_srv.c
  CC    ssl_ticket.c
  CC    ssl_tls.c
  CC    ssl_tls13_keys.c
  AR    libmbedcrypto.a
  AR    libmbedx509.a
  AR    libmbedtls.a
  CC    aes/crypt_and_hash.c
  CC    hash/generic_sum.c
  CC    pkey/dh_client.c
  CC    pkey/dh_server.c
  CC    hash/hello.c
  CC    pkey/dh_genprime.c
  CC    pkey/ecdh_curve25519.c
  CC    pkey/ecdsa.c
  CC    pkey/gen_key.c
  CC    pkey/key_app.c
  CC    pkey/key_app_writer.c
  CC    pkey/mpi_demo.c
  CC    pkey/pk_encrypt.c
  CC    pkey/pk_decrypt.c
  CC    pkey/pk_sign.c
  CC    pkey/pk_verify.c
  CC    pkey/rsa_decrypt.c
  CC    pkey/rsa_encrypt.c
  CC    pkey/rsa_genkey.c
  CC    pkey/rsa_sign.c
  CC    pkey/rsa_verify.c
  CC    pkey/rsa_sign_pss.c
  CC    pkey/rsa_verify_pss.c
  CC    psa/crypto_examples.c
  CC    psa/key_ladder_demo.c
  CC    psa/psa_constant_names.c
  CC    random/gen_entropy.c
  CC    random/gen_random_ctr_drbg.c
  CC    random/gen_random_havege.c
  CC    ssl/dtls_client.c
  CC    ssl/dtls_server.c
  CC    ssl/mini_client.c
  CC    ssl/ssl_client1.c
  CC    test/query_config.c
  CC    ssl/ssl_test_lib.c
  CC    ssl/ssl_fork_server.c
  CC    ssl/ssl_server.c
  CC    ssl/ssl_mail_client.c
  CC    test/benchmark.c
  CC    test/selftest.c
  CC    test/udp_proxy.c
  CC    test/zeroize.c
  CC    util/pem2der.c
  CC    util/strerror.c
  CC    x509/cert_req.c
  CC    x509/cert_app.c
  CC    x509/cert_write.c
  CC    x509/crl_app.c
  CC    x509/load_roots.c
  CC    x509/req_app.c
  CC    ssl/ssl_client2.c
  CC    ssl/ssl_context_info.c
  CC    ssl/ssl_server2.c
  CC    test/query_compile_time_config.c
 aarch64-linux-android21-clang common.o onefile.o fuzz_client.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_client
 aarch64-linux-android21-clang common.o onefile.o fuzz_dtlsclient.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_dtlsclient
 aarch64-linux-android21-clang common.o onefile.o fuzz_dtlsserver.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_dtlsserver
 aarch64-linux-android21-clang common.o onefile.o fuzz_privkey.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_privkey
 aarch64-linux-android21-clang common.o onefile.o fuzz_pubkey.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_pubkey
 aarch64-linux-android21-clang common.o onefile.o fuzz_server.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_server
 aarch64-linux-android21-clang common.o onefile.o fuzz_x509crl.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_x509crl
 aarch64-linux-android21-clang common.o onefile.o fuzz_x509crt.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_x509crt
 aarch64-linux-android21-clang common.o onefile.o fuzz_x509csr.o ../../tests/src/asn1_helpers.o ../../tests/src/fake_external_rng_for_test.o ../../tests/src/helpers.o ../../tests/src/psa_crypto_helpers.o ../../tests/src/psa_exercise_key.o ../../tests/src/random.o ../../tests/src/threading_helpers.o ../../tests/src/drivers/hash.o ../../tests/src/drivers/platform_builtin_keys.o ../../tests/src/drivers/test_driver_aead.o ../../tests/src/drivers/test_driver_cipher.o ../../tests/src/drivers/test_driver_key_management.o ../../tests/src/drivers/test_driver_mac.o ../../tests/src/drivers/test_driver_signature.o ../../tests/src/drivers/test_driver_size.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-O1,--icf=safe -o fuzz_x509csr
~/Documents/Develop/BaseLib/mpv-android/buildscripts
Preparing dav1d...
Dependencies: 
Building dav1d...
~/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d ~/Documents/Develop/BaseLib/mpv-android/buildscripts
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson setup --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
ninja: Entering directory `_build-arm64'
[1/5] Generating include/vcs_version.h with a custom command
ninja: Entering directory `_build-arm64'
[1/2] Installing files.
Installing src/libdav1d.a to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/lib
Installing tools/dav1d to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/bin
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/include/dav1d/common.h to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/include/dav1d
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/include/dav1d/data.h to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/include/dav1d
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/include/dav1d/dav1d.h to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/include/dav1d
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/include/dav1d/headers.h to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/include/dav1d
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/include/dav1d/picture.h to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/include/dav1d
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/_build-arm64/include/dav1d/version.h to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/include/dav1d
Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/_build-arm64/meson-private/dav1d.pc to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64/opt/homebrew/lib/pkgconfig
~/Documents/Develop/BaseLib/mpv-android/buildscripts
Building ffmpeg...
~/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/ffmpeg ~/Documents/Develop/BaseLib/mpv-android/buildscripts
ERROR: dav1d >= 0.5.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by sfan5** [comment]
> Installing /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/deps/dav1d/_build-arm64/meson-private/dav1d.pc to /Users/bytedance/Documents/Develop/BaseLib/mpv-android/buildscripts/prefix/arm64<b>/opt/homebrew</b>/lib/pkgconfig

Something in your environment is influencing the installation path, which breaks the build.
