### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by stokito** [mpv-android/mpv-android#782]
The WebDAV is an HTTP extension to work with files and folders. For example to get a list of files inside of directory call method PROPFIND.
The protocol is good for self hosting because unlike SMB it can be easily used over internet with HTTPS and Basic Authorization.
Could you please add an ability to open a WebDAV shared folder and store it as bookmark?

In the #496 it was said that the player is not a media center. But the change should be not too difficult to implement but it can improve UX significantly.

Currently the Nova Player is the only that works with WebDAV. It would be great to have at least one an alternative.

**Comment by sfan5** [comment]
Reading media from WebDAV URLs is easy, the protocol part must just be replaced by `http(s)://`.

> But the change should be not too difficult to implement but it can improve UX significantly.

Not really.
I'd need to deal with the webdav protocol or pull in a library to do it, stuff like basic auth also doesn't come for free and needs UI, a bookmark functionality does not exist yet.

As also mentioned in the other issue in general the better solution is to have a third-party app be the document provider that mpv-android can use via standard APIs.

**Comment by stokito** [comment]
When making a seek internally the player should perform a GET with [Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) header to get only a part of the video.
I'm not sure if some document provider will be fine with this.
If any such providers exists today that would be great. Still not sure if users will install it.
For the implementation you can use any http client library like OKHttp and you can just scrap all links to video files without even parsing the XML. This can also work for any plain HTML page with GET request.
Anyway, as you said this is out of scope of the app so I closing the FR.
Thank you for the answer.

**Comment by sfan5** [comment]
> When making a seek internally the player should perform a GET with [Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) header to get only a part of the video.
> I'm not sure if some document provider will be fine with this.

AFAIK document providers aren't really well suited for this since the file needs to be available locally, sort of.
For a seamless experience the file manager app would ideally just pass the http(s) URL to mpv.
