### ISSUE TITLE
inconsistent choosing of `mediacodec`(hw+) and `mediacodec-copy`(hw)?

### ISSUE THREAD

**Issue by hasezoey** [mpv-android/mpv-android#783]
i have noticed that it is rather inconsistent whether `mediacodec`(hw+) or `mediacodec-copy`(hw) is chosen, though i have found some relations on when something is chosen:

- opening the same file multiple times may sometimes choose "hw" and sometimes "hw+", choosing the same file again (if it was the last one opened / is cached, it almost certainly chooses `hw+`)
- toggling the hw/sw switch while it is still switching from some hw to sw, will almost certainly choose "hw"
- occasional hw/sw switching (while waiting for it to have switched) may choose either (even if "hw+" was previously working fine on the same instance)

(hw/sw switching as in "pushing the button", not opening up the manual selector)

(tested on the exact same file(s) and same device)

is this intended to be this inconsistent or is something in my setup wrong? (mainly asking about the "codec chosen on file open")

to my understanding `mediacodec`(non copy), at least in this case, should always be able to be chosen and should provide better battery efficiency because it does not need to copy anything back (if https://github.com/mpv-android/mpv-android/issues/623 is explanation is correct)

file(s) in question are `mkv` with `h264(high)` or `h265` & `aac`

### Additional information

android 13
mpv-android: 2023-08-27 (fdroid)

to my knowledge i have no filters enabled (aside from scaling?)

**Comment by sfan5** [comment]
I haven't noticed anything. Do you have a log file handy?

**Comment by hasezoey** [comment]
> Do you have a log file handy?

of what exactly? the manual switching or of opening files?

**Comment by sfan5** [comment]
Latter is probably more useful.

**Comment by hasezoey** [comment]
i have now actually done both

File open "HW" instead of "HW+":
[mpv_log_open_hw.txt](https://github.com/mpv-android/mpv-android/files/12677483/mpv_log_open_hw.txt)

(opening the same file again will likely choose "hw+", also manually choosing "hw+" will also work, though was not included in the log)

Fast switching before being ready:
[mpv_log_hw_sw_switching.txt](https://github.com/mpv-android/mpv-android/files/12677484/mpv_log_hw_sw_switching.txt)

what both have in common are the following lines:
```txt
V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to dequeue output buffer (status=-542398533)
V mpv     : [vd:warn] Error while decoding frame (hardware decoding)!
V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to dequeue output buffer (status=-542398533)
V mpv     : [vd:warn] Error while decoding frame (hardware decoding)!
V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to dequeue output buffer (status=-542398533)
V mpv     : [vd:warn] Error while decoding frame (hardware decoding)!
V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalStateException occurred
V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to flush codec
V mpv     : [vd:v] Attempting next decoding method after failure of h264_mediacodec-mediacodec.
```
(though i am sure they reach the illegal state differently)

also what i noticed is that "hw+" gets skipped (likely illegal state) more often with files that somehow either have a long latency from the server (like disk wakeup before being served or general latency) or have `[mkv:v] Deferring reading cues.` logged (likely the mkv cues element being at the end instead of the front of the file)

**Comment by sfan5** [comment]
By the way I looked at this weeks ago and the answer is :shrug:
