### ISSUE TITLE
`save-position-on-quit` how ?

### ISSUE THREAD

**Issue by asklow** [mpv-android/mpv-android#785]
I'm sorry about this noob question. I'm very familiar with mpv linux. But not sure how to get the exact same behaviors on android device. [Here's my desktop config](https://git.sr.ht/~asklow/home/tree/master/item/.config/mpv/mpv.conf). I did use `mpv.conf` from app settings, but it doesn't save or resume any media.

I just need saving watch position, as well as ability to delete watch-later content. How to achieve these ?

I've already read existing issues but none helped. None of them describe exactly how to configure configs. I've already searched for documentation, but you didn't provide any.

**Comment by sfan5** [comment]
The option in app settings should work. If it doesn't please open a new bug report with the right template
