### ISSUE TITLE
How can we edit mpv conf so that we can crop and completely hide OSD?

### ISSUE THREAD

**Issue by jbarry786** [mpv-android/mpv-android#786]
As the title says, I am looking to be able to crop a section of some videos when I play them (bottom bar) and also I would like to completely hide any info that spoils the length of a video (in this case it's sports games, so you cannot know the running time, otherwise it will spoil if it went to overtime etc).

Attaching a couple of screenshots, so you know what I want to crop out.

![Screenshot_20230923-163446424](https://github.com/mpv-android/mpv-android/assets/30951795/2b8184b5-af96-41f9-a190-24fab776225e)

![Screenshot_20230923-163446424](https://github.com/mpv-android/mpv-android/assets/30951795/e51c4d26-c988-4682-af77-5836b912a665)

On my PC, I can easily do this.

> vf=crop=in_w:in_h*0.928:0:0
>osc=no
 
I have tried for a long time to play around with the conf on mpv on android and never have been able to crop the video or hide the spoiling status bar/display.

So thought I'd ask here to see if what I want to achieve is possible on android or not.

The other question I have is:

Where can we find the mpv.conf file on android or is it possible to create a folder or file somewhere? It would be much easier to test the configurations if we could just edit the mpv.confi file directly.

So far I've had to do it via mpv -> settings -> advanced.

**So to sum up, questions:**

1. Can we crop a video on Android using the conf?
2. Can we totally hide the OSD/time bars, remaining time, total time on android... or for some reason there will always be that bar showing the time and elapsed bar (screenshot above=?
3. Can we switch to a different profile (with unique settings) by using input.conf? 
4. Where can we find or create the mpv.conf file so that we can more easily edit it?

### Additional information

Tested these settings and no cropping happened and also have that display above (I guess that bar may be external to mpv?)
![image](https://github.com/mpv-android/mpv-android/assets/30951795/4bde6889-805a-44e6-ad04-8d1b19e373f2)
 
Thanks in advance for the feedback and clearing these doubts for me. Tried hard to figure it out myself, but ended up giving up each single time :)

Hope my text made sense!

**Comment by ghdotc** [comment]
1. You can. For vf you need hw(mediacodec-copy) and not hw+(mediacodec)
2.  From what I understand OSC isn't from mpv itself and have no connection to configs from mpv.
3. I couldn't get 'apply-profile' to work even on a pc. Ofc if it's about that.
4. It's under /data/user/(userid)/mpv/files

**Comment by sfan5** [comment]
`vf=crop` will work, but not if you are using hardware decoding. Prefer mpv's native cropping options.

`osc=no` has no effect because the mpv-android UI is completely external to mpv.

Or directly your questions:
1. yes
2. not possible (atm)
3. yes
4. it's in the app data folder, you can't access it from other apps (unless your device is rooted)
