### ISSUE TITLE
Audio channels are swapped using audiotrack

### ISSUE THREAD

**Issue by gamernoob24** [mpv-android/mpv-android#789]
### Important information

Android version:

Android version 12
Api version 31
mpv-android version:

This version of mpv is self build

```
  mpv 0.35.0-501-g48e0ee9979 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
  built on Wed Jul 05 03:14:54 2023
 FFmpeg version: N-111338-gd694c25b44
 FFmpeg library versions
    libavutil       58.14.100
    libavcodec      60.22.100
    libavformat     60.10.100
    libswscale      7.3.100
    libavfilter     9.8.102
    libswresample   4.11.100
 
 Configuration: -Diconv=disabled -Dlua=enabled -Dlibmpv=true -Dcplayer=false -Dmanpage-build=disabled -Ddefault_library=shared --cross-file=/home/jess/mpv-android/buildscripts/prefix/arm64/crossfile.txt
List of enabled features: android android-media-ndk av-channel-layout avif_muxer build-date cplugins egl-android egl-helpers ffmpeg gl glibc-thread-name gpl jpegxl libass libavdevice libdl libm linux-fstatfs lua noexecstack opensles posix stdatomic threads vector vt.h zlib
```

Which version of mpv-android introduced the problem (if known):
None
### Description

Using 
`ao=audiotrack`
swaps the audio channels while
`ao=opensles`
Doesn't but it wont pickup audio equalizers (specifically ViPER4Android FX)

### Log output

https://0x0.st/HVEW.txt

### Additional information

Here is my full mpv.conf

```
ao=audiotrack

log-file=/sdcard/aaa.txt

#msg-level=all=info

#hwdec=mediacodec-copy

#hwdec-codecs=all

#af=asubboost=dry=0.01:wet=1:boost=12

#af=pan="stereo|c0=c1|c1=c0"
```

you can ignore the lines starting with # 
As I only changed the ``ao`` setting
Also ``af=pan="stereo|c0=c1|c1=c0"`` was my workaround for switching the channels
but it screw up when I play videos that has audio beyond 2 channels (eg. 5.1, 7.1)

**Comment by syphyr** [comment]
This seems like an issue with mpv, not mpv-android.

**Comment by sfan5** [comment]
can you check if mpv-android [2023-06-04](https://github.com/mpv-android/mpv-android/releases/tag/2023-06-04) also has this issue?
If not, this could be a regression from my recent changes.

**Comment by gamernoob24** [comment]
i updated to the latest release and still has the issue
so i had to downgrade a bit more until this version works
https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2021-10-10

**Comment by sfan5** [comment]
If you go back that far you probably hit a version that does not contain ao_audiotrack and/or defaults to opensles.
Anyway I tested using [this file](http://www.aoakley.com/articles/2018-08-24-stereo-test.php) and headphones and the channels are correct.

**Comment by gamernoob24** [comment]
I did test it my other phone (J500H) and yes the channels are correct
On the latest version 
but on my main phone (Infinix X6815C) the channels are swapped

but I can confirm that version is on audiotrack
https://0x0.st/HVGN.txt

**Comment by sfan5** [comment]
Possibly relevant change between 2021-10-10 and 2021-10-28: https://github.com/mpv-player/mpv/commit/7356ee53392befbdf5e1e36fb03c972fdb5534ef
However I'm more convinced that it's your audio equalizer plugin messing the channels up at the moment...

**Comment by gamernoob24** [comment]
> However I'm more convinced that it's your audio equalizer plugin messing the channels up at the moment...

both phones have ViPER4Android FX
and only my main phone has this issue 

and it still has the issue even if my equalizer is uninstalled

**Comment by gamernoob24** [comment]
Welp I don't have time to look at the code but my other alternative solutions
(on my main phone) is to not use the headphone jack
Bluetooth and USB audio work perfectly for some reason
I am probably not going to use MPV as my main audio player
and will still use this as my video player

**Comment by syphyr** [comment]
Since the stereo issue is only with headphone jack and not bluetooth, then It's probably the mixer settings for your rom.
