### ISSUE TITLE
Dex Support/ Background play

### ISSUE THREAD

**Issue by zhunsaker** [mpv-android/mpv-android#79]
Don't know if this is possible, but background play support would be awesome, i'm using the Samsung dex dock and was wondering how difficult it would be to add support for window resizing and background play on the dex dock. The documentation on modifying is here:

http://developer.samsung.com/samsung-dex/modify-optimizing

I am more than happy to test or provide screenshots/whatever is necessary. I have done some programming but never android, if someone can point me in the right direction I could possibly try to do a PR..

**Comment by sfan5** [comment]
Sounds like we just need multi-window support for this to work.
And perhaps the `keepalive` property and possibly(?) saving of playback state (#62).

**Comment by sfan5** [comment]
@zhunsaker
I just implemented multi-window support in ec523bfe442f5905368bab26e54048ea247867c1, please check whether this is enough for Samsung Dex to work.
