### ISSUE TITLE
About cache

### ISSUE THREAD

**Issue by spavlovich001** [mpv-android/mpv-android#796]
1. what is the default cache value? I hope the cache is disabled by default?

2. Which parameter is responsible for forcibly disabling the cache?

**Comment by sfan5** [comment]
1:
https://github.com/mpv-android/mpv-android/blob/7664eda8f67166d3ed7ab88d05f0c38e8aff8fb8/app/src/main/java/is/xyz/mpv/MPVView.kt#L119-L123

2:
Set the same option or read the manual for other alternatives.

**Comment by spavlovich001** [comment]
Thanks!

3. Is the cache on disk or in memory?

**Comment by sfan5** [comment]
In RAM.
