### ISSUE TITLE
4k video won't open on TV

### ISSUE THREAD

**Issue by spavlovich001** [mpv-android/mpv-android#798]
1. Open file(54gb) in Cx File Explorer(smb) and see a black screen. Video won't start
2. hardware: xiaomi q2 55"

**Comment by sfan5** [comment]
Issue template?

**Comment by spavlovich001** [comment]
> Issue template?

I can’t do adb logcat on a TV. mpv version is the latest

**Comment by conceptrat** [comment]
Try the following (I know it's for a Sony but most Android TV support this like my LG)
http://stackoverflow.com/questions/39834242/ddg#39839668
