### ISSUE TITLE
Freezes after a pause

### ISSUE THREAD

**Issue by spavlovich001** [mpv-android/mpv-android#799]
1. I turn on any video (avi, mkv) on hw+. I'm putting it on pause. I press pause and mpv starts playing the video for 0.1 seconds and freezes tightly. When sw is turned on, this does not happen
2. hardware: xiaomi q2 55"(4 x 1500GHz • ARM Cortex-A55  + Mali G52 MP2)

**Comment by sfan5** [comment]
Fill in the issue template.

**Comment by spavlovich001** [comment]
> Fill in the issue template.

I can’t do adb logcat on a TV. mpv version is the latest

**Comment by spavlovich001** [comment]
> Fill in the issue template.

So maybe we can do something so that we don’t have to use adb logcat? So that, for example, the debug log is generated in storage/emulated/0/mpv/debug.log? and in the mpv.conf setting it was possible to specify debug=yes?

**Comment by sfan5** [comment]
I have considered enabling that but a problem is that a log would only contain why libmpv has logged, not anything of the Java/C code in mpv-android.
btw I'm pretty sure most TVs have some sort of developer mode that enables you to use adb over WiFi.

**Comment by spavlovich001** [comment]
> I have considered enabling that but a problem is that a log would only contain why libmpv has logged, not anything of the Java/C code in mpv-android. btw I'm pretty sure most TVs have some sort of developer mode that enables you to use adb over WiFi.

https://stackoverflow.com/questions/53816074/write-all-exception-in-file
