### ISSUE TITLE
Xperia 1 V no 4K output

### ISSUE THREAD

**Issue by NikoofDeath** [mpv-android/mpv-android#802]
### Important information

Android version: 13

mpv-android version: 2023-08-27 release

### Description

I am using an Xperia 1 V, which (along with the rest of the Xperia phones with 4K displays) without modification will only use the full 4K display resolution in specific use cases (primarily video playback), rendering at 2560x1096 otherwise. Unfortunately there isn't (as far as I know) detailed documentation from Sony on how exactly the system works, and how developers can natively support it.
Regardless, both MX Player and VLC appear to work fine displaying 4K videos (without, as far as I'm aware, explicit support from either Sony or the app developers), whereas MPV does not. As an example, here are screenshots of each player displaying a test pattern video
![MX](https://github.com/mpv-android/mpv-android/assets/9629341/6fe2bcb2-15c4-45ef-b4d9-a24cdd975c2b)
![VLC](https://github.com/mpv-android/mpv-android/assets/9629341/81c75d80-e8d4-4d8b-ab6a-82abbf9b9127)
![MPV](https://github.com/mpv-android/mpv-android/assets/9629341/85fdc10e-a419-42fd-8e02-e6c0b718e6d5)
Unfortunately, my brief skimming of VLC's logs when displaying 4K video did not show any clear point where the 4k display was recognized, all the logs about the output resolution appeared to treat it as a 2560x1096 display. Given that in both VLC and MX the 4K output appears to only work whe using HW acceleration, I assume this means the phone is doing some trickery when the app is passing the video off to the hardware, that the app does not have any part in. By extension, I assume it not working MPV is due to some sort of bug in the hardware acceleration, not a missing feature.
Since it is a relatively obscure device (and again, lacks the documentation it really should have), I realize this may be difficult to work on, so please let me know any information or testing I can provide to help find a solution.

**Comment by sfan5** [comment]
If you provide logcat output and do this https://github.com/mpv-android/mpv-android/issues/293#issuecomment-667973890 then I can take a closer look. Can't promise a fix however.

**Comment by NikoofDeath** [comment]
For reference, heres mx's logcat opening the same video:
[Log_2023-10-23_10-36-59.txt](https://github.com/mpv-android/mpv-android/files/13072096/Log_2023-10-23_10-36-59.txt)

**Comment by sfan5** [comment]
Your dumpsys output indeed shows 1096x2560 as display resolution with 1644x3840 as an alternative mode.
The mpv log is unfortunately junk, none of the relevant mpv lines are in there.

> Regardless, both MX Player and VLC appear to work fine displaying 4K videos (without, as far as I'm aware, explicit support from either Sony or the app developers)

I could imagine that vlc does something to request the system change its resolution to the highest available, but this is only a guess and I don't have time to dig through the code right now.
