### ISSUE TITLE
major delay when entering/exiting background

### ISSUE THREAD

**Issue by lucas-mior** [mpv-android/mpv-android#803]
### Important information

Android version: 10

mpv-android version: 32

### Description

I have set `background playback` for video in the settings.
It works, however, everytime I press the button on my phone to turn the screen off,
it takes seconds for the playback to resume.
The same thing happens when I press it again and unlock the phone.

I've tried other video players, but most don't support this feature.
VLC does, and does not have the delay, however when unlocking and reopening,
only audio is playing and I have to manually enable video again, and then the video comes all messed up.

Brave browser is perfect for video playback, it works flawlessly both for local videos and youtube videos,
however for local videos, I have to go through multiple prompts from my file manager to select brave as the video opener.
I am describing other programs just to make it clear that it is possible to have a smooth experience.

Thanks in advance.

**Comment by sfan5** [comment]
To diagnose this issue I will need the information indicated in the issue template.

**Comment by biopsin** [comment]
related to  #239

**Comment by lucas-mior** [comment]
@sfan5 is the issue supposed to be fixed or you are closing in favor of #239? Thanks.

**Comment by sfan5** [comment]
You have not provided the information needed to diagnose the issue.
It is probably a duplicate anyway.
