### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by Hesidv** [mpv-android/mpv-android#804]
ANR in is.xyz.mpv (is.xyz.mpv/.MPVActivity)
PID: 22652
Reason: Input dispatching timed out (74be08c is.xyz.mpv/is.xyz.mpv.MPVActivity (server) is not responding. Waited 5000ms for MotionEvent)
Parent: is.xyz.mpv/.MPVActivity
ErrorId: 7bbdf12b-6e9b-4ce4-9fc9-ad4facfca269
Frozen: false
Load: 3.24 / 3.69 / 3.78
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.06 avg300=0.12 total=40870425
full avg10=0.00 avg60=0.03 avg300=0.05 total=24351017
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=1.19 avg60=2.39 avg300=3.01 total=3650620317
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=0.04 avg60=0.28 avg300=0.46 total=381662306
full avg10=0.01 avg60=0.14 avg300=0.25 total=265583856
----- End output from /proc/pressure/io -----
CPU usage from 12260ms to 0ms ago (2023-10-27 00:37:58.946 to 2023-10-27 00:38:11.206) with 99% awake:
  88% 22652/is.xyz.mpv: 75% user + 12% kernel / faults: 5967 minor
  14% 567/surfaceflinger: 10% user + 4.5% kernel / faults: 40 minor
  10% 1240/media.codec: 0.5% user + 10% kernel / faults: 8 minor
  3.3% 1617/system_server: 2% user + 1.3% kernel / faults: 1679 minor
  2.6% 667/android.hardware.graphics.composer@2.1-service: 1.3% user + 1.2% kernel / faults: 4 minor
  2.5% 2605/com.android.systemui: 1.8% user + 0.7% kernel / faults: 418 minor
  1.9% 6510/com.f0x1d.logfox: 1.6% user + 0.3% kernel / faults: 2093 minor
  1.5% 532/irq/27-1008000.: 0% user + 1.5% kernel
  1.2% 967/audioserver: 1.1% user + 0% kernel
  1% 9940/mdss_fb0: 0% user + 1% kernel
17% TOTAL: 11% user + 5.3% kernel + 0% iowait + 0.5% irq + 0.1% softirq
CPU usage from 37ms to 629ms later (2023-10-27 00:38:11.243 to 2023-10-27 00:38:11.835):
  110% 1617/system_server: 42% user + 67% kernel / faults: 5262 minor
    54% 22761/AnrAuxiliaryTas: 11% user + 42% kernel
    38% 1672/Signal Catcher: 22% user + 15% kernel
    4.5% 2426/binder:1617_3: 4.5% user + 0% kernel
    4.5% 2573/GameManagerServ: 2.2% user + 2.2% kernel
    2.2% 1904/android.anim.lf: 2.2% user + 0% kernel
    2.2% 22760/AnrConsumer: 0% user + 2.2% kernel
  105% 22652/is.xyz.mpv: 91% user + 14% kernel / faults: 67 minor
    102% 22702/mpv/audiotrack: 87% user + 14% kernel
    7.2% 22694/MediaCodec_loop: 3.6% user + 3.6% kernel
    3.6% 22678/Thread-4: 3.6% user + 0% kernel
  49% 567/surfaceflinger: 36% user + 12% kernel / faults: 6 minor
    22% 567/surfaceflinger: 16% user + 5.5% kernel
    14% 586/RenderEngine: 12% user + 1.8% kernel
    7.3% 701/surfaceflinger: 5.5% user + 1.8% kernel
    1.8% 695/appSf: 1.8% user + 0% kernel
    1.8% 2467/binder:567_3: 1.8% user + 0% kernel
  44% 7918/com.google.android.inputmethod.latin: 25% user + 19% kernel / faults: 5967 minor
    41% 7941/Signal Catcher: 22% user + 19% kernel
    2.7% 7948/HeapTaskDaemon: 2.7% user + 0% kernel
  21% 2605/com.android.systemui: 16% user + 4.7% kernel / faults: 92 minor
    14% 2758/RenderThread: 11% user + 2.3% kernel
    2.3% 2605/ndroid.systemui: 2.3% user + 0% kernel
    2.3% 12685/binder:2605_D: 2.3% user + 0% kernel
  7.3% 667/android.hardware.graphics.composer@2.1-service: 1.8% user + 5.5% kernel
    5.5% 667/composer@2.1-se: 1.8% user + 3.6% kernel
  10% 3941/com.android.nfc: 7.8% user + 2.6% kernel / faults: 826 minor
    10% 4003/Signal Catcher: 7.8% user + 2.6% kernel
  10% 3965/.dataservices: 7.8% user + 2.6% kernel / faults: 803 minor
    10% 4034/Signal Catcher: 7.8% user + 2.6% kernel
  1.6% 9/rcu_preempt: 0% user + 1.6% kernel
  1.6% 10/rcu_sched: 0% user + 1.6% kernel
  1.7% 70/rcuop/7: 0% user + 1.7% kernel
  1.7% 273/kgsl_worker_thr: 0% user + 1.7% kernel
  1.8% 518/logd: 1.8% user + 0% kernel
  2.7% 6510/com.f0x1d.logfox: 2.7% user + 0% kernel / faults: 79 minor
    2.7% 6539/DefaultDispatch: 2.7% user + 0% kernel
  2.8% 9927/kworker/u16:12: 0% user + 2.8% kernel
  3.1% 14956/kworker/0:0: 0% user + 3.1% kernel
  3.5% 22291/kworker/6:2H: 0% user + 3.5% kernel
46% TOTAL: 26% user + 17% kernel + 0.4% iowait + 0.8% irq + 0.2% softirq
Completed ANR of is.xyz.mpv in 1602ms, latency 0ms

**Comment by sfan5** [comment]
That's not a crash.
