### ISSUE TITLE
Pixel 8 Pro Line Artifacts

### ISSUE THREAD

**Issue by Cheakerdoodels** [mpv-android/mpv-android#805]
### Important information

Android version: 14

mpv-android version: 2023-08-27-release / 8032

### Description

Videos on Pixel 8 Pro show occasional odd vertical lines randomly during playback they happen more often with HW+ on. but I have seen them with it on SW. I don't have a second P8Pro to test if it is a one device issue but I have seen absolutely no signs of graphics issues or artifacts on any other video player application on either SW or HW decoding nor any issues at all in gpu intensive 2d or 3d applications. 

Same files played on same mpv and android version on a Pixel 5a play with no lines

Video files used were h264 and will usually show issue within a minute of viewing.

**Comment by sfan5** [comment]
Log file?
