### ISSUE TITLE
Cannot invoke "java.io.File.equals(Object)" because "current" is null

### ISSUE THREAD

**Issue by GitUMini** [mpv-android/mpv-android#806]
I got an error when i build this project.

(The latest code downloaded in github)
(Android studio on Windows10 1809)

### Additional information
> Task :app:dexBuilderDefaultDebug
> Task :app:mergeProjectDexDefaultDebug
> Task :app:mergeDefaultDebugJavaResource

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDefaultDebugJniLibFolders'.
> Cannot invoke "java.io.File.equals(Object)" because "current" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 29s

**Comment by sfan5** [comment]
Sounds like you didn't build the native dependencies. Windows is not supported for building them.

**Comment by GitUMini** [comment]
> Sounds like you didn't build the native dependencies. Windows is not supported for building them.

Can  I use libmpv.so instead of these native scripts?

**Comment by sfan5** [comment]
What?

**Comment by GitUMini** [comment]
Solved

**Comment by rohitghali** [comment]
> Solved

How? Trying to build on windows.

**Comment by bnichs5** [comment]
Running into the same issue as you. How did you manage to fix this error?

**Comment by rohitghali** [comment]
> Running into the same issue as you. How did you manage to fix this error?

I think it's an out of memory issue. I don't remember how I solved it, but I think I tried running it again and again and it worked. Is your page file memory enabled?

**Comment by waseemhehe** [comment]
@GitUMini brother how u resolve this issue, do u have libmpv.so file ???
