### ISSUE TITLE
Add reset button to speed dialog

### ISSUE THREAD

**Issue by foxjaw** [mpv-android/mpv-android#807]
Playback speed seeker has a wide range. It's better to have two buttons `+` & `-` beside the seekbar for accurate speed positioning.

**Comment by foxjaw** [comment]
This isn't in the oct build. Will be in the new release ?

**Comment by sfan5** [comment]
Sorry, I confused this with another part of the UI.
Do you really need to enter speed values more precise than 0.05? Or higher than 6?

**Comment by foxjaw** [comment]
I actually need button interface instead of a slider. Precision is not the preference.  
I'm have fat fingers lmao.

**Comment by sfan5** [comment]
Maybe a reset button would be good then?

**Comment by foxjaw** [comment]
Yup
