### ISSUE TITLE
Question: Should mpv-android support libunibreak/libass already and line break long CJK subtitles?

### ISSUE THREAD

**Issue by escape0707** [mpv-android/mpv-android#808]
Recently I filed an issue related to long CJK subtitle line break in the mpv repo here: https://github.com/mpv-player/mpv/issues/12851
Before I wrote up that issue, I reproduced the same problem with mpv-android installed from Google Play. But it turns out that the PC version's problem cause is lacking libunibreak as a runtime dependency for libass. Then I tried some simple search in this repo but I can't find the code change introduced by the pull request mentioned in the upstream mpv issue.

So, my question is, is mpv-android rebased to include upstream CJK subtitle line break already? Will there be an addition to include libunibreak as a runtime dependency for libass some day? 

Thanks for reading my question.

**Comment by sfan5** [comment]
I'll check how bothersome it is to include libunibreak.
