### ISSUE TITLE
How to load shaders in MPV Android?

### ISSUE THREAD

**Issue by arianaa30** [mpv-android/mpv-android#810]
So far I am loving MPV! I came up with some shaders ([here](https://github.com/bloc97/Anime4K)) that I load in the Windows MPV and it works perfectly. But how can I load these shaders on the Android MPV? 

I edited the `mpv.conf` with the locations of the shaders as below (I just copied them from the Windows shaders and replaced some with `S` version:

`glsl-shaders="/storage/self/primary/Documents/shaders/Anime4K_Clamp_Highlights.glsl;/storage/self/primary/Documents/shaders/Anime4K_Restore_CNN_S.glsl;/storage/self/primary/Documents/shaders/Anime4K_Upscale_CNN_x2_S.glsl;/storage/self/primary/Documents/shaders/Anime4K_AutoDownscalePre_x2.glsl;/storage/self/primary/Documents/shaders/Anime4K_AutoDownscalePre_x4.glsl;/storage/self/primary/Documents/shaders/Anime4K_Upscale_CNN_x2_S.glsl"`

But now that I have these, how to enable them? Do I need to enter anything in the `input.conf` as well? 

![image](https://github.com/bloc97/Anime4K/assets/5509837/01ecd40e-36b4-48f2-a0d6-19f5929444a9)

**Comment by arianaa30** [comment]
I do toggle 2 when playing video..nothing there. Also, I don't notice any file permissions errors in logcat.
I put the shaders under Android Documents/cache/mpv/shaders.

Do I need to change the input.conf as well?

**Comment by sfan5** [comment]
You don't.

**Comment by arianaa30** [comment]
Ok..not sure what's missing 🤔

**Comment by arianaa30** [comment]
How to do stats lua?

**Comment by sfan5** [comment]
Settings > Developer > Show stats
