### ISSUE TITLE
Frame traverse in Android MPV

### ISSUE THREAD

**Issue by arianaa30** [mpv-android/mpv-android#812]
Are these two important features present in the Android MPV?

1. I want to go to a specific frame/time. How to do that?
2. Enable/Disable user shaders. Is there a way to do that? We need it to compare the visual comparisons of a video frame before/after applying a shader.

**Comment by sfan5** [comment]
You can try bind frame stepping or any other commands to gestures, and then also do that with the command you need to toggle shaders.

**Comment by arianaa30** [comment]
I realized in Android studio the keyboard shortcut works. Is there a shortcut to toggle shaders?

**Comment by sfan5** [comment]
You can see available shortcuts in the mpv manual and also define your own.
