### ISSUE TITLE
input.conf `no-osd` command prefix has no effect

### ISSUE THREAD

**Issue by rkitover** [mpv-android/mpv-android#813]
Android version:
`11`

mpv-android version:
`2023-08-27-release`

I have the following in my `input.conf`:

````console
REWIND no-osd seek -3 exact
FORWARD no-osd seek 3 exact
PLAYPAUSE no-osd cycle pause
````
, the keys function, however, the `no-osd` command prefix does not stop the interface from popping up.

An identical configuration for mpv on Windows works correctly, with nothing popping up when I press the keys.

This is annoying for me because I'm watching Anime with subtitles and I want to use these keys so I can pause to read the subtitles or skip back to read text I missed, and the interface is on the bottom where the subtitles are.

Thank you for this amazing project.

**Comment by sfan5** [comment]
This is effectively not something I can fix since the `no-osd` piece of information only exists inside mpv and the UI is entirely on the Java side with no knowledge of this.

**Comment by sfan5** [comment]
The best mpv could do is expose osd visiblity as a property but even in that case it'll be hard to properly "merge" this into mpv-android's internal UI state.

**Comment by sfan5** [comment]
> you are saying the UI is entirely on Java side so the command has no effect. Why is that? Can't the entire UI be MPV only?

To get any amount of integration with the rest of Android (UI look and feel, file I/O, ...) you need to write your GUI in Java or Kotlin.

The most realistic fix here is to change the mpv-android UI to *not* show up for every key that is pressed. (why does it do that actually?)
