### ISSUE TITLE
HW Decode fail

### ISSUE THREAD

**Issue by InnovatorSteve** [mpv-android/mpv-android#814]
DEVICE (2)
-->

phenomenon：
By logcat view, i can see already open the hardware decoder, and successfully decoded image, after the first delivery to the display of fd, notifyFillBufferDone calls are normal, but haven't call renderOutputBufferAndRelease by MPV.
The screen keeps black screen，When I kill the mediaserver process, the mpv can normally fall back to toSys mode for hard decode playback, but the cpu usage is high, that's not what I was hoping for.
In addition，codec can play normal in toFd mod with same env.
I'm not sure if it's a bug or if it requires additional configuration.

**Comment by sfan5** [comment]
The log is cut off. In the visible part I don't see any errors.

**Comment by fengchao-wei** [comment]
CompositionEngine: [Background for -SurfaceView - is.xyz.mpv/is.xyz.mpv.MPVActivity#0] Invalid device requested composition type change: SOLID_COLOR (3) --> DEVICE (2) 
maybe is a error?
In same env, VLC and MX Player can work smoothly,

**Comment by fengchao-wei** [comment]
my phone is Android11 in docker

**Comment by InnovatorSteve** [comment]
In addition， I would like to ask, I saw MPV call dequeueoutbuffer success through debugging, but did not call renderOutputBufferAndRelease correlation function, the invocation of the implementation is in MPV - android, libmpv or ffmeg implementation, I notice that FFmpeg has an interface for calling ff_AMediaCodec_releaseOutputBuffer, but I still have no idea what that is, and I'd be grateful if you could give me some instructions。
Tanks

**Comment by sfan5** [comment]
> maybe is a error?

I don't know.

> I saw MPV call dequeueoutbuffer success through debugging, but did not call renderOutputBufferAndRelease correlation function, the invocation of the implementation is in MPV - android, libmpv or ffmeg implementation, I notice that FFmpeg has an interface for calling ff_AMediaCodec_releaseOutputBuffer,

libmpv calls `av_mediacodec_release_buffer` [here](https://github.com/mpv-player/mpv/blob/86b498ecc0e6276bb905df57f479d0506b45ba53/video/out/hwdec/hwdec_aimagereader.c#L327-L332), the rest of buffer handling is up to ffmpeg.

**Comment by InnovatorSteve** [comment]
MPV call MediaCodec allocateOutputBuffersFromNativeWindow 10 buffers, and cancel 9 buffer, omx plugin recived 1 outbuffer only, but mpv need at least 2 buffer in get_req_frames.
So, they can't work, but VLC can work with 1 buffer in begin
