### ISSUE TITLE
Notification seekbar

### ISSUE THREAD

**Issue by foxjaw** [mpv-android/mpv-android#817]
Expose seekbar in the notification on A12+

**Comment by peerless2012** [comment]
Should use MediaStyle Notification.

**Comment by sfan5** [comment]
I already use MediaStyle for notifications, but something is missing. Maybe [`setMediaSession`](https://developer.android.com/reference/androidx/media/app/NotificationCompat.MediaStyle#setMediaSession(android.support.v4.media.session.MediaSessionCompat.Token))?
Or do all other apps use custom notification views to enable stuff like a seek bar?
