### ISSUE TITLE
Seek thumbnail preview

### ISSUE THREAD

**Issue by jan-kleks** [mpv-android/mpv-android#821]
Show a changing thumbnail when seeking through a video to make searching for a particular movie fragment easier.

You can see an example of such a feature here: https://github.com/rubensousa/PreviewSeekBar

**Comment by sfan5** [comment]
High complexity to integrate with libmpv¹, not planned at the time.

¹: consider that existing mpv scripts for this spawn a second mpv instance in encoding mode and control it via IPC to achieve this
