### ISSUE TITLE
Since you aren't not providing yt-dlp variant apk, let us build ourself using GitHub Actions

### ISSUE THREAD

**Issue by aicynide** [mpv-android/mpv-android#826]
Open-source the yt-dlp variant build script (including python scripts) and provide Github Actions support to automate apk build and git commit nightly apk build

**Comment by sfan5** [comment]
There is nothing closed-source. You are free to do it yourself.

**Comment by Bonboon229** [comment]
Yeah, this is not a constructive issue in the slightest

Mods, please lock this.
