### ISSUE TITLE
pip issue on samsung oneui 5.1 (android 13)

### ISSUE THREAD

**Issue by allentown521** [mpv-android/mpv-android#829]
[###](url) Important information

Android version:

mpv-android version:

Which version of mpv-android introduced the problem (if known):

### Description

pip issue on samsung oneui 5.1 (android 13) . please see attachment

Uploading b8adc846c250aacc0cae44c2a86cb0e2.mp4…

If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s 'mpv:*' '*:F'

You can attach text files on Github directly or use sites like https://0x0.st/ to upload your logs.
Depending on the nature of the bug, a log file might not be required and you can *omit this section*. If in doubt provide one, it will help us find possible issues later.

### Additional information

If your issue is only reproducible with a specific (type of) file, provide a short sample file that can be used to reproduce the problem.
You can again use https://0x0.st/ or other cloud storage to share it.

If your issue relates to a certain set of configuration options, provide a full copy of your `mpv.conf` below.

If no additional information is provided please *delete this section*.

**Comment by allentown521** [comment]
https://github.com/mpv-android/mpv-android/assets/69662387/7bf2457e-e4e6-4fc6-953e-31f81270e9f8

**Comment by sfan5** [comment]
Ask the developer of the relevant app, that doesn't look like mpv-android.

**Comment by allentown521** [comment]
抱歉，没有说清楚，我是开发者，我集成了mpv android ，晚点我会附上日志。包括mpv android 的日志

**Comment by sfan5** [comment]
FWIW the play/pause button works for me in PiP (that's what you mean, right?). So it's likely to be due to code change done by you.
