### ISSUE TITLE
Request to translate the two main buttons on the main interface

### ISSUE THREAD

**Issue by FanXiangTM** [mpv-android/mpv-android#831]
Can OPEN DOCUMENT TREE and FILEPICKER (LEGACY) add translations to these two buttons?

Describe the wanted behaviour of the new feature and potential usecases for it here.

**Comment by sfan5** [comment]
Yes, they can be translated.
But I don't speak (presumably) Chinese to actually translate them. Feel free to contribute one.

**Comment by FanXiangTM** [comment]
> Yes, they can be translated. But I don't speak (presumably) Chinese to actually translate them. Feel free to contribute one.

I don't know how to contribute

OPEN DOCUMENT TREE → 打开目录树
FILEPICKER (LEGACY) →文件选择器（旧版）

**Comment by sfan5** [comment]
added: 688091264f07e7f022f753c31a79385c768665e8
