### ISSUE TITLE
Cannot write screenshots

### ISSUE THREAD

**Issue by noobworth** [mpv-android/mpv-android#832]
### Important information

Android version: 12 (MIUI Global 13.0.2 Stable)

mpv-android version:
mpv-android 2023-11-30-release-oldapi / 8033 (debug)

Which version of mpv-android introduced the problem (if known):
Unknown

### Description

Upon trying to take a screenshot `Taking screenshot failed` error message displays on screen with the following messages in console (screenshot attached)

![Screenshot_2023-12-21-04-03-11-993_is.xyz.mpv.jpg](https://github.com/mpv-android/mpv-android/assets/130678801/f0dcccad-30ef-4670-b7f4-fef09271929e)

### Log output

I do not have access to a desktop at the moment, but will provide a log later if need be.

### Additional information

mpv.conf:
```
vo=gpu-next
hwdec=mediacodec
scale=catmull_rom
cscale=catmull_rom
dscale=catmull_rom
vf=format=yuv420p
dither-depth=8
deband=yes
target-prim=bt.709
target-trc=srgb
blend-subtitles=yes
keep-open
demuxer-mkv-subtitle-preroll=yes
sub-auto=fuzzy
audio-file-auto=fuzzy
slang=eng,en,rus,ru,jpn,ja
alang=jpn,ja,eng,en
screenshot-dir=/storage/emulated/0/mpv-screenshots/
screenshot-template="%F (%P)"
screenshot-format=jpg
screenshot-jpeg-quality=100
scripts=/storage/emulated/0/mpv/scripts/trackselect.lua:/storage/emulated/0/mpv/scripts/fuzzydir.lua:/storage/emulated/0/mpv/scripts/sub-fonts-dir-auto.lua
script-opts=trackselect-preferred_audio_lang=jpn/ja/eng/en,preferred_audio_channels=2,preferred_sub_lang=eng/en/rus/ru/jpn/ja,excluded_sub_words=sign
sub-file-paths=**
audio-file-paths=**
[protocol.https]
cache-pause=yes
[protocol.http]
profile=protocol.https
```

input.conf:
```
0x10002 screenshot
0x10003 script-binding console/enable
```

The issue persists with no config as well.

**Comment by noobworth** [comment]
Yeah it was probably `:`.
Changed to `screenshot-template="%F (%wH-%wM-%wS.%wT)"` in the config and it works properly now

**Comment by sujitfg1** [comment]
You seem to know alot about Config in mpv Android

You've discord or anything to chat with you?
