### ISSUE TITLE
AV1 gpu-next color plane rotated 180° in playback

### ISSUE THREAD

**Issue by faustaahmad** [mpv-android/mpv-android#833]
### Important information
Android version: 11
mpv-android version: 2023-11-30-release / 8033 (latest november 2023 release)

### Description
Just enable gpu-next then play AV1 video wih SW decoder
Video used E09 Yuru Yuri ([Trix's release](https://nyaa.si/view/1680971))
<table><tr>
<th colspan=2>gpu-next (landscape only)</th>
</tr><tr>
<th>playback</th>
<th>paused</th>
</tr><tr>
<td><img src="https://x0.at/Zvgs.jpg" name="gpu-next playback"></img></td>
<td><img src="https://x0.at/ydfu.jpg" name="gpu-next paused"></img></td>
</tr>
</table>

### Additional information
```
# mpv.conf
no-deband
cache=no
demuxer-readahead-secs=60
dither=no
vd-queue-enable=yes
vd-queue-max-bytes=1000MiB
vd-queue-max-samples=36000
vd-queue-max-secs=60

# Language & subtitles
sub-visibility=yes
alang=jp,jpn,ja,en,eng
slang=jp,jpn,ja,en,eng

# Subtitle
demuxer-mkv-subtitle-preroll=yes
sub-auto=fuzzy
audio-file-auto=fuzzy
sub-file-paths=ass:srt:sub:subs:subtitles
embeddedfonts=yes
sub-fix-timing=no
sub-ass-force-style=Kerning=yes

# Scaling
scaler-resizes-only=no
linear-downscaling=yes
correct-downscaling=yes
sigmoid-upscaling=yes

scale=bilinear
dscale=spline16
cscale=bilinear

# Antiring
scale-antiring=0
dscale-antiring=0
cscale-antiring=0
```

**Comment by sfan5** [comment]
Both your screenshots are from gpu-next. Are you sure it's not another option doing this?

Can't reproduce here either.

**Comment by faustaahmad** [comment]
Potrait mode work fine though
Landscape mode caused the problem on my side
Video resolution is 720p, while my phone still using 720p display too

**Comment by sfan5** [comment]
> Idk how to grab logcat without computer or root

Me neither but without the log there's no chance at investigating this.

**Comment by faustaahmad** [comment]
Tried to grab the logcat (my device didnt hv root)
Enable USB debugging & connect to laptop
Then I used `adb logcat -s 'mpv:*' '*:F'` and it doesnt output anything other than "Beginning of crash or system or main"
Tried using different usb cable & still same

This bug seems to only happen on my device with gpu-next, AV1, and same resolution as my screen (720p)
Other than that, it's fine even with gpu (gpu-next disabled)

**Comment by sfan5** [comment]
If `adb logcat` also prints nothing then your device does not expose any debug info.

**Comment by faustaahmad** [comment]
Tried with this [app](https://github.com/tananaev/rootless-logcat), but still doesnt output any log for mpv until I enabled some random debugging settings inside dev options (that idk what it'll change)
Also tried with my laptop too after those random dev options that I have enabled, but it still spit out nothing 🙃
So here we go my [logcat.txt](https://github.com/mpv-android/mpv-android/files/13817606/logcat.txt) but I cant use the command, sorry if it's noisy
Hope this'll help

**Comment by abdallahmehiz** [comment]
This also happens to me.
### Some Device Info:
Xiaomi Redmi Note 8 Pro, Android 14 AOSP.
mpv-android 2023-11-30-release
### Configuration info
The only things i changed from installing mpv-android are
Enabled gpu-next
mpv.conf:
```
vf=format=yuv420p
```
Episode 3 of [MTBB'S Release](https://nyaa.si/view/1671992)
### [Video of it happening](https://files.catbox.moe/nr3xzl.mp4)

**Comment by sfan5** [comment]
As it turns out this seems to affect certain AV1 videos and not all.
I can also reproduce it myself now (w/ the FOSDEM recordings).

**Comment by abdallahmehiz** [comment]
For some reason, using any video aspect in the settings and even using the property `video-aspect-override` to an aspect ration different from the video's original fixed this for me.

**Comment by faustaahmad** [comment]
> For some reason, using any video aspect in the settings and even using the property `video-aspect-override` to an aspect ratio different from the video's original fixed this for me.

The bug only occur if the the video isnt up/downscaled
Also if aspect ratio set to different value, it's working properly but... need to do it manually and it wont look as good as with original aspect ratio

**Comment by abdallahmehiz** [comment]
> it wont look as good as with original aspect ratio

You can try making it unnoticeable like 1920/1081 or something like that

**Comment by faustaahmad** [comment]
Here's better solution to the problem without sacrificing aspect ratio that much, thanks for the idea```
video-scale-x=0.99999
video-scale-y=0.99999
```

**Comment by abdallahmehiz** [comment]
> Here's better solution to the problem without sacrificing aspect ratio that much, thanks for the idea
> 
> ```
> video-scale-x=0.99999
> video-scale-y=0.99999
> ```

Shouldn't changing only one of these fix it? :sweat_smile: Why change both?

**Comment by sfan5** [comment]
simpler workaround: `vd-lavc-film-grain=cpu`

**Comment by sfan5** [comment]
The workaround is now enabled by default.
