### ISSUE TITLE
Setting up Hi-Fi audio in mpv

### ISSUE THREAD

**Issue by romain8991** [mpv-android/mpv-android#835]
Hello everyone,

I'm pretty new to mpv here and I've been struggling to set up an Hi-Fi audio configuration for the last few days. So, basically, by essentially using FFmpeg filters, I tried to set up exclusive mode, 64 bit internal sample, 24 bit output and swr 48000 khz resampling with 1.00 cutoff. But, appart from the audio output (set on aaudio push), I couldn't get any audio settings to work and currently have no sound, with the following commands:

--ao=aaudio.c
--exclusive-mode=yes
--af=lavfi=graph[:internal_sample_fmt[:o=S64le]]
--af=lavfi=graph[:dither_method[:o=triangular]]
--af=lavfi=graph[:out_sample_fmt[:o=S24le]]
--audio-swresample-o=48000=cutoff=1.00

Could anyone please help? Thanks in advance! 😅

**Comment by sfan5** [comment]
> --ao=aaudio.c

Someone proposed to add this, it does not actually exist.

>  --exclusive-mode=yes

Not supported by any current driver afaik

> --af=lavfi=graph[:internal_sample_fmt[:o=S64le]]
--af=lavfi=graph[:dither_method[:o=triangular]]
--af=lavfi=graph[:out_sample_fmt[:o=S24le]]

None of this syntax looks right to me.

>  --audio-swresample-o=48000=cutoff=1.00

`cutoff` seems to be an encoding option, so this is pointless. The syntax is also wrong.

**Comment by romain8991** [comment]
@sfan5 Thanks for the reply. My bad, I thought aaudio output was already included and working (I struggled to be sure, because I couldn't find how to generate any logs). Why is it that no current audio driver actually support exclusive mode? In every case, I knew that something was probably wrong with my syntax, since I can't get any sound with it, regardless of the platform. Then again, I'm quite new to mpv and not a programmer myself, even though I'm trying to learn some basics, especially in audio settings.
