### ISSUE TITLE
Remember folder in filepicker after playback

### ISSUE THREAD

**Issue by PhoenixBlade24** [mpv-android/mpv-android#838]
While MPV-Android is a great application, there are some nagging issues that continue to persist. For instance, I watch a lot of movies and shows on my external SSD, and every time an episode or movie ends I have to then click multiple times to get back to the folder I was on (if I want to continue), because the application kicks me back to the system files rather than the folder I was on, on my SSD. Stopping playback also has the same issue.

**Comment by sfan5** [comment]
This was probably already reported but I can't find the other issue right now.
