### ISSUE TITLE
(dis)connection of BT keyboard stops playback and loses timeline position

### ISSUE THREAD

**Issue by nrvale0** [mpv-android/mpv-android#842]
### Important information

Android version:

LineageOS 20-20231227-nightly-gts4lvwifi / Android 13

mpv-android version:

2024-11-30-release

Which version of mpv-android introduced the problem (if known):

This has been a long-running issue with all(?) releases over the past few years.

### Description

If a video or audio file is playing and a BT keyboard is connected/disconnected the media file's playback halts and upon restarting the timeline progress has been lost. Meaning the media file restart play at 0:00.

### Log output

[log.txt](https://github.com/mpv-android/mpv-android/files/13837637/log.txt)

**Comment by sfan5** [comment]
As far as I can see the app handles all relevant [configuration changes](https://developer.android.com/guide/topics/resources/runtime-changes) and I don't have a BT keyboard to test this myself right now.
Nothing useful in the log either unfortunately.
