### ISSUE TITLE
Picture settings on Sony TV won't work in MPV

### ISSUE THREAD

**Issue by knosuhor** [mpv-android/mpv-android#843]
Android version:
Android 10 on Sony TV KD55XH9096

mpv-android version:
2023-11-30-release from google play

Many Sony TV's advanced picture settings won't make any effect when using MPV, settings like:
live color, noise reduction, motionflow (frame interpolation), etc.
Tried few other players from google play (vlc, mx, just player, nova) and MPV was the only one with this issue.

**Comment by sfan5** [comment]
fundamentally the same as for https://github.com/mpv-android/mpv-android/issues/822#issuecomment-1837596006 applies

tl;dr can't fix due to how mpv works

**Comment by knosuhor** [comment]
@sfan5 Indeed "vo=mediacodec_embed" made those options work, but disabled subtitles, guess no way around it?

**Comment by sfan5** [comment]
Nope.
