### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by JimPancakes** [mpv-android/mpv-android#844]
I am trying to build mpv-android on Ubuntu VM using the [source](https://github.com/mpv-android/mpv-android/releases/tag/2023-11-30) from the latest release, without modifying anything, by following [these](https://github.com/mpv-android/mpv-android/blob/master/buildscripts/README.md) instructions. I got as far as I can on my own and got to a point where it just feels beyond me. 

`./download.sh` worked mostly fine. The only thing to point out is that it kept stopping saying `Error: missing Java Development Kit. Install it using e.g. sudo apt-get install default-jre-headless`. So I tried using `sudo apt-get install default-jre-headless` as it said and it installed openjdk version "11.0.21" and it still didn't work. After deleting it I then used `sudo apt install openjdk-21-jdk` and that worked. [This](https://github.com/mpv-android/mpv-android/files/13849841/download.sh_out.txt) is the log from `./download.sh` after the openjdk-21-jdk installation. (I also used openjdk-17-jdk but the entire process went the same in regards to the next paragraph)

I then ran `./buildall.sh --arch arm64 mpv` (because I want it to work on a 64bit phone) and after I ran `./buildall.sh`. These ones looked really weird at times. Not being that familiar with linux I don't even know where to begin. It kept saying `DEPRECATION: "pkgconfig" entry is deprecated and should be replaced by "pkg-config"` and `Found CMake: NO` even though cmake is installed and pkg-config seems up to date. There were also a bunch of red `NO` at various entries but maybe not everything needed to be `YES`??? At the end the build fails saying:
```
> Task :app:compileDefaultDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:compileDefaultDebugJavaWithJavac'.

> Could not resolve all files for configuration ':app:androidJdkImage'.

   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.

      > Execution failed for JdkImageTransform: /home/jim/Downloads/mpv-android/buildscripts/sdk/android-sdk-linux/platforms/android-33/core-for-system-modules.jar.

         > Error while executing process /usr/lib/jvm/java-21-openjdk-amd64/bin/jlink with arguments {--module-path /home/jim/.gradle/caches/transforms-3/a50eae4fc3daf72081556cf440252d2c/transformed/output/temp/jmod --add-modules java.base --output /home/jim/.gradle/caches/transforms-3/a50eae4fc3daf72081556cf440252d2c/transformed/output/jdkImage --disable-plugin system-modules}
```

[This](https://github.com/mpv-android/mpv-android/files/13849973/buildall.sh_arm64_out.txt) is the log from `./buildall.sh --arch arm64 mpv`. And [this](https://github.com/mpv-android/mpv-android/files/13850085/buildall.sh_out.txt) from `./buildall.sh`.

I really don't know where to go form here and would really appreciate some help.

**Comment by sfan5** [comment]
> So I tried using `sudo apt-get install default-jre-headless` as it said and it installed openjdk version "11.0.21" and it still didn't work.

what does "didn't work" mean here?

>  It kept saying DEPRECATION: "pkgconfig" entry is deprecated and should be replaced by "pkg-config" and Found CMake: NO even though cmake is installed and pkg-config seems up to date. 

Nothing to worry about.

> There were also a bunch of red NO at various entries but maybe not everything needed to be YES???

indeed

>  At the end the build fails saying: [...]

Now here the actual reason might be that our Gradle version does not (yet) support Java 21.
The CI uses Java 17 and I also have that version here so maybe try that. Also why the first question is important.

**Comment by JimPancakes** [comment]
It didn't work as in I ran the suggested command `sudo apt-get install default-jre-headless`. Then I did `java --version` and I got:
```
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

Running `./download.sh` after this still gave me `Error: missing Java Development Kit. Install it using e.g. sudo apt-get install default-jre-headless`.

Only after doing `sudo apt install openjdk-21-jdk` or `sudo apt install openjdk-17-jdk` did `./download.sh` stop giving that error and continued to download everything.

So now I took it from zero. Downloaded the source again, uninstalled all the java versions that were installed. This time I ran `sudo apt install openjdk-17-jdk` which installs:
```
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)
```
I was typing this as I was working on it and... IT WOOOORKS. Thanks for the help @sfan5.

For those that run into the same problem as me please take note that if you used `sudo apt-get install default-jre-headless` and it installed openjdk 11 make sure to delete it and only have openjdk 17 installed. I'm pretty sure the reason why it kept giving me errors is because I had both.
