### ISSUE TITLE
Should MPV's interpolation work on Sony android TV?

### ISSUE THREAD

**Issue by knosuhor** [mpv-android/mpv-android#846]
Since using TV's build-in interpolation is not possible (#843) I've been trying to configure MPV's interpolation option to reduce judder, but enabling it  on my TV won't work as intended. 

- With interpolation enabled and gpu-next disabled video will flicker black frames and mpv will completely freeze after few seconds of playback.
- With gpu-next enabled video will play but will stutter heavily and drop/ mistime frames, making it much worse than interpolation disabled. 

Is it a bug or is this feature not usable on TV performance-wise? Tried all "video-sync=" options.

### Additional information

Android version:
Android 10 on Sony TV KD55XH9096

mpv-android version:
2023-11-30-release from google play

**Comment by sfan5** [comment]
The only answer I can give you is "maybe".
Embedded GPUs and/or their drivers are notably prone to issues with the functionality mpv uses.
