### ISSUE TITLE
Hello, is there any way to know whether the video is finished or failed?

### ISSUE THREAD

**Issue by MRDHR** [mpv-android/mpv-android#848]
Hello, is there any way to know whether the video is finished or failed? I looked up the data of libmpv and couldn't find the relevant instructions. So far, only the end-file incident is known. However, this event will be called back when the playback of other files is replaced, the playback is completed, or the playback fails.

### Additional information
mpv-android 2023-11-30 Build

**Comment by sfan5** [comment]
It's not clear if you're asking for help with the libmpv API or with using mpv-android externally.

**Comment by MRDHR** [comment]
mpv-android

The judgment of playback completion and playback failure was not found in this project. I noticed that app quit playeractivity after being notified by end-file.

**Comment by MRDHR** [comment]
I also checked libmpv's events and tried error_file 's event snooping, but it was not consistent with the document description. Cannot receive the string return value of error_file

**Comment by sfan5** [comment]
You're asking about libmpv.

mpv-android checks for the [shutdown event](https://github.com/mpv-android/mpv-android/blob/ae6c3ca65bd127752377944d6acb8c998ee6e185/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L1687-L1690) but waiting for end-file is the better way to do this.
