### ISSUE TITLE
Built-in stats use deprecated props

### ISSUE THREAD

**Issue by sfan5** [mpv-android/mpv-android#85]
<pre>
12-23 15:20:00.284 16160 16222 V mpv     : [cplayer:warn] Warning: property 'drop-frame-count' was replaced with 'decoder-frame-drop-count' and might be removed in the future.
12-23 15:20:00.284 16160 16222 V mpv     : [cplayer:warn] Warning: property 'vo-drop-frame-count' was replaced with 'frame-drop-count' and might be removed in the future.
</pre>

**Comment by xyzz** [comment]
c14a9dad32ec481436150e8aae8f57fd4d17bb06
