### ISSUE TITLE
New toast notification popup does not visually override old one

### ISSUE THREAD

**Issue by fritzrehde** [mpv-android/mpv-android#852]
### Important information

Android version: 13 (LineageOS 20)

mpv-android version: 2023-11-30

Which version of mpv-android introduced the problem (if known):

### Description

Android toast notification popups (the small popups at the bottom of the screen) are shown e.g. when the audio is toggle on or off in the bottom menu. However, here is a slightly inconvenient behaviour that I observe:
1. Click on toggle audio buttom.
2. "Audio off" toast pops up.
3. Click on toggle audio button for a second time while the "Audio off" toast is still visible.
4. Expect e.g. `"Audio #1"` toast to show up and override the now-outdated "Audio off" toast. However, what actually happens is that the "Audio off" toast is still shown, and there is no visual indication that the audio is back (besides hearing it of course).

If you replace step 3 with:
Click on toggle audio button for a second time **after** the "Audio off" toast has disappeared, the new `"Audio #1"` toast is shown.

I am not sure if the desired overriding is even possible with Android's toast SDK, but it would be very useful to override previous toasts so the latest toast is always shown.
Obviously, this is also not an issue in the audio button, but in the general showing of toasts. The same behaviour can be observed for the subtitles button/toast as well.

**Comment by jaqarll** [comment]
I can confirm this behaviour concerning subtitles. Especially when there are numerous subtitles in a file finding the right one by pressing the button once can be a hassle as the user needs to wait for the older toast do disappear to be able to see the next subtitle language.

**Comment by sfan5** [comment]
> Especially when there are numerous subtitles in a file finding the right one by pressing the button

FYI you can long-press it to get a direct selection menu

**Comment by jaqarll** [comment]
Yes, I found that out after a while. But pressing repeatedly sometimes feels like a more comfortable option. Long-press on a standing tablet always feels a bit weird to me.

**Comment by sfan5** [comment]
fixed: ae6c3ca65bd127752377944d6acb8c998ee6e185
