### ISSUE TITLE
Android Box, Turkish character problem.

### ISSUE THREAD

**Issue by demir28** [mpv-android/mpv-android#856]
Hello, I installed mpv on my Android box device via Google Play store. I solved the subtitle size with "sub-font-size". When I watched a movie with subtitles, I noticed that some Turkish characters looked wrong. "ı,ş,ğ" How can I fix this permanently with "mpv.conf" in the settings section?

**Comment by sfan5** [comment]
Probably an encoding issue, not fixable in the config.
