### ISSUE TITLE
hwdec: cannot play files encoded with hevc_vaapi

### ISSUE THREAD

**Issue by ansemjo** [mpv-android/mpv-android#857]
I recently found out how I can use the `hevc_vaapi` encoder with `ffmpeg` to speed up encoding significantly on my computer. Unfortunately, `mpv` on my Pixel 7 does not seem to be able to play these files using a hardware decoder. Switching to software decoding works fine, though sometimes struggles with larger files.

### Important Information

Android version: 14 / Pixel 7 / UQ1A.240105.004

mpv-android version:
> mpv-android 2023-11-30-release / 8033
> mpv v0.37.0-55-g8b4a995a9d

Which version of mpv-android introduced the problem (if known): no idea, I only noticed when I started encoding with `hevc_vaapi` recently

Encoding performed on:
> Lenovo Thinkpad P14s Gen 2 AMD
> AMD Ryzen 7 PRO 5850U with Radeon Graphics
> ffmpeg version n6.1

### Description

Any file that I encode with `hevc_vaapi` on my computer is completely garbled and corrupted when playing in mpv with hardware decoding. There is a small pause at the beginning and then the audio plays fine but I only get a very noisy and corrupted frame every few seconds.
![Screenshot_20240122-204233](https://github.com/mpv-android/mpv-android/assets/11139925/3d045c6b-c16a-44eb-818b-f3d75fa337dd)

Switching to software decoding immediately fixes the issues and continues playing the video fine.
![Screenshot_20240122-204312](https://github.com/mpv-android/mpv-android/assets/11139925/5cdf7ed3-b4f6-4447-8abf-6fba8122d2da)

Other `hevc` video files, which I encode with a software encoder in ffmpeg work fine with hardware decoding. Also, the `hevc_vaapi` files play fine on my computer in `mpv 0.36.0`.
![Screenshot_20240122-204249](https://github.com/mpv-android/mpv-android/assets/11139925/672e06b8-3ff6-41bf-a418-b33cf8b9ff6e)

#### Reproduce:

* Use some file you want to transcode; I'll use [Big Buck Bunny](https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov) where I sliced only the first 20 seconds of it.
* Encode the video with ffmpeg using the `hevc_vaapi` encoder:
  > ffmpeg -vaapi_device /dev/dri/renderD128 -i big_buck_bunny_720p_h264_20sec.mov -hide_banner -loglevel info -stats -c:v hevc_vaapi -preset veryfast -pix_fmt vaapi -movflags +faststart -c:a aac -vf format=nv12,hwupload -rc_mode CQP -global_quality 30 -profile:v main big_buck_bunny_720p_h264_20sec.hevc_vaapi.mp4
* Copy to Android device and play in mpv.

### Log output

* when playing file encoded with `hevc_vaapi`: [logcat-hevc_vaapi.txt](https://github.com/mpv-android/mpv-android/files/14015094/logcat-hevc_vaapi.txt)
* when playing file encoded with `hevc`: [logcat-hevc.txt](https://github.com/mpv-android/mpv-android/files/14015090/logcat-hevc.txt)

### Additional information

Files:
* [big_buck_bunny_720p_h264_20sec.hevc_vaapi.mp4](https://github.com/mpv-android/mpv-android/assets/11139925/e2d3b32d-07e8-4858-9df5-a46cf29bd2f8)
* [big_buck_bunny_720p_h264_20sec.hevc.mp4](https://github.com/mpv-android/mpv-android/assets/11139925/13f7949e-aaf2-4e22-8936-f6497213bb80)

I've tried adding `hwdec=mediacodec-copy` to the config, to see if it changes anything but it happens either way.

Most of the other issues pertaining to hardware decoding of HEVC videos seem to stem from 10 bit support or high bitrates. But these files are comparatively tiny 720p videos in 8 bits, so that can't be it?! Is there some simple argument I'm missing from my ffmpeg encoding?

One thing I noticed when looking at the produced files with `ffprobe` is that the files produced by `hevc_vaapi` seem to have no B-frames and I can't force any with `-bf 2` either. I'm not sure if this is significant.
> ffprobe -v error -print_format json -show_streams -show_format big_buck_bunny_720p_h264_20sec.hevc_vaapi.mp4 | jq .streams[0].has_b_frames
> 0

**Comment by sfan5** [comment]
I'm not familiar enough with HEVC to tell you what's different about your file.
That it doesn't play is either because
* there's a bug in ffmpeg. (less likely IMO)
* or the vendor cut some corners and didn't implement some part of the specification that they thought was not needed to play "normal" HEVC content. (more likely)

FWIW I get the same artifacts playing it on my phone.

**Comment by ansemjo** [comment]
I've also tried playing the file with MxPlayer because it was mentioned in some other issues and MxPlayer can play the video fine while showing `HW` in the corner.

I don't see any obvious errors or warnings in the logcat output of mpv though, which might indicate any difference in handling these video files.

---

Finally, I've tried parsing more information from the files themselves. The only meaningful difference that `mediainfo` shows is the missing "library name" in the VAAPI-encoded file:

```diff
$ diff <(mediainfo --Full big_buck_bunny_720p_h264_20sec.hevc.mp4) \
  <(mediainfo --Full big_buck_bunny_720p_h264_20sec.hevc_vaapi.mp4) \
  | grep -Eiv "((stream |file |header|data)size|proportion|bit rate|modification|file name|bits/)"
23,25c23,25
< Complete name                            : big_buck_bunny_720p_h264_20sec.hevc.mp4
---
> Complete name                            : big_buck_bunny_720p_h264_20sec.hevc_vaapi.mp4
[...]
---
137,146c137,141
< Writing library                          : x265 - 3.5:[Linux][GCC 11.2.0][64 bit] 8bit+10bit+12bit
< Writing library                          : x265 3.5:[Linux][GCC 11.2.0][64 bit] 8bit+10bit+12bit
< Encoded_Library_Name                     : x265
< Encoded_Library_Version                  : 3.5:[Linux][GCC 11.2.0][64 bit] 8bit+10bit+12bit
< Encoding settings                        : cpuid=1111039 / frame-threads=4 / wpp / [...]
---
[...]
```

Is the library name used somewhere for decision-making?
