### ISSUE TITLE
Linux / Ruby script / mpv => Android /?

### ISSUE THREAD

**Issue by philiprhoades** [mpv-android/mpv-android#858]
People,

On Fedora Linux for years I have had a Ruby script which creates a list of MP3s from a directory, randomises the order of the list and then plays the list using mpv.  I have mpv-android which works nicely for single selections to play but what would be the simplest way to reproduce the Ruby script on Android? - I have played around with rooting my phones in the past but I would prefer not to have to do that this time . .

Thanks,
Phil.

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/735, I guess
