### ISSUE TITLE
Why mpv isn't recognising sub font from storage?

### ISSUE THREAD

**Issue by sujitfg1** [mpv-android/mpv-android#860]
I've Adobe CaslonPro Subtitles Stored in Download directory and i wanted to use it as sub font so i wrote 

`sub-font='ACaslonPro-Semibold'`

But it seem MPV isn't recognising the font and using Android default Serif font as fallback

What's proper way to use custom font?

Dir: `/storage/emulated/0/Download/adobe-caslon-pro/ACaslonPro-Semibold.otf`

**Comment by sfan5** [comment]
There is no proper way to use a custom font since Android's sandbox likely will block read access to ones you store in public folder (same problem as all the other questions about external files).

**Comment by sujitfg1** [comment]
So there's no way to do that?

BTW MPV sometimes don't change colour of subtitles any reason?

**Comment by sujitfg1** [comment]
Woaaa😮 did you fixed it?
