### ISSUE TITLE
No mediacodec option

### ISSUE THREAD

**Issue by zhengqwe** [mpv-android/mpv-android#861]
### Important information

Android version: 6.0 (ColorOS 3.0)

mpv-android version: 2023-11-30-release / 8033 (release)

### Description

No HW+(mediacodec) option, but my another device has it
![image](https://github.com/mpv-android/mpv-android/assets/103168200/6dbaf65b-9db9-4b67-a354-a354e531884b)

### Log output

None

### Additional information

None

**Comment by syphyr** [comment]
This commit would help in your situation
https://github.com/syphyr/mpv-android/commit/dcad459c405f4080d0b2debdc495dfaa694bcddf

**Comment by sfan5** [comment]
> Android version: 6.0 

Simply too old.
