### ISSUE TITLE
Double tap the player control and the navigation bar won't disappear

### ISSUE THREAD

**Issue by grindklast** [mpv-android/mpv-android#863]
### Important information

Android version:
11 (MIUI 12.5.5 - Xiaomi Redmi Note 10 Pro)

mpv-android version:
2023-11-30-release / 8033 (release)

Which version of mpv-android introduced the problem (if known):
2023-08-27-release / 8032 (release)

### Description

In the [February 2023](https://github.com/mpv-android/mpv-android/releases/download/mpv-android-2023-02-27/app-default-arm64-v8a-release.apk) and [June 2023](https://github.com/mpv-android/mpv-android/releases/download/2023-06-04/app-default-arm64-v8a-release.apk) builds, to bring up the player controls with just 1 tap and the gesture will work as it should.
However, in the [August 2023](https://github.com/mpv-android/mpv-android/releases/download/2023-08-27/app-default-arm64-v8a-release.apk) and [November 2023](https://github.com/mpv-android/mpv-android/releases/download/2023-11-30/app-default-arm64-v8a-release.apk) builds I had to touch it 2 times to bring up the player controls.
Then the next problem in the August 2023 and November 2023 builds was that the navigation bar wouldn't disappear if I touched it once. Double-tap to reveal the player controls and navigation bar, then they go back into hiding at the same time.
Additionally, I only tested on arm64-v8a, other than that I don't know.

### Log output

[logcat.txt](https://github.com/mpv-android/mpv-android/files/14175729/logcat.txt)

### Additional information

Setting changes I made:
• Disable hardware decoding
• Enable position on quit
• Enable media title display
• Disable controls at bottom of screen
• Disable vertical drag at touch gestures
• Show FPS counter statistics

This is mpv-android build [November 2023](https://github.com/mpv-android/mpv-android/releases/download/2023-11-30/app-default-arm64-v8a-release.apk).
https://github.com/mpv-android/mpv-android/assets/18084273/805e4a36-610d-4740-a874-0edfaf2f9d58

Then this is mpv-android build [February 2023](https://github.com/mpv-android/mpv-android/releases/download/mpv-android-2023-02-27/app-default-arm64-v8a-release.apk).
https://github.com/mpv-android/mpv-android/assets/18084273/6d4995a9-ff83-484e-bee0-a74776cba1c9

Additional note, I use aspect ratio: pan/scan so that the navigation bar is clearly visible.

**Comment by sfan5** [comment]
I can't reproduce this on my Android 14 phone.
Tapping once will show the player UI, the navigation keys and *not* the status bar. Touching a second time (or waiting 1.5s) will fade both out again.

There are a bunch of somewhat related changes [between those two builds](https://github.com/mpv-android/mpv-android/compare/2023-06-04...2023-08-27), but nothing immediately jumps out to me

If I'm not understanding the problem correctly please describe the expected and actual behavior in more detail.
