### ISSUE TITLE
Add an option to disable exit confirmation dialog when playlists are loaded

### ISSUE THREAD

**Issue by obscenelyvague** [mpv-android/mpv-android#864]
When playlists are loaded with autoload script there is a confirmation dialog when exiting the player if it isn't the last file of the playlist being played. Please add a toggle in settings to disable this exit confirmation dialog. 

![Screenshot_mpvdialog](https://github.com/mpv-android/mpv-android/assets/36733368/b6381aab-deee-474c-9c4c-22b6baa79c63)

**Comment by sujitfg1** [comment]
>playlists are loaded with autoload script 

How you using script in MPV Android I'm unable to do it
