### ISSUE TITLE
How to jump to specific time ?

### ISSUE THREAD

**Issue by KaKi87** [mpv-android/mpv-android#865]
Hi,

I'm looking for a way to jump playback position to a specific time with up-to-the-second precision.

Using ADB, I tried running `input tap <x> <y>` with `x` = *width of `is.xyz.mpv:id/playbackSeekbar`* × *targeted position in seconds* ÷ *media duration in seconds* but I end up 5.5 minutes behind.

Then, I noticed that the first and last 25 pixels of the bar actually don't count, but even considering this I'm still almost as far off.

What am I missing in my calculations and is there a better option ?

### Additional information

Android version is 6.0.1 and MPV version is 2023-11-30.

---

Thanks

**Comment by KaKi87** [comment]
@sfan5 Please ? :pray:

**Comment by sfan5** [comment]
You want to do this from where exactly? adb, another app, termux, ...?
Also what's your goal?

**Comment by KaKi87** [comment]
> You want to do this from where exactly?

ADB.

> what's your goal?

Jump to a specific time, e.g. like `Ctrl+T` on desktop VLC.

Thanks

**Comment by KaKi87** [comment]
What about using my initial idea : clicking the `is.xyz.mpv:id/playbackSeekbar` at the specific pixel position matching a specific time ?

Thanks

**Comment by KaKi87** [comment]
Well, I managed to do it on Spotify at ± 2 sec accuracy, which is perfect considering it's a much smaller seek bar :

![](https://github.com/mpv-android/mpv-android/assets/21284089/cf1485f0-e032-4886-86c8-4a37e16a5cf8)

So, I don't understand why doesn't the same calculation work on MPV.

Thanks

**Comment by KaKi87** [comment]
Please ?

**Comment by sfan5** [comment]
You are on your own to figure this out.
