### ISSUE TITLE
"Save position on quit" doesn't work with videos in folders with a `.nomedia` file

### ISSUE THREAD

**Issue by danieljl** [mpv-android/mpv-android#866]
### Important information

Android version: 14

mpv-android version: 2023-11-30-release / 8033 (release)

Which version of mpv-android introduced the problem (if known):

### Description

Steps to reproduce:

1. Enable "Save position on quit" in the settings
2. Pick any video on your device
3. Create an empty file named `.nomedia` in the folder which your video is in
4. Play the video and seek to any location
5. Close mpv-android gracefully (i.e. with the back button)
6. Open the video again and you'll find mpv playing it from the beginning

The bug also happens if any ancestor folder of the video has a `.nomedia` file. For example, if  `/movies/.nomedia` exists, then a video at `/movies/interstellar/remux.mkv` is also affected.

**Comment by sfan5** [comment]
Missing log file.
