### ISSUE TITLE
ffmpeg audio resampler out_sample_rate option stuck at 48 kHz

### ISSUE THREAD

**Issue by romain8991** [mpv-android/mpv-android#869]
Device:

Oppo Find X5 Pro

Android version:

14

mpv-android version:

2023-11-30 release

Version of mpv-android that introduced the problem:

unknown

### Description

could not resample output sound to anything other than 48 kHz, using the following ffmpeg audio resampler command:

af=lavfi=[aresample=resampler=swr:cutoff=1:out_sample_rate=44100]

**Comment by romain8991** [comment]
> Do not ignore the issue template.

Sorry, but I can't acces my mpv logs, since I don't know how to generate it. My Android version is 14. But, if my second question is misplaced, perhaps I can ask it somewhere else.

**Comment by sfan5** [comment]
I checked the mpv code and here's what it does:
https://github.com/mpv-player/mpv/blob/3e8d69e3e86fbca6719028ffda9b75918b4c575f/audio/out/ao_audiotrack.c#L671-L682

It never outputs at a higher rate than the native rate of the system. In most cases this means you can't go higher than 48kHz.
Android's audio subsystem might still do resampling internally so this must not necessarily match the values 'Bluetooth Codec Changer' shows you.

**Comment by romain8991** [comment]
> I checked the mpv code and here's what it does: https://github.com/mpv-player/mpv/blob/3e8d69e3e86fbca6719028ffda9b75918b4c575f/audio/out/ao_audiotrack.c#L671-L682
> 
> It never outputs at a higher rate than the native rate of the system. In most cases this means you can't go higher than 48kHz. Android's audio subsystem might still do resampling internally so this must not necessarily match the values 'Bluetooth Codec Changer' shows you.

As a matter of fact, I'm using opensles audio driver (sorry to haven't mention it earlier). Does it change anything to the situation? Personnally, I think it actually does because I could manage to output 96 kHz audio files without resampling, while disabling ffmpeg/ resampling command lines in my conf file (see the attached screen capture for proof):
![Screenshot_20240221_181701](https://github.com/mpv-android/mpv-android/assets/154625818/bfeddf93-197c-44ef-b23b-ddf4a9448e2b)
![Screenshot_20240221_181418](https://github.com/mpv-android/mpv-android/assets/154625818/66eb0f6d-3144-4e74-9abb-fb1f08f4af2e)
.

**Comment by romain8991** [comment]
When I enable mpv/ffmpeg audio resampling, the source sample rate indicated in Bluetooth Codec Changer matches the one that I choosed in my conf file (for instance, 48 or 96 kHz).

**Comment by sfan5** [comment]
> As a matter of fact, I'm using opensles audio driver (sorry to haven't mention it earlier). Does it change anything to the situation?

ao_opensles does not meaningfully restrict the rate it outputs and uses what it gets.
Such details are exactly why I need a log file. It is a waste of *my* time to investigate vague reports.

> Therefore, could you please reopen the issue, until it's fixed?

I am not convinced that there is any bug here, partially due to lack of information.

**Comment by romain8991** [comment]
> > As a matter of fact, I'm using opensles audio driver (sorry to haven't mention it earlier). Does it change anything to the situation?
> 
> ao_opensles does not meaningfully restrict the rate it outputs and uses what it gets. Such details are exactly why I need a log file. It is a waste of _my_ time to investigate vague reports.
> 
> > Therefore, could you please reopen the issue, until it's fixed?
> 
> I am not convinced that there is any bug here, partially due to lack of information.

Yes, I know and I'm sorry, because I tried to get logs on my computer, like I said in previous messages, but couldn't, despite following the tutorial in the issue template.
