### ISSUE TITLE
Audio Passthrough still not supported?

### ISSUE THREAD

**Issue by Arch-Storm** [mpv-android/mpv-android#871]
I just recently got a Nvidia Shield and wanted to try using MPV as my Jellyfin player. I found that audio passthrough doesn't seem to be working even though #93 got supposedly fixed by 2c4d5af but it doesn't seem to work for me? I tried:
```
audio-spdif=ac3,dts,eac3,dts-hd,truehd
audio-channels=7.1,5.1,stereo
```
This however makes audio not play at all. In ExoPlayer passthrough works fine on my setup but DTS:X is not supported and I would really prefer MPV, as i use it on all my other devices. Am I missing something in the config or was passthrough never implemented?

### Additional information

Android TV 11 on Nvidia Shield Pro 2019 (FW 9.1.1)
using 2023-11-30-release

**Comment by Arch-Storm** [comment]
> Use Kodi

I tested Kodi (among all other players) and it didn't work for me (tried all settings). I also didn't ask what other apps possible support this. I asked whether MPV on android supports audio passthrough. I currently have DTS:X passthrough working with libVLC in Jellyfin but this doesn't answer my question.

**Comment by sfan5** [comment]
As far as I can see mpv implements audio passthrough as it should be on Android.
I don't have a device to test the implementation myself but maybe I can find something out if you provide a log file.
