### ISSUE TITLE
Separate app volume from the system one

### ISSUE THREAD

**Issue by frenksisco** [mpv-android/mpv-android#872]
I mean if it is possible to detach mpv player volume from the Android system.
For example, you can do this on MX Player
Can this be done by editing mpv.conf?

**Comment by sfan5** [comment]
Not possible.

**Comment by frenksisco** [comment]
![4kk4xnn](https://github.com/mpv-android/mpv-android/assets/1014756/aa20baf9-6bdd-45de-b22d-0d6acd2d467a)

**Comment by sfan5** [comment]
I have no plans to implement this.
