### ISSUE TITLE
How to rebuild single component if targeting multiple architectures?

### ISSUE THREAD

**Issue by T-10001** [mpv-android/mpv-android#873]
Build instructions say
```
Rebuilding a single component
If you've made changes to a single component (e.g. ffmpeg or mpv) and want a new build you can of course just run ./buildall.sh but it's also possible to just build a single component like this:

./buildall.sh -n ffmpeg
# optional: add --clean to build from a clean state
Note that you might need to be rebuild for other architectures (--arch) too depending on your device.
```

So, if we run `./buildall.sh -n ffmpeg` and we are targeting multiple architectures like `x86_64` and `arm64`, do we also need to run 

```
./buildall.sh --arch arm64 mpv
./buildall.sh --arch x86_64 mpv
```
again and then `./buildall.sh -n`?

**Comment by sfan5** [comment]
If you want to rebuild a single component for multiple architectures the process would be:
* `./buildall.sh -n ffmpeg`
* `./buildall.sh -n ffmpeg --arch arm64`
* `./buildall.sh -n ffmpeg --arch x86_64`
* `./buildall.sh -n` (jni/gradle build -> APK)

Note that depending on how the library is linked you might have to run a full rebuild. FFmpeg and mpv are dynamically linked, so it works in this example.
