### ISSUE TITLE
Can't use FFmpeg input and internal sample formats at s64p with audio resampling

### ISSUE THREAD

**Issue by romain8991** [mpv-android/mpv-android#875]
**Android version:**

14

**My device:**

Oppo Find X5 Pro

**mpv-android version:**

2023-11-30

**Version of mpv-android that introduced the problem :**

Unknown

**Description:**

While using the following ffmpeg command lines, my lavfi filters chain (including audio resampling) is broken and cease to operate (resulting in a crash of the app, while playing audio files), at s64p input and internal sample formats (despite this sample format supposed to be usable, according to mpv's af=format=format=help, on my Windows computer):

af=lavfi=[aresample=in_sample_fmt=s64p:resampler=swr:cutoff=1:out_sample_rate=48000:internal_sample_fmt=s64p:dither_method=triangular:out_sample_fmt=s32]
softvol=no
ao=opensles
loop-playlist=inf

**Log output:**

02-29 22:18:58.678  3142  3251 V mpv     : [cplayer:v] Setting option 'af' = 'lavfi=[aresample=in_sample_fmt=s64p:resampler=swr:cutoff=1:out_sample_rate=48000:internal_sample_fmt=s64p:dither_method=triangular:out_sample_fmt=s32]' (flags = 4)
02-29 22:18:58.678  3142  3251 V mpv     : [cplayer:v] Setting option 'ao' = 'opensles' (flags = 4)
02-29 22:18:58.787  3142  3251 V mpv     : [af:v] [lavfi] 44100Hz stereo 2ch s16
02-29 22:18:58.787  3142  3251 V mpv     : [ffmpeg:error] Unsupported sample format
02-29 22:18:58.787  3142  3251 V mpv     : [ffmpeg:fatal] Assertion 0 failed at src/libswresample/resample.c:232

**Additional information:**

This issue occurs on the latest version of mpv aswell on my Windows computer and with the very same settings (apart from the audio output used of course, being wasapi in this case).

**Comment by romain8991** [comment]
Also, I did further testing with the af=audio-format command, to check if planar formats (such as s16p or s32p) on my computer and Android phone, and they all seems to be supported by mpv. So, I think it's somehow related to ffmpeg audio filters or their implementation in mpv.

**Comment by sfan5** [comment]
If ffmpeg says it's unsupported then it's clearly not an mpv or mpv-android problem.
