### ISSUE TITLE
VIdeos shuttering 

### ISSUE THREAD

**Issue by Eve9181** [mpv-android/mpv-android#878]
### Important information
Device: Redmi note 10 pro (sweetin)
Rom:Voltage os 
Android version:
14
mpv-android version: 
mpv v0.37.0-55-g8b4a995a9d Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects built on Nov 30 2023 16:40:32
libplacebo version: v6.338.0-60-g795600a4
FFmpeg version: n6.1
FFmpeg library versions:
libavutil
58.29.100
libavcodec
60.31.102
libavformat
60.16.100
libswscale
7.5.100
libavfilter
9.12.100
libswresample 4.12.100

### Description
videos shutters a lot tried interpolation but no avail 

### Log output

[06_03-18-39-01_499.zip](https://github.com/mpv-android/mpv-android/files/14510430/06_03-18-39-01_499.zip)

**Comment by sfan5** [comment]
Is the "SW" decoding mode faster? what about "HW"?

Your video is 10-bit although your device offers hardware decoding for it. Maybe that's broken somehow?

**Comment by Eve9181** [comment]
nope was shuttering in both 
also this seems to have been a rom issue somehow so ignore it,i forgot to close the issue
