### ISSUE TITLE
remaining time on OSD

### ISSUE THREAD

**Issue by lodgerz** [mpv-android/mpv-android#879]
hi, it is possible to show the time remaining to the end of the video on the right side of the panel (as happens on mpv for PC)?
i have tried to put timetotal=yes or --osd-msg3 on mpv.conf but it doesnt work.
![z](https://github.com/mpv-android/mpv-android/assets/9266267/18614c5e-2e92-4a44-852b-0b447573064f)

Thanks.

**Comment by da3dsoul1** [comment]
This osd is custom writte, it's nothing like on pc, so anything config related won't work. If you want to show remaining time I think you have to code it yourself or wait for someone to implement it.

**Comment by sfan5** [comment]
That is correct. mpv's osd/osc settings have no effect on mpv-android.

**Comment by sfan5** [comment]
and in fact this has been requested before: #369

**Comment by tarantinosaur** [comment]
> That is correct. mpv's osd/osc settings have no effect on mpv-android.

Is there a way to disable the osd/progress bar?

**Comment by sfan5** [comment]
Currently not.
