### ISSUE TITLE
fullscreen messes up player dialog windows

### ISSUE THREAD

**Issue by foxjaw** [mpv-android/mpv-android#882]
### Important information

Android version: A14

mpv-android version: v0.37.0

Which version of mpv-android introduced the problem (if known): Exists forever

### Description

When I select a chapter, the next one gets selected. I suspect the fullscreen as the culprit (hiding of the navigation bar & status bars).

https://github.com/mpv-android/mpv-android/assets/150133625/94e5485a-3b41-4103-88b4-042f86018243

**Comment by sfan5** [comment]
Can you suggest where I can find an audio file with this many chapters to reproduce the problem?

**Comment by sfan5** [comment]
Can't reproduce this issue on my Android 14 phone.

> mpv-android version: v0.37.0

This is an mpv version number.

**Comment by sfan5** [comment]
Yes, I do. Causing the status bar to show or hide does not produce any weird behavior of the chapter dialog.
