### ISSUE TITLE
ISO file playback issue

### ISSUE THREAD

**Issue by JackDropHammer** [mpv-android/mpv-android#884]
### Important information

**Android versio**n: 11 (miui 12.5)

**mpv-android version**: 2023-08-27-release

Which version of mpv-android introduced the problem (if known):

### Description
When you try to open ISO files (dvd/cd), the playback is extremely buggy. The menu only shows up for a split second(if at all) and you cannot interact with the menu either. It directly starts playing some random stream in that iso and is the seek bar looks broken, the time is displayed wrong(? kind of, I mean that it doesn't show the "correct" time but instead how long it has played the file) and it continuously flicker between 0:00 and current time. The support for menu in mpv desktop is not present (intentionally) so I don't expect menu to work, but atleast playback should be usable.

**Describe your issue in detail here.**
The menu only shows up for a split second(if at all) and you cannot interact with the menu either. It directly starts playing some random stream in that iso and is the seek bar looks broken, the time is displayed wrong(? kind of, I mean that it doesn't show the "correct" time but instead how long it has played the file) and it continuously flicker between 0:00 and current time. The support for menu in mpv desktop is not present (intentionally) so I don't expect menu to work, but atleast playback should be usable. So far I've only tested two iso files, both of which play correctly on mpv, vlc desktop. They both don't play on mpv, vlc Android.

*If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.*

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s 'mpv:*' '*:F'

You can attach text files on Github directly or use sites like https://0x0.st/ to upload your logs.
Depending on the nature of the bug, a log file might not be required and you can *omit this section*. If in doubt provide one, it will help us find possible issues later.

**I DON'T HAVE A COMPUTER ON HAND RIGHT NOW**

### Additional information

*If your issue is only reproducible with a specific (type of) file, provide a short sample file that can be used to reproduce the problem.
You can again use https://0x0.st/ or other cloud storage to share it.*

I can provide the complete file(3 GB) from mega.nz but not a specific sample as I don't know how to cut a dvd iso. **NOTE:- YOU NEED TO DOWNLOAD THE RAR FILES AND THEN EXTRACT THEM, THE RAR FILES ARE SPLIT INTO 7 PARTS BUT IF YOU KEEP THEM UNDER THE SAME FOLDER AND EXTRACT THE FIRST ONE, YOUR PROGRAM SHOULD EXTRACT THE COMPLETE FILE**.
Link:- https://mega.nz/folder/l9xCQCIa#ZYEhx_SqgLWW5DHO19yCfw

**Comment by sfan5** [comment]
mpv-android is not compiled with libraries for DVD or Blu-Ray support.
I don't think the trouble adding them is worth it as 1) mpv doesn't support disc media all that well 2) the only use for this is to open ISOs, Android devices don't have disk drives.

**Comment by JackDropHammer** [comment]
> mpv-android is not compiled with libraries for DVD or Blu-Ray support. I don't think the trouble adding them is worth it as 1) mpv doesn't support disc media all that well 2) the only use for this is to open ISOs, Android devices don't have disk drives.

I see, it's okay then as I found that kodi for Android can do the job but thank you for taking the time to reply to me, hope you have a nice day!
