### ISSUE TITLE
Adding More Touch Gesture Option 

### ISSUE THREAD

**Issue by sujitfg1** [mpv-android/mpv-android#885]
We need More Touch Gesture In MPV Android indeed. 

For example Long Press fro 2x speed (Originally In Youtube then , MX Player) already requested in #876 

Double Tap Right side to skip the chapter and vice Versa for anime better chapter skipping also Show chapter In seekbar like YouTube like it got break between two chapters or any colour indication something 

Long tap on Speed (1.00 X) icon to return Normal Playback Rate 

Also Please find any workaround for Custom font for SRT 

Appreciate your dedication and passion for Android User

Thanks

**Comment by sfan5** [comment]
> For example Long Press fro 2x speed (Originally In Youtube then , MX Player) already requested in https://github.com/mpv-android/mpv-android/issues/876

duplicate, obviously

> Double Tap Right side to skip the chapter

doable with custom gestures

> Show chapter In seekbar like YouTube like it got break between two chapters or any colour indication something

Already requested elsewhere, I'm sure

> Long tap on Speed (1.00 X) icon to return Normal Playback Rate

It opens a dialog where you can reset the rate

> Also Please find any workaround for Custom font for SRT

Requested elsewhere (and also not easily possible)
