### ISSUE TITLE
How to Access MPV data files and Load Any Lua Or Scripts?

### ISSUE THREAD

**Issue by sujitfg1** [mpv-android/mpv-android#887]
I didn't finding any way to use script on MPV Android because there's no way to access MPV data file on Android 14

Also `volume-max=150` not working so have to use `af-add=volume=1.5` this works fine.

**Comment by sfan5** [comment]
Effectively not possible on newer Android, see https://github.com/mpv-android/mpv-android/issues/709#issuecomment-1542775752
