### ISSUE TITLE
Automatic screen orientation does not work?

### ISSUE THREAD

**Issue by i-report-bugs** [mpv-android/mpv-android#890]
### Important information

Android version: 12

mpv-android version: 2023-11-30-release

### Description

On Settings > User Interface > Screen Orientation, I have it set to "Automatic" but if I play portrait videos, it still turns landscape. I was hoping that it will detect the aspect ratio of the video playing and automatically turn it landscape or portrait accordingly but right now, all videos play in landscape.

**Comment by sfan5** [comment]
Log file?

**Comment by obscenelyvague** [comment]
Maybe this can help.
Mpv doesn't seem to abide by rotation metadata and decides orientation based on resolution and aspect ratio.
Here is a sample video with such metadata

https://github.com/mpv-android/mpv-android/assets/36733368/13ebc68b-e419-4ff4-b7ba-7575c3d00334

Mpv plays this in landscape mode with black bars on both sides.
