### ISSUE TITLE
Two instances of MPV player

### ISSUE THREAD

**Issue by smelovsky** [mpv-android/mpv-android#891]
Is it possible to create two instances of MPV player?

We need show two streams in one screen simultaneously. For that I integrated MPV player libs (libmpv.so, libplayer.so, ...) in my app and added two SurfaceView. It works fine for one instance and something wrong if I tried call initialize fun of MPVView class for next instance.

**Comment by sfan5** [comment]
This is possible, yes. But the support code inside mpv-android is not laid out for this.
