### ISSUE TITLE
Need a standalone website for mpv Android 

### ISSUE THREAD

**Issue by MyNameIsAnujRanjan** [mpv-android/mpv-android#892]
Hey developer i don't know how you react so sorry
But i think you can make a website for mpv Android
Besides GitHub you can inform about the new features and and FAQ related to the app of what app has keepable of doing and can't and may guides about the app mpv.config input and difference between mpv for pc Android So that people can get their answer without having to search on Reddit or anywhere else.

**Comment by sfan5** [comment]
I don't think this is particularily necessary (also who is going to write the guides? not me).
