### ISSUE TITLE
Controls never hide since v2024-04-09 for Android TV

### ISSUE THREAD

**Issue by Aymkdn** [mpv-android/mpv-android#894]
Android version: Android TV 10

mpv-android version: 2024-04-09

Which version of mpv-android introduced the problem (if known): 2024-04-09

### Description

When playing a video, if you use the arrows to move forward or backward, the UI that shows how much time remaining and other buttons, is missing. Only the horizontal bar is visible. Before this new version it was working fine. 

In the settings, under User Interface, I have "Display media title" that is checked, as well as "Show controls at bottom of screen". 

To now see the controls at the bottom, I have to press the down arrow, but then the controls will remain on screen until I leave the video. 

### Additional information 

I tried to uninstall and reinstall, I also try a reboot. 

Thanks for your help

**Comment by sfan5** [comment]
The user interface no longer automatically shows if you press any key, this is intentional.

> To now see the controls at the bottom, I have to press the down arrow, but then the controls will remain on screen until I leave the video.

You can obviously press up/down again and the controls will disappear.

**Comment by Aymkdn** [comment]
Thanks for your answer. 


> The user interface no longer automatically shows if you press any key, this is intentional

Oh? This is disappointing 🙁 Could we not use the settings "Show controls at bottom of screen" to allow people to bring it back when pressing a key?

> You can obviously press up/down again and the controls will disappear.

Nope, it doesn't work here. The controls stay on the screen, and no arrow up, down, right or left remove it. I tried everything. The only way is to leave the video and get back.

**Comment by Asgardsurfer** [comment]
Seeing the same thing here on Fire TV.
Was good before this update. Glad to hear I am not the only one.

**Comment by Fumon** [comment]
I prefer the bar being the only thing visible on seek. 

However, I have the same issue of the controls not vanishing once summoned by pressing up or down. I'm on the old Nvidia Shield which is android tv.

Once the controls are on screen, pressing up or down cycles (loops between, i.e. pressing only down repeatedly) between the buttons and the progress slider.

Pressing back will just terminate playing and return to the app that launched it (in my case, jellyfin)
There seems to be no way to clear the controls without exiting the app with a standard android TV remote.

**Comment by Asgardsurfer** [comment]
Fire OS 7.6.4.6
Latest JellyFin Android

**Comment by sfan5** [comment]
> Nope, it doesn't work here. The controls stay on the screen, and no arrow up, down, right or left remove it. I tried everything. The only way is to leave the video and get back.

I can reproduce this bug.

**Comment by Aymkdn** [comment]
Thanks. But any chance to bring the previous behavior back? Maybe behind a setting?

**Comment by Aymkdn** [comment]
Any ETA on when the fix will be released? It's a huge problem because we cannot change the subtitles language of the video !

Also, not having the time showing up while moving in the video is super annoying....

Thanks

**Comment by sfan5** [comment]
I will release a fixed build in the next few days.

> But any chance to bring the previous behavior back? Maybe behind a setting?

I decided against this, sorry.

**Comment by Aymkdn** [comment]
Sorry to ask for it, but any idea when the fix will be released? Thank you so much 🙏

**Comment by sfan5** [comment]
The fix is already released, but Google rejected the last update for some trivial reasons. You can install the APK [from here](https://github.com/mpv-android/mpv-android/releases/tag/2024-05-04).

**Comment by Aymkdn** [comment]
> The fix is already released, but Google rejected the last update for some trivial reasons. You can install the APK [from here](https://github.com/mpv-android/mpv-android/releases/tag/2024-05-04).

I could install the APK but my concern is for the hundreds of people who use my free app (a file explorer for Android TV called "Pop Files") that calls yours to play videos. I often receive questions about this bug from my users. 

I appreciate the efforts to get the bug fix online 🙏 Thank you very much!

**Comment by fabricefou** [comment]
Hello @sfan5 could you please release mpv to make it available in Google store to use @Aymkdn app without this bug ?

Regards.

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/894#issuecomment-2108546937, nothing about the situation has changed.

**Comment by Aymkdn** [comment]
@sfan5 what is the trivial reason provided by Google? You cannot fix what they're asking for? Does it mean you won't provide any more updates on the Google Play Store?

**Comment by sfan5** [comment]
For Android TV specifically Google claims the remote control play/pause button does not work. I tested it in the emulator and it *does* work. 
They replied to an appeal on the 11th but I haven't had time to re-check and reply to that yet.

> Does it mean you won't provide any more updates on the Google Play Store?

Dunno. I might have no choice but to stop offering mpv for Android TV via the Play Store.

**Comment by sfan5** [comment]
![email](https://github.com/mpv-android/mpv-android/assets/1042418/58915e70-5aac-450f-a419-2d0d6f5f917c)

This is verifiably false.
I have better use for the time in my life than to talk against a wall. I will be depublishing mpv for Android TV.

**Comment by Aymkdn** [comment]
It's a very bad news :-( 

I'll check your code and see how I can integrate MPV in my app then…
