### ISSUE TITLE
Why video stats subtitles 

### ISSUE THREAD

**Issue by MyNameIsAnujRanjan** [mpv-android/mpv-android#896]
Android version -13
Version - latest build 2024

After enabling video stats selected audio information is given but selected subtitles information is not. Please add subtitles information .

**Comment by sfan5** [comment]
stats.lua is provided by mpv, open an issue there.

**Comment by MyNameIsAnujRanjan** [comment]
> stats.lua is provided by mpv, open an issue there.

Does this mean I have to report issues on the mpv desktop GitHub where stats.lua is?

**Comment by sfan5** [comment]
Yes.
