### ISSUE TITLE
Unable to add subtitle to video via "open document" (SAF)

### ISSUE THREAD

**Issue by unnecs** [mpv-android/mpv-android#897]
### Important information

Android version: 13
mpv-android version: 2024-04-09-release / 8034

### Description

Subtitle file won't load when picking it via **open document** (SAF). While on the other hand, opening a subtitle file via **legacy file picker** works perfectly.

I would like to be able to rely on SAF exclusively to pick subtitle files (and in the whole app generally) since I think it would greatly reduce potentional future attack surface and vulnerability harm. Also, I think it would somewhat future-proof this feature from newer android versions that might phase legacy file picking.

Thank you for the best android video player <3

**Comment by sfan5** [comment]
Please provide a log file so I can diagnose the problem.
