### ISSUE TITLE
Interpolation Like the desktop MPV?

### ISSUE THREAD

**Issue by Tsubajashi** [mpv-android/mpv-android#90]
Is there currently a way of using tscale? As I already have seen we do have some sort of video-sync=display-resample, but Is there any sort of tscale already? Maybe I didn't see right just yet.
Also, what exactly is scale-param 1 and 2? As I can only type in numbers there, I would like to know what exactly does what.
Sorry for posting it here, but I haven't seen a better place like a discord or something.

**Comment by sfan5** [comment]
Newer versions of mpv-android support interpolation (this is not available in the Play Store yet).

`scale-param1` and `scale-param2` are advanced settings you probably don't need to touch.
read the [docs](https://mpv.io/manual/master/#options-scale)
