### ISSUE TITLE
Android TV 9, the basic menu don't go away, the menu showing play/pause subtitles and other buttons.

### ISSUE THREAD

**Issue by josepheiba** [mpv-android/mpv-android#904]
### Important information

Android version:

mpv-android version:
2024-04-09-release
Installed from the Play Store Android TV 9

2024-04-09-release introduced the problem.

### Description

If I show the player menu (the basic menu showing play/pause and other buttons), the menu don't go away automatically anymore, I'm using a remote, and I don't have anyway to make it go away, if I press the back button the player closes (nothing wrong with the player closing) but I'm just stuck with the menu on the screen, I summon the menu so that I can change the subtitles language, but it sticks on the screen, please help.

If this an issue on all android TV versions? or maybe just on Android TV 9?
I didn't think log files are necessary cause this issue might be happening on all versions, but if it's necessary I'll provide it.
Regards

**Comment by sfan5** [comment]
Has been reported and fixed already: #894
