### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by meireal** [mpv-android/mpv-android#906]
Hi, I found "Better support for scoped storage on newer API levels is being worked on." in [2022-03-23 Build](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2022-03-23) description.
And That's the last version that I can use shaders.(Anime4K) I'm not sure whether there is a bug in the newer versions.

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/709#issuecomment-1542775752
