### ISSUE TITLE
Only first time run am start to play video will work, others will just pause the played video in first frame.

### ISSUE THREAD

**Issue by langyxxl** [mpv-android/mpv-android#908]
### Important information

Android version:

mpv-android version:
installed from f-droid is.xyz.mpv_34.apk

### Description

Only first time run am start to play video will work, others will just pause the played video in first frame.

steps:
1. am start -a android.intent.action.VIEW -t video/any -p is.xyz.mpv -d http://192.168.31.104/a.mp4
2. wait video to play normally.
3. am start -a android.intent.action.VIEW -t video/any -p is.xyz.mpv -d http://192.168.31.104/a.mp4
4. the video will paused in firsh frame.

### Log output
after step 3, log outputs:
**04-29 09:23:24.948 29175 29201 V mpv     : [cplayer:v] Set property: pause=true -> 1**
04-29 09:23:24.949 29175 29175 V mpv     : onNewIntent(Intent { act=android.intent.action.VIEW dat=http://192.168.31.104/... typ=video/any flg=0x10000000 pkg=is.xyz.mpv cmp=is.xyz.mpv/.MPVActivity })
04-29 09:23:24.949 29175 29201 V mpv     : [cplayer:v] EOF code: 3
04-29 09:23:24.950 29175 29201 V mpv     : event: audio-reconfig
04-29 09:23:24.973 29175 29175 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
04-29 09:23:24.974 29175 29201 V mpv     : event: video-reconfig
04-29 09:23:24.984 29175 29175 E mpv     : mpv_get_property(hwdec-current) format 1 returned error property unavailable
04-29 09:23:25.021 29175 29201 V mpv     : event: end-file
---
---
04-29 09:23:26.821 29175 29201 V mpv     : [swresample:v] 44100Hz stereo floatp -> 44100Hz stereo float
04-29 09:23:26.821 29175 29201 V mpv     : [af:v] [out] 44100Hz stereo 2ch float
04-29 09:23:26.827 29175 29201 V mpv     : [cplayer:v] first video frame after restart shown
04-29 09:23:26.828 29175 29201 V mpv     : [cplayer:v] audio ready
04-29 09:23:26.828 29175 29201 V mpv     : event: playback-restart
04-29 09:23:26.828 29175 29201 V mpv     : [cplayer:v] starting audio playback
**04-29 09:23:26.828 29175 29201 V mpv     : [cplayer:v] playback restart complete @ 0.000000, audio=playing, video=playing (paused)**
04-29 09:23:27.724 29175 29201 V mpv     : [lavf:v] EOF reached.

**Comment by sfan5** [comment]
Please provide a full log.

**Comment by MyNameIsAnujRanjan** [comment]
He can someone guide me to how to run shaders in mpv I have tried but failed please step by step.
