### ISSUE TITLE
Command-line options support (export frames as images)

### ISSUE THREAD

**Issue by pspot2** [mpv-android/mpv-android#91]
Does mpv-android support the CLI options of the desktop version? Can I somehow execute the following desktop logic on Android?

mpv --vo=image --vo-image-outdir /sdcard/mpv_images --sstep=30 /sdcard/path/to/video.mp4

Thanks

**Comment by andrew-shulgin** [comment]
Use FFmpeg for this. MPV is a player

**Comment by pspot2** [comment]
Unfortunately FFmpeg does it much slower as it has to parse the complete video. More info and benchmarks: https://stackoverflow.com/questions/10957412/fastest-way-to-extract-frames-using-ffmpeg/28321986#28321986

With MPV the solution is much more compact, elegant and blazing fast, and works perfectly with the desktop version. As MPV's documentation on CLI options mentions Android features, I was having a hope that the same thing could be done on Android.

**Comment by sfan5** [comment]
It doesn't, mpv-android only implements the "playing videos" aspect of mpv.

However part of the build artifacts is an `mpv` binary, if you copy this to the device (+ required libs) you should be able to call mpv on the CLI from a terminal emulator.

**Comment by pspot2** [comment]
Thanks

I did this, but looks like Android 7 allows only PIE binaries:

"/data/local/tmp/mpv": error: only position independent executables (PIE) are supported

What would be the right place in the build script to add the respective CFLAGS?

**Comment by sfan5** [comment]
*untested
<pre>
diff --git a/buildscripts/scripts/mpv.sh b/buildscripts/scripts/mpv.sh
index 0436016..5ab6a07 100755
--- a/buildscripts/scripts/mpv.sh
+++ b/buildscripts/scripts/mpv.sh
@@ -16,7 +16,7 @@ fi
 extrald=
 [[ "$ndk_triple" == "aarch64"* ]] && extrald="-fuse-ld=gold"
 
-LDFLAGS="$extrald" \
+LDFLAGS="$extrald -fPIC" CFLAGS="-fPIC" \
 ./waf configure \
        --disable-iconv --lua=52 \
        --enable-libmpv-shared \

</pre>

**Comment by andrew-shulgin** [comment]
Please read and understand the whole SO answer linked in your second comment and use ffmpeg, as it is the correct tool for your task. MPV is not - it's a player and is based on ffmpeg. BTW, the SO topic does not mention MPV at all.
