### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by nullac123** [mpv-android/mpv-android#920]
Hello everyone,
I can't change package name in android studio
it give me many error
Thanks

**Comment by sfan5** [comment]
Ok, cool.

**Comment by CounterPillow** [comment]
To quote my response to the previous shitter that asked about this:

> Sir Please Kindly Respond I Must Rename Your App So I Can Sell It As Best Free Media Player Pro On Play Store So My Family Can Afford New Plastic Monoblock Chair
