### ISSUE TITLE
Could not create task ':app:dataBindingGenBaseClassesDefaultDebug'

### ISSUE THREAD

**Issue by Nilesh-d** [mpv-android/mpv-android#921]
A problem occurred configuring project ':app'.
> Could not create task ':app:dataBindingGenBaseClassesDefaultDebug'.
   > Cannot use @TaskAction annotation on method DataBindingGenBaseClassesTask.writeBaseClasses() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

getting this error while running this project with:

**Comment by sfan5** [comment]
Works fine for me locally (also with Android Studio) and also on CI.

**Comment by Nilesh-d** [comment]
> Works fine for me locally (also with Android Studio) and also on CI.

I'm using:
Kotlin:  1.7.10
gradle: 7.2.1
compileSdk 34


and getting "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0."

**Comment by sfan5** [comment]
Then what does this have to do with mpv-android?
