### ISSUE TITLE
Pause playback automatically when the headphone is disconnected

### ISSUE THREAD

**Issue by traktori** [mpv-android/mpv-android#928]
I'm not sure if this is a bug or a feature request, but when the headphone is disconnected, mpv should automatically pause playback. I'm talking about wireless headphones in this case. When I disconnect my wireless headphones, the playback continues. But this may also be the case with wired headphones. This is a feature on almost all other Android media players I've used, such as VLC and AntennaPod.

**Comment by sfan5** [comment]
Android provides a mechanism called "audio focus" for this and mpv implements it:
https://github.com/mpv-android/mpv-android/blob/e6868ed335bf998b74ed8ecf509e1dcec13ae4f4/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L96-L124

It looks like this isn't working correctly however.

**Comment by sfan5** [comment]
Nevermind, it's [this](https://developer.android.com/media/platform/output#becoming-noisy) actually which mpv does not implement.
