### ISSUE TITLE
How can I use open external subtitles -> open url can any one give me url 

### ISSUE THREAD

**Issue by Jagadishwar49** [mpv-android/mpv-android#929]
How can I use open external subtitles -> open url can any one give me url

**Comment by Jagadishwar49** [comment]
![Uploading Screenshot_2024-05-31-00-04-47-356_is.xyz.mpv.jpg…]()

**Comment by Jagadishwar49** [comment]
![Uploading Screenshot_2024-05-31-00-04-47-356_is.xyz.mpv.jpg…]()

**Comment by sfan5** [comment]
You enter a direct link to a subtitle file, common extensions are `.srt` and `.ass`.
