### ISSUE TITLE
Audio pass-through support

### ISSUE THREAD

**Issue by hatharry** [mpv-android/mpv-android#93]
It would be a nice feature to enable ac3/dts pass-through over HDMI

**Comment by tmm1** [comment]
This would require a new audio driver in mpv that wraps AudioTrack via JNI, similar to how VLC does it.

**Comment by Doofussy2** [comment]
This is a big problem for Android TV devices. Being able to bitstream audio, is important.

**Comment by tmm1** [comment]
There are atleast five different ways to do passthrough audio on Android, and the one you need to use depends on the device and android version.

I have some half baked patches that work on certain devices, but it is no easy task.

**Comment by Doofussy2** [comment]
I was thinking of trying the lavfi wrapper, to apply the audio-spdif, filter. But I'm not sure it's even present in the android build? My Android TV device is running 6.0.1

**Comment by tmm1** [comment]
mpv already supports spdif, via `--audio-spdif=ac3` etc.

But the OpenSLES Android API does not support spdif, and the AudioTrack Android API only supports `AudioFormat.ENCODING_IEC61937` starting with Android 7.0 (and even then not many devices implement it).

**Comment by Doofussy2** [comment]
But you said there ways to achieve it?

**Comment by tmm1** [comment]
Depends on the device. If you tell me what device I can tell you which techniques might work on it.

**Comment by Doofussy2** [comment]
MiBox 3

**Comment by tmm1** [comment]
MiBox3 doesn't support SPDIF. It does support `AudioFormat.ENCODING_AC3` etc via AudioTrack API. I have only tested passthrough with AC3 on that device, which works as long as the audio is of a constant bit-rate. Doing the same for other codecs is possible but even more complicated.

Unfortunately mpv doesn't have a good way to pass raw audio codecs to decoders at the moment. I have some WIP pull requests open on mpv to hack in support, but they are quite messy and buggy at the moment. See https://github.com/mpv-player/mpv/pull/5703 and https://github.com/mpv-player/mpv/pull/5589

TBH, if passthrough is important to you then you're better off using Exoplayer.

**Comment by Doofussy2** [comment]
Ha! Yeah, that has been said to me, about the Exoplayer, but it can't play MPEG2 natively, only with an HLS stream. 

Thank you for the input. Now I can comfortably abandon this device :)

**Comment by Doofussy2** [comment]
Hi, yeah I should have been more specific. Their site says it doesn't support MPEG-TS container, which is what my Live TV MPEG2 streams, come in. They say it only supports it in HLS. So not the codec, specifically. I'm actually going to run some testing on the audio capabilities of the MiBox. It's site claims it can pass through DTS and DD+, but I have a feeling it's just decoding. I'll find out when I run my tests. There's lots of info floating around, and some of it is conflicting. So I want to do some real world testing.

**Comment by tmm1** [comment]
The live streams from my tuner are also in mpeg-ts, and they worked just fine in Exoplayer. Good luck.

**Comment by Doofussy2** [comment]
Interesting. Maybe expolayer hasn't updated their page, but they say they have no plans to support it, but they will with HLS. Now I'm really going to test the MiBox, capabilities.

**Comment by Pentaphon** [comment]
I'm pretty sure this is possible now. Kodi and Nova Video Player do it just fine.
