### ISSUE TITLE
Better battery consumption 

### ISSUE THREAD

**Issue by Sensex00** [mpv-android/mpv-android#930]
I don't know if you can make this happen 
With all due respect MPV itself is good but compar with video player like vlc it is bad in battery optimisation like playing same 10m video on both results were MPV used more battery for mpv its 3% and 1% battery consum for vlc can you make better battery efficient performance In mpv

It will help for watching moviees and tv shows 
Mpv is powerful but it will need this improvement.

**Comment by sfan5** [comment]
see https://github.com/mpv-android/mpv-android/issues/351#issuecomment-763673215

**Comment by sfan5** [comment]
Literally read (and understand) the linked comment.
