### ISSUE TITLE
Please answer these

### ISSUE THREAD

**Issue by Sensex00** [mpv-android/mpv-android#931]
https://github.com/mpv-android/mpv-android/issues/930#issuecomment-2142141441
Or here 
Why can't you make MPV more battery efficient like vlc and rest I know it provide great video quality but I am sure you can maybe because of are just porting the code pc version to Android or why are any solution just curious to ask this possibilities 
Also can you tell me if your making this app m3
Allreason

**Comment by biopsin** [comment]
Can you please stop your nonsense, go rant some other place.

**Comment by Sensex00** [comment]
> Can you please stop your nonsense, go rant some other place.

Can you please stop your nonsense, go rant some other place also you if you can't tell something valuable besides this comment and there no discussion so I asked it here so why are you having the problem if @sfan5 doesn't

**Comment by Sensex00** [comment]
**this is a genuine question and it's only question want to ask and there's no discussion tab so I was forced to question here on issues**
