### ISSUE TITLE
video-rotate won't rotate 270 or 90 degrees in latest build

### ISSUE THREAD

**Issue by thayerw** [mpv-android/mpv-android#933]
### Important information

Android version: 14

mpv-android version: 2024-05-24
Which version of mpv-android introduced the problem (if known): 2024-05-24

### Description

Since the latest update (20240524), `video-rotate` will no longer rotate videos 90 or 270 degrees. As soon as a video is rotated 90 degrees, the display rotates it another 90 degrees; effectively making it a 180 degree rotation. This occurs whether `panscan` is set to 0 or 1. 

For example, I use the following gesture in `input.conf`:

    # double-tap right to rotate videos
    0x10003 cycle-values video-rotate 270 0

With previous versions, this resulted in a toggled rotation of 270 and 0 degrees, but now results in a toggle of 180 and 0 degree rotation. I've also tried setting the above to `video-rotate 270 180 90 0` and it still only rotates between 180 and 0 degrees. I've tested several video formats and all are effected.

I use this feature in combination with `panscan` and `video-pan-y` to pan and zoom on technical videos when in the field.

Edit: Looks like it could be related to [this commit](https://github.com/mpv-android/mpv-android/commit/ded0803a36f20b4de6fefb3cef4ff4fc3858bf30), though I'm still working out the logic used within.

Downgrading to build 2024-05-04 resolves the issue.

**Comment by sfan5** [comment]
Hm well this sounds like an unintended but logical consequence.
The new code sees the rotation and then "rotates" the app to match.
You could fix this by disabling auto rotation in settings but arguably this behavior isn't useful.

**Comment by thayerw** [comment]
> You could fix this by disabling auto rotation in settings but arguably this behavior isn't useful.

If you're referring to the Android system settings, this did not resolve the issue either. I disabled auto-rotate from the Android Quick Settings menu and mpv still rotates only 180 and 0 degrees. I can't seem to force it to rotate 90 or 270 degrees at all. If mpv has its own setting for auto-rotate, I would manage okay having that at least (I didn't see anything in the documentation for that however).

**Comment by sfan5** [comment]
I was referring to Settings > User Interface > Screen Orientation.

**Comment by thayerw** [comment]
> I was referring to Settings > User Interface > Screen Orientation.

This workaround did resolve the issue for me, so if there is a larger consensus to see your original update applied, I'm good with that too. Thanks again for looking into it.
