### ISSUE TITLE
How to use glsl shaders in a video player in code?

### ISSUE THREAD

**Issue by arianaa30** [mpv-android/mpv-android#934]
I used Mpv android to apply some upscaling shaders. It is pretty efficient and strong and does it in realtime.

I want to apply a shader in a video player and upscale the frames just like Mpv. Is is easy enough to do? Where can I start from? Any samples would help.

**Comment by sfan5** [comment]
mpv specifically uses OpenGL to render video frames so features like upscaling and shaders can work.
Other players (e.g. ExoPlayer) do not and thus can't.

**Comment by arianaa30** [comment]
Got it. Do you have a pointer to the code where it loads a .glsl shader and applies it to frames?

**Comment by Sensex00** [comment]
> Got it. Do you have a pointer to the code where it loads a .glsl shader and applies it to frames?

in that case, you should be able to just put the shaders in /sdcard/cache/shaders/

then in MPV android, open Settings>Advanced>edit mpv.conf:

add the shaders to mpv.conf 

glsl-shaders='/storage/emulated/0/cache/shaders/fsr.glsl'

I tried with fsr it worked

**Comment by IM71** [comment]
> > Got it. Do you have a pointer to the code where it loads a .glsl shader and applies it to frames?
> 
> in that case, you should be able to just put the shaders in /sdcard/cache/shaders/
> 
> then in MPV android, open Settings>Advanced>edit mpv.conf:
> 
> add the shaders to mpv.conf
> 
> glsl-shaders='/storage/emulated/0/cache/shaders/fsr.glsl'
> 
> I tried with fsr it worked

Hi, I want to use AdaptiveSharpen.glsl, my phone only have internal storage.
I put the shader in: /storage/emulated/0/cache/shaders

and set the mpv.conf to: 
glsl-shaders='/storage/emulated/0/cache/shaders/AdaptiveSharpen.glsl'

When I check if the shader is working properly, I didn't see the working status in setting>advanced>2.

Could you please tell me am I missing any steps?

Thank you.

**Comment by Sensex00** [comment]
> > > Got it. Do you have a pointer to the code where it loads a .glsl shader and applies it to frames?
> > 
> > 
> > in that case, you should be able to just put the shaders in /sdcard/cache/shaders/
> > then in MPV android, open Settings>Advanced>edit mpv.conf:
> > add the shaders to mpv.conf
> > glsl-shaders='/storage/emulated/0/cache/shaders/fsr.glsl'
> > I tried with fsr it worked
> 
> Hi, I want to use AdaptiveSharpen.glsl, my phone only have internal storage. I put the shader in: /storage/emulated/0/cache/shaders
> 
> and set the mpv.conf to: glsl-shaders='/storage/emulated/0/cache/shaders/AdaptiveSharpen.glsl'
> 
> When I check if the shader is working properly, I didn't see the working status in setting>advanced>2.
> 
> Could you please tell me am I missing any steps?
> 
> Thank you.

I have tried and it is working all the steps are right i think the problem has to be with device maybe because for low end devices can't handle all the shaders but I also have could you tell what's yours device

**Comment by Sensex00** [comment]
https://gist.github.com/igv/8a77e4eb8276753b54bb94c1c50c317e
Download your Shader by link I have given 
And change the conf. To glsl-shaders='/storage/emulated/0/cache/shaders/adaptive-sharpen.glsl'

**Comment by IM71** [comment]
> > > > Got it. Do you have a pointer to the code where it loads a .glsl shader and applies it to frames?
> > > 
> > > 
> > > in that case, you should be able to just put the shaders in /sdcard/cache/shaders/
> > > then in MPV android, open Settings>Advanced>edit mpv.conf:
> > > add the shaders to mpv.conf
> > > glsl-shaders='/storage/emulated/0/cache/shaders/fsr.glsl'
> > > I tried with fsr it worked
> > 
> > 
> > Hi, I want to use AdaptiveSharpen.glsl, my phone only have internal storage. I put the shader in: /storage/emulated/0/cache/shaders
> > and set the mpv.conf to: glsl-shaders='/storage/emulated/0/cache/shaders/AdaptiveSharpen.glsl'
> > When I check if the shader is working properly, I didn't see the working status in setting>advanced>2.
> > Could you please tell me am I missing any steps?
> > Thank you.
> 
> I have tried and it is working all the steps are right i think the problem has to be with device maybe because for low end devices can't handle all the shaders but I also have could you tell what's yours device

My device is S22U SD8GEN1.

**Comment by Sensex00** [comment]
Follow all the steps and try these https://github.com/mpv-android/mpv-android/issues/934#issuecomment-2211684346

**Comment by Sensex00** [comment]
> > > > > Got it. Do you have a pointer to the code where it loads a .glsl shader and applies it to frames?
> > > > 
> > > > 
> > > > in that case, you should be able to just put the shaders in /sdcard/cache/shaders/
> > > > then in MPV android, open Settings>Advanced>edit mpv.conf:
> > > > add the shaders to mpv.conf
> > > > glsl-shaders='/storage/emulated/0/cache/shaders/fsr.glsl'
> > > > I tried with fsr it worked
> > > 
> > > 
> > > Hi, I want to use AdaptiveSharpen.glsl, my phone only have internal storage. I put the shader in: /storage/emulated/0/cache/shaders
> > > and set the mpv.conf to: glsl-shaders='/storage/emulated/0/cache/shaders/AdaptiveSharpen.glsl'
> > > When I check if the shader is working properly, I didn't see the working status in setting>advanced>2.
> > > Could you please tell me am I missing any steps?
> > > Thank you.
> > 
> > 
> > I have tried and it is working all the steps are right i think the problem has to be with device maybe because for low end devices can't handle all the shaders but I also have could you tell what's yours device
> 
> My device is S22U SD8GEN1.

You Just have to name config accordingly to shaders file name copy file name I think the shader might contain  adaptive-sharpen you not write '-' between them

**Comment by IM71** [comment]
> Follow all the steps and try these [#934 (comment)](https://github.com/mpv-android/mpv-android/issues/934#issuecomment-2211684346)

Also not working, could it be file manager's issue?

**Comment by Sensex00** [comment]
> > Follow all the steps and try these [#934 (comment)](https://github.com/mpv-android/mpv-android/issues/934#issuecomment-2211684346)
> 
> Also not working, could it be file manager's issue?

You have name config accordingly to the shader name have you used  1. adaptive-sharpen or 2. adaptivesharpen this time you to use first one

**Comment by Sensex00** [comment]
> > > Follow all the steps and try these [#934 (comment)](https://github.com/mpv-android/mpv-android/issues/934#issuecomment-2211684346)
> > 
> > 
> > Also not working, could it be file manager's issue?
> 
> You have to name config accordingly to the shader name exactly have you used 1. adaptive-sharpen or 2. adaptivesharpen this time you to use first one

**Comment by IM71** [comment]
> > > Follow all the steps and try these [#934 (comment)](https://github.com/mpv-android/mpv-android/issues/934#issuecomment-2211684346)
> > 
> > 
> > Also not working, could it be file manager's issue?
> 
> You have to name config accordingly to the shader name exactly have you used 1. adaptive-sharpen or 2. adaptivesharpen this time you to use first one

Yes, I did change the shader's name to adaptive-sharpen.

**Comment by Sensex00** [comment]
Ok here's a tutorial
Suggesting an app called filemanager+ ope app go to cache then shaders go for shader properties copy it path
Open mpv go to mpv.conf glsl-shaders='name of the shader.glsl'

Glsl-shaders='/storage/emulated/0/cache/shaders/adaptive-sharpen.glsl'

I will try to upload tutorial here but 10mb limit by GitHub i will different method

**Comment by IM71** [comment]
> Ok here's a tutorial Suggesting an app called filemanager+ ope app go to cache then shaders go for shader properties copy it path Open mpv go to mpv.conf glsl-shaders='name of the shader.glsl'
> 
> Glsl-shaders='/storage/emulated/0/cache/shaders/adaptive-sharpen.glsl'
> 
> I will try to upload tutorial here but 10mb limit by GitHub i will different method

Here's my set up right now.
![Screenshot_20240706_172140](https://github.com/mpv-android/mpv-android/assets/53524000/f0f5031b-d986-40e0-a4d4-9466c93ce486)
![Screenshot_20240706_172216_mpv+ytdl](https://github.com/mpv-android/mpv-android/assets/53524000/1d23ed6f-3c82-4aff-9221-5567755553ba)

**Comment by Sensex00** [comment]
I think you are using the normal app version you should use mpv api29 debug or universal apk from here GitHub because it normally i think it can't work because of newer api or normal apk

**Comment by IM71** [comment]
> I think you are using the normal app version you should use mpv api29 debug or universal apk from here GitHub because it normally i think it can't work because of newer api or normal apk

I know what's the issue that causing the problem.
I toggled the gpu-next function, and that's the reason why the shader didn't load properly. (I'm using the ytdl version btw)

Thank you for your help.

**Comment by Maawu** [comment]
just for info
shader works on Google play version
just use the "media" folder in android as the movies folder. and rename .glsl to .srt.
Example:

glsl-shader='/sdcard/Movies/shaders/adaptive-sharpen.srt'

Or

glsl-shader='/storage/emulated/0/Movies/shaders/adaptive-sharpen.srt'


I tested some shaders; FSR, SSimSuperRes, Anime4k.
on Android 14 and everything works
![Screenshot_2024-10-10-02-23-04-715_is xyz mpv](https://github.com/user-attachments/assets/b141bdc1-30dd-44c8-9812-ab1351a28c2c)
![Screenshot_2024-10-10-02-21-34-077_is xyz mpv](https://github.com/user-attachments/assets/d66a998c-06d3-4725-9afe-7d092e90efc8)

**Comment by IM71** [comment]
> just for info shader works on Google play version just use the "media" folder in android as the movies folder. and rename .glsl to .srt. Example:
> 
> glsl-shader='/sdcard/Movies/shaders/adaptive-sharpen.srt'
> 
> Or
> 
> glsl-shader='/storage/emulated/0/Movies/shaders/adaptive-sharpen.srt'
> 
> I tested some shaders; FSR, SSimSuperRes, Anime4k. on Android 14 and everything works ![Screenshot_2024-10-10-02-23-04-715_is xyz mpv](https://private-user-images.githubusercontent.com/28914715/375235437-b141bdc1-30dd-44c8-9812-ab1351a28c2c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzAzMDMsIm5iZiI6MTcyODU3MDAwMywicGF0aCI6Ii8yODkxNDcxNS8zNzUyMzU0MzctYjE0MWJkYzEtMzBkZC00NGM4LTk4MTItYWIxMzUxYTI4YzJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE0MjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYmQ4ZDU4MjRiYzgwNGZhN2MwYjMxMzYzMmM3N2IyODY4NzBkNmUzYzZiMGMzNTMxZjJhMWRhMTljY2U5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BooCO9mIiMPIXTwvttAs2HhvttbmEEtKAfJfWKzPUkY) ![Screenshot_2024-10-10-02-21-34-077_is xyz mpv](https://private-user-images.githubusercontent.com/28914715/375235453-d66a998c-06d3-4725-9afe-7d092e90efc8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzAzMDMsIm5iZiI6MTcyODU3MDAwMywicGF0aCI6Ii8yODkxNDcxNS8zNzUyMzU0NTMtZDY2YTk5OGMtMDZkMy00NzI1LTlhZmUtN2QwOTJlOTBlZmM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE0MjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3Mjc3NjQ3YmMyMWI1ZjRhMTRiMjM3ZWU3ZTdhYTRlNjk4OGZkZDUyMDY4ZGJmZGEwZjNlNmUzNGVhMWY5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lBn62s9Bi_-W4qDVp78V1WQa5CKZA2bOfgSbmpBG0uQ)
> 
> @sfan5 can you make a note about shaders

Hi,
Could you please help check if this lumasharpen
[lumasharpen.zip](https://github.com/user-attachments/files/17329705/lumasharpen.zip)
 shader works?
I tried your method on my device but couldn't get it to work (I'm using the mpv+ytdl version btw).

Thanks.
![Screenshot_20241010_222028_mpv+ytdl](https://github.com/user-attachments/assets/01c39fc2-1181-497b-86ef-1e8ae386135f)
![Screenshot_20241010_222211_mpv+ytdl](https://github.com/user-attachments/assets/cf73d597-a23b-46c1-8895-cf131425e7ff)

**Comment by Maawu** [comment]
it doesn't work, some that I tested didn't work either, like NVScaler

**Comment by IM71** [comment]
> it doesn't work, some that I tested didn't work either, like NVScaler

Got it, thank you.
