### ISSUE TITLE
Playlist m3u

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [mpv-android/mpv-android#936]
It would be great if the app could also open and run m3u Playlists

In order to play Playlist m3u, you need to install other player VLC kodi.
Their players also have problems with format decoding, consume more resources on the phone and have a complicated interface.😒

### Additional information

m3u list
https://github.com/iptv-org/iptv

**Comment by sfan5** [comment]
m3u playlists are supported.

**Comment by BoostCookie** [comment]
Thanks for the info. That actually worked.

mystream.pls
```pls
[playlist]
File1=rtsp://example.com/live/av0
Title1=mystream
NumberOfEntries=1
```
