### ISSUE TITLE
Bug unresolved reference causing failure of my custom package name during compiling from my forked repository [build bug, not app bug]

### ISSUE THREAD

**Issue by MartinEesmaa** [mpv-android/mpv-android#942]
Hi! I have a problem compiling my custom build of my custom package name.

When I renamed from `is.xyz.mpv` to `is.vvceasy.mpv` of Android package name before I started to compile on my forked repo, then I tried to compile Android build via Gradle after all of dependencies until I got errors:

```
e: file:///home/martineesmaa/mpv-android-vvc/app/src/main/java/is/vvceasy/mpv/FilePickerActivity.kt:149:27 Unresolved reference: filterPredicate
e: file:///home/martineesmaa/mpv-android-vvc/app/src/main/java/is/vvceasy/mpv/FilePickerActivity.kt:150:21 Unresolved reference: filterPredicate
e: file:///home/martineesmaa/mpv-android-vvc/app/src/main/java/is/vvceasy/mpv/FilePickerActivity.kt:179:33 Unresolved reference: hasPermission
e: file:///home/martineesmaa/mpv-android-vvc/app/src/main/java/is/vvceasy/mpv/FilePickerActivity.kt:188:24 Unresolved reference: filterPredicate
```

My operating system for compiling I run Ubuntu 22.04 LTS and 24.04 LTS server. I tried with both OS, didn't work.
Here's forked repository if you want to look: https://github.com/MartinEesmaa/mpv-android-vvc

When some developers wanted to change the Android package name of mpv-android something else, they might get unresolved reference for unknown reasons.

This isn't app bug, but building Android bug after Android package name is changed to custom than `is.xyz.mpv` original package name.

Feel free to ask or reply to me. Thanks! :)

Sincerely,
Martin Eesmaa

**Comment by sfan5** [comment]
I can't possibly fix any changes you have made in your copy.

**Comment by MartinEesmaa** [comment]
I understand... thanks.

There's only one way to solve the problem to rename the package name using apktool after compile. :)

- Martin Eesmaa
