### ISSUE TITLE
Support DisplayManager to output video to second screen and only show control or black screen on the phone

### ISSUE THREAD

**Issue by read8873** [mpv-android/mpv-android#943]
Support DisplayManager to output video to type-c (DP) port and only show control on the phone
This will greatly save phone battery and extend the use case of mpv-android (for example, connecting the phone to a XR headset/TV via type-c).

Additional context

https://developer.android.com/reference/android/hardware/display/DisplayManager

**Comment by read8873** [comment]
https://github.com/mpv-android/mpv-android/issues/728

**Comment by sfan5** [comment]
Thanks for the info, closing in favor of the other issue however.
