### ISSUE TITLE
how to play video with seek

### ISSUE THREAD

**Issue by kllkko** [mpv-android/mpv-android#945]
I am using mpv-android as a library in my project, and I want to implement the save-position-on-quit feature myself. I have already recorded the last playback position. How do I use the playFile method with seek in MPVView?
Please take some time to have a look and provide an answer. Thank you

**Comment by sfan5** [comment]
Please take some time to familiarize yourself with [the mpv manual](https://mpv.io/manual/master/) and the APIs libmpv operates on. This is easy to figure out.

**Comment by kllkko** [comment]
> Please take some time to familiarize yourself with [the mpv manual](https://mpv.io/manual/master/) and the APIs libmpv operates on. This is easy to figure out.

ok，Thank you very much

**Comment by kllkko** [comment]
I got it！

MPVLib.command(arrayOf("loadfile", filePath as String,"replace","start=10"))
