### ISSUE TITLE
Crash when changing scalers

### ISSUE THREAD

**Issue by gasune** [mpv-android/mpv-android#947]
### Important Information
Android version: Android 14 QPR3

mpv-android version: 2024-06-05-release / 8037

Which version of mpv-android introduced the problem (if known):
2024-06-05, doesn't happen in 2024-04-09

### Description

Change `scale` and `dscale` to something like ewa_lanczos or spline64, and then opening any video would result in a crash. Does not crash when set to `bilinear` (default)

### Log output

[mpv.log](https://github.com/user-attachments/files/15934694/mpv.log)

**Comment by sfan5** [comment]
I can't reproduce this but from the backtrace it looks like https://github.com/haasn/libplacebo/commit/691ab15945093a4c260032bb88468e5233afbaca could be related.

**Comment by sfan5** [comment]
Found the likely problem.

**Comment by gasune** [comment]
Tested with scale, dscale, cscale on mpv-android 2024-11-16-release / 8040 (release), and it's fixed. Thanks for looking into it.
