### ISSUE TITLE
libmpv.so is missing

### ISSUE THREAD

**Issue by Aymkdn** [mpv-android/mpv-android#948]
Hi,

I'm trying to build this project and to run it on an Android TV emulation. The Android TV is x86.

I went throught all the steps in [buildscripts](https://github.com/mpv-android/mpv-android/blob/master/buildscripts/README.md) (using WSL):

1. I opened WSL (Ubuntu)
2. I did a `git clone https://github.com/mpv-android/mpv-android`
3. I ran `dos2unix` on the shell files to avoid error messages due to `\r`
4. I moved to the `buildscripts` folder
5. I executed `./download.sh` and I think everything went OK
6. I executed `./buildall.sh --arch x86_64 mpv` and I think everything went OK:
    > [227/227] Linking target libmpv.so
    > ninja: Entering directory `_build-x64'
    > [1/2] Installing files.
    > Installing libmpv.so to /mnt/d/GitHub/mpv-android/buildscripts/prefix/x86_64/usr/local/lib
    > Installing /mnt/d/GitHub/mpv-android/buildscripts/deps/mpv/libmpv/client.h to /mnt/d/GitHub/mpv-android/buildscripts/prefix/x86_64/usr/local/include/mpv
    > Installing /mnt/d/GitHub/mpv-android/buildscripts/deps/mpv/libmpv/render.h to /mnt/d/GitHub/mpv-android/buildscripts/prefix/x86_64/usr/local/include/mpv
    > Installing /mnt/d/GitHub/mpv-android/buildscripts/deps/mpv/libmpv/render_gl.h to /mnt/d/GitHub/mpv-android/buildscripts/prefix/x86_64/usr/local/include/mpv
    > Installing /mnt/d/GitHub/mpv-android/buildscripts/deps/mpv/libmpv/stream_cb.h to /mnt/d/GitHub/mpv-android/buildscripts/prefix/x86_64/usr/local/include/mpv
    > Installing /mnt/d/GitHub/mpv-android/buildscripts/deps/mpv/_build-x64/meson-private/mpv.pc to /mnt/d/GitHub/mpv-android/buildscripts/prefix/x86_64/usr/local/lib/pkgconfig
    > /mnt/d/GitHub/mpv-android/buildscripts
8. I executed `./buildall.sh` – on that one I stopped the process after having the below "IDLE" during 40 minutes:
    > make: Leaving directory '/mnt/d/GitHub/mpv-android/app/src/main'
    > Downloading https://services.gradle.org/distributions/gradle-8.6-bin.zip
    > ............10%.............20%............30%.............40%.............50%............60%.............70%.............80%............90%.............100%
    > 
    > Welcome to Gradle 8.6!
    > 
    > Here are the highlights of this release:
    >  - Configurable encryption key for configuration cache
    >  - Build init improvements
    >  - Build authoring improvements
    > 
    > For more details see https://docs.gradle.org/8.6/release-notes.html
    > 
    > Starting a Gradle Daemon (subsequent builds will be faster)
    > > IDLE

In the `libs` folder I have the below:
![image](https://github.com/mpv-android/mpv-android/assets/946315/b371b2cb-b9fb-4a98-afe5-a6955cb80383)

I want to build the project with Android Studio on Windows 11. I went to the SDK Manager and I changed the directory:
![image](https://github.com/mpv-android/mpv-android/assets/946315/29c76382-4e9c-4c38-a6ef-b5f357e988a2)

I opened `mpv-android` as a project in Android Studio.

I received an error:
> Installed Build Tools revision 34.0.0 is corrupted. Remove and install again using the SDK Manager

So I went to the SDK Manager, under SDK Tool, I checked "Show details", and I uninstall Build Tools v34.0.0 and I installed it again.

I asked Android Studio to rebuild the project, and it gave me the error `Execution failed for task ':app:mergeDefaultDebugJniLibFolders'`. What I did was to remove the Linux symbolic link and to make a Windows symbolic link `mklink /D libs jniLibs`. The error went away.

I started an Android TV emulator (x86) and I'm able to install the app. However, when I want to open a video, logcat shows the below message:
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/is.xyz.mpv-SjXoK3IBH2fW4RWDFVECHQ==/base.apk"],nativeLibraryDirectories=[/data/app/is.xyz.mpv-SjXoK3IBH2fW4RWDFVECHQ==/lib/x86, /system/lib]]] couldn't find "libmpv.so"

**Note**: I tried different things (different from the above), starting from scratch each time, but I always end up with the same message...

**Comment by sfan5** [comment]
Windows is not supported for compiling.
If you do some symlink trickery a setup like yours might work but you are entirely on your own.

**Comment by Aymkdn** [comment]
So… I made it work!

For anyone who wants to build it with Windows… You need to do everything in the Linux Subsystem (WSL):
1. install X Server (I installed [VsXsrc](https://github.com/marchaesen/vcxsrv))
2. open WSL console from Windows 11
4. install Android Studio for Linux
5. clone this repository (`git clone https://github.com/mpv-android/mpv-android`) in your home folder `~` (do **NOT** use `/mnt/` drives)
4. go to the buildscripts folder (`cd ~/mpv-android/buildscripts`)
6. `./download.sh`
7. `./buildall.sh --arch x86_64 mpv`
8. `./buildall.sh --arch x86 mpv`
9. `./buildall.sh`
10. open Android Studio (e.g. `/usr/local/android-studio/bin/studio.sh`)
11. define the SDK location to `~/mpv-android/sdk/`
12. open the project from `~/mpv-android/`
13. you can also install a web browser for Linux in case you click links from Android Studio (`sudo apt install epiphany-browser`)

It should then work as expected. I was afraid that Android Studio will be very slow inside the WSL, but it's actually a bit faster that the one running on Windows!
