### ISSUE TITLE
Support 16 KB page sizes

### ISSUE THREAD

**Issue by allentown521** [mpv-android/mpv-android#952]
https://developer.android.com/guide/practices/page-sizes

**Comment by sfan5** [comment]
Is there a real device with these specs?

**Comment by allentown521** [comment]
> Is there a real device with these specs yet?有具有这些规格的真实设备吗？

you can test it easy with emulator
![image](https://github.com/mpv-android/mpv-android/assets/69662387/5e6959d2-2c62-4065-ae92-11e2fc2f81a6)
