### ISSUE TITLE
Subtitles sometimes will not display

### ISSUE THREAD

**Issue by 77-77SP** [mpv-android/mpv-android#958]
### Important information

Android version: 13

mpv-android version: 2024-06-05-release/8037

### Description

On rare occasions, when switching to a different subtitle or adding a subtitle file, the new subtitle will not load, as if no subtitle has been selected. To fix it I try first to keep switching subtitles until they appear on screen again and if this does not help, I re-open the video.

I have no idea what causes it and unfortunately I am unable to upload logs. If it happens to anyone else please chip in.

Thank you for developing the best video player for android <3

**Comment by 77-77SP** [comment]
I would like to add that this is not related to a specific subtitle language since the same subtitle will load when the video is re-opened. So no encoding issue.

**Comment by sfan5** [comment]
Need log file.

**Comment by da3dsoul1** [comment]
Also have this issue when  seeking subtitles may disappear. It's hard to do a logcat, because sometimes they may reappear again after seeking. Also closing and opening video file again helps too.
