### ISSUE TITLE
watch-later-dir support

### ISSUE THREAD

**Issue by avidseeker** [mpv-android/mpv-android#960]
In Settings > Advanced > mpv.conf, setting `watch-later-dir=.mpvcache` has no effect.

Expected: https://mpv.io/manual/master/#options-watch-later-dir

mpv-android version: 2024-06-05

**Comment by sfan5** [comment]
And what effect do you expect when you don't provide an absolute path?

If you hadn't ignored part of the issue template, the logcat output would have provided more insight here.
