### ISSUE TITLE
Control skip frwd/skip back with remote control buttons Channel Up/Channel Down

### ISSUE THREAD

**Issue by fatSquirrel42** [mpv-android/mpv-android#961]
I would like to control “go to next chapter” and “go to beginning of chapter / previous chapter” using the Channel Up and Channel Down buttons on my remote control. From what I have read and found, I would need to add skip frwd and skip back with the corresponding buttons to input.conf.

Where I get stuck is which keys I would have to specify in the conf. From what I have found out, the remote transmits KEYCODE_CHANNEL_UP 166 and KEYCODE_CHANNEL_DOWN 167 to the device. But neither "KEYCODE_CHANNEL_UP skip frwd" nor "166 skip frwd" worked.
Perhaps I have already entered this incorrectly in the conf.

Does anyone know if and how this is possible?

Nvidia Shield TV
Android 11
mpv 2024-06-05

**Comment by sfan5** [comment]
You're missing a step: mpv-android maps keycodes from the OS to ones libmpv knows.

In this case
https://github.com/mpv-android/mpv-android/blob/66276e03e13437f54c409a9150669f0e47641faf/app/src/main/java/is/xyz/mpv/KeyMapping.java#L50-L51
so simply use the right ones in your input.conf

**Comment by fatSquirrel42** [comment]
> You're missing a step: mpv-android maps keycodes from the OS to ones libmpv knows.
> 
> In this case
> 
> https://github.com/mpv-android/mpv-android/blob/66276e03e13437f54c409a9150669f0e47641faf/app/src/main/java/is/xyz/mpv/KeyMapping.java#L50-L51
> 
> 
> so simply use the right ones in your input.conf

I have tested it this way, but unfortunately it does not work. The key itself works fine. At least with the seek command. Any ideas?

![PXL_20240730_213906778](https://github.com/user-attachments/assets/cfd2dee8-9cc9-4fb0-b8e1-3db132a29e35)

**Comment by fatSquirrel42** [comment]
The correct commands are add chapter 1 and add chapter -1.
