### ISSUE TITLE
App crash after call mpv_destroy in case create multiple mpv_handle

### ISSUE THREAD

**Issue by bachhoan88** [mpv-android/mpv-android#962]
Can you support me fix the crashes. Thank you so much!!!

### How to create multiple mpv player
I made some modifications to several files in the native layer, such as `main.cpp`, to support 2 simultaneous players.
```C++
mpv_handle *g_mpv_1;
mpv_handle *g_mpv_2;
```
In the initialization function, I added a corresponding id when initializing each player:
```C++ 
jni_func(void, create, jobject appctx, jint id)
```
Similarly, for other functions, I added an id to distinguish which player is being referred to.
I managed to make both players capable of playing video simultaneously. However, when calling the destroy method `mpv_destroy(g_mpv_1);` the app crashes.

### Crash information
```
java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: jmethodID was NULL
java_vm_ext.cc:591]     in call to CallIntMethod
is.xyz.mpv                           A  runtime.cc:691] Runtime aborting...
runtime.cc:691] Dumping all threads without mutator lock held
runtime.cc:691] All threads:
runtime.cc:691] DALVIK THREADS (31):
runtime.cc:691] "main" prio=10 tid=1 Native
runtime.cc:691]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x72c69e48 self=0xb4000072fafaabe0
runtime.cc:691]   | sysTid=32656 nice=-10 cgrp=default sched=0/0 handle=0x74aaadcd18
runtime.cc:691]   | state=S schedstat=( 870598050 41040116 1453 ) utm=78 stm=8 core=4 HZ=100
runtime.cc:691]   | stack=0x7ff2a8e000-0x7ff2a90000 stackSize=8188KB
runtime.cc:691]   | held mutexes=
```

### Full crashes 
[crash.txt](https://github.com/user-attachments/files/16444708/crash.txt)

**Comment by sfan5** [comment]
I do not provide free programming help.
