### ISSUE TITLE
Treat KEYCODE_NUMPAD_ENTER in the same way as KEYCODE_ENTER and KEYCODE_DPAD_CENTER

### ISSUE THREAD

**Issue by fatSquirrel42** [mpv-android/mpv-android#963]
### Important information

Android version: 11 - Android TV

mpv-android version: 2024-06-05

### Description

I can't press any UI elements with my remote control during video playback. Also, pause/resume does not work with the D-pad Center button.

I found out that the remote control I use for my Android TV does not send the KEYCODE_DPAD_CENTER command when I press the D-pad Center button, but KEYCODE_NUMPAD_ENTER.

I was able to find two places in the code that check for both KEYCODE_DPAD_CENTER and KEYCODE_ENTER. At these points, it would probably also be necessary to check against KEYCODE_NUMPAD_ENTER.

I also connected a real keyboard as a test and was able to verify that the normal Enter key can be used to press the UI elements and pause/resume playback, but not with the Numpad Enter Key.

### Additional information

https://github.com/mpv-android/mpv-android/blob/66276e03e13437f54c409a9150669f0e47641faf/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L771

https://github.com/mpv-android/mpv-android/blob/66276e03e13437f54c409a9150669f0e47641faf/app/src/main/java/is/xyz/mpv/MPVActivity.kt#L820

**Comment by sfan5** [comment]
Well this is good information. Maybe this is what caused Google to reject the app because their testers were using a similar non-standard input.

**Comment by sfan5** [comment]
So to be clear your input sends `DPAD_{UP,DOWN,LEFT,RIGHT}` correctly, but `NUMPAD_ENTER` instead of `DPAD_CENTER`?

**Comment by fatSquirrel42** [comment]
Yes, that is correct.

**Comment by sfan5** [comment]
Thanks.

**Comment by fatSquirrel42** [comment]
Thanks for the quick fix. Much appreciated.
