### ISSUE TITLE
Quality menu 

### ISSUE THREAD

**Issue by Univalpha** [mpv-android/mpv-android#964]
Dear Dev...
Please add quality menu in MPV android like YouTube and other online players have it.
I want to choose quality whenever it's available .
I am not technical person don't know its possible or not but if you can then do it please 🥺 
Thanks.

**Comment by sfan5** [comment]
Choosing quality from inside mpv is only possible if mpv is made aware of the different streams available.
Even with yt-dlp this is not the case by default and the most likely way this can be made to work (DASH manifest) is a bit buggy and does not work without libxml.
