### ISSUE TITLE
Application closes after trying to play

### ISSUE THREAD

**Issue by dexaltat** [mpv-android/mpv-android#965]
When I try to open this file via mpv, then I have application crash. I checked it on several devices. I provide a link to Google Drive with file. Vlc play it.

Device: Galaxy A52 
OS: Oneui 6 (Android 14)
mpv version: mpv-android 2024-06-05-release
Type of file: avi
Log file: sorry, I don't have a PC to create log. 
https://drive.google.com/drive/folders/19Th4PzIO17OApg43IEM3BkcHKaZEu6wG

Or

https://mega.nz/folder/Xt0j2JzQ#6od5G-QO03XmYgOxIxegwA

**Comment by sfan5** [comment]
Link is private.

**Comment by dexaltat** [comment]
> Link is private.

Oh I'm so sorry, try again please

**Comment by sfan5** [comment]
Works for me. Could be a problem with hwdec, try disabling that.

**Comment by dexaltat** [comment]
> Works for me. Could be a problem with hwdec, try disabling that.

Yes, you are right. If I add it to the playlist and first turn on the swdec, then everything is fine. It is possible to somehow enable swdec for all files by default?
