### ISSUE TITLE
Support for Data URI Scheme for subtitles

### ISSUE THREAD

**Issue by elyeandre** [mpv-android/mpv-android#967]
Request to add support for data: URI scheme for subtitles in mpv-android. This allows passing subtitle content directly via intents using base64-encoded data: URIs.

e.g

```
Intent intent = new Intent(Intent.ACTION_VIEW);
intent.setDataAndType(Uri.parse("video_file_path"), "video/any");

String subtitleDataURI = "data:text/plain;base64,VGhpcyBpcyBhIHNhbXBsZSBzdWJ0aXRsZQ==";
intent.putExtra("subs", subtitleDataURI);
intent.putExtra("title", "Your Video Title");

intent.setPackage("is.xyz.mpv");
startActivity(intent);
```

**Comment by sfan5** [comment]
https://mpv.io/manual/master/#protocols
mpv has `data:` (though it needs to be used as `data://`)
there's also `memory://` and `hex://`

problem is mpv-android exposes none of them

**Comment by sfan5** [comment]
I have implemented this, but note that [content providers](https://developer.android.com/guide/topics/providers/content-provider-creating) are the better alternative if you want to pass data to other apps. I don't know what the size limit for intent extras is.
