### ISSUE TITLE
Audio only via OPEN URL

### ISSUE THREAD

**Issue by p-mackay** [mpv-android/mpv-android#970]
I want to conserve mobile data. Is there an equivalent of $mpv --no-video https://example.com on mpv-android? Or some other solution that would reduce data usage.

### Additional information
Android 14

I'm using the apk from https://github.com/mpv-android/mpv-android/issues/840.
Changing mpv.conf with: 
profile=fast
no-video=yes (had no effect)

Further, when playing a video in the background it would be nice if the app automatically switched to audio only.

**Comment by 77-77SP** [comment]
Adding --no-video to mpv.conf works perfectly on my end. I am using the official release.
