### ISSUE TITLE
Debanding, differences between CPU and GPU mode

### ISSUE THREAD

**Issue by fatSquirrel42** [mpv-android/mpv-android#972]
Hello,
I was wondering what the differences are between CPU and GPU debanding modes. I assume there are differences in quality and performance?
Is it fair to say that one is generally better than the other?

**Comment by sfan5** [comment]
I have no idea.
Selecting CPU uses the `gradfun` filter from ffmpeg, which is based on an AviSynth filter called `gradfun2db`.
Selecting GPU will use mpv's deband algorithm (which is the same with [gpu](https://github.com/mpv-player/mpv/blob/acc69e082fff67398834de3045ef48d33d2f4d54/video/out/gpu/video_shaders.c#L967) and [gpu-next](https://github.com/haasn/libplacebo/blob/82bf46ae8b4cacd2523f994da292e4d12312c026/src/shaders/sampling.c#L179)), but I couldn't find out if it has a name.

Without commenting on quality or differences between the algorithms: if "GPU" works for you, you should be using it.
