### ISSUE TITLE
Error displaying statistics stats.lua

### ISSUE THREAD

**Issue by MrDark-code** [mpv-android/mpv-android#976]
If you set Cache and Timing in the settings, then general statistics are shown. The correct behavior will only occur if you manually switch to 2 or 3
![Screenshot_2024-08-21-11-44-51-709_is xyz mpv](https://github.com/user-attachments/assets/6d1a9d9c-4c7b-4a20-a963-c3a34d9a58ea)
![Screenshot_2024-08-21-11-45-44-978_is xyz mpv](https://github.com/user-attachments/assets/8c8f73f4-9280-483f-862a-42aed3b35392)

**Comment by MrDark-code** [comment]
@sfan5 
Save position on quit doesn't seem to work either. Test Android 10.

**Comment by sfan5** [comment]
One bug report per issue.

**Comment by MrDark-code** [comment]
@sfan5 
msg-level=all=trace
[mpvlog.txt](https://github.com/user-attachments/files/16763019/mpvlog.txt)
is that ok ? )
