### ISSUE TITLE
Support for Data URI Scheme for Audio Tracks

### ISSUE THREAD

**Issue by SonaliBendre** [mpv-android/mpv-android#981]
### Describe the wanted behaviour of the new feature and potential usecases for it here.

Request to add support for data: URI scheme for extra audio tracks in mpv-android. This allows passing audio tracks content directly via intents using base64-encoded data: URIs.

### Additional information

e.g.

```
Intent intent = new Intent(Intent.ACTION_VIEW);
intent.setDataAndType(Uri.parse("video_file_path"), "video/any");

String subtitleDataURI = "data:text/plain;base64,VGhpcyBpcyBhIHNhbXBsZSBzdWJ0aXRsZQ==";
intent.putExtra("dubs", audioDataURI);
intent.putExtra("title", "Your Video Title");

intent.setPackage("is.xyz.mpv");
startActivity(intent);

```

**Comment by sfan5** [comment]
Rejected. Intents are not the place for bulk binary data, especially not in base64 format.
