### ISSUE TITLE
A-B Loop with seekbar 

### ISSUE THREAD

**Issue by waseemhehe** [mpv-android/mpv-android#987]
![aaaabbbbb](https://github.com/user-attachments/assets/68c3ae9a-3176-4e86-96ee-72ed3d4c9a5b)

Like VLC showing with seek bar points A-B loop can we do that in Mpv Android ,
i m making same ui like VLC so i required this feature, if this feature already exist can u provide me information how to do this

**Comment by sfan5** [comment]
Since you can't even configure a-b loop using the UI I don't see value in this.

**Comment by waseemhehe** [comment]
anyway i did that A-B loop functionality it was more easy then we think lol

**Comment by waseemhehe** [comment]
this functionality has been done here is code which u can u use , if someone need it 

<ImageView
    android:id="@+id/pointA"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginBottom="2dp"
    android:src="@drawable/pointa"
    android:visibility="gone"
    app:layout_constraintBottom_toTopOf="@+id/playbackSeekbar"
    app:layout_constraintEnd_toStartOf="@+id/playbackSeekbar"
    app:layout_constraintStart_toStartOf="@+id/playbackSeekbar"
    app:layout_constraintTop_toTopOf="parent" />
<SeekBar
    android:id="@+id/playbackSeekbar"
    android:layout_width="0dp"
    android:layout_height="match_parent"
    android:layout_gravity="center_vertical"
    android:layout_marginTop="20dp"
    app:layout_constraintEnd_toStartOf="@+id/playbackDurationTxt"
    app:layout_constraintStart_toEndOf="@+id/playbackPositionTxt"
    app:layout_constraintTop_toTopOf="parent" />
<ImageView
    android:id="@+id/pointB"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    android:layout_marginStart="74dp"
    android:layout_marginBottom="2dp"
    android:src="@drawable/pointb"
    android:visibility="gone"
    app:layout_constraintBottom_toTopOf="@+id/playbackSeekbar"
    app:layout_constraintEnd_toStartOf="@+id/playbackSeekbar"
    app:layout_constraintStart_toStartOf="@+id/playbackSeekbar"
    app:layout_constraintTop_toTopOf="parent" />

Now in player Activity 

private var isPointASet = false
private var isPointBSet = false
private var pointATime: Double = 0.0
private var pointBTime: Double = 0.0
private var isLoopingAB = false
abLoop.setOnClickListener {
    binding.loopSettings.visibility = View.VISIBLE
}
selection.setOnClickListener {
    if (!isPointASet) {
        setPointADrawable()
        pointATime = player.getCurrentPosition() ?: 0.0
        isPointASet = true
    } else if (!isPointBSet) {
        setPointBDrawable()
        pointBTime = player.getCurrentPosition() ?: 0.0
        isPointBSet = true
        if (isPointASet) {
            startABLoop()
        }
    }
}
cancelLoop.setOnClickListener {
    cancelABLoop()
}
private val seekBarChangeListener = object : SeekBar.OnSeekBarChangeListener {
    override fun onProgressChanged(seekBar: SeekBar, progress: Int, fromUser: Boolean) {
        if (!fromUser)
            return
        player.timePos = progress.toDouble() / SEEK_BAR_PRECISION
        // Note: don't call updatePlaybackPos() here either
    }

    override fun onStartTrackingTouch(seekBar: SeekBar) {
        userIsOperatingSeekbar = true
    }

    override fun onStopTrackingTouch(seekBar: SeekBar) {
        userIsOperatingSeekbar = false
        showControls() // re-trigger display timeout
    }
}
private fun startABLoop() {
    if (isPointASet && isPointBSet && pointATime < pointBTime) {
        isLoopingAB = true
        binding.loopSettings.visibility = View.VISIBLE
        runABLoop()
    }
}

private fun cancelABLoop() {
    removeABLoop()
    isLoopingAB = false
    binding.pointA.visibility = View.GONE
    binding.pointB.visibility = View.GONE
    isPointASet = false
    isPointBSet = false
    binding.loopSettings.visibility = View.GONE
}

private fun runABLoop() {
    handler.post(runnable)
}

private fun removeABLoop() {
    handler.removeCallbacks(runnable)
}

private val runnable = object : Runnable {
    override fun run() {
        val currentTime = player.getCurrentPosition()?.toFloat() ?: 0f
        if (isLoopingAB) {
            if (currentTime >= pointBTime) {
                player.timePos = pointATime
            }
            handler.postDelayed(this, 100)
        }
    }

}
And Remember to remove the handler in onDestroy method 
have a Good Day
this for Only Android Users XD
