### ISSUE TITLE
MPV not able to render hindi subtitles.

### ISSUE THREAD

**Issue by sujitFYI** [mpv-android/mpv-android#988]
This is kind of problem I'm facing from very Start. 

MPV Android don't render Hindi Subtitles instead it shows "▯▯▯▯▯▯▯▯▯▯▯" this type of boxes.

Its very common issue that can be produced by using any srt file. So I'm not including extra details and log currently.

**Comment by sfan5** [comment]
sample file?

**Comment by sujitFYI** [comment]
I currently don't have sample file neither i can upload but I'm giving you sample srt file so you can add it using external subtitles in any video and see yourself.

[sample hindi srt.srt.txt remove .txt ](https://github.com/user-attachments/files/16897919/sample.hindi.srt.srt.txt)

**Comment by sfan5** [comment]
confirmed:
<pre>
10-13 02:44:43.160  8788 14439 V mpv     : [sub/ass:v] Glyph 0x947 not found, selecting one more font for (sans-serif, 400, 0)
10-13 02:44:43.160  8788 14439 V mpv     : [sub/ass:info] fontselect: Using default font: (sans-serif, 400, 0) -> /data/user/0/is.xyz.mpv/files/subfont.ttf, 0, (none)
10-13 02:44:43.160  8788 14439 V mpv     : [sub/ass:v] fontselect: (sans-serif, 400, 0) -> /data/user/0/is.xyz.mpv/files/subfont.ttf, 0, (none)
10-13 02:44:43.160  8788 14439 V mpv     : [sub/ass:v] Got a font face that already is available! Skipping.
10-13 02:44:43.160  8788 14439 V mpv     : [sub/ass:info] Glyph 0x947 not found, broken font? Trying all charmaps
10-13 02:44:43.160  8788 14439 V mpv     : [sub/ass:warn] Glyph 0x947 not found in font for (sans-serif, 400, 0)
</pre>
