### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by waseemhehe** [mpv-android/mpv-android#989]
i have request that can u provide in release the Libmpv.so files like this in pictures, it would be easy for windows android studio users to use library of mpv, i m using libmpv.so file in my project after build the native code of mpv.
 
![image](https://github.com/user-attachments/assets/4bbfb40f-333b-4a8d-bf8a-f9fe4098fd33)

**Comment by sfan5** [comment]
mpv-android is not a library and does not aim to be one. So no.
