### ISSUE TITLE
OSD back colour issue

### ISSUE THREAD

**Issue by WaruiDevil** [mpv-android/mpv-android#997]
OSD back colour isn't applying. It was fine till mpv version 2024-06-05-release, I use old api but it's in normal too.

**Before**
![Screenshot_2024-09-18-03-25-20-073_is xyz mpv ytdl](https://github.com/user-attachments/assets/163496aa-121f-49a7-ba3b-466b716b5796)
![Screenshot_2024-09-18-03-25-25-858_is xyz mpv ytdl](https://github.com/user-attachments/assets/2e29adeb-b956-4ed6-bd53-11519bcc0db7)

**Now**
![Screenshot_2024-09-18-03-26-37-261_is xyz mpv](https://github.com/user-attachments/assets/00942880-84ce-4a41-b8d5-347faf75a208)
![Screenshot_2024-09-18-03-26-53-692_is xyz mpv](https://github.com/user-attachments/assets/1db47ae3-4119-4a98-9ff0-53444a519e93)

**Config**
![Screenshot_2024-09-18-03-28-08-360_com mixplorer silver~2](https://github.com/user-attachments/assets/a19ffd32-325c-4b95-9833-dc2569236a6c)

**Comment by obscenelyvague** [comment]
Set `osd-border-style=background-box`

**Comment by WaruiDevil** [comment]
@obscenelyvague Thanks it's working now. It wasn't needed in past and this `osd-border-style=background-box` isn't added in https://mpv.io/manual/stable/, so I thought it's a bug

**Comment by sfan5** [comment]
> `osd-border-style=background-box` isn't added in https://mpv.io/manual/stable/, so I thought it's a bug

mpv-android follows the git version of mpv, so you want to check https://mpv.io/manual/master/
